### ISSUE TITLE
Get the option to skip blob\commit scan by size OR limit the rule scan\regex by time

### ISSUE THREAD

**Issue by roma8389** [zricethezav/gitleaks#1001]
Hi,

i am using gitleaks which is a great tool, but in some cases i have large objects in .git history which resolve to very long time of the tool execution. i was wonder if it possible to get a CLI switch where i will add timeout pre rule or size of blob to skip. one of this option will solve my problem. the other option is to remove large files from history which is not stable solution.
I do need the history scan as i am follow secrets from history which are not neccesry now in the code base.
TY!!!

**Comment by zricethezav** [comment]
closing this issue with the release of https://github.com/zricethezav/gitleaks/releases/tag/v8.14.0

Thanks @roma8389

**Comment by roma8389** [comment]
@zricethezav  TY!
