### ISSUE TITLE
false positives in pnpm lockfile

### ISSUE THREAD

**Issue by elijaholmos** [zricethezav/gitleaks#1014]
### Discussed in https://github.com/zricethezav/gitleaks/discussions/1005

<div type='discussions-op-text'>

<sup>Originally posted by **elijaholmos** October  7, 2022</sup>
I use CI for dependency management in one of my [public repos](https://github.com/elijaholmos/halo-discord-extension), and recently, a pull request was created that triggered several false positives from the Gitleaks GitHub action; see https://github.com/elijaholmos/halo-discord-extension/pull/51.

Is this an intentional feature with gitleaks? How am I able to stop all package versions with hashes (eg `0.11.0_hc4yn5f4ebzhrwwrb4uuunvgqi`) from being caught by gitleaks in the future?</div>

**Comment by SubOptimal** [comment]
You might use a customized `.gitleaks.toml`, e.g. in the root directory of your repository. Assuming `gitleaks` run the scan from the root.

Copy the file [gitleaks.toml](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) to the root of your repository as `.gitleaks.toml`.

As the `pnpm-lock.yaml` most probably is updated with `pnpm i --lockfile-only` it could be excluded from the scan.

Find below two possibilities to exclude the `pnpm-lock.yaml` in the root directory of your directory.

**1. add the file to the allow list to exclude it from all scans**
```
[allowlist]
description = "global allow lists"
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket)$''',
    '''(go.mod|go.sum)$''',
    '''node_modules''',
    '''vendor''',
    '''^pnpm-lock.yaml$'''
]
```

**2. exclude the file only from the `Generic API Key` rule**
```
[[rules]]
description = "Generic API Key"
id = "generic-api-key"
...
[rules.allowlist]
paths = [
  '''Database.refactorlog''',
  '''^pnpm-lock.yaml$'''
]
```

To use the file `.gitleaks.toml` is only one possibility. Others are mentioned in the gitleaks help.

```
$ gitleaks --help
...
  -c, --config string              config file path
                                   order of precedence:
                                   1. --config/-c
                                   2. env var GITLEAKS_CONFIG
                                   3. (--source/-s)/.gitleaks.toml
                                   If none of the three options are used, then gitleaks will use the default config
```

**Comment by elijaholmos** [comment]
hi @SubOptimal, thank you for the response. I was able to setup a `.gitleaks.toml` file in my repository and used the first configuration option you sent to add `pnpm-lock.yaml` to the global allow list.

I didn't want to copy the entire [gitleaks.toml](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml?rgh-link-date=2022-10-15T21%3A36%3A22Z) that you linked, so my `.gitleaks.toml` is very barebones:
```toml
title = "gitleaks config"

[allowlist]
description = "global allow lists"
paths = ['''^pnpm-lock.yaml$''']
```

this successfully disabled false positives for the `pnpm-lock.yaml` file in the root of my repository. however, when I added a `test.yaml` with the exact same contents as the suspect `pnpm-lock.yaml`, gitleaks did not raise any flags.
does my `.gitleaks.toml` file merge with the base [gitleaks.toml](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml?rgh-link-date=2022-10-15T21%3A36%3A22Z)? or is my `.gitleaks.toml` configuration used as the absolute source of truth, and since it is missing most of the base configuration, files that should normally be flagged are allowed to pass?

**Comment by weineran** [comment]
> does my .gitleaks.toml file merge with the base [gitleaks.toml](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml?rgh-link-date=2022-10-15T21%3A36%3A22Z)?

No. By putting a .gitleaks.toml file in your repo root, you are overriding the default config.

It sounds like you might want to "extend" the default config. See this blog post for more info: https://blog.gitleaks.io/stop-leaking-secrets-configuration-2-3-aeed293b1fbf#15a4

**Comment by elijaholmos** [comment]
thanks @weineran for sharing that article. the `useDefault` flag is exactly what I was looking for. unfortunately, the example repo linked in the article has been taken down, but I was still able to gather enough from the written examples. thank you both for your help!

**Comment by zricethezav** [comment]
@elijaholmos links have been fixed :) 

Closing this issue as it looks like you have found what you're looking for. Feel free to reopen if I closed it prematurely
