### ISSUE TITLE
scanmode: 'all' does not identify secrets from historic commits

### ISSUE THREAD

**Issue by meeragirijan** [zricethezav/gitleaks#1033]
I'm implementing gitleaks as cred scanner alternative in a DevOps pipeline using YAML. 
Trying out scanmode 'all' option on a feature branch with multiple commits, the runs seem to only detect the current state of the branch and not previous commits. What is the expected behavior, is any additional settings that I'm missing?

**Comment by zricethezav** [comment]
Hi @meeragirijan, could you provide the command you are attempting to run? Also what version of gitleaks are you using?

**Comment by meeragirijan** [comment]
@zricethezav  Got this resolved. I had to set the fetchDepth to 0 explicitly on the repo; without it, it was defaulting and checking only the latest commit. It would be good to update the documentation with this for future reference.

**Comment by zricethezav** [comment]
> Got this resolved. I had to set the fetchDepth to 0 explicitly on the repo; without it, it was defaulting and checking only the latest commit. It would be good to update the documentation with this for future reference.

@meeragirijan are you referring to the gitleaks-action? 

As this has been resolved, I'm going to close this issue.
