### ISSUE TITLE
gitleaks --repo-url xxx is doesn't work now? I want to check remote private repo , how to do with gitleaks？

### ISSUE THREAD

**Issue by Josie-ljw** [zricethezav/gitleaks#1035]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@Josie-ljw v8.0.0 removed all network activity. I.e, gitleaks does not handle cloning repos anymore. You can do something like:

```
git clone {repo}
cd {repo}
gitleaks detect
```
