### ISSUE TITLE
Incorrect startLine

### ISSUE THREAD

**Issue by weineran** [zricethezav/gitleaks#1037]
**Describe the bug**
Quick description: The scan reports the wrong startLine of a secret. I'm not sure if this is always the case or just sometimes.

**To Reproduce**
I will try to reproduce later, but for now, here is an example from a scan that was run using Gitleaks-Action: https://github.com/whoopsify/app/actions/runs/3476503806
The report says the start line was 2.
However, if you click "View Secret", you will see the secret was actually on line 1 (and the file only has 1 line total).

**Expected behavior**
startLine should be correct

**Screenshots**
![image](https://user-images.githubusercontent.com/5898785/202089157-cdbfe67b-cd64-4107-9049-3b2862e9a9f2.png)
![image](https://user-images.githubusercontent.com/5898785/202089205-251274a4-4ca7-4400-8fce-ee9f9094dab5.png)

**Basic Info (please complete the following information):**
 - OS: GitHub Actions ubuntu-latest
 - Gitleaks Version: 8.12.0

**Additional context**
N/A

cc @zricethezav

**Comment by zricethezav** [comment]
@weineran good catch, I'll look into this hopefully sometime this weekend. I have a feeling this is an edge case when the secret is on the first line of a file/diff

**Comment by weineran** [comment]
Yes definitely an edge case. My theory (speculative) is that it only
happens when the diff is 1 line long or the file is only 1 line long.
