### ISSUE TITLE
Install v7 with `go install`

### ISSUE THREAD

**Issue by nawa** [zricethezav/gitleaks#1040]
**Describe the bug**
`go install` fails with `v7`

**To Reproduce**
```
$ go install github.com/zricethezav/gitleaks/v7@latest
go: github.com/zricethezav/gitleaks/v7@latest (in github.com/zricethezav/gitleaks/v7@v7.6.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Expected behavior**
`gitleaks` binary is successfully installed

**Basic Info (please complete the following information):**
 - Go: `go1.19.2`, ... ?

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
I don't support anything < `v8.x.x`. I recommend install using the [release binaries](https://github.com/zricethezav/gitleaks/releases/tag/v7.6.1) rather than `go install`. Or you could build from source by manually updating the `go.mod` file but I'm not making any guarantees that that will work.
