### ISSUE TITLE
Slice bounds out of range panic in v8.15.1-v8.12.0

### ISSUE THREAD

**Issue by LauraXiulan** [zricethezav/gitleaks#1042]
**Describe the bug**
When running gitleaks on my repo, I get the error: "panic: runtime error: slice bounds out of range [:-1]". See the logging below.

````
panic: runtime error: slice bounds out of range [:-1]

goroutine 160 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0xc0000a4e70, 0xf}, 0xd9, 0xd9, 0x1e, 0x5e, {0xc0004ae7c3, 0x16}, {0xc0004ae7e0, 0x1e}, ...})
	/Users/zrice/code/zricethezav/gitleaks/detect/utils.go:105 +0x142d
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0xc0000a4e70, 0xf}, 0xd9, 0xd9, 0x1e, 0x5e, {0xc0004ae7c0, 0x19}, {0xc0004ae7e0, ...}, ...})
	/Users/zrice/code/zricethezav/gitleaks/detect/detect.go:579 +0x3c5
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
	/Users/zrice/code/zricethezav/gitleaks/detect/detect.go:469 +0x305
github.com/fatih/semgroup.(*Group).Go.func1()
	/Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e
##[warning]Execution errors occured. See log for details.
##[section]Finishing: Scan for leaked secrets for haas/traject-cleanup
````

**To Reproduce**
I have seen the previous closed bug #842 where this issue was reported for version 8.7.0. So I have looked at the changesets for utils.go, which is the file the stacktrace refers to and have tried different versions in which changes have been made. Based on that I have determined that the issue occurs at least until version **8.12.0** and disappears when I am using version **8.11.2**. So I am assuming it has been (re-)introduced in 8.12.0.

**Additional context**
I am running Gitleaks as a build step in Azure Devops. Please let me know if you need more information.

cc @zricethezav

**Comment by zricethezav** [comment]
Thanks for brining this bug up @LauraXiulan! Would it be possible to create a file or repo (with fake or scrambled secrets) that reproduces the bug you're describing?

**Comment by LauraXiulan** [comment]
I will try to create one

**Comment by rdiezsj** [comment]
Same problem here. The `--redact` option causes the error. Without that option the repository is scanned correctly: `gitleaks detect --no-git --verbose`

**Comment by zricethezav** [comment]
@rdiezsj unfortunately, I'm unable to reproduce this bug. Could you provide a sample file or secret that will trigger this behavior?

**Comment by rdiezsj** [comment]
I have managed to filter the content until limiting it to a single line that causes the error:

```
private static final String NX_SNOWFLAKE_PRIVATE_KEY_B64_ENV = "NX_SNOWFLAKE_PRIVATE_KEY_B64";
```

```bash
❯ ls -1
fail
❯ cat fail
private static final String NX_SNOWFLAKE_PRIVATE_KEY_B64_ENV = "NX_SNOWFLAKE_PRIVATE_KEY_B64";%                                                                                                                                                                                   
❯ gitleaks detect --source="." --no-git -f json --redact --verbose

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

5:40PM INF scan completed in 8.95ms
5:40PM WRN leaks found: 1
❯ gitleaks detect --source="." --no-git -f json --redact --verbose

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

panic: runtime error: slice bounds out of range [:-1]

goroutine 11 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0x1400034f870, 0xf}, 0x1, 0x1, 0x32, 0x5d, {0x1400030a000, 0x36}, {0x14000018198, 0x18}, ...})
        github.com/zricethezav/gitleaks/v8/detect/utils.go:105 +0x1138
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0x1400034f870, 0xf}, 0x1, 0x1, 0x32, 0x5d, {0x1400030a000, 0x36}, {0x14000018198, ...}, ...})
        github.com/zricethezav/gitleaks/v8/detect/detect.go:579 +0x304
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
        github.com/zricethezav/gitleaks/v8/detect/detect.go:469 +0x238
github.com/fatih/semgroup.(*Group).Go.func1()
        github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0x8c
created by github.com/fatih/semgroup.(*Group).Go
        github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x28c

 /private/tmp/datasource/1       
```

**Comment by zricethezav** [comment]
@rdiezsj this is happening because the _secret_, `NX_SNOWFLAKE_PRIVATE_KEY_B64` is also found in the identifier, `NX_SNOWFLAKE_PRIVATE_KEY_B64_ENV`. 

`NX_SNOWFLAKE_PRIVATE_KEY_B64_ENV` becomes `REDACTED_ENV` in the _line_, but in the _match_, it is still `KEY_B64_ENV`, if that makes sense. The secret being part of the identifier breaks shit. I can hack together a solution that would treat the whole line as the match when printing findings. That seems like a decent solution since this is an edge case

**Comment by rdiezsj** [comment]
New release 8.15.2 works without problem. Thank you very much
