### ISSUE TITLE
Question about allowlist rules

### ISSUE THREAD

**Issue by bplaxco** [zricethezav/gitleaks#1064]
Given [this rule for AWS Access Keys](https://github.com/leaktk/patterns/blob/5461292e947af3e37ce40590ef3db5179c03e9b9/patterns/gitleaks/8.12.0/99-general.toml#L31), does anyone know how I'd ignore [AWS presigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html) like [this](https://github.com/leaktk/patterns/blob/5461292e947af3e37ce40590ef3db5179c03e9b9/tests/gitleaks/8.12.0/test_gitleaks.py#L129)?

In gitleaks<8 the allowlist would match against the whole match line, not just the secret, so it was pretty easy to write allowlist regexes that also took the context around the match into consideration. I have a [handful of rules](https://github.com/leaktk/patterns/blob/main/target/patterns/gitleaks/7.6.1) that I'm in the process of migrating and several (especially the "General Secrets" ones) rely on the full line matching to cut down on FPs. 

Sorry if the answer is clearly documented somewhere and I just missed it. I'll happily accept a RTFM response with a link :sweat_smile: (I picked through the detect.go code and didn't see a path that matched what I was trying to do).

Also sorry for not using one of the templates. This didn't really seem like a bug, feature request (yet), or maint.

If it's worth adding an option to the allowlist config to set the match scope (defaulting to what it is today but also having the options (secret|match|line or what ever makes the most sense), I'm up for contributing code and docs.

Thanks for the great project!

**Comment by weineran** [comment]
@bplaxco There is a PR in progress that I believe addresses this question: https://github.com/zricethezav/gitleaks/pull/1045
Let me know if I misunderstood.

**Comment by bplaxco** [comment]
@weineran yeah that looks exactly like the issue I'm talking about.

> RegexTarget which could be one of the following: line, match, or secret.

And at a glance that looks exactly like what I was looking for.

I didn't get to pick through all of the details but I'll be back at a laptop next week and will pick through it more. Thanks for sending that my way and responding so quick.

Feel free to close this out, I've subscribed to the other ticket 😊

**Comment by weineran** [comment]
@bplaxco Great!

It looks like I don't have the ability to close the discussion. Maybe the opener needs to close it? Or maybe @zricethezav can close.
