### ISSUE TITLE
bash detection of "password=.."

### ISSUE THREAD

**Issue by strowi** [zricethezav/gitleaks#1094]
**Describe the bug**
Gitleaks seems to not detect simple `password=..`  or `url=https://123:321@127.0.0.1..` secrets.

**To Reproduce**
`mkdir -p test && cd test && echo "password=testing123" > test.sh && gitleaks detect -v --no-git  .`
`mkdir -p test && cd test && echo "url=https://123:321@127.0.0.1" > test.sh && gitleaks detect -v --no-git  .`

**Expected behavior**
Detection of those secrets in bash-scripts

**Basic Info (please complete the following information):**
 - OS: Ubuntu
 - Gitleaks Version: 8.15.3

**Additional context**
Found #837 but it seems not working.

cc @zricethezav

**Comment by zricethezav** [comment]
> mkdir -p test && cd test && echo "password=testing123" > test.sh && gitleaks detect -v --no-git  .

`testing` is a stop word for the generic rule and won't consider the match a secret. See https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L482-L495

> mkdir -p test && cd test && echo "url=https://123:321@127.0.0.1" > test.sh && gitleaks detect -v --no-git  .

By default gitleaks does not detect passwords in urls, you can use a custom rule if you want to detect that
