### ISSUE TITLE
fail to scan single file

### ISSUE THREAD

**Issue by marcelo321** [zricethezav/gitleaks#1095]
so gitleaks is failing to scan a single file, and I don't really know why.

` gitleaks --path=/pathtofile/a`

```
INFO[0000] opening /pathtofile/a            
ERRO[0000] stat /pathtofile/a/.git: not a directory
```

**Comment by zricethezav** [comment]
@marcelo321 
> ERRO[0000] stat /pathtofile/a/.git: not a directory

`a` is not a git repo so you need to use the `--no-git` flag
