### ISSUE TITLE
List of regexes for service secrets

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#119]
Would love some help on gathering a list of regexes for services so that folks could search for a service they use. This list could be put into its own wiki page and referenced in the README

**Comment by jfowl** [comment]
Can't edit your wiki pages :/

Here is the markdown you might want to copy:

---

Supported Services
==================

gitleaks supports the following services or secrets:

- RKCS8 keys
- RSA keys
- SSH keys
- Github API tokens
- AWS API tokens
- Facebook API tokens
- Twitter API tokens
- Telegram bot tokens

**Comment by zricethezav** [comment]
Awesome! Appreciate it. I'll be adding the Telegram bot token shortly
