### ISSUE TITLE
scanning github orgs' private repos

### ISSUE THREAD

**Issue by derricksong** [zricethezav/gitleaks#132]
trying to use the --github-org option, but it's only targetting public repos.  my API key definitely has full repo access (to public and private), what am I missing?

**Comment by zricethezav** [comment]
is gitleaks using the correct ssh key? gitleaks will use a default `~/.ssh/id_rsa` if you dont manually supply one with the `--ssh-key` option

**Comment by derricksong** [comment]
oh I was trying to give it a personal API token... makes sense

**Comment by zricethezav** [comment]
You need both. You have to supply an API token so gitleaks can hit the github api and grab all the private repos. Then gitleaks will clone using ssh for those repos which requires your ssh key

**Comment by zricethezav** [comment]
@derricksong closing this, if this is unresolved open it again

**Comment by thearthur** [comment]
Here's a working example of doing this without divulging the ssh key (so it can work in jenkins with jenkin's credential store) and scanning all the private repos:

```docker run --rm --name=gitleaks -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK \                                      2 ↵  arthur@a:14:40:23
                                    -e SSH_AUTH_SOCK \
                                    -e SSH_AGENT_PID \
                                    -e GITHUB_TOKEN zricethezav/gitleaks --github-org=your-org-name-here```
