### ISSUE TITLE
Wiki: error , From # 8 To # 10 ⬇️

### ISSUE THREAD

**Issue by chinanf-boy** [zricethezav/gitleaks#136]
### From 

- [8. Running against a Github Organization](https://github.com/zricethezav/gitleaks/wiki#8-running-against-a-github-organization)

### To

- [10. Running against a Github User](https://github.com/zricethezav/gitleaks/wiki#10-running-against-a-github-user)

## Error

- [ ] 1. The ❤️ two times ?
- [ ] 2. The Code 💛 `--github-org` three times ? 
- [ ] 3. And `NOTE` issues ❓

### Source -> Html

8. Running against a Github Organization ❤️ 

```
gitleaks --github-org=gitleakstestorg 💛 
```
NOTE: you may want to use --disk if the organization you are auditing is large

9. Running against a Github Organization ❤️ 
```
gitleaks --github-org=gitleakstestorg 💛 
```
NOTE1: you may want to use --disk if the organization you are auditing is large

NOTE2: you may want to use --log=debug to see which repos you will be auditing.

10. Running against a Github User
```
gitleaks --github-org=gitleakstest 💛 
```
NOTE: you may want to use --disk if the user you are auditing is large

NOTE2: you may want to use --log=debug to see which repos you will be auditing.
```

**Comment by zricethezav** [comment]
fixed, thanks for pointing this out
