### ISSUE TITLE
[feature request] define disk temp path

### ISSUE THREAD

**Issue by riramar** [zricethezav/gitleaks#137]
Thanks for such amazing tool!
I'm scanning a huge organization and not sure if the space in my disk will be enough to store everything under /tmp/ directory.
So my suggest is include an optional parameter to define the temp directory when --disk is used.
I'd like to help implement that but I don't know golang enough to contribute.

**Comment by zricethezav** [comment]
hey @riramar great suggestion. Would a separate `--disk-path=` option work?

**Comment by riramar** [comment]
yes... it should work! thanks @zricethezav

**Comment by zricethezav** [comment]
Closed this prematurely, sorry. Still have not implemented this.

**Comment by zricethezav** [comment]
Use `--clone-path` in v7
