### ISSUE TITLE
How to find a file

### ISSUE THREAD

**Issue by riramar** [zricethezav/gitleaks#139]
How to find the file inside the repo from the log below?
OBS.
- The https://github.com/organization/xptorepo/commit/abc123 point to a different file than test/xpto/file.go
- The https://github.com/organization/xptorepo/tree/master/test/xpto folder doesn't exist (probably exist in the past)
- Didn't find anything when searching by "xptoname" or "tralala"
- Didn't find the branch "aaaa/heads/master"

```
{
   "line": "\txptoname = `-----BEGIN PRIVATE KEY-----",
   "commit": "abc123",
   "offender": "-----BEGIN PRIVATE KEY-----",
   "reason": "PKCS8",
   "commitMsg": "tralala",
   "author": "that guy",
   "file": "test/xpto/file.go",
   "branch": "aaaa/heads/master",
   "repo": "xptorepo",
   "date": "2017-11-14T00:09:57-08:00"
}
```

**Comment by zricethezav** [comment]
What does OBS mean? 

The urls you have 404. There is no need for `organization`

What command are you running with?

**Comment by riramar** [comment]
OBS == observation

You got 404 because these I redacted the organization name in order to avoid any the disclosure. The names in my example are fake.

# gitleaks --github-org=organization --disk --log=debug -v --report=gitleaks.csv

**Comment by zricethezav** [comment]
So youre searching for a specific file, not a string within that file? Right now there is not an option to search for a specific file.

**Comment by zricethezav** [comment]
default ref is ref/heads/master. you can specify the branch with `--branch` or run with `--all-ref` to scan all branches

**Comment by riramar** [comment]
I got the log below and I'm trying to find the file with the string "-----BEGIN PRIVATE KEY-----" inside from the repo but I'm not able to find the file.

```
{
   "line": "\txptoname = `-----BEGIN PRIVATE KEY-----",
   "commit": "abc123",
   "offender": "-----BEGIN PRIVATE KEY-----",
   "reason": "PKCS8",
   "commitMsg": "tralala",
   "author": "that guy",
   "file": "test/xpto/file.go",
   "branch": "aaaa/heads/master",
   "repo": "xptorepo",
   "date": "2017-11-14T00:09:57-08:00"
}
```

**Comment by riramar** [comment]
do you have an email that I can send you the real log?

**Comment by zricethezav** [comment]
probably because the file has since been removed from the repo

**Comment by zricethezav** [comment]
email is on my github user page

**Comment by riramar** [comment]
You're right! The file was deleted. Thanks for your help and patient.
