### ISSUE TITLE
Ignored files by default

### ISSUE THREAD

**Issue by camaya** [zricethezav/gitleaks#142]
Hi,

In version 1.17.0 one of the added features was:

* Default whitelisting: bin, doc, jpeg, gif

But it seems like that was removed in this commit: https://github.com/zricethezav/gitleaks/commit/7e3c7405928dfffcfdc1490843742786668ed4e5#diff-7ddfb3e035b42cd70649cc33393fe32cL193

Was this removal a mistake or am I missing something?

Cheers

**Comment by zricethezav** [comment]
whoops. thats a mistake. was doing some testing with this https://github.com/zricethezav/gitleaks/blob/master/main.go#L494-L496 but didnt readd the file whitelist. Thanks for pointing that out
