### ISSUE TITLE
Persistant/Local Repos

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#15]
A feature that has been requested by a few folks is the ability to audit local repos as scheduled tasks. @JustinAzoff in https://github.com/zricethezav/gitleaks/issues/8 suggested using a data store like boltDB to cache commits so we don't run redundant checks on commits that have already been vetted.

I'm thinking we keep the default behavior but add some options like a `--dir`, `-d` flag to tell gitleaks run this for a local repo: `$ gitleaks --dir {my_repo}`. For persistent support we can add a `--persist`, `-p` flag that tell gitleaks to skip the `rm -rf` call and check the data store before running all checks.

**Comment by ryh** [comment]
will this local feature work with `on-stage files` (not commit yet) ?
Would be more awesome gitleaks can check before commit/push ing

**Comment by zricethezav** [comment]
Handled: https://github.com/zricethezav/gitleaks/releases/tag/v0.2.0
