### ISSUE TITLE
Add option to test a single commit

### ISSUE THREAD

**Issue by camaya** [zricethezav/gitleaks#154]
When there's a leak that I now exists on a specific commit and I want to tweak the gitleaks configuration to catch it, it'd be very helpful if I could run the tool against that single commit. My suggestion is to add the option: `--single-commit={sha}`

What do you think?

**Comment by nightspotlight** [comment]
I totally agree and would like to see this feature. It would be very useful in a CI environment, for example where one wants to validate a single commit before it gets merged to the master branch. I've tried running gitleaks with `--commit=${sha} --depth=1`, but it doesn't seem to do what's expected

**Comment by camaya** [comment]
@nightspotlight Agree with the name of the `--commit` option. I think it'd be better to call it `--stop-at`

I haven't done this yet because it involves more work than I thought since currently there's not a function like `auditCommit` for instance so to this, there should be an important refactor.

**Comment by zricethezav** [comment]
```     
 --commit-stop=    sha of commit to stop at
 --commit=         sha of commit to audit
```
will do the trick
