### ISSUE TITLE
Add option to run only on current files in the repo

### ISSUE THREAD

**Issue by camaya** [zricethezav/gitleaks#156]
Going back in time to check every single commit can be a slow process on big repositories. It'd be nice if we could add an option to check only the files that exist currently on the master branch. Maybe adding a --only-master-files option.

What do you think?

**Comment by nightspotlight** [comment]
`--depth=1` seems to do the trick.

It would be nice though to specify in the manual which values are accepted by `--depth`. I can't understand what `--depth=0` does exactly

**Comment by camaya** [comment]
@nightspotlight I thought `--depth=1` would check the last commit in the repo but I might be wrong here. 

@zricethezav Can you clarify, please?

**Comment by zricethezav** [comment]
that is correct @camaya, `--depth=1` will inspect the changes from the most recent commit. If your repo only has one commit then you would be checking all the current files in the repo but only for that case.

**Comment by nightspotlight** [comment]
Today at work I've tried `--depth=1`, and in the report it showed results for more than just the most recent commit.

**Comment by nightspotlight** [comment]
@zricethezav is there (will there be) an option to scan just one specific branch?

**Comment by avishnyakov** [comment]
There is a key `--branch=YOUR_BRANCH_NAME`, goes all over the history.

`--only-master-files` would be a super-useful flag. As mentioned, going back in history is very nice but slow and might not be optimal. Secrets could have been already changed and rotated, not much value going back.

In this case, we want to know if current state of the repository, the latest (not the commit but all the latest files) have secrets. `--only-master-files` option should make GitLeaks going via the latest fileset to identify is there are any secrets right now right here in the repository.

**Comment by Kamleshpa** [comment]
This feature should have been there by default. Why would I want to fail my pipeline because of some historical secret checkin which does not exists anymore.

**Comment by zricethezav** [comment]
`--files-at-commit=latest` will do the trick
