### ISSUE TITLE
Bug: Repo name not showing up in reports when analyzing repo from local disk

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#160]
Repo name field in generated reports should be the directory name of the git repo as locally cloned to disk. Repo name currently displayed as "."

**Comment by nightspotlight** [comment]
have you tried specifying absolute path to `--repo-path`?

**Comment by galiagante** [comment]
Relative path, yes, I can re-test for any change in output using absolute paths.

**Comment by galiagante** [comment]
Reporting back: Use of absolute paths did not change the output present in the report files. Repo name is still being displayed as "."

**Comment by zricethezav** [comment]
Sorry about the delay, I'll give this a look this weekend. Thanks for bringing this to my attention.

**Comment by zricethezav** [comment]
I believe this issue has been fixed, reopen if still a problem
