### ISSUE TITLE
Whitelist regexes checks inconsistent and sometimes redundant

### ISSUE THREAD

**Issue by milo-minderbinder** [zricethezav/gitleaks#161]
# Expected Behavior
For each line with a regex finding, an entropy finding, or both, each whitelist regex should be checked once and only once.

# Observed Behavior
Currently, for a given line if:
1. No whitelist regexes match the line
2. Two or more finding regexes match the line

then the full set of whitelist regexes are checked against the line for each matched finding regex in *[2]* unnecessarily.

Alternatively, for a given line, if:
1. One or more whitelist regexes match the line
2. No finding regexes match the line
3. One or more entropy findings are found in the line

then the whitelist regex is never checked and the entropy finding(s) are incorrectly reported, even though one or more whitelist regex would match the line if checked.

**Comment by zricethezav** [comment]
again, thanks!
