### ISSUE TITLE
whiteListFiles regexes are checked unnecessarily for every chunk of each file

### ISSUE THREAD

**Issue by milo-minderbinder** [zricethezav/gitleaks#162]
The whiteListFiles regexes are checked in the `inspect(diff gitDiff) []Leak` function, instead of being called in the `auditGitReference(repo *RepoDescriptor, ref *plumbing.Reference) []Leak` function where `inspect` is called. This is redundant, since inspect is called for every 'chunk' and there may be many chunks in a single `FilePatch`.

Instead, the whiteListFiles regexes should be checked against each `FilePatch` _before_ generating the list of `Chunk`s for the `FilePatch` and calling `inspect` on those chunks. @

**Comment by zricethezav** [comment]
thanks for handling this!
