### ISSUE TITLE
[+] Feature Request : File Extension Detection Patterns

### ISSUE THREAD

**Issue by arbazkiraak** [zricethezav/gitleaks#167]
Feature Request:
================

A way to detect the files based on the given `File Extension patterns`?

Ex:

```
    match:       ".pem",
    description: "Potential cryptographic private key",

    match:       ".pcap",
    description: "Network traffic capture file",

**Comment by arbazkiraak** [comment]
@milo-minderbinder Any thoughts on it?  would be good find sensitive files based on regex given "File name based"

**Comment by arbazkiraak** [comment]
Any thoughts on this @zricethezav @milo-minderbinder

**Comment by arbazkiraak** [comment]
Hi @zricethezav ,

Any update on the feature?

**Comment by arbazkiraak** [comment]
Hi @zricethezav,

* Please provide an update regarding the feature, 

Thanks!

**Comment by milo-minderbinder** [comment]
It’s not my project, but IMO rules based on file path and/or extension _alone_ would not likely provide much value. For example, pem files can contain public keys (non sensitive) as well as private keys, and I can’t really think of many examples of file extensions that are exclusively for secrets.

That said, I have considered making a feature request for adding the git commit hash, file path, and line number to the whitelist and blacklist patterns, kind of like the `git-secrets` Project.

**Comment by arbazkiraak** [comment]
> but IMO rules based on file path and/or extension alone would not likely provide much value.

* Yes, There would be high chances for FP since we are just checking the file extensions & filing an offender leak, 
* How about keeping this feature  as optional,
if the user defines a set of extensions in `gitleaks.toml` then only gitleaks look for leaks along with extensions.
Please look at how `Gitrob` does the extension based leaks.

https://github.com/michenriksen/gitrob/blob/master/core/signatures.go

**Comment by zricethezav** [comment]
@arbazkiraak I agree with what you're saying. This would be a useful option. No progress on this feature yet, but I have it on my roadmap.

**Comment by theoretick** [comment]
This would be a very welcome addition! We recently dropped a similar library ([`diffence`](https://github.com/techjacker/diffence)) that offered this due to performance and maintenance issues. Would be great to rely entirely on `gitleaks`.

I might suggest expanding the scope of this feature more generically to "filename matches" rather than just extensions.

Beyond `gitrob` signature list linked above, here's [`diffence`'s rule list](https://github.com/techjacker/diffence/blob/master/rules.go).

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/wiki/config-toml you can now check match file regexes with `filetypes` in the config

**Comment by zricethezav** [comment]
See https://github.com/zricethezav/gitleaks/#rules-summary
