### ISSUE TITLE
Sarif output report not generated with 8.22.0

### ISSUE THREAD

**Issue by ccjernigan** [zricethezav/gitleaks#1677]
**Describe the bug**
I no longer see a report sarif file with Gitleaks 8.22.0 but this does work with 8.21.2.

**To Reproduce**
Does not reproduce: 
`podman run --network none -v $(pwd):/path zricethezav/gitleaks:v8.21.2@sha256:0e99e8821643ea5b235718642b93bb32486af9c8162c8b8731f7cbdc951a7f46 detect --verbose --source="/path" --report-format sarif --report-path /path/gitleaks-results.sarif`

Does reproduce: 
`podman run --network none -v $(pwd):/path zricethezav/gitleaks:v8.22.0@sha256:9c008fc701d3a0a2a15b77a7677b940e2e5942e8af8cc2a0b6e078c4365c3c86 detect --verbose --source="/path" --report-format sarif --report-path /path/gitleaks-results.sarif`

**Expected behavior**
gitleaks 8.22.0 should produce a gitleaks-results.sarif like 8.21.2

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: macOS Sonoma, Ubuntu (GitHub Actions)
 - Gitleaks Version: 8.22.0

cc @zricethezav

**Comment by kachick** [comment]
@ccjernigan Is that the same problem as https://github.com/gitleaks/gitleaks/pull/1673? The merged commit has not been included in version 8.22.0.

https://github.com/gitleaks/gitleaks/compare/v8.21.2...v8.22.0
https://github.com/gitleaks/gitleaks/compare/v8.22.0...7edfc6b5d5bfc642144932c0b9188fee1cb00560

**Comment by kachick** [comment]
https://github.com/gitleaks/gitleaks/compare/v8.21.2...v8.21.4

As I understand it, 8.21.3 and 8.21.4 also do not include the commit. I expect that the master branch or the next release will fix your problem. 🙏
