### ISSUE TITLE
request slightly longer example in readme for enterprise github runs

### ISSUE THREAD

**Issue by JustinGOSSES** [zricethezav/gitleaks#173]
Hi. Could more information be added to the readme for how to run this on a hosted enterprise github? The readme blurb seems to suggest I should add /API/v3/ onto the end of the base url for my enterprise github. That doesn't do anything for me or return an error, even with --verbose. I've tried using 

`gitleaks --github-url=<myURLtoHostedEnterpriseGithub>/<org>/<repo>`
`gitleaks --github-url=<myURLtoHostedEnterpriseGithub>/API/v3/`
`gitleaks --github-url=<myURLtoHostedEnterpriseGithub>/API/v3/ -github-org==<orgName>`
`gitleaks --github-url=<myURLtoHostedEnterpriseGithub>/<org>/<repo> -github-org==<orgName`
`gitleaks --github-url=<myURLtoHostedEnterpriseGithub>/API/v3/<orgName>`

I'm making calls from with the firewall. I can't get any errors to print to terminal, so I'm struggling to figure out what is stopping me.

Any help would be great. I started to use this on public github and appreciate it a lot.

This is related to  #85 #84 by @eripa

**Comment by zricethezav** [comment]
dropped support for github/gitlab integrations in v7
