### ISSUE TITLE
False Positives When Sourcing Github Hash

### ISSUE THREAD

**Issue by phundisk** [zricethezav/gitleaks#175]
The github regex is currently producing a lot of false positives when there exists something like this in the source code "    { url : "https://github.com/KenanY/node-uuid", branch : "7a018f2d075b03a73409e8356f9b29c9ad4ea2c5" }"
It happens when we are referencing a git URL with a hash.  We should exclude any hits that have "github.com\/" in the results.

**Comment by zricethezav** [comment]
Couple a things you can do:
1. write custom rules for whitelisting regexes
2. enable entropy
3. filter entropy hits with additional regexes
