### ISSUE TITLE
Feature Request: Behavior change for --commit option

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#178]
When using the --commit flag, it appears that while the use of this flag correctly exits an analysis chain at the specified commit ID, the actual commit being referenced by the flag is not, itself,  scanned. 

I would like to request a change in the behavior of the --commit flag to ensure the referenced commit is included in the analysis chain prior to exiting said chain.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/179 addresses this
