### ISSUE TITLE
shell injection

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#18]
https://github.com/zricethezav/gitleaks/blob/master/leaks.go#L29 could be pwned by malicious repo urls. need to do some regexing or use https://github.com/src-d/go-git for the clones.

**Comment by anant2614** [comment]
Should we use go-git for now ? I can take this up.

**Comment by zricethezav** [comment]
@anant2614 we should use go-git for cloning at the very least. The other git operations should be fine to shell out since `rev-list` is a defined string. `git diff` should also be to shell out too. If you want to take this on that would be much appreciated! 👍

**Comment by mcuadros** [comment]
One question why `git diff` should be the shell output? It's something wrong with the diff output from go-git?

**Comment by zricethezav** [comment]
Ideally, gitleaks would use go-git for all git commands. I raised this issue specifically for the clone. Using go-git for other commands are nice-to-haves... but also easy to implement so I agree with you, go-git should be used for the diff and rev-list (if supported).

**Comment by anant2614** [comment]
@zricethezav well I worked just on the clone part.I went through the go-git docs of supported commands,could not find git-diff and rev-list features and these are open feature requests in their issues.

**Comment by zricethezav** [comment]
closing this. @mcuadros feel free to open an issue for getting `rev-list` and `diff` working for go-git.

**Comment by mcuadros** [comment]
I just asking because diff and rev-list are being used intensively, and
documented ad supported.

https://github.com/src-d/go-git/blob/master/COMPATIBILITY.md

So I wanted to know if you had any missing features.

>

**Comment by zricethezav** [comment]
@mcuadros I see that now. I'll be looking into replacing all shelled cmds with go-git in the future when I have some more time to develop this.

**Comment by zricethezav** [comment]
@mcuadros v1.0.0 is now powered by go-git. Awesome package! Thanks source-d :+1:
