### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by arbazkiraak** [zricethezav/gitleaks#181]
```
→ gitleaks --repo=https://github.com/tomochain/tomochain --config=/root/cimex2/mainapp/gitleaks.toml -e 5 --depth=100 --report='tomochain.json'
INFO[2019-02-13T18:56:14+05:30] cloning https://github.com/tomochain/tomochain 
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Total 86861 (delta 0), reused 0 (delta 0), pack-reused 86860
Killed
```

**Comment by zricethezav** [comment]
Attempting to clone now. Taking a real long time and consuming ~7GBs of memory. Big repo, have you tried running this with `--disk`?

**Comment by arbazkiraak** [comment]
Hi @zricethezav ,

Thanks for helping me out.

* Using `--disk` worked. 

is there any way to keep the cloned repository ? I noticed that it will delete the repo once it done with scanning.

Also Any thoughts on this `https://github.com/zricethezav/gitleaks/issues/167`

**Comment by zricethezav** [comment]
@arbazkiraak If you wanted to keep the repo after the scan I would suggest first cloning the repo then using the `--repo-path=` option to point to that repo. 

I'll take a look at that issue this weekend. Thats a useful feature for sure

**Comment by Miloy03** [comment]
Hi @zricethezav,

I am facing the same issue wherein my scan gets killed. Is this because it does not get enough RAM memory? Also the "--disk" option does not seem to be working for me. Can you please suggest a solution?
