### ISSUE TITLE
Feature Request: Option for relaxed host key checking for SSH access methods

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#182]
This issue has popped up as part of "hands-off" automation efforts. Like most any SSH client (or workalike) the ability to relax the usual host key checking rules can be a useful feature.

While I am requesting this as a feature, I also plan to have a go at addressing this on my own. I will post a PR for review if it goes well.

**Comment by zricethezav** [comment]
Gitleaks is not responsible for cloning in v8
