### ISSUE TITLE
Clarification on the default gitleaks.toml configuration

### ISSUE THREAD

**Issue by theoretick** [zricethezav/gitleaks#185]
Hello! Thank you for this project.

When looking for the default configuration I was a bit confused and was wondering if we could improve the documentation or remove duplication around the default configuration. I assumed `./gitleaks.toml` was the default configuration however it looks like there is `defaultConfig` defined within `main.go` that will be used when generating a sample. Both have distinct regexes and rulesets that don't look quite the same.

 - `./gitleaks.toml`: https://github.com/zricethezav/gitleaks/blob/v1.24.0/gitleaks.toml
 - `defaultConfig`: https://github.com/zricethezav/gitleaks/blob/v1.24.0/main.go#L143

the root level config has an additional `Stripe API Key` rule and an `RKCS8` rule, where-as the sample uses `PKCS8`, an `[entropy]` configuration, and distinct regexes.

Can you clarify the distinction? After discussion I'm happy to provide an PR to either (A) document the two or (B) unify the configs

**Comment by theoretick** [comment]
@zricethezav just a bump on this, would you be interested in merging these two configs or improving the docs on the difference between the two?

**Comment by zricethezav** [comment]
👋 gonna close this one out. I did take your advice eventually and did improve the docs [here](https://github.com/zricethezav/gitleaks/wiki/Configuration) :)
