### ISSUE TITLE
False negatives when testing against custom rules defined in gitleaks.toml

### ISSUE THREAD

**Issue by Eric-Hern** [zricethezav/gitleaks#186]
Thank you for developing this tool. 

I would like the tool to flag certain strings, (e.g.: "password", "key", etc). I've also added rules to flag IP addresses and email addresses.   I've added the appropriate regex to gitleaks.toml

The criteria that I'm specifying in my regex is skipped over when I run the tool against the repo. What am I doing wrong? Thank you so much for your help. 

`
# gitleaks --version
1.24.0

# cat gitleaks.toml
...
description = "PASSWORD STRING"
regex = '''[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd].'''
[[regexes]]
description = "IP ADDRESS"
regex = '''\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'''
[[regexes]]
description = "KEY(s) STRING"
regex  = '''[Kk][Ee][Yy].'''
...

`

**Comment by Eric-Hern** [comment]
`[[regexes]]
description = "EMAIL ADDRESS"
regex = '''(?<email>.+@.+)\s'''`

**Comment by galiagante** [comment]
I have been doing a number of custom regex's for this tool. Here's a version using a case-insensitive search for a given string:
  [[regexes]]
  description = "Password String"
  regex = '''(?i)password'''

Here's another for both case- and sequence-insensitive search for a given group of characters:
  [[regexes]]
  description = "Password String"
  regex = '''(?i)[pasword]'''

Both have been tested. Note that all three lines are generally necessary.

**Comment by Eric-Hern** [comment]
> I have been doing a number of custom regex's for this tool. Here's a version using a case-insensitive search for a given string:
> [[regexes]]
> description = "Password String"
> regex = '''(?i)password'''
> 
> Here's another for both case- and sequence-insensitive search for a given group of characters:
> [[regexes]]
> description = "Password String"
> regex = '''(?i)[pasword]'''
> 
> Both have been tested. Note that all three lines are generally necessary.

Thank you! I will test this ASAP. Can you think of any reason why my initial syntax didn't work as planned?

**Comment by galiagante** [comment]
I'm going to speculate by suggesting that the exact formatting of the statement(s) added to your custom TOML file might have been malformed, and hence ignored? But that's merely an educated guess...

**Comment by Eric-Hern** [comment]
Thank you for the insight. 

Oddly enough, I'm still having issues where the string `password` is not getting matched and therefore not showing up as a leak.  I've used the syntax that you've specified. 

I agree that there has to be something wrong with my toml file (posted here in my test repo):

https://github.com/Eric-Hern/TEST_JS/blob/master/gitleaks.toml

I'm running gitleaks against the repo above (TEST_JS) and my  sample 'malicious' data (within the test.md file) is getting ignored.  I'll take a look (maybe run the toml file through a syntax checker) and see what the story is... Thank you again for your help.

**Comment by galiagante** [comment]
After a quick review, I haven't noticed anything wrong with the formatting or syntax of your TOML file. I'll have to pull a copy and do some live-fire testing before rendering any further opinion(s).

**Comment by zricethezav** [comment]
can be avoided by using a global allowlist https://github.com/zricethezav/gitleaks#configuration
