### ISSUE TITLE
Feature Request: Pure JSON Output Option

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#187]
As JSON is a very useful data format, having adulterated output can be troublesome to use I might suggest an option that would output this.....

    INFO[2019-03-22T13:35:29-04:00] cloning git@github.com:armadillo-field-testing/snippets.git
    Enumerating objects: 1783, done.
    Counting objects: 100% (1783/1783), done.
    Compressing objects: 100% (806/806), done.
    Total 1783 (delta 829), reused 1717 (delta 801), pack-reused 0
    {
       "line": "# fake key used to (re-)trigger REDACTED",
       "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
       "offender": "REDACTED",
       "reason": "Test String",
       "commitMsg": "Updated with multiple genuine fake keys",
       "author": "Rick Pelletier \u003crpelletier@gannett.com\u003e",
       "file": "triggered.py",
       "repo": "snippets.git",
       "date": "2019-03-07T10:37:00-05:00"
    }
    {
       "line": "key = \"REDACTED\"",
       "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
       "offender": "REDACTED",
       "reason": "Twitter",
       "commitMsg": "Updated with multiple genuine fake keys",
       "author": "Rick Pelletier \u003crpelletier@gannett.com\u003e",
       "file": "triggered.py",
       "repo": "snippets.git",
       "date": "2019-03-07T10:37:00-05:00"
    }
    {
       "line": "another_key = \"REDACTED\"",
       "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
       "offender": "REDACTED",
       "reason": "AWS",
       "commitMsg": "Updated with multiple genuine fake keys",
       "author": "Rick Pelletier \u003crpelletier@gannett.com\u003e",
       "file": "triggered.py",
       "repo": "snippets.git",
       "date": "2019-03-07T10:37:00-05:00"
    }
    WARN[2019-03-22T13:35:31-04:00] 3 leaks detected. 1 commits inspected in 1 second 554 milliseconds

...into something like this....

    [
      {
        "line": "# fake key used to (re-)trigger REDACTED",
        "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
        "offender": "REDACTED",
        "reason": "Test String",
        "commitMsg": "Updated with multiple genuine fake keys",
        "author": "Rick Pelletier <rpelletier@gannett.com>",
        "file": "triggered.py",
        "repo": "snippets.git",
        "date": "2019-03-07T10:37:00-05:00"
      },
      {
        "line": "key = \"REDACTED\"",
        "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
        "offender": "REDACTED",
        "reason": "Twitter",
        "commitMsg": "Updated with multiple genuine fake keys",
        "author": "Rick Pelletier <rpelletier@gannett.com>",
        "file": "triggered.py",
        "repo": "snippets.git",
        "date": "2019-03-07T10:37:00-05:00"
      },
      {
       "line": "another_key = \"REDACTED\"",
        "commit": "c194337a48f9a3f5559ec3383b317d92f2ed1725",
        "offender": "REDACTED",
        "reason": "AWS",
        "commitMsg": "Updated with multiple genuine fake keys",
        "author": "Rick Pelletier <rpelletier@gannett.com>",
        "file": "triggered.py",
        "repo": "snippets.git",
        "date": "2019-03-07T10:37:00-05:00"
      }
    ]

**Comment by zricethezav** [comment]
`--report=fileName.json` you can save the report as a json. Would this cover what you're looking for?

**Comment by galiagante** [comment]
I considered this idea, but it adds a good deal of extra "plumbing" to what would otherwise be a relatively simple sub-process run that just captures output on 'stdout'. I am, however, open to suggestions?

**Comment by zricethezav** [comment]
10-4, feature will be added

**Comment by zricethezav** [comment]
I dropped the ball on this one and never got around to it, however a simple workaround would be to pipe the output of gitleaks to jq and use the `fromjson` builtin which would filter the output for valid json. 

ex:
`gitleaks --repo-path=. -v | jq -R 'fromjson?'`

cc @galiagante

**Comment by zricethezav** [comment]
Gonna close this one out. The solution presented above with `jq` is the best I'm willing to do at this point. Feel free to pick this up/open a PR for me to review.

**Comment by zricethezav** [comment]
@galiagante you can now use `-q/--quiet` mode which will only output pure json leaks
