### ISSUE TITLE
Bug: Out-of-Scope Results using '--commit' Option

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#188]
Scans of a target repo by commit ID can reveal results in files outside the contents of the commit in question. This has been confirmed to occur in version 1.24.0 and might exist in previous versions.

Note: Due to the proprietary nature of the data used to confirm this bug, specific details will not be posted here. Continued conversation(s) with the author regarding this issue will be conducted privately.

**Comment by avishnyakov** [comment]
@galiagante which commit ID you use? 

Seeing this issue on 1.25.0 on short form commit id, like this
> git log --pretty=format:'%h' -n 1
> d9ad639

But it work on full commit id like this:
> d9ad639e704c5ab3a886651371bd6084a0b3f9d7

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/236 closes this one out
