### ISSUE TITLE
Bug : Panicking when running gitleaks with --repo-path in gitlab-ci  

### ISSUE THREAD

**Issue by hakkay** [zricethezav/gitleaks#192]
Hi,

I use the latest version (v.1.25.1) of Gitleaks in my pipeline to scan my repo with the --repo-path option.
Before the v1.25.1 gitleaks worked well in my gitlab repo but after this release my job always fail.
However When I use the --repo option to scan a remote repo in gitlab it works.  
Also when I used gitleaks locally with --repo-path option it works.

My Job gitleaks : 

`
gitleaks:
  image: docker:stable
  variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_DRIVER: overlay2
  services:
      - docker:dind
  script:
      - docker run --rm --name=gitleaks -v $(pwd)/:/code/  zricethezav/gitleaks -v --repo-path=/code --repo-config --threads=1 --report=/code/report.json || true
`

 The output log : 

`$ docker run --rm --name=gitleaks -v $(pwd)/:/code/  zricethezav/gitleaks -v --repo-path=/code --repo-config --threads=1 --report=/code/report.json || true
Unable to find image 'zricethezav/gitleaks:latest' locally
latest: Pulling from zricethezav/gitleaks
5d20c808ce19: Pulling fs layer
54a09226c381: Pulling fs layer
2ee7accc2ae8: Pulling fs layer
5d20c808ce19: Verifying Checksum
5d20c808ce19: Download complete
2ee7accc2ae8: Verifying Checksum
2ee7accc2ae8: Download complete
54a09226c381: Verifying Checksum
54a09226c381: Download complete
5d20c808ce19: Pull complete
54a09226c381: Pull complete
2ee7accc2ae8: Pull complete
Digest: sha256:*********************
Status: Downloaded newer image for zricethezav/gitleaks:latest
time="2019-04-03T08:15:56Z" level=info msg="opening /code"
time="2019-04-03T08:15:56Z" level=warning msg="recovering from panic on commit ***************, likely large diff causing panic"
...................
time="2019-04-03T08:15:57Z" level=warning msg="recovering from panic on commit ***************, likely large diff causing panic"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x576756]

goroutine 1 [running]:
regexp.(*Regexp).get(0x0, 0xc0000938c0)
	/usr/local/go/src/regexp/regexp.go:211 +0x26
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0004c3e90, 0x28, 0x0, 0x2, ...)
	/usr/local/go/src/regexp/exec.go:419 +0x40
regexp.(*Regexp).FindString(0x0, 0xc0004c3e90, 0x28, 0x0, 0x0)
	/usr/local/go/src/regexp/regexp.go:759 +0xa9
github.com/zricethezav/gitleaks/src.inspect(0xc0004c3e90, 0x28, 0x0, 0xc000a0c540, 0x35, 0xb18b95, 0x1, 0xc0004c3f50, 0x28, 0xc0002c9cd0, ...)
	/go/src/github.com/zricethezav/gitleaks/src/utils.go:99 +0x4e4
github.com/zricethezav/gitleaks/src.(*RepoInfo).auditSingleCommit.func1(0xc0007298b0, 0xc0007298b0, 0x0)
	/go/src/github.com/zricethezav/gitleaks/src/repo.go:313 +0x413
gopkg.in/src-d/go-git.v4/plumbing/object.(*FileIter).ForEach(0xc0007af920, 0xc000047b58, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/object/file.go:125 +0x87
github.com/zricethezav/gitleaks/src.(*RepoInfo).auditSingleCommit(0xc00006d540, 0xc0001ccff0, 0xc0004c3b60, 0x28, 0x103b9c0)
	/go/src/github.com/zricethezav/gitleaks/src/repo.go:288 +0xb5
github.com/zricethezav/gitleaks/src.(*RepoInfo).audit.func2(0xc0001ccff0, 0x0, 0x0)
	/go/src/github.com/zricethezav/gitleaks/src/repo.go:188 +0x17e
gopkg.in/src-d/go-git.v4/plumbing/object.(*commitAllIterator).ForEach(0xc00000c6a8, 0xc000372a40, 0xc0002e1180, 0xc00000c6a8)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/object/commit_walker.go:301 +0xb3
github.com/zricethezav/gitleaks/src.(*RepoInfo).audit(0xc00006d540, 0x0, 0x0, 0x7fff8c010f71, 0xc0000bde20, 0x429552)
	/go/src/github.com/zricethezav/gitleaks/src/repo.go:174 +0x3ae
github.com/zricethezav/gitleaks/src.Run(0xc0000a4b00, 0x0, 0x0, 0x0)
	/go/src/github.com/zricethezav/gitleaks/src/core.go:72 +0x46f
main.main()
	/go/src/github.com/zricethezav/gitleaks/main.go:11 +0x39`

  
Any help would be great :).

**Comment by zricethezav** [comment]
Yep definitely looks like a bug, thanks for submitting this. Will be looking into it

**Comment by hakkay** [comment]
The bug has been fixed in the latest release (v2.0.0), we can close this issue.
