### ISSUE TITLE
Consider "severity" or "tags" field for regexes configs

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#193]
Hi team, 

Thanks for the great tool, it's really cool!

It might be a good idea to have a way to groups findings. For example, as simple as adding severity field or tags into *.toml

Say, AWS findings are critical, and app related are less critical: 10 and 5 as severity.

```
# gitleaks.toml
title = "gitleaks config"
[[regexes]]
description = "AWS keys"
severity = "10'
tags = [ "aws", "key", "application", "infrastructure" ] 
regex = '''....'''

# adding your own
[[regexes]]
description = "Application keys"
severity = "5"
tags = [ "key", "application", "software" ] 
regex = '''app_key='''
```

These fields would be promoted into result JSON output. That way, we would be able to range our checks, slice and dice as needed.

Currently, I don't see a way to implement this. We tend to use formatted descriptions for our checks, like comma separated, so that later we can parse and normalize data into title, severity and descriptions for further analysis. Something like this:

```
# gitleaks.toml
title = "gitleaks config"
[[regexes]]
description = "10; AWS; AWS key"
regex = '''....'''
```

and then we parse in output JSON or other systems turning description "10; AWS; AWS key" into three fields:
* severity: 10
* title: AWS
* description: AWS key

Personally, I'd vote for tags, more universal approach. Hope that's fine, thanks again for a grea work!

**Comment by zricethezav** [comment]
Hey @avishnyakov I like this idea a lot. I'll work on putting this into my next release. I'm going to rework the language and values of the gitleaks.toml configuration file. Gonna look something like

```title = "gitleaks config"
[[rule]]
description = "Rule 1 - only entropy"
entropy = [ "3.3-4.30" ]

[[rule]]
description = "Rule 2 - AWS key in go files"
regex = '''AKIA[0-9A-Z]{16}'''
filetypes = [ "*.go" ]
tags = ["aws", "key"]
severity = "5"

[[rule]]
description = "Rule 3 - generic facebook"
regex = '''(?i)facebook.*['\"][0-9a-f]{32}['\"]'''

[whitelist]
regexes = [
  # "AKIA.*EXAMPLE",
]
files = [
  "(.*?)(jpg|gif|doc|pdf|bin)$"
]
```

**Comment by avishnyakov** [comment]
Sounds like a plan, thanks for listening @zricethezav .

On that note, rule ID might be a good idea, tracked here:
* Ability to run only particular regexes rule #194

That would simplify maintainability of the toml and rules tuning. Hope that make sense.

**Comment by zricethezav** [comment]
@avishnyakov v2.0.0 adds severity and tags https://github.com/zricethezav/gitleaks/wiki/config-toml
