### ISSUE TITLE
Ability to run only particular regexes rule(s)

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#194]
Might be overlooking but cannot find a way to run gitleaks with selected regexes rules.

**The first use** case is tuning our custom rules, testing on a smaller amount of data, ensuring that a particular rule works as needed:

```
# gitleaks.toml

title = "gitleaks config"

[[regexes]]
description = "rule-1"
regex = '''....'''

# adding your own
[[regexes]]
description = "rule-2"
regex = '''....''
```

It would be nice if we could do this in order to simplify rule tuning

```
gitleaks --rule rule-1 my-test-repo
expect 5 positives against test repo, assess with Pester/ServerSpec, etc

gitleaks --rule rule-2  my-test-repo
expect 16 positives against test repo, assess with Pester/ServerSpec, etc
```

**The second use case** is running a subset of the rules. For example, consider naming convention for all rules (or tags as in the other ticket). We have several subsets to address severe problems and get some insights on the source code (simply, hardcoded URLs, for example). Here is the config:

```
# gitleaks.toml

[[regexes]]
description = "mandatory.security.rule1"
regex = '''....'''

[[regexes]]
description = "mandatory.security.rule2"
regex = '''....'''

[[regexes]]
description = "optional.info.rule1"
regex = '''....'''

[[regexes]]
description = "optional.info.rule2"
regex = '''....'''
```

Now, we can say this:
```
# this must fail the build, mandatory checks
gitleaks --rule-ids "mandatory*" my-test-repo

# this kinda optional, info only
gitleaks --rule-ids "optional*" my-test-repo
```

Such an approach gives the ability to maintain and organize rules in a better way. Moreover, CLI becomes very powerful allowing pick and choose which rules to run and hence tune the behaviour needed. Just think about how we can organize and manage 50-150 rules in a better way.

Thoughts?

**Comment by avishnyakov** [comment]
Hey @zricethezav, there was a great progress on tags and severity and even entropy in https://github.com/zricethezav/gitleaks/issues/193

Did you have plan to implement this feature? Executing a single rule would have been a great win.

**Comment by zricethezav** [comment]
I don't plan on adding this feature since it is possible to test rules using a custom config. This is a bit more work for the end user but has the benefit of not cluttering the cli
