### ISSUE TITLE
Consider CLI option to validate toml config

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#195]
It would be nice to have --validate-config or similar option to ensure config validity prior execution.

Malformed toml or badly written regexp can result in super-mystic go stack trace. Might be not critical but surely challenging while playing with dozens of toml configs and tons of rules. 

> time="2019-04-12T00:47:12Z" level=error msg="problem loading config: Near line 28 (last key parsed 'whitelist.files'): invalid escape character 'R'; only the following escape characters are allowed: \\b, \\t, \\n, \\f, \\r, \\\", \\\\, \\uXXXX, and \\UXXXXXXXX"

Here is the one, something like this:

```
[[regexes]]
... legit stuff here

[whitelist]
files = [
     .. legit stuff here
     .. one bad line
    "TrustKit\README.md",
      .. legit stuff here
]
```

**Comment by zricethezav** [comment]
this is a great idea! Definitely going to work on implementing this in the next week or so

**Comment by zricethezav** [comment]
so taking another look at this I think this feature is already implemented since if gitleaks cannot load an external config it will exit. Also I agree that the error message is not the best but I am not going to be building an error message parser specifically for making toml errors more readable.
