### ISSUE TITLE
v2.0.0 Ignores Regexes defined in --config File

### ISSUE THREAD

**Issue by chu-fu** [zricethezav/gitleaks#199]
## Test Setup
```
root@6913f6cf4b98:/opt/gitleaks# cd /tmp
root@6913f6cf4b98:/tmp# mkdir secrets
root@6913f6cf4b98:/tmp# cd secrets
root@6913f6cf4b98:/tmp/secrets# git init
warning: templates not found /usr/share/git-core/templates
Initialized empty Git repository in /tmp/secrets/.git/
root@6913f6cf4b98:/tmp/secrets# echo "-----BEGIN PRIVATE KEY-----" > x
root@6913f6cf4b98:/tmp/secrets# echo "-----BEGIN OPENSSH PRIVATE KEY-----" >> x
root@6913f6cf4b98:/tmp/secrets# git add x
root@6913f6cf4b98:/tmp/secrets# git commit x -m "Example, true positives."                           
[master (root-commit) 08fc28f] Example, true positives.
 1 file changed, 2 insertions(+)
 create mode 100644 x
```
`root@6913f6cf4b98:/tmp/secrets# /usr/bin/gitleaks --version`

> 2.0.0

`root@6913f6cf4b98:/tmp/secrets# cat /opt/gitleaks/gitleaks.toml | grep KEY -B2`                        

> [[regexes]]
> description = "RKCS8"
> regex = '''-----BEGIN PRIVATE KEY-----'''
> [[regexes]]
> description = "SSH"
> regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''

`root@6913f6cf4b98:/tmp/secrets# /usr/bin/gitleaks -v --config /opt/gitleaks/gitleaks.toml --repo-path=.`

> INFO[2019-04-19T19:55:52Z] opening .                                    
> INFO[2019-04-19T19:55:52Z] 0 leaks detected. 1 commits inspected in 4 milliseconds`

## Default Config (Works as expected)

`root@6913f6cf4b98:/tmp/secrets# /usr/bin/gitleaks -v --repo-path=.`                                                                                                                                          

> INFO[2019-04-19T19:58:48Z] opening .                                    
> {
>    "line": "-----BEGIN PRIVATE KEY-----",
>    "commit": "08fc28f671d000b3153f5768dcdc81ca429d9392",
>    "offender": "-----BEGIN PRIVATE KEY-----",
>    "rule": "PKCS8",
>    "info": "-----BEGIN PRIVATE KEY----- regex match",
>    "commitMsg": "Example, true positives. ",
>    "author": "root",
>    "email": "root@example.com",
>    "file": "x",
>    "repo": ".",
>    "date": "2019-04-19T19:47:39Z",
>    "tags": "key, PKCS8",
>    "severity": ""
> }
> {
>    "line": "-----BEGIN OPENSSH PRIVATE KEY-----",
>    "commit": "08fc28f671d000b3153f5768dcdc81ca429d9392",
>    "offender": "-----BEGIN OPENSSH PRIVATE KEY-----",
>    "rule": "SSH",
>    "info": "-----BEGIN OPENSSH PRIVATE KEY----- regex match",
>    "commitMsg": "Example, true positives. ",
>    "author": "root",
>    "email": "root@example.com",
>    "file": "x",
>    "repo": ".",
>    "date": "2019-04-19T19:47:39Z",
>    "tags": "key, SSH",
>    "severity": ""
> }
> WARN[2019-04-19T19:58:48Z] 2 leaks detected. 1 commits inspected in 48 milliseconds`
> 

## Working version with same config. (Expected Result)
`root@6913f6cf4b98:/tmp/secrets# /bin/gitleaks --version`

> 1.25.1

`root@6913f6cf4b98:/tmp/secrets# /bin/gitleaks -v --config /opt/gitleaks/gitleaks.toml --repo-path=. `

> INFO[2019-04-19T19:56:27Z] opening .                                    
> {
>    "line": "-----BEGIN PRIVATE KEY-----",
>    "commit": "08fc28f671d000b3153f5768dcdc81ca429d9392",
>    "offender": "-----BEGIN PRIVATE KEY-----",
>    "reason": "RKCS8",
>    "commitMsg": "Example, true positives. ",
>    "author": "root",
>    "email": "root@example.com",
>    "file": "x",
>    "repo": ".",
>    "date": "2019-04-19T19:47:39Z"
> }
> {
>    "line": "-----BEGIN OPENSSH PRIVATE KEY-----",
>    "commit": "08fc28f671d000b3153f5768dcdc81ca429d9392",
>    "offender": "-----BEGIN OPENSSH PRIVATE KEY-----",
>    "reason": "SSH",
>    "commitMsg": "Example, true positives. ",
>    "author": "root",
>    "email": "root@example.com",
>    "file": "x",
>    "repo": ".",
>    "date": "2019-04-19T19:47:39Z"
> }
> WARN[2019-04-19T19:56:27Z] 2 leaks detected. 1 commits inspected in 88 milliseconds

**Comment by zricethezav** [comment]
The config structure has changed to use a `rules` table instead of `regexes`

**Comment by zricethezav** [comment]
@chu-fu  please see https://github.com/zricethezav/gitleaks/wiki/config-toml
