### ISSUE TITLE
checkRegex test fails

### ISSUE THREAD

**Issue by arjunyel** [zricethezav/gitleaks#2]
Looks like the test is failing because checkRegex is being assigned to two vars but only returns one, a string[]

https://github.com/zricethezav/gitleaks/blob/06c2141a02ce51ab8ba9726c5d03a4a3f41f0004/checks_test.go#L23

**Comment by zricethezav** [comment]
good catch, should probably set this up on travis

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/commit/6eba1bb24e32a532f375715d5b8ebed26a644f27 simple fix for now
