### ISSUE TITLE
Brew install out of date

### ISSUE THREAD

**Issue by jdesulme** [zricethezav/gitleaks#201]
I noticed that when I perform a brew install that it's a couple versions behind. Is there any plans to keep the versions in sync and pull the latest since it's now a bit out of date? 

```
$ brew install gitleaks
Warning: gitleaks 1.24.0 is already installed and up-to-date
To reinstall 1.24.0, run `brew reinstall gitleaks
```
https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitleaks.rb

**Comment by zricethezav** [comment]
Thank you for opening this. Will prepare a PR tonight.

**Comment by zricethezav** [comment]
@jdesulme https://github.com/Homebrew/homebrew-core/pull/40734 just gotta wait for them to merge

**Comment by zricethezav** [comment]
@jdesulme done

**Comment by jdesulme** [comment]
Thank you!!
