### ISSUE TITLE
Feature Request: Scan all users of an organization

### ISSUE THREAD

**Issue by janmasarik** [zricethezav/gitleaks#205]
Hey 👋,

First, thanks for your awesome work, I really love the new _rules_ option in config! 

It would be cool if `gitleaks`, much like [`gitrob`](https://github.com/michenriksen/gitrob) could take an organization and automatically scan all the users of it. 

Do you see this as a possible addition to gitleaks?

**Comment by zricethezav** [comment]
@janmasarik that's definitely a feature that could be added. Next minor release I'll work on putting that in

**Comment by janmasarik** [comment]
Wow, that escalated quickly, thanks @zricethezav! 😅 👍 

I have one more separate question - do you plan on implementing a directory scan? (something like https://github.com/dxa4481/truffleHog/issues/92) 

Should I create a separate feature request for it or have I overlooked it and it's already implemented somehow?

**Comment by zricethezav** [comment]
You can do a directory scan with `--repo-path` or `--owner-path`
From the `--help`:
```
      --repo-path=     Path to repo
      --owner-path=    Path to owner directory (repos discovered)
```

**Comment by janmasarik** [comment]
Tried it already, but when I point it to `/tmp/dir/` with either `--repo-path=` or `--owner-path=`, it won't any find secrets in `/tmp/dir/file-with-secrets.py`. 

My use case would be to do simple run on files, without the need to initialize a git repo, and based on the number of 👍 in Trufflehog, I believe I'm not the only one. :-)  


#### Steps to reproduce:
```
docker run -v /home/user/config:/data -v /tmp:/tmp s14ve/gitleaks  --repo-path=/tmp/dir --config=/data/gitleaks.toml -v --report=/data/gitleaks.csv
```

`--repo-path=`  output:
```
time="2019-05-10T15:07:23Z" level=info msg="opening /tmp/dir/"
time="2019-05-10T15:07:23Z" level=error msg="unable to open /tmp/dir/"
time="2019-05-10T15:07:23Z" level=info msg="0 leaks detected. 0 commits inspected in 12 milliseconds"
```

`--owner-path=` output:
```
time="2019-05-10T15:06:48Z" level=info msg="0 leaks detected. 0 commits inspected in 8 milliseconds"
```

Thing is that even if I do `git init` in `/tmp/dir`, it won't find anything as it seems to go only through commits. 

Once I do `git add * && git commit -m "Commit secrets"`, it detects the secrets right away.

**Comment by janmasarik** [comment]
Hey @zricethezav, do you still see this as a possible addition?

Even though my Go skills are non-existent, I can try to help. Based on a brief look, it should be a fairly straightforward addition as a function in https://github.com/zricethezav/gitleaks/blob/master/src/github.go, that will call `auditGithubRepos()` on each user found, right?

**Comment by zricethezav** [comment]
This should be done in a script
