### ISSUE TITLE
Fedramp and compliance

### ISSUE THREAD

**Issue by ORESoftware** [zricethezav/gitleaks#206]
With regard to fedramp

https://www.fedramp.gov/

any idea if gitleaks gets us close to fulfilling the requirements?

**Comment by zricethezav** [comment]
Hi @ORESoftware what requirements are you referring to?

**Comment by ORESoftware** [comment]
Not sure, just wondering if this repo could document what kind of compliance it can satisfy

**Comment by zricethezav** [comment]
If you want to do some more research on how Gitleaks could offer some compliance in accordance with fedramp then by all means open another issue. No plans to work on it atm so I'm closing this issue
