### ISSUE TITLE
Only scan additions, ignore removals

### ISSUE THREAD

**Issue by Incisive** [zricethezav/gitleaks#207]
Thanks for this great tool! 

Hoping to get some clarification here surrounding commits.  I've setup automation around Gitleaks to scan commits as they happen on a few repositories, however, the tool is alerting when the secret is first committed, and then alerting a second time when it's removed (not a file deletion, but a line removal).

Is there any configuration options to disable alerts when lines are deleted? And only have it trigger when something is added?

Doing something like below is how I'd do it from the CLI, but I see you're using go-git, and I'm afraid I'm not familiar enough with that library to make a PR for this.

```
# Only show added lines
git show 7d81268492972fc3f25c0e8c10ca530f76b3cff4 | grep -E "^\+" 
```

**Comment by zricethezav** [comment]
that's a good call out. I can look to add this in a future release.

**Comment by milo-minderbinder** [comment]
This is something I’ve wanted too, and I’ve implemented it in my personal fork. The basic functionality only required modifying a few lines IIRC, but one issue that I came across is that `go-git`s diff algorithm does not detect renamed/moved files like cgit and will instead mark them as new additions ([link to open issue](https://github.com/src-d/go-git/issues/938)). This may or may not be a major annoyance depending on your use case, but if you’re like me and you’re trying to find the exact commit where a secret was _actually_ first introduced so you can scrub it from the git history with BFG, it definitely makes things more annoying. Anyway, if it’s helpful I can dig up my changes and create a PR if helpful, but figured I’d share the potential issue for what it’s worth.

**Comment by dorneanu** [comment]
This is indeed a missing feature. Fortunately I use GitHub webhooks to receive information about current commits. And in that event message I do have the removed and added files as lists. My plan was:

1) Checkout repo with specific commit SHA (via `go-git`)
2) Use `gitleaks` to scan only *added* files

However `gitleaks` doesn't support scanning only individual files (yet). I might have a look at the code and submit some PR. 

BR,
Victor

**Comment by xfornesa** [comment]
Related to #268

**Comment by zricethezav** [comment]
@Incisive This is the default behavior now. https://github.com/zricethezav/gitleaks/releases/tag/v5.0.0
