### ISSUE TITLE
Scan all commits - and cache commits that have already been scanned

### ISSUE THREAD

**Issue by ORESoftware** [zricethezav/gitleaks#208]
Couple questions for you

1. how to scan all commits
2. how to cache which commits have already been scanned

is there a way to do this with gitleaks?

**Comment by ORESoftware** [comment]
I ran it like so:
```
docker run --rm --name=gitleaks \
   -v "$HOME/.ssh:/root/.ssh:ro"  \
   zricethezav/gitleaks  \
   --ssh-key=/root/.ssh/oresoftware \
   --repo git@gitlab.com:HURU/api-vertx.git
```

it says:

```
time="2019-05-10T17:59:19Z" level=info msg="cloning git@gitlab.com:HURU/api-vertx.git"
Enumerating objects: 210, done.
Counting objects: 100% (210/210), done.
Compressing objects: 100% (187/187), done.
Total 210 (delta 107), reused 0 (delta 0)
time="2019-05-10T17:59:21Z" level=info msg="0 leaks detected. 5 commits inspected in 2 seconds 287 milliseconds"
```

so it looks like it went through all the commits, but it would be cool if we could cache that somewhere, so we don't always have to go through all the commits

**Comment by zricethezav** [comment]
you can use `commit-stop` option:
```
      --commit-stop=    sha of commit to stop at
```
So I would a full gitleaks audit and take note of the most recent commit then use that as the value for `--commit-stop`
