### ISSUE TITLE
more stopWords please

### ISSUE THREAD

**Issue by ryh** [zricethezav/gitleaks#21]
- BEGIN CERTIFICATE
 (.crt CERTIFICATE)
- BEGIN RSA PRIVATE KEY
 (.key PRIVATE KEY)
- secret
 (Oauth or  jwt.io or other API but passed the regx check)

and there some false alarm with 

```
[
	{
		"content": "+[![Cocoapods](https://cocoapod-badges.herokuapp.com/v/DateTools/badge.png)](http://cocoapods.org/?q=datetools)",
		"commit": "70b07b600c79cfaf7dbcc68402dbda73d32e965e"
	},
	{
		"content": "+[![Cocoapods](https://cocoapod-badges.herokuapp.com/v/DateTools/badge.png)](http://cocoapods.org/?q=datetools)",
		"commit": "f6f9cbe91ce9564ffe65c3dede2dbab017d95eb5"
	}
]
```

**Comment by zricethezav** [comment]
False positives taken care of here: https://github.com/zricethezav/gitleaks/releases/tag/v0.2.0.
RSA handled. Will look into .crt and .key
