### ISSUE TITLE
Cannot get ssh-keys to work with Docker container running as sibling container

### ISSUE THREAD

**Issue by ORESoftware** [zricethezav/gitleaks#212]
It's fairly common to run Jenkins as a container - `jenkins/jenkins:lts`, ran like so:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock  jenkins/jenkins:lts
```

so any container launched within Jenkins jobs, is running as "a container in a container", in reality though they should be sibling containers both launched by the host fs.

However, even so, I can't seem to get my ssh keys into the gitleaks container using the docker --volume option. Has anyone else reported this probem to you? Not really a problem with gitleaks perse, although it would be nice to document a solution here.

**Comment by zricethezav** [comment]
gitleaks is not responsible for cloning in v8+
