### ISSUE TITLE
support multiple commits at the command line

### ISSUE THREAD

**Issue by ORESoftware** [zricethezav/gitleaks#215]
Right now there is a CLI option:

``` 
--commit=         sha of commit to audit
```

I am looking for something like this:

```
--commits=         comma separated sha's of commits to audit
```

or just keep --commit and split on commas?

Basically  I want to be able to test 5-50 commits at once:

```
gitleaks --commit=$1 --commit=$2 --commit=$3 --commit=$4  ... --commit=50
```

**Comment by zricethezav** [comment]
No plans to add this, submit a PR if you want to implement this feature
