### ISSUE TITLE
gitleaks isn't finding 'password', when there is a password?

### ISSUE THREAD

**Issue by hannylicious** [zricethezav/gitleaks#217]
I've installed gitleaks on my development machine (macOS) and I've cloned my repo locally.
In my repo - there is some dummy data that is listed (and committed) to the repo - stuff like 

`password=r@nd0mp@assw0rdomg`

and a few other key things I'd like to check for in some repos.

Here is my process:

cd into repo directory
run `gitleaks --repo ./`

It says it checks the commits (which seems to be accurate in terms of how many commits) but it doesn't find the sample data I've put in there.

Am I using this wrong? Or is there a different way to tweak this?
I could be completely off - so I apologize if I'm misunderstanding the scope of the tool.

**Comment by zricethezav** [comment]
Hi @hannylicious you need to specifically define the regex gitleaks should look for in a config file 

something like 
```
[[rules]]
description = "Generic Password"
regex = '''(?i)password(.{0,6})?(:|=|=>|:=)'''
tags = ["generic", "password"]
```

You can see what gitleaks will currently audit for if you look at the config here: https://github.com/zricethezav/gitleaks/blob/master/gitleaks.toml

**Comment by mad-eye21** [comment]
> 
> 
> I've installed gitleaks on my development machine (macOS) and I've cloned my repo locally.
> In my repo - there is some dummy data that is listed (and committed) to the repo - stuff like
> 
> `password=r@nd0mp@assw0rdomg`
> 
> and a few other key things I'd like to check for in some repos.
> 
> Here is my process:
> 
> cd into repo directory
> run `gitleaks --repo ./`
> 
> It says it checks the commits (which seems to be accurate in terms of how many commits) but it doesn't find the sample data I've put in there.
> 
> Am I using this wrong? Or is there a different way to tweak this?
> I could be completely off - so I apologize if I'm misunderstanding the scope of the tool.

I'm also facing same issue with username and passwords and some patterns of database username password also, it is not able to detect but value is given in file.

**Comment by zricethezav** [comment]
@mad-eye21 did you supply a custom config?

**Comment by mad-eye21** [comment]
Hi,
I'm actually using gitleaks-linux-amd64 binary file and moving it to /usr/local/bin/ to use it direct.
I don't have any idea how to use configuration file with this.

**Comment by mad-eye21** [comment]
> 
> 
> @mad-eye21 did you supply a custom config?

![git](https://user-images.githubusercontent.com/48945491/58790295-b91ea180-860d-11e9-8ab8-d5d4ffcb4147.JPG)
like this?

**Comment by mad-eye21** [comment]
> 
> 
> > @mad-eye21 did you supply a custom config?
> 
> ![git](https://user-images.githubusercontent.com/48945491/58790295-b91ea180-860d-11e9-8ab8-d5d4ffcb4147.JPG)
> like this?

OK its working like this 
![25 leakes](https://user-images.githubusercontent.com/48945491/58796009-bcb82580-8619-11e9-82e8-3821c14ab9a5.JPG)

with command "gitleaks --config=/home/gitleaks.toml --repo=https://github.com/yourproject.git –v"

**Comment by zricethezav** [comment]
@mad-eye21 yep, exactly. @hannylicious is this still an issue or can I close this?

**Comment by jaikishantulswani** [comment]
Hi @zricethezav I am also not getting any issue flagged by gitleaks even on a fresh install.
Getting this
```
./gitleaks --config=gitleaks.toml --repo=https://github.com/user/private.git –v
INFO[2019-06-03T18:25:15+05:30] cloning https://github.com/user/private.git 
Enumerating objects: 33, done.
Total 33 (delta 0), reused 0 (delta 0), pack-reused 33
INFO[2019-06-03T18:25:17+05:30] 0 leaks detected. 10 commits inspected in 1 second 870 milliseconds 

```

**Comment by mad-eye21** [comment]
> 
> 
> @mad-eye21 yep, exactly. @hannylicious is this still an issue or can I close this?

I got the solution and making my own regex to make tool work according to me.
Thanks for your help and this tool.
issue is solve you can close it.

**Comment by zricethezav** [comment]
@jaikishantulswani what are the contents of your config and what regex are you looking for?

**Comment by jaikishantulswani** [comment]
@zricethezav Its working now, kind of regex issue. Thanks
