### ISSUE TITLE
Filter repositories of user/organisation 

### ISSUE THREAD

**Issue by chneau** [zricethezav/gitleaks#22]
Hello,

Something I noticed is, if I fork a big project (like [node](https://github.com/nodejs/node) or better, the [linux kernel](https://github.com/torvalds/linux) ) and then I scan myself, it will take a while !

From here I can see two areas that can get an enhancement:
- Options to scan or not forked project
- Options to filter repos by size ( number of commits, project size or number of files ?)
- (Or scan repositories ordered by size, so at some point I could kill the process)

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v1.9.0 and https://github.com/zricethezav/gitleaks/releases/tag/v1.8.0 can do this filtering @chneau
