### ISSUE TITLE
Can't scan an org

### ISSUE THREAD

**Issue by timidri** [zricethezav/gitleaks#220]
HI,

I'm trying to use gitleaks to scan an org, I am calling it like this:

`gitleaks --github-org=<my-org-name> --log=debug`

and this is my result:

`INFO[2019-05-17T12:29:13+02:00] 0 leaks detected. 0 commits inspected in 11 seconds 583 milliseconds`

What am I doing wrong here? I can scan other orgs and my user normally so I am assuming I don't have the right permissions in the org? I can see it through the github UI though.

Thanks for the awesome tool!

**Comment by zricethezav** [comment]
Since you can scan other orgs and users this is likely an issue with running gitleaks without a github token env var set. Gitleaks needs to hit the github api with a valid github token in order to scan private repos in an organization

**Comment by timidri** [comment]
@zricethezav Thanks, will try this out and report my findings.

**Comment by timidri** [comment]
@zricethezav I have created a personal token and exported a variable GITHUB_TOKEN. I still can't scan that particular org. Do I by any chance need admin permissions in an org in order to be able to scan?

**Comment by zricethezav** [comment]
Hi @timidri would you be willing to share the org name? What version of gitleaks are you running?

**Comment by timidri** [comment]
Hi @zricethezav, I have done some debugging of the source think I found the root cause.
In github.go onl line 146 the following call is made:
```
pagedGithubRepos, resp, err = githubClient.Repositories.ListByOrg(ctx, opts.GithubOrg, githubOrgOptions)
```
This call returns "502 Bad Gateway" on my org (puppetlabs) which contains lots of repositories. I have had the same problem with that org with my own project which uses the same go-github library as yours. The issue is described here: https://github.com/google/go-github/issues/999. I have not been able to find a workaround until now.

**Comment by zricethezav** [comment]
I no longer support gitlab/github integrations
