### ISSUE TITLE
can't install with go

### ISSUE THREAD

**Issue by Aholicknight** [zricethezav/gitleaks#221]
I am trying to install goleaks on my kali virtual machine and it shows no output when I try to install with go. This is the command I use:
![image](https://user-images.githubusercontent.com/7843719/57977551-27c9f100-79b8-11e9-8587-3dce69a8291d.png)
No output shows and when i type `uname -r` it says: 
`Linux kali 4.19.0-kali1-686-pae #1 SMP Debian 4.19.13-1kali1 (2019-01-03) i686 GNU/Linux`
Does anyone know how to resolve this issue? Thanks.

**Comment by fr0stedfl4ke** [comment]
I tried using Kali Linux as well and it doesn't work by default. You have to properly configure the go language environment variables and setup the environment variables as GOROOT,GOPATH and PATH and set the PATH variable to access go binary system wide. I ended up just starting from scratch and using this guide: https://tecadmin.net/install-go-on-debian/. See if this helps.

**Comment by jonfairbanks** [comment]
Saw similar when install Go with snap/apt on Ubuntu 18.04.

Fixed with the following:
```
which go
export GOROOT=/usr/bin/
export GOPATH=$HOME/Go/
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
go get -u github.com/zricethezav/gitleaks
```

**Comment by jonfairbanks** [comment]
Ran into the same issue on Ubuntu 18.04. Here was the fix:
```
export GOPATH=$HOME/Go/
export PATH=$GOPATH/bin:$PATH
```
You can add these to **~/.profile** so they persist a reboot.

**Comment by dbuteau** [comment]
got the same problem, i've done this if it can help to understand the prb.
Seem like the dependencie with xanzy is broken
```
$ go get -v -u   github.com/xanzy/go-gitlab
[...]
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
github.com/xanzy/go-gitlab
# github.com/xanzy/go-gitlab
../../../go/src/github.com/xanzy/go-gitlab/runners.go:87:9: undefined: json
../../../go/src/github.com/xanzy/go-gitlab/runners.go:87:22: undefined: strings
```

**Comment by zricethezav** [comment]
Solution: https://github.com/zricethezav/gitleaks/issues/405#issuecomment-653691458
