### ISSUE TITLE
Adding new regexs

### ISSUE THREAD

**Issue by ni8walk3r** [zricethezav/gitleaks#225]
How can we add our own custom regex in this tool?

**Comment by zricethezav** [comment]
Create a config like this https://github.com/zricethezav/gitleaks/blob/master/gitleaks.toml with your custom regexes and then point gitleaks to that config when you run it by either setting the env var `GITLEAKS_CONIFG` as the path to the config or by using the `--config` option

**Comment by utkrsht** [comment]
Thanks a lot!

**Comment by zricethezav** [comment]
@ni8walk3r does that make sense?

**Comment by zricethezav** [comment]
@ni8walk3r reopen if that doesn't work out for you

**Comment by ni8walk3r** [comment]
@zricethezav Yeah, thanks for your help.
