### ISSUE TITLE
What is entropyROI and entropies ?

### ISSUE THREAD

**Issue by jameslindisney** [zricethezav/gitleaks#228]
Please point out documentation if there is any. Thanks.

**Comment by jameslindisney** [comment]
Can you explain what is  entropyROI and entropies ? There is absolutely no explanation or documentation so far?

**Comment by zricethezav** [comment]
Hi @jameslindisney. Thanks for pointing out this hole in documentation. Let me know if this wiki page I just created helps. https://github.com/zricethezav/gitleaks/wiki/config-toml

**Comment by rgmz** [comment]
> Hi @jameslindisney. Thanks for pointing out this hole in documentation. Let me know if this wiki page I just created helps. https://github.com/zricethezav/gitleaks/wiki/config-toml

Hi @zricethezav, I have done some research but still do not understand how to actually use "entropies". Can you please explain the significance of entropy ranges and why they're between 0-8? 

Thank you!
