### ISSUE TITLE
Save report on HUP

### ISSUE THREAD

**Issue by pdparchitect** [zricethezav/gitleaks#233]
No report will be saved if the user attempts to kill the process. This means that if gitleaks was running for couple of hours and the user decides to terminate the process the results will be lost.

This feature request is to add a feature where gitleaks will attempt to save the results when kill signal is sent to the process.

**Comment by zricethezav** [comment]
Agreed, thanks for raising this issue.

**Comment by zricethezav** [comment]
@pdparchitect adding this in next release. super easy to implement

**Comment by zricethezav** [comment]
added in v3.0.0 https://github.com/zricethezav/gitleaks/releases/tag/v3.0.0

**Comment by soorajnr** [comment]
is it possible to access external scanner device for preview and scanning

**Comment by zricethezav** [comment]
@soorajnr I'm not sure what you mean by that, if you could open another issue and expand on this it that would be great.
