### ISSUE TITLE
Feature Request: Stateful Tracking of Previous Scans

### ISSUE THREAD

**Issue by galiagante** [zricethezav/gitleaks#234]
Use case: Repetitive scanning a large number of repos with a large number of commits and branches can become increasingly resource and time intensive. The ability to track the last known commit ID's within a given branch for a given repo can be used as a way to avoid previously scanned information and yield results for newly-committed assets more quickly. As scans complete, the commit ID pointer(s) can be updates accordingly. Under the hood, these pointers might be used in conjunction with the "--commit-depth" functionality.

The feature does not seem useful as a default stance, and might be better controller via command-line flag (like '--track').

**Comment by zricethezav** [comment]
Gitleaks v8 should have the performance to avoid the need to statefully track scans. I don't have any plans to introduce this at this time
