### ISSUE TITLE
Feature Request: Scan specified daterange

### ISSUE THREAD

**Issue by galitz** [zricethezav/gitleaks#235]
For large and/or complex enterprise github sites, the ability to scan on specified daterange would be very useful.  With a large number of repos or orgs, using commits or depth to bound a scan requires significant research to generate a clean report.

Propose example:  gitleaks -r /something --from=2019-01-31 --until=2019-02-15

**Comment by avishnyakov** [comment]
Double that. Very useful for continuous scanning implementation.
Right now, continuous scanning with gitleaks is a bit of a pain.

**Comment by zricethezav** [comment]
```
	CommitSince   string `long:"commit-since" description:"Scan commits more recent than a specific date. Ex: '2006-01-02' or '2006-01-02T15:04:05-0700' format."`
	CommitUntil   string `long:"commit-until" description:"Scan commits older than a specific date. Ex: '2006-01-02' or '2006-01-02T15:04:05-0700' format."`
```

@galitz @avishnyakov Use `--commit-since` and `--commit-from`
