### ISSUE TITLE
--commit-stop appears broken

### ISSUE THREAD

**Issue by electrofelix** [zricethezav/gitleaks#237]
The `--commit-stop` option does not appear to be working as expected.

Given a test git repo with the following
```
*   0890661f9f2104c94d697ff68930d1f98c097be2 (HEAD -> pr1) Merge branch 'master' into pr1
|\
| * ca4117fe8ffdc8b26080f45dc197a888edfbec0c (master) commit 3
| * a8326badc2612b1f1e366c7ba9497524979c70ef commit 2
* | ff9b23d5863b822ba26cd9352bc981d6c36a2cc9 commit 6
* | 2cc0e3e48da1a212a60b86273564ede96c87942c commit 5
* | 6c2545c3b34a8725123507950cb1373f09bbe143 commit 4
|/
* f3f185f178bb02d13ad090fbf98dadb53b17730f commit 1
* 3393b6b25130a41a395b34343a945cba6638afd5 initial commit
```

Running gitleaks on it with `--commit-stop=f3f185f178bb02d13ad090fbf98dadb53b17730f` I would expect to see a summary output saying that either 6 or 7 commits were scanned (wasn't sure if it was exclusive or inclusive), but instead it prints 8 commits scanned

```
time="2019-06-26T10:40:02Z" level=info msg="0 leaks detected. 8 commits inspected in 3 milliseconds"
```

I've was trying this on real repos and it seemed to always scan the entire history, no matter what I put as the stop commit so created a test repo just to be sure.

Args passed to it (running via a docker container on a local repo mounted at /src):
```
--repo-path=/src --commit-stop=f3f185f178bb02d13ad090fbf98dadb53b17730f
```

**Comment by zricethezav** [comment]
@electrofelix https://github.com/zricethezav/gitleaks/releases/tag/v3.1.0 reimplemented the `commit-stop` feature. Let me know if this doesn't work for ya
