### ISSUE TITLE
passwords\token leaks 

### ISSUE THREAD

**Issue by legik** [zricethezav/gitleaks#243]
If someone will use oauth2 or username/password authentication for repo cloning, the password\token would be leaked in the "INFO" message. But in the "ERROR" message it's masked. I think that it should be masked in both places. You can see examples in the image below:
![2019-07-25_11-21](https://user-images.githubusercontent.com/657615/61858510-e3cefd00-aece-11e9-8b2e-4c760c56024b.png)

**Comment by avishnyakov** [comment]
Had similar one.

This is exactly why we might want to separate gitleaks execution against repository from fetching repository. Adding more options to work with different providers would increase gitleaks scope and featureset leading to more work and bugs.

Instead adding more and more options to gitleaks, we might just script fetching the source code externally, in separate script or docker container, and then use gitleaks agains already fetched codebase.

**Comment by zricethezav** [comment]
I believe this issue has been resolved, reopen if still a problem
