### ISSUE TITLE
Hit error when trying to scan github enterprise using user

### ISSUE THREAD

**Issue by WaiLoonTan** [zricethezav/gitleaks#245]
I need to scan all the repositories belong to organizations of my user.

This is under Github Enterprise.

I already set the token for my user

When i run the command 

 `gitleaks --github-user=user_name --log=debug -v`

it returned 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x9e1ef1]

goroutine 1 [running]:
github.com/zricethezav/gitleaks/src.auditGithubRepos(0xc0000b4870, 0x0, 0x0)
        C:/Gitleak/src/github.go:151 +0x4c1
github.com/zricethezav/gitleaks/src.Run(0xc000068c80, 0x0, 0x0, 0x0)
        C:/Gitleak/src/core.go:92 +0x2a4
main.main()
        C:/Gitleak/main.go:12 +0x32

Do i need to set other parameters ?

**Comment by cameronc56** [comment]
We are seeing the same thing: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b6283]

goroutine 1 [running]:
gopkg.in/src-d/go-git.v4/plumbing/object.(*Blob).Reader(...)
	/Users/zrice/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/object/blob.go:93
gopkg.in/src-d/go-git.v4/plumbing/object.(*File).IsBinary(0x0, 0x0, 0x0, 0x0)
	/Users/zrice/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/object/file.go:48 +0x33
github.com/zricethezav/gitleaks/src.(*Repo).auditTreeChange(0xc000130e00, 0xc019e020f0, 0xc019e02000, 0x0, 0x0)
	/Users/zrice/go/src/github.com/zricethezav/gitleaks/src/repo.go:442 +0x207
github.com/zricethezav/gitleaks/src.(*Repo).auditSingleCommit(0xc000130e00, 0xc019e02000, 0xdd22f8c955adf6b8, 0x986ed0e7c55fd547)
	/Users/zrice/go/src/github.com/zricethezav/gitleaks/src/repo.go:362 +0x1df
github.com/zricethezav/gitleaks/src.(*Repo).audit(0xc000130e00, 0x0, 0x0)
	/Users/zrice/go/src/github.com/zricethezav/gitleaks/src/repo.go:180 +0x7e8
github.com/zricethezav/gitleaks/src.Run(0xc0000deb40, 0x0, 0x0, 0x0)
	/Users/zrice/go/src/github.com/zricethezav/gitleaks/src/core.go:65 +0x105
main.main()
	/Users/zrice/go/src/github.com/zricethezav/gitleaks/main.go:12 +0x2b

**Comment by cameronc56** [comment]
The command I am running is: 

['/redacted/file/path/gitleaks-linux-amd64', '--repo=/redacted/repo/path', '--config=/redacted/file/path/.gitleaks.toml', '--redact', '--commit=b8f6ad55c9f822dd47d55fc5e7d06e98a6248b09', '--report=/redacted/file/path/scan.json']

There doesn't appear to  be anything odd in the commit we are scanning either. And this has been scanning hundreds of commits without issues until this one.

**Comment by avishnyakov** [comment]
To be fair, this could be feature creep. Adding more features to support multiple git hosting services leads to increased complexity of the gitleaks itself.

It might just make it KISS focusing on scanning capabilities, and "the how" code gets into gitleaks is surely not the gitleaks responsibility.

**Comment by zricethezav** [comment]
Again, what @avishnyakov said. Ditching this with https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0. I'm not supporting gitlab/github integrations anymore.
