### ISSUE TITLE
Generic API key regex in config example inconsistent with sample config

### ISSUE THREAD

**Issue by izgeri** [zricethezav/gitleaks#247]
The sample config that you get when you run `gitleaks --sample-config` in v2.1.0 shows the regex for the `Generic API key` to be
```
'''(?i)(api_key|apikey)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
```
but the `gitleaks.toml` file [in this repo](https://github.com/zricethezav/gitleaks/blob/master/gitleaks.toml#L96) lists it as
```
'''(?i)api_key(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
```

In practice I've found that the first version is more effective than the second version. Can the gitleaks.toml file in this repo be updated to be consistent with the `sample-config`? Thanks!

**Comment by zricethezav** [comment]
good catch!

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/commit/c271497ecbd08cc636d9309fd28d174d656926b5 thanks for pointing that out. I'd like to add a CI process that ensures parity between the example toml and the hardcoded default config 👍
