### ISSUE TITLE
--repo-config with missing config file always succeeds

### ISSUE THREAD

**Issue by apotterri** [zricethezav/gitleaks#248]
Running `gitleaks  --repo-config ...` in a repo without a config file always succeeds:

```
$ ls -l .gitleaks.toml
ls: .gitleaks.toml: No such file or directory
$ gitleaks --repo-config --repo-path .
INFO[2019-08-03T05:11:42-04:00] opening .
INFO[2019-08-03T05:11:42-04:00] 0 leaks detected. 0 commits inspected in
$ echo $?
0
```

Per the description in the README, it should return 2, with an error message indicating that the repo config file doesn't exist.

**Comment by bufferoverflow** [comment]
@apotterri does `gitleaks --repo-config --repo-path=./` work?

**Comment by zricethezav** [comment]
v3.0.0+ should handle this error correctly: 
```
./gitleaks --repo-config --repo-path=.
ERRO[2020-01-12T10:17:16-05:00] problem loading repo config: open /Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/gitleaks.toml: no such file or directory
```
Reopen the issue if it remains an issue
