### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by styfle** [zricethezav/gitleaks#25]
Can I install gitleaks [without installing Go](https://stackoverflow.com/q/33945738/266535)?
Or maybe a better question is, can you attach the binaries to the [GitHub Releases](https://github.com/zricethezav/gitleaks/releases)?

**Comment by zricethezav** [comment]
Good call, will be working on this this weekend.

**Comment by zricethezav** [comment]
@styfle binaries here: https://github.com/zricethezav/gitleaks/releases/tag/v0.4.0

**Comment by styfle** [comment]
Thanks, I'll check it out! 👍
