### ISSUE TITLE
travis fails on all pull requests

### ISSUE THREAD

**Issue by bufferoverflow** [zricethezav/gitleaks#250]
I have the feeling that all build fail if sent via pull request. Maybe the following variables have an impact on this?
https://github.com/zricethezav/gitleaks/blob/master/.travis.yml#L15

**Comment by zricethezav** [comment]
That's exactly what is happening. I've been meaning to switch over to github actions or gitlab ci. Good thread on why things are failing here: https://github.com/OHDSI/Achilles/issues/165

**Comment by bufferoverflow** [comment]
thanks @zricethezav ! gitlab ci has a limitation... PR's do not build, this might change, see https://gitlab.com/gitlab-org/gitlab-ee/issues/5667 and https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/15082

**Comment by zricethezav** [comment]
Rewrote the tests so this does not rely on any external apis or git repos
