### ISSUE TITLE
Question & Suggestion on Report

### ISSUE THREAD

**Issue by mousavian** [zricethezav/gitleaks#251]
Hey @zricethezav ,
First of all, thank you for this beautiful library. What it does is definitely helpful in many ways.

To give you a little bit of context, I am integrating this with bunch of other libraries for an internal Github App that we have. So I'm not using the binary file but I'm interested to programmatically run gitleak and do sth with the report.

I have noticed that during [refactoring the code here](https://github.com/zricethezav/gitleaks/pull/240/files#diff-7068f45f5b75ce783e5e372582b55cbbR33), you have changed the signature of the `Run` function from returning a `Report` to returning an `int`.

The problem is that new signature limits programatic usage of this lib by not being able to access report after executing `Run` function(, unless writing the report to a file and reading from file). 

In my opinion, `Run` should still return the `Report` struct and then it's up to caller to decide what to do with it.

What I have is

```go
numberOfLeaks, err := gitleaks.Run(&gitleaks.Options{ ... my config ... })
```
and the report is either available in stdout or file which is not really ~useful~ ideal.

Let me know what do you think.
Cheers,

**Comment by zricethezav** [comment]
@mousavian thanks for bringing up this issue. I think that is a good idea. I didn't know folks used gitleaks as a library, what a pleasant surprise! I'll be sure to put this in the next release.

**Comment by mousavian** [comment]
If you don't mind may I also suggest how we get token for github from user as well?
Currently it's being expected to be provided through env variable.
I think the better approach is to get that as a cli parameter for the sake of consistency so that when you run the application with certain params we can make sure nothing from outside can affect the execution. In this case the caller can do `./gitleak --github-token=${GITHUB_TOKEN}`

We can load config from env vars optionally in addition to above as well, [something similar to this](https://github.com/palantir/go-githubapp/blob/11133322fc78cb94c91460b96ca75d6e057549a9/githubapp/config.go#L42-L53).

**Comment by zricethezav** [comment]
Hey @mousavian in v3.0 I addressed these problems. I refactored Gitleaks to be used as more of a library. Check https://github.com/zricethezav/gitleaks/blob/master/main.go and https://godoc.org/github.com/zricethezav/gitleaks. I also added a `--access-token=` option to auth via cli with access token.

**Comment by mousavian** [comment]
Hi Zachary,

Although I'm not involved in the project I was working on back then when I raise this but I did a quick check and it looks great. I am sure it'll be useful for others.

Thanks for changes.
Cheers,
Rahman
