### ISSUE TITLE
Entropy checks?

### ISSUE THREAD

**Issue by camaya** [zricethezav/gitleaks#252]
Hi,

I hadn't checked the project in a while and after updating it, I've realised that the entropy feature is gone in version 2.0.0. What happened? There are some cases where that is the only way to find some secrets.

As an example, this would not be flagged without entropy checks:

```
Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
```

Entropy checks can be quite noisy, but you could enable the `--noise-reduction` flag and that would give more accurate results.

**Comment by avishnyakov** [comment]
Entropy can be very noisy, indeed. Useful for initial exploration of the codebase but later, it still needs tuning.
 
Maybe gitleaks can add various entropy on top of found value via regex? We still write regex to identify interesting string, and then gitleaks would add entropy and "entropy for value without empty string" on top, in the JSON output?

For example, I don't use built-in entropy. Instead, I post-process JSON report augmenting finding with entropy and other useful information.

**Comment by zricethezav** [comment]
@camaya Entropy has been removed as an option and instead is now defined by the config. You can set a per-rule entropy range and use it in combination with regex. Example: https://github.com/zricethezav/gitleaks/blob/master/examples/regex_and_entropy_config.toml

**Comment by zricethezav** [comment]
Reopen if the examples aren't what you're lookin for
