### ISSUE TITLE
unable to generate ssh key: ssh: cannot decode encrypted private keys 

### ISSUE THREAD

**Issue by KarynaTaranova** [zricethezav/gitleaks#253]
I'm trying to scan my private repo using ssh-key option (on MacOC) with this example:

export SSH_KEY_DIR=$(echo $HOME)/.ssh
export SSH_KEY_NAME=id_rsa
export REPO="git@github.com:zricethezav/gitleaks.git"

docker run --rm --name=gitleaks \
    --mount type=bind,src=${SSH_KEY_DIR},dst=/root/.ssh,readonly \
    zricethezav/gitleaks \
        --ssh-key=/root/.ssh/${SSH_KEY_NAME} \
        --verbose \
        --repo=${REPO}

I have private SSH key on my machine, associated with my user, which have pull access to my repo.
gitleaks fials with next error:
ERRO[2019-09-02T13:31:54Z] unable to generate ssh key: ssh: cannot decode encrypted private keys

**Comment by arthurakay** [comment]
I'm actually hitting this same error... did you find a solution for it?

**Comment by simkin** [comment]
I also like to learn how to pass SSH password as it seem steh agent is not used

**Comment by danksim** [comment]
Same here... Has anyone figured this out? @KarynaTaranova @arthurakay @simkin
