### ISSUE TITLE
More tracing for findings and rules?

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#254]
Might be overlooking but can gitleaks add more tracing while executing rules and crawling repositories, commits and branches?  

Large repositories and tons of rules can lead to a longer execution time, minutes and tens of minutes. Output does not say why it took so much time - was it an aggressive regexp, amount of branches, commits, files, etc. 

Ideally, it would be nice to have this:
- total execution time (exists already)
- exec time per branch
- exec time per-branch + per-commit
- exec time per-branch + per-commit + per-file (so we can whitelist all binary files :) 
- exec time on rule; overall exec time per repo, branch, commit(s)

Such visibility has to do with Ability to run only particular regexes rule(s) #194 
Large codebase, dozens of custom rules, and then regression dataset to ensure that rules actually works correctly on positives, negatives and whistling. It just stuck for minutes, blind guesses on why. and then magically report pops up.

**Comment by zricethezav** [comment]
@avishnyakov Does https://github.com/zricethezav/gitleaks/releases/tag/v3.0.0 accomplish what you are looking for? Check out the `More useful debugging` section

**Comment by avishnyakov** [comment]
@zricethezav nice work, good enough.

**Comment by avishnyakov** [comment]
JSON formatted, machine-readable log output would be the next big thing, then :) 
So we can analyse such stat against thousands of repositories at scale.

**Comment by zricethezav** [comment]
@avishnyakov could you open a new issue and give an example of your desired output?
