### ISSUE TITLE
Ability to define a folder with *.toml configirations

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#257]
Following Ability to define positive/negatives datasets for rules? #256, having a folder with *.toml files might be very helpful.

Organizing dozens rules in the same *.toml is not fun.
Adding positive/negative dataset might expand rule significantly. At the end, file name might be a good indicatino of the rule, and then the *.toml itself would have all we need - the rule, tags, metadata and regression datasets.

Right now it is a challenge to organize and author dozen rules within one file, not to mention handling regression and assertions against positive/negative datasets and whitelistings.

**Comment by zricethezav** [comment]
I don't have plans to support this. I like the simplicity of the current configuration
