### ISSUE TITLE
Positive look ahead support or multiple regexps per rule?

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#258]
Looks that indernearh regexp library does not support feature like positive look-ahead?
Trying to use anything like (?=regex) yields exception during compilation.
> https://stackoverflow.com/questions/30305542/using-positive-lookahead-regex-with-re2

Any ways to support more advanced regexp support?

Other way around is to support array of regexps per rule with AND / OR logic.
For example, handling 32 long tokens which kind of look random.

```toml
[[regexes]]
description = "Catching this AND this AND that"
regex = [
 "has_to_be_string_of_32_chars",
 "has_to_have_at_least_one_number",
 "has_to_have_at_least_one_upper_case_letter",
 "has_to_have_at_least_one_lower_case_letter",
]
```

Similar approach can be used for OR match across several regexps. 
This is helpful to catch general tokens all across the codebase without particular format - in hardcoded strings within the code or configurations.

**Comment by rgmz** [comment]
> Looks that indernearh regexp library does not support feature like positive look-ahead?
> Trying to use anything like (?=regex) yields exception during compilation.
> 
> > https://stackoverflow.com/questions/30305542/using-positive-lookahead-regex-with-re2

The same is true for look-behind; my understanding is that those features cannot be safely compiled, and thus are deliberately not supported.

> Other way around is to support array of regexps per rule with AND / OR logic.
> For example, handling 32 long tokens which kind of look random.
> 
> ```toml
> [[regexes]]
> description = "Catching this AND this AND that"
> regex = [
>  "has_to_be_string_of_32_chars",
>  "has_to_have_at_least_one_number",
>  "has_to_have_at_least_one_upper_case_letter",
>  "has_to_have_at_least_one_lower_case_letter",
> ]
> ```

This is an interesting solution. How would you differentiate AND vs OR in this fashion? 

Not to clutter the syntax, but perhaps something explicit like `regex_any_of = []` for OR and `regex_all_of = []` for AND?

**Comment by avishnyakov** [comment]
@rgmz good point. Agree, multiple regexp per rule should be coming with ability to define matching pattern. This is a challenge for GitLeaks and number of other similar projects out there.

There might be a better way to handle rules configuration.

Why not to consider YARA rules? The pattern matching swiss knife BY VirusTotal used by many security companies.
* https://github.com/virustotal/yara
*  http://virustotal.github.io/yara/

Leaning towards industry standards might be a good idea. Surely, pros and cons but...
* no need to spend energy on things which already were done
* enable broader audience of security researchers
* rules reuse: there are tons of YARA rules out there
* potentially, rules will be portable if other tools out there support YARA rules (for example, shhgit is also an interesting tool, yet the tool has its own config for rules and will struggle with the same-same problem while advancing rule configurations)
 
Btw, looks, there is a huge set of YARA rules already, done and supported by researchers. Boom!
* https://yararules.com/

GitLeaks is great, one of the best tools currently available. It does solve a particular problem, solves it great. No need to make drastic change, but maybe providing plugins functionality so that other people can implement different processing (not only with built-in TOML and regexp but also with YARA) and reporting (cc @mtulio)?

I suggested plugins in the following ticket. Having plugins might be a good option so that we can implement and play with very very different approaches without blowing the GitLeaks core. 
* Enhancement proposal: provide extensibility points or plugins #282

What do you think of this idea, @rgmz?

**Comment by zricethezav** [comment]
Positive lookaheads are not available for gitleaks at this time however. However I have been experimenting with using hyperscan as the regex engine which does support positive lookaheads

**Comment by tarunkant** [comment]
@zricethezav do we have any update on this?
