### ISSUE TITLE
v2.1.0 is not available on the DockerHub

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#259]
https://hub.docker.com/r/zricethezav/gitleaks/tags does not seem to have v2.1.0
It is suggested that there is v2.1.0, as per https://github.com/zricethezav/gitleaks/releases page

**Comment by Chan9390** [comment]
Looks like the issue is solved as we have latest release on Dockerhub (latest version 4.0.1 at the time of commenting).

**Comment by zricethezav** [comment]
closing this issue
