### ISSUE TITLE
--repo-path option locks gitleaks to 1 thread 

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#260]
There is option `--threads=` which suggests that gitleaks would perform bettter.

However, `--repo-path` option locks thread number to 1. Testing with different amount of cpu/cores and ram also suggests there is no difference while using `--repo-path`  option. See this locked here:

https://github.com/zricethezav/gitleaks/blob/master/src/repo.go#L220

Is that because processing scales per-repo, not per commits or branches within a single repo?
Should `--owner-path` be used to improve gitleaks performance and leverage more cpu power available?

**Comment by zricethezav** [comment]
Thanks for bringing this up and I should've made a comment on the code to remind me why this decision was made. I believe that the go-git library would panic if multiple go-routines tried to access a local repo. I'll double check and update this issue.

**Comment by zricethezav** [comment]
@avishnyakov this is no longer an issue in v3.0.0+ of gitleaks. Threading is available for local repos. Feel free to open this again if it remains a problem for you.
