### ISSUE TITLE
Missing option to ignore certificate issues

### ISSUE THREAD

**Issue by gkroon** [zricethezav/gitleaks#265]
Please consider the below example:

```
$ gitleaks -r https://foo.bar/foo/bar --ssh-key=~/.ssh/id_ed25519
INFO[2019-09-19T17:47:10+02:00] cloning https://foo.bar/foo/bar 
ERRO[2019-09-19T17:47:11+02:00] Get https://foo.bar/foo/bar/info/refs?service=git-upload-pack: x509: certificate is valid for bar.foo, not foo.bar
```

It's nice to see that the certificate is being checked for (common) errors. But would it not be an idea to add an option that ignores certificate issues like this? I'm not asking to change the default behaviour, but just an option to override this default _and correct_ behaviour.

**Comment by rgmz** [comment]
If you are using macOS you can work around this by adding those certificates to your keychain and trusting them; Go/Gitleaks should respect the system keychain settings.

But I agree that it would be nice to have an option that passes through the underlying Git/GitHub client contexts. 👍

**Comment by technopwnsauce** [comment]
Go-git doesn't directly provide this option, but they have documented a way to define a custom http.Client to accept insecure certificates.

https://github.com/src-d/go-git/issues/817

**Comment by technopwnsauce** [comment]
@gkroon @rgmz Are there any public repos with invalid certs you know off-hand I could use for testing?

**Comment by gkroon** [comment]
@technopwnsauce You could use any public git repo with your local burp or zaproxy in between. Without importing their local CA cert, this will show up an invalid (untrusted) certificate warning by default.

**Comment by rgmz** [comment]
> @gkroon @rgmz Are there any public repos with invalid certs you know off-hand I could use for testing?

I don't know any off-hand — we have a corporate proxy, so everything is invalid.

:+1: to this:
>  You could use any public git repo with your local burp or zaproxy in between.

**Comment by zricethezav** [comment]
gitleaks is not responsible for cloning anymore
