### ISSUE TITLE
Why doesn't gitleaks find my committed secrets? 

### ISSUE THREAD

**Issue by kramer65** [zricethezav/gitleaks#270]
So I recently added a secret to on of our repos by accident. To prevent this from happening in the future I found this repo. I downloaded the linux binary and I tested it but it doesn't seem to find the secret I comitted at all.

The password I committed is in the README.md and was formed as follows:

    export OURCOMPANYNAME_OBJECTSTORE_PASSWORD=16_character_random_string

I added the binary to the root of my repo and then tried the following command (the README.md in which I committed the password is also in the root dir of the repo):

```
$ ./gitleaks-linux-amd64 --repo-path=.
INFO[2019-10-16T16:01:58+02:00] opening .                                    
INFO[2019-10-16T16:02:39+02:00] No leaks detected. 141 commits inspected in 40 seconds 622 milliseconds 
```

The name of the constant I committed even includes the word PASSWORD in there so I presumed that would be the simplest thing to find.

Am I doing something wrong? Am I misunderstanding what this project should be doing? Or is this some kind of extremely rare exception that it can't find it?

All tips are welcome!

**Comment by rgmz** [comment]
> The name of the constant I committed even includes the word PASSWORD in there so I presumed that would be the simplest thing to find.
> ...
> Am I doing something wrong? Am I misunderstanding what this project should be doing?

Finding secrets is harder than just searching for "password"—if the rules are too general you will get a significant number of false-positives, and the results won't be useful.

The [default search rules](https://github.com/zricethezav/gitleaks/blob/master/src/constants.go#L16) look for patterns of known secrets like API keys, private keys, etc. However, you can provide a custom [rule configuration](https://github.com/zricethezav/gitleaks/blob/master/gitleaks.toml) to search for more stuff.

I've been compiling my own set of patterns, and plan to open a PR with them soon.

**Comment by zricethezav** [comment]
What @rgmz said, finding a general secret is tricky. Check out the example configs: https://github.com/zricethezav/gitleaks/tree/master/examples. Here's an example of a rule that looks for a "key" which defines a regex and an entropy range. Use both entropy and regex to get the best results.
