### ISSUE TITLE
Go panic and sigsegv on large diffs

### ISSUE THREAD

**Issue by equals215** [zricethezav/gitleaks#275]
Hi,
I'm currently using gitleaks for an enterprise project and after scanning a large repo with large diffs the package throws this error : 
```
WARN[0315] recovering from panic on commit 65774bf8dcb53899db..., likely large diff causing panic 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc5ac1c0000 pc=0x45c79c]
```
Is it a known error ? Or is there a way to bypass this error and not analyze the large diffs ?

**Comment by zricethezav** [comment]
This is a known bug and will be addressed in the next release. I'm adding a `--timeout=` option which allows you to tune how long you want a goroutine to work on a commit. So if creating the diff is taking >` --timeout` then it will be ignored.

**Comment by equals215** [comment]
Thanks for your fast response, when will the new release come out ?

**Comment by zricethezav** [comment]
Hoping to get to it this weekend or early next week

**Comment by equals215** [comment]
This is good news ! Good luck for this release.
I'm closing the issue.
