### ISSUE TITLE
Add test dataset for built-in rules in gitleaks.toml 

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#279]
Current `gitleaks.toml ` has tons of rules, and more are coming with PRs:
* add rule for DSA keys #276

It might be a reasonable idea to add a test dataset to ensure that these rules work as expected.
For example:
* create a new repository called "gitleaks-dataset"
* create folders to represent every rule
* within these folders, add two files: data.txt and whitelisting.txt
* fill these files with examples of secrets on which target rule is expected to trigger
* then run `gitleaks` against this test dataset; we know how many occurrences of a particular rule should be, assert that in a simple script, integrate with CI build

That way, new rules can be tested against test dataset every CI build. This gives assurance on rules and provides a quick way to test and enhance old and new rules.

Potentially, that can also close this ticket:
* Ability to define positive/negatives datasets for rules? #256

**Comment by paul-m** [comment]
For instance:
```
 {
  "Description": "Ionic API token",
  "StartLine": 793,
  "EndLine": 793,
  "StartColumn": 30,
  "EndColumn": 75,
  "Context": "class Google_Service_Prediction_AnalyzeModelDescriptionConfusionMatrixRowTotals extends Google_Model",
  "Secret": "ion_AnalyzeModelDescriptionConfusionMatrixRowT",
  "Entropy": 0,
  "Tags": [],
  "RuleID": ""
 },
```
This is a class name with entropy 0 which is a false positive from Gitleaks 8.0.4.

**Comment by zricethezav** [comment]
The `cmd/generate` package effectively does this. You can define false positives and true positives to test rules against
