### ISSUE TITLE
Enhancement proposal: provide extensibility points or plugins

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#282]
Hi all, I put together some thoughts on the GitLeaks after using it for almost a year and exploring various limits and workarounds at scale. Thoughts on features, architecture and current work in progress. Hope that's fine and I am excited to learn from other people experience.

## The challenge 
GitLeaks tends to be monolithic application incorporating more and more features. That complicates new feature development, testing and release cycles.

### Example on supporting repository systems
Additional support for other repository systems increases complexity and comes back in various tickets over and over. 10 out of 48 open issues are about supporting GitHub functionality which seems to be is out of the initial GitLeaks mission of scanning repos for secrets.
* There is an error trying to connect to ssh in the --github-user option. #277
* Missing option to ignore certificate issues #265
* How to pass SSH key password as argument? #263
* Hit error when trying to scan github enterprise using user #245
* Cannot get ssh-keys to work with Docker container running as sibling container #212
* Better error message when --ssh-key is absent #209
* Feature Request: Scan all users of an organization #205
* Feature Request: Specify Github Token as Command-Line Arg #183
* Feature Request: Option for relaxed host key checking for SSH access methods #182
* request slightly longer example in readme for enterprise github runs #173
* [feature request] define disk temp path #137

That is 20% of all open issues. Statistically, adding support for Bitbucket, Azure repos, and other systems might be challenging. Mentioned that here:
* https://github.com/zricethezav/gitleaks/issues/277#issuecomment-553727102

### Example on advancing scanning capabilities
Currently, GitLeaks decomposes repositories into chunks of additions and deletions. It does such decomposition really well - either full repo, a single branch, commit or bunch of commits. Next, GitLeaks runs a bunch of regexp based rules to identify secrets. 

Unfortunately, regexps have limited applicability. Here are several examples:
* Positive look ahead support or multiple regexps per rule? #258
* regexps lack "context": where exactly the secrets is being used, which file, was it a function or config file, etc, which can be critical on identifying secret 
* regexps also lack additional attributes to make a decision if this is a real secret: for example, adding Shannon entropy, more advanced white-listing
* number of other scenarios where regexp can be replaced with AST (https://en.wikipedia.org/wiki/Abstract_syntax_tree)

Entropy checks did not seem to solve complexity of the scans as well. Entropy calculation needs to be executed against matched value, not the line, and only then we might be able to make a decision on marking a secret as secret. Moreover, final decision might depend on several factors, several entropy values to improve precision, lookup against white-listing or blacklists.
* Support capturing groups as a rule match value #280
* Entropy checks? #252 

Supporting AST at some point would be super-nice. It will bring better precision while identifying variables in various languages or config files, exactly where the regexps struggle. Embedding this into GitLeaks would be super-hard, but injecting via extensibility points or plugins is feasible.

One more thing: duplication of the secrets. Currently, GitLeaks gives secrets in one or many branches. It might also be extremely useful to identify secrets in the "working copy". There are several way to do that but the point is that overwhelming amount of historical secrets is nice yet having ability to slice and dice secrets in various ways would be nice. For example, additional attributes in the final report:
* https://github.com/zricethezav/gitleaks/pull/268#discussion_r345043637

GitLeaks might also consider "outsourcing" secrets processing to plugins or other programms. That way, the core gitleaks would only dissect repository into chunks of additions or deletions, and the plugins would run processing against these chunks. Out of the box plugins would be regexp based (the current way GitLeaks does the job) but other people would be able to write additional processing plugins based on other criteria and targeting very specifics of their lanscape and languages.

One "interesting feature" would be using GitLeaks to dissect repositories into additions/deletions per commit and branch in a local file system. With a special flag, GitLeaks could turn incoming repository into a folder based structure:
```
- commit_id
---- additions 
---- deletions
- commit_id
---- additions 
---- deletions
```
That feature is super useful for research purposes and more advanced processing. For example, consider having access to such folders to test your regexps, use other methods to scan repositories, test out AST (https://en.wikipedia.org/wiki/Abstract_syntax_tree) and other methods.

Writing such a plugins is not hard, GitLeaks already does heavy-lifting  - we only need to output additions and deletions into folders.

### Example on reporting
Finally, reporting. Just turn this into plugins. Out of the box has two reporting features: JSON and CSV. There was a brilliant PR by @mtulio which is just too broad to be incorporated into GitLeaks. 
* feat/report-writer: supporting AWS S3 and syslog, and multiple report outputs #278
It does sounds like plugins, indeed.

## The proposal
* refactor GitLeaks into modular application to support plugins: checkout, processing, and reporting plugins
* define processing pipeline; eg. (1) checkout repo (2) scan repo with multiple scanners (3) produce report
* refactor existing functionality into our of the box plugins; plugins for GitHub, plugin for scanning with regexps, plugin for scanning with entropy, plugins for producing JSON and CSV reports
* provide ability to write plugins so that new functionality can be added and tested in isolation without bloating GitLeaks core

Plugins in GoLang make sense. External programs similar to what Terraform does (like JSON in, JSON out) make also perfect sense for people who aren't heavy on GoLang. But they also enable much richer integration and orchestration points - think about anything from bash, to Python, JS, other docker containers, web-hooks. Such move can help grow ecosystem around GitLeaks.

**Comment by zricethezav** [comment]
I'm happy with the design of gitleaks recently in v8. It's only responsibility is scanning. See https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0
