### ISSUE TITLE
Support multi-line regexp execution 

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#283]
It seems that currently GitLeaks uses GoLang regex.FindString value against a single line of code.
https://github.com/zricethezav/gitleaks/blob/f3360cbf66be167c29aaa55f08cb0c1a5ce4575a/src/utils.go#L119

That does not seem to work against JSON based configuration like this:
```
"myUsername": {
    "value": "some-username"
},

"myPassword": {
    "value": "some-password"
 },
```

Regexp not ideal, looks somewhat like this:
```
\"[a-zA-Z:0-9_.]*(?i:username)[a-zA-Z:0-9_.]*\"{1}\s*:\s*\{\n\s*\"value\"\s*:\s*\"(\S{5,})\"\s*\n\s*\}
```

Can be tested here:
* https://regex-golang.appspot.com/assets/html/index.html
* https://regex101.com/

![image](https://user-images.githubusercontent.com/3785585/68849242-d2cc2500-0725-11ea-8d64-e5bd57986a4c.png)

I might be missing something but cannot find a way to get GitLeaks capture such configs. Regexps seem to be ok while testing on the test dataset. With line by line execution, we have a single line which looks like `"value": "some-password"` - not enough to make an informed decision if this is a secret or not.

Can rules be improved to support optional multi-line regexp execution?

Also relates to the following suggestion. It we had capturing group value extraction, then we would be able to factor entropy value of the captured secret which in turn can be a workaround to handle multi-line secrets better.
* Support capturing groups as a rule match value #280

**Comment by karsten-wagner** [comment]
+1 

We are running into false positive on files that have been encrypted and the output was saved as a base64 encoded string. Just by accident there are lines included that look like an AWS key, but apparently the are not.
With the multi line regexp, we might be able to define a regexp for the whitelisting that is skipping such files...

**Comment by rzandonai** [comment]
https://github.com/zricethezav/gitleaks/pull/598 check my pr

**Comment by zricethezav** [comment]
v8 supports multiline regexes
