### ISSUE TITLE
Since V3 the file element of the report json doesn't contain the full path

### ISSUE THREAD

**Issue by onrelgan** [zricethezav/gitleaks#288]
Hi,

We've used gitleaks for some time and have built some automation around it.  We think it's an excellent tool.

Prior to V3, the file component of the JSON report had the full path to the offending file, something like:

```
{
    <snip>
    "file": "foo/bar/blob.yml",
    <snip>
}
```

Now, with V3, the path is missing and you just get the name of the file:

```
{
    <snip>
    "file": "blob.yml",
    <snip>
}
```

You can reproduce the problem by checking out the 2.1.0 tag and running gitleaks with ```go run main.go``` and comparing that to what you get on master.

This is a huge problem for us as it means the automation we have surrounding gitleaks can no longer work.

Is this on purpose?  Is it possible for us to revert to the old behaviour?

Thanks in advance.

**Comment by zricethezav** [comment]
Thanks for bringing that issue up. It wasn't on purpose just a relic of refactoring. I can include the full file path in the next release.

**Comment by onrelgan** [comment]
Hi,

I really appreciate the response and I'm glad it's something that can be fixed.  I look forward to the next release.

Thanks again.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v3.0.2 @onrelgan 3.0.2 includes the full filepath in the json report

**Comment by zricethezav** [comment]
closing this @onrelgan. open again if it does not accomplish what you were looking for

**Comment by onrelgan** [comment]
@zricethezav I've checked and we're all good, thank-you!
