### ISSUE TITLE
Minified files

### ISSUE THREAD

**Issue by GolanTrevize10** [zricethezav/gitleaks#292]
Hi, I am using gitleaks to scan several git repositories. The problem is some of those repositories have minified js files and, if gitleaks finds any password on those files, because the file has only one line, gitleaks prints the whole file in the report. So the report can be in some cases hundreds of megabytes.  Is there any way of printing only a fragment of the line in the report?

PS: I know it is not a good practice to have minified js code in the repository but I cannot force the repository owners to remove it.

**Comment by zricethezav** [comment]
Just merged https://github.com/zricethezav/gitleaks/pull/305 which should handle this issue. I set the max "offender" length to be 200 characters.

**Comment by zricethezav** [comment]
@GolanTrevize10 does #305 resolve this issue for you?

**Comment by GolanTrevize10** [comment]
@zricethezav yes thank you very much
