### ISSUE TITLE
Version 3 is missing the --depth option

### ISSUE THREAD

**Issue by morhimi** [zricethezav/gitleaks#299]
Since version 3 got released, the --depth option is no longer available.
how can I achieve that functionality in V3?

**Comment by arbazkiraak** [comment]
this depth feature was indeed helpful in previous versions where we can only perform scans over newer commits , any reasons why it has been removed @zricethezav ?

**Comment by zricethezav** [comment]
@arbazkiraak No reason, I simply dropped the ball on including all the features when doing the v3 rewrite. This should be added in the next minor version release.

**Comment by arbazkiraak** [comment]
* Since gitleaks now support commit scan range feature I don't think depth feature is necessary.

**Comment by morhimi** [comment]
@arbazkiraak the range addition is 3.1 is very cool but it is not a good replacement for the depth option. nothing beats `--depth 100` in simplicity and ease of use

**Comment by zricethezav** [comment]
cc @morhimi https://github.com/zricethezav/gitleaks/pull/321 going into 3.2.0
