### ISSUE TITLE
gitleaks --repo-path=. -n 10 for number of scanned commits

### ISSUE THREAD

**Issue by erebos12** [zricethezav/gitleaks#300]
**FEATURE-REQUEST:**

When the repo is very big then the scan takes quite long. See output below:

```
time gitleaks --repo-path=.
INFO[2019-11-28T13:15:15+01:00] No leaks detected. 1806 commits audited in 38 seconds 508 milliseconds 543 microseconds
real	0m38.548s
```

When I could specify how many commits (i.e. last 10 commits) should be scanned would make this kinda scan a lot faster.

**Comment by arbazkiraak** [comment]
have u tried `--depth=` argument?

**Comment by arbazkiraak** [comment]
I guess depth feature has been removed in the newer version

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/321 cc  @arbazkiraak  @erebos12. This is going into 3.2.0
