### ISSUE TITLE
Docker automated builds

### ISSUE THREAD

**Issue by petegallagher** [zricethezav/gitleaks#306]
I noticed the last time the [Docker Hub image](https://hub.docker.com/r/zricethezav/gitleaks) was updated was 2 months ago.

![Screenshot 2019-12-02 at 13 27 54](https://user-images.githubusercontent.com/688331/69963194-94957a80-1507-11ea-83bb-7a92c9e66a72.png)

Is it possible to setup automated builds? The screenshot below shows the required config for both a "latest" (i.e. built from master) and a released version.

![Screenshot 2019-12-02 at 13 19 36](https://user-images.githubusercontent.com/688331/69962709-78450e00-1506-11ea-8d7e-273b18f2b89d.png)

| Source Type | Source | Docker Tag | 
| -------------|--------|-------------|
| Branch | `master` | `latest` |
| Tag | `/^v([0-9.]+)$/` | `release-{\1}` |

**Comment by petegallagher** [comment]
@zricethezav is there anything else I can do to help this one? Happy to configure this for you if want to make [me](https://hub.docker.com/u/petergallagher) a collaborator on Docker Hub for this project.

**Comment by prabhu** [comment]
Looks like the author is struggling to deal with the popularity of this library :(

**Comment by zricethezav** [comment]
I'll get on it this week

**Comment by zricethezav** [comment]
https://hub.docker.com/r/zricethezav/gitleaks/tags @prabhu @petegallagher there ya go. I'll be updating the makefile/dockerfile next release

**Comment by petegallagher** [comment]
Awesome, thank you.
