### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by seb-ehm** [zricethezav/gitleaks#308]
Currently, gitleaks does not seem to contain any license information, at least I was not able to find any. This makes gitleaks impossible to use in a productive setting - and contributing to the repository isn't possible either. Could you add a license file?

**Comment by zricethezav** [comment]
Thanks for the reminder: https://github.com/zricethezav/gitleaks/commit/274e8212a6aa833c4723d151af35e9377ba70e8b
