### ISSUE TITLE
Add GitHub Topic: gitleaks

### ISSUE THREAD

**Issue by katrinleinweber** [zricethezav/gitleaks#309]
Thanks for publishing this! A few people started using that [topic](https://help.github.com/articles/about-topics/) already to make [related repos more findable](https://github.com/topics/gitleaks). So, how about adding it to this "mothership" as well?

**Comment by zricethezav** [comment]
Done. Thanks for the suggestion @katrinleinweber.

**Comment by katrinleinweber** [comment]
You're welcome & thanks for adding the topic :-)
