### ISSUE TITLE
How to use organization to audit?

### ISSUE THREAD

**Issue by dleyanlin** [zricethezav/gitleaks#312]
in new version prompt" repository does not exist" when want to use audit organization

**Comment by gavinelder** [comment]
Hey passer by but stepping through the code and testing this works.

```
 gitleaks --host=github --org=ACME  --access-token=
```

**Comment by phuhaquoine** [comment]
I got this error while trying to run the audit for my organization.
======================
`NFO[2019-12-26T10:53:30+07:00] gathering github repos... progress: page 1 of 6 
INFO[2019-12-26T10:56:08+07:00] gathering github repos... progress: page 2 of 6 
INFO[2019-12-26T10:56:13+07:00] gathering github repos... progress: page 3 of 6 
INFO[2019-12-26T10:56:17+07:00] gathering github repos... progress: page 4 of 6 
INFO[2019-12-26T10:56:21+07:00] gathering github repos... progress: page 5 of 6 
INFO[2019-12-26T10:56:23+07:00] gathering github repos... progress: page 6 of 6 
INFO[2019-12-26T10:56:23+07:00] cloning... https://github.com/abc/abc.git
WARN[2019-12-26T10:56:24+07:00] unable to clone via https and access token, attempting with ssh now 
WARN[2019-12-26T10:56:24+07:00] unable to get ssh auth, skipping clone and audit for repo https://github.com/abc/abc.git: open /Users/testdata/.ssh/id_rsa: no such file or directory 
INFO[2019-12-26T10:56:24+07:00] cloning... git@github.com:abc/abc.git 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14978bb]
goroutine 1 [running]:
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*PublicKeys).ClientConfig(0x0, 0x0, 0x50, 0x2b9c2e8)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/transport/ssh/auth_method.go:171 +0x3b
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0xc000206cd0, 0x18b08c0, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/transport/ssh/common.go:113 +0x4d
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0xc0000105b8, 0x17d397d, 0xf, 0xc0009fa240, 0x18b08c0, 0x0, 0x3, 0x0, 0x1c, 0xc0000a5440)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/transport/ssh/common.go:52 +0x8f
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0xc0000f0480, 0x17d397d, 0xf, 0xc0009fa240, 0x18b08c0, 0x0, 0x0, 0x0, 0xc0009fa240)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/transport/internal/common/common.go:112 +0x89
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0xc0000f0480, 0xc0009fa240, 0x18b08c0, 0x0, 0xc0009fa240, 0x0, 0x0, 0xc000896f80)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/transport/internal/common/common.go:89 +0x62
gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0xc0001f01e0, 0x2b, 0x18b08c0, 0x0, 0xc000206c30, 0x10af3c2, 0xc0001ae000, 0x2900d98)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/remote.go:351 +0x9c
gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc00032e440, 0x18b76c0, 0xc000024090, 0xc00022a820, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/remote.go:289 +0x121
gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc000892c60, 0x18b76c0, 0xc000024090, 0xc00022a820, 0x17cf38e, 0x4, 0x0, 0x0, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:877 +0xbc
gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc000892c60, 0x18b76c0, 0xc000024090, 0xc00022ad08, 0xc000892c60, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:744 +0x2a8
gopkg.in/src-d/go-git%2ev4.CloneContext(0x18b76c0, 0xc000024090, 0x18bf020, 0xc0009fa1e0, 0x0, 0x0, 0xc00022ad08, 0x30, 0xc000892a80, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:211 +0xb6
gopkg.in/src-d/go-git%2ev4.Clone(...)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/.brew_home/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:193
github.com/zricethezav/gitleaks/audit.(*Repo).Clone(0xc0001bc200, 0xc00022ad08, 0x17ee4db, 0x42)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/audit/repo.go:72 +0x53c
github.com/zricethezav/gitleaks/hosts.(*Github).Audit(0xc0001d2000)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/hosts/github.go:95 +0x590
github.com/zricethezav/gitleaks/hosts.Run(0xc0000b3680, 0x7ffeefbffba0, 0x6)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/hosts/host.go:35 +0x105
main.Run(0xc0000b3680, 0x0, 0x0)
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/main.go:88 +0x5f
main.main()
	/private/tmp/gitleaks-20191130-61779-1kio8bk/gitleaks-3.0.3/main.go:43 +0x36d`

**Comment by lghakamo-paf** [comment]
Getting a similar error when running it on an organisation and supplying the ssh key gives the error "unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable".
Running it on a single repo in the organisation with the same token works though 🤔

**Comment by lghakamo-paf** [comment]
Seems to be different implementations when doing the cloning that causes this.

Cloning a single repo: https://github.com/zricethezav/gitleaks/blob/master/audit/repo.go#L70
Cloning a repo as part of iterating Organisation repos: https://github.com/zricethezav/gitleaks/blob/master/hosts/github.go#L96

**Comment by waristea** [comment]
Is it possible to scan an org's public repositories without supplying the access-token?
I tried it a few times to no avail

**Comment by 1UC1F3R616** [comment]
> 
> 
> Is it possible to scan an org's public repositories without supplying the access-token?
> I tried it a few times to no avail

@waristea any success in doing this?

**Comment by waristea** [comment]
@1UC1F3R616 
I think I used this bash script back then:
`org=$1
items=$2
depth=$3

curl https://api.github.com/orgs/$org/repos?per_page=$items |
grep “full_name” |
awk -v org=“$org” -F”\“” ‘{print “https://github.com/”$4}’ > $org-repos.txt

while read in; do gitleaks --repo=“$in” --verbose --pretty --depth=$3 --threads=5 --report=$org-gitleaks-result; done < $org-repos.txt`

**Comment by 1UC1F3R616** [comment]
> @1UC1F3R616 
> 
> I think I used this bash script back then:
> 
> 
> 
> `
> 
> org=$1
> 
> items=$2
> 
> depth=$3
> 
> 
> 
> curl https://api.github.com/orgs/$org/repos?per_page=$items |
> 
> grep “full_name” |
> 
> awk -v org=“$org” -F”\“” ‘{print “https://github.com/”$4}’ > $org-repos.txt
> 
> 
> 
> while read in; do gitleaks --repo=“$in” --verbose --pretty --depth=$3 --threads=5 --report=$org-gitleaks-result; done < $org-repos.txt
> 
> `

Hmm, a good workaround it is.

**Comment by zricethezav** [comment]
I am not supporting github/gitlab apis anymore https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0

**Comment by thecybermafia** [comment]
> @1UC1F3R616
> I think I used this bash script back then:
> 
> `
> org=$1
> items=$2
> depth=$3
> 
> curl https://api.github.com/orgs/$org/repos?per_page=$items |
> grep “full_name” |
> awk -v org=“$org” -F”\“” ‘{print “[https://github.com/”$4}’](https://github.com/%E2%80%9D$4%7D%E2%80%99) > $org-repos.txt
> 
> while read in; do gitleaks --repo=“$in” --verbose --pretty --depth=$3 --threads=5 --report=$org-gitleaks-result; done < $org-repos.txt
> `

@zricethezav @waristea I created a small bash script that does the org scanning and it can pass any arguments to gitleaks as well, take a look at it [here](https://github.com/thecybermafia/orgleaks)
