### ISSUE TITLE
[Feature Request] : Only scan from a given commit hash

### ISSUE THREAD

**Issue by arbazkiraak** [zricethezav/gitleaks#314]
- It would be super useful if gitleaks could have the functionality to perform scan only from given commit hash.
-  when we are scanning large scale repos on a daily basis, instead of scanning entire repos we could just start a scan from commit hash given. this could save lot of time, memory, bandwidth.

Please let me know what's your views on this.

Thank you,

**Comment by GolanTrevize10** [comment]
That is supported using the --commit option.

**Comment by arbazkiraak** [comment]
Closing as duplicate `#315` https://github.com/zricethezav/gitleaks/issues/315
