### ISSUE TITLE
Scan a range of commits

### ISSUE THREAD

**Issue by GolanTrevize10** [zricethezav/gitleaks#315]
Hi, I think it would be very useful if it were possible to scan a commits range instead of the whole repository or only a specific range. Something like

gitleaks --commit-from=<from rev> --commit-to=<to rev>

**Comment by rafaveira3** [comment]
Totally agree! It will help [huskyCI](husky.ci) a lot scan repositories with a large number of commits.

**Comment by arbazkiraak** [comment]
+1

**Comment by zricethezav** [comment]
@arbazkiraak @rafaveira3 @GolanTrevize10  https://github.com/zricethezav/gitleaks/pull/317. Let me know if there are any issues before I put this in 3.1.0

**Comment by GolanTrevize10** [comment]
@zricethezav  it looks good for me. Thanks

**Comment by arbazkiraak** [comment]
Looks good!

**Comment by rafaveira3** [comment]
@zricethezav, thanks for working on this one! It is indeed a very useful feature!
