### ISSUE TITLE
Repo configuration changes

### ISSUE THREAD

**Issue by awiddersheim** [zricethezav/gitleaks#318]
**Describe the bug**
At some point between `2.1.0` and `3.1.0`, the way repo configurations interacted with the base configuration changed. Previously the repo configuration was merged into the global config. For example, you could have a base set or rules and whitelists configured globally but for individual repos you could have explicit whitelists or rules that may apply. Now, the repo configuration is taken whole sale leaving the global configuration behind. While I can understand the need for this I did like having the previous behavior. Maybe behind a command line option.

**To Reproduce**
Add both `--config` and `--repo-config` to a scan and you will only see `--repo-config` things happen.

**Expected behavior**
Have some ability to merge what is in `--config` and `--repo-config` similar to the previous behavior.

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Docker container
 - Gitleaks Version: `3.1.0`

**Additional context**
N/A

cc @zricethezav

**Comment by zricethezav** [comment]
This was never a bug, `--repo-config` takes precedence over `--config`
