### ISSUE TITLE
Running from pre-receive hook

### ISSUE THREAD

**Issue by sunilkarthy89** [zricethezav/gitleaks#324]
**Describe the bug**
Running from pre-receive hook to scan the latest commit is failing with timeout even after adding the --timeout option.

**To Reproduce**
Add the gitleaks docker image in the github environment. Setup pre-receive hook to run on the gitleaks environment and scan the latest commit everytime.

**Expected behavior**
the scans should be completed and the leaks should be reported.

**Screenshots**
![image](https://user-images.githubusercontent.com/41190972/72973532-6fc8cf80-3df3-11ea-9791-d3661ce6da80.png)
you can see the scan is failing even after adding the timeout with 3seconds

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version: 3.2.0 also happens to older version 2.0.1

cc @zricethezav

**Comment by sunilkarthy89** [comment]
adding the script we have configured in the hook.

#!/bin/bash
echo "starting script - "`date`
echo "GIT HUB REPOSITORY IS : " $GITHUB_REPO_NAME
echo "GITLEAKS VERSION      : "`gitleaks --version`
zero_commit="0000000000000000000000000000000000000000"
ls -ltr
cat /go/src/github.com/zricethezav/gitleaks/config/gitleaks_dhl.toml

# Do not traverse over commits that are already in the repository
# (e.g. in a different branch)
# This prevents funny errors if pre-receive hooks got enabled after some
# commits got already in and then somebody tries to create a new branch
# If this is unwanted behavior, just set the variable to empty
excludeExisting="--not --all"

while read oldrev newrev refname; do
  echo "PAYLOAD               : $refname $oldrev $newrev"

  # branch or tag get deleted
  if [ "$newrev" = "$zero_commit" ]; then
    continue
  fi

  # Check for new branch or tag
  if [ "$oldrev" = "$zero_commit" ]; then
    span=`git rev-list $newrev $excludeExisting`
  else
    span=`git rev-list $oldrev..$newrev $excludeExisting`
  fi

  #echo $span;
  for COMMIT in $span;
  do
	echo "CURRENT COMMIT ID IS  : $COMMIT";
	gitleaks --repo-path=. --commit=$COMMIT --config=/go/src/github.com/zricethezav/gitleaks/config/gitleaks_dhl.toml --depth=1 --verbose --pretty --timeout=3s;
  done
done
echo "finishing script - "`date`
exit 0

**Comment by zricethezav** [comment]
Hi @sunilkarthy89 are you sure this is a gitleaks error? The error message: "execution time exceeded 5s" is not coming from gitleaks.

**Comment by sunilkarthy89** [comment]
But the timeout option should've killed the scan if it exceeds 3 seconds.

**gitleaks --repo-path=. --commit=$COMMIT --config=/go/src/github.com/zricethezav/gitleaks/config/gitleaks_custom.toml --depth=1 --verbose --pretty --timeout=3s;**

**Comment by zricethezav** [comment]
When you run this locally was do you see? There is a known bug with the `--commit` option where it scan the entirety of the repo at that commit, not just the changes so if there is a large file or you have a complex regular expression that could be the issue.

When you run it locally, could you also use `--debug` to see the timings on the regular expression being used? (redact the actual regexes if they contain sensitive information)

@sunilkarthy89

**Comment by zricethezav** [comment]
This has been fixed

**Comment by roshvin** [comment]
Hi @sunilkarthy89    could you please share some inside how we can configure gitleaks as pre-receive hook
