### ISSUE TITLE
Avoid History Scan/ Duplicate findings 

### ISSUE THREAD

**Issue by arguptasec** [zricethezav/gitleaks#328]
If it is possible can we avoid history scan .. so that unnecessary findings can be avoided .
cc @zricethezav

**Comment by zricethezav** [comment]
Hi @arguptasec could you elaborate? This seems like two different issues:
1. Avoid history scan, in other words scan what is presently in the repo. 
2. Dedupe leaks that are found in multiple rules.

Is this what you were thinking?

**Comment by arguptasec** [comment]
Hi @zricethezav  , request is for .. 1- Can we avoid Github History Scan  in Gitleaks (Like those secrets which has been removed from code but still coming in history as well in merging too )

**Comment by sdhanawade-tavisca-com** [comment]
Hi, I belong to same team as @arguptasec. What challenge we are facing is as below -
1. Gitleaks scans latest source code as well as historical changes. Historical changes might have been fixed already in the latest source code, we do not want to highlight those in scan report
2. In case of merges, when developers are doing 'git pull' before 'git push' and earlier developer had induced leaks, then for second developer too the leaks are shown, though both are identical.

We want to ensure we scan the latest source code.

**Comment by sdhanawade-tavisca-com** [comment]
@zricethezav - Do you have further updates?

**Comment by Chan9390** [comment]
Hi @sdhanawade-tavisca-com and @arguptasec , here are few of my thoughts:

> 1. Gitleaks scans latest source code as well as historical changes. Historical changes might have been fixed already in the latest source code, we do not want to highlight those in scan report

Gitleaks allows you to scan secrets between few commits only using `--commit-from` and `--commit-to`. So you can customize your wrapper around gitleaks to scan the repo till the HEAD commit you had last scanned.

> 2. In case of merges, when developers are doing 'git pull' before 'git push' and earlier developer had induced leaks, then for second developer too the leaks are shown, though both are identical.

Where are you running gitleaks ? On developer laptops as a pre commit hook ?
Please give more context.

**Comment by fnxpt** [comment]
I have the same issue, and if we use the option --commit-from and --commit-to we won't be able to scan the complete repository, since this will only scan the files changed on those commits.
I think @arguptasec idea is to scan the current status of the repo, not things that could be already removed from the current HEAD

**Comment by Chan9390** [comment]
Didn't know such a feature existed. Yeah `--files-at-commit` tag works.
