### ISSUE TITLE
Scan Free Text / Patch provided instead of cloning the repo

### ISSUE THREAD

**Issue by jatindhankhar** [zricethezav/gitleaks#331]
**Is your feature request related to a problem? Please describe.**
To scan a particular commit/patch of a repo there is ``--commit`` but it takes lot of time if the repo is quite big. 

Since it first needs to first clone the repo (no shallow clones there) and then checkout the particular commit followed by scan. 

If all we need is a patch then we can provide the patch using provider api and scan the text only 

For example, Github exposes commit data via their api. 

https://api.github.com/repos/jatindhankhar/rails/commits/48a67ea8a95dd4199ce30f94bf228724cc28518c

```json
"files": [
    {
      "sha": "2b5815023bfb19acb600d5805860600a13b7cd5d",
      "filename": "activesupport/lib/active_support/core_ext/date_and_time/calculations.rb",
      "status": "modified",
      "additions": 12,
      "deletions": 0,
      "changes": 12,
      "blob_url": "https://github.com/jatindhankhar/rails/blob/48a67ea8a95dd4199ce30f94bf228724cc28518c/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb",
      "raw_url": "https://github.com/jatindhankhar/rails/raw/48a67ea8a95dd4199ce30f94bf228724cc28518c/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb",
      "contents_url": "https://api.github.com/repos/jatindhankhar/rails/contents/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb?ref=48a67ea8a95dd4199ce30f94bf228724cc28518c",
      "patch": "@@ -31,6 +31,18 @@ def today?\n       to_date == ::Date.current\n     end\n \n+    # Returns true if the date/time is of next day (tomorrow)\n+    def tomorrow?\n+      to_date == ::Date.current.tomorrow\n+    end\n+    alias_method :next_day?, :tomorrow?\n+\n+    # Returns true if the date/time is of previous day (yesterday)\n+    def yesterday?\n+      to_date == ::Date.current.yesterday\n+    end\n+    alias_method :prev_day?, :yesterday?\n+\n     # Returns true if the date/time is in the past.\n     def past?\n       self < self.class.current"
    },
```
patch node contains the text that we need to scan.

**Describe the solution you'd like**
Since supporting different api for different providers would be difficult to maintain. 
Maybe another flag `--free-text` can be exposed which takes in the text and scans only the text provided. 
This Bypasses any need of clone and allows us to scan any text beyond just git repos. 

**Describe alternatives you've considered**
Haven't tried any alternatives yet. 

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@jatindhankhar This sounds like a good idea. I might generalize it a bit and add the ability to scan streaming data as well. Thanks for this. I'll try and work on it in the coming weeks.

**Comment by jatindhankhar** [comment]
Thanks for the response. 
A big Thanks for making such an awesome tool ❤️, out of many tools in the similar spectrum, we found this to be the most customizable tool with least amount of false positive. 

Only false positives we came across were base64 encoded image strings.
 
I tried looking at the code for this and this seems to be the entry point for scanning strings. 
` inspectFileContents` https://github.com/zricethezav/gitleaks/blob/master/audit/util.go#L221, but this looks tightly coupled with git mechanics.

Let me know if I can be of any help :)

**Comment by zricethezav** [comment]
@jatindhankhar I created https://github.com/zricethezav/anyleaks a while ago. Anyleaks accepts a gitleaks config.

**Comment by jatindhankhar** [comment]
@zricethezav, this looks great. 

Let me try this out, will share my feedback here. 

Again, thank you for your selfless work :)

**Comment by zricethezav** [comment]
You can now use `--no-git` to scan files. See https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
