### ISSUE TITLE
Report only states repo as "." when scanning an organisation

### ISSUE THREAD

**Issue by lghakamo-paf** [zricethezav/gitleaks#335]
**Describe the bug**
The report when scanning repos in an organisation only states dot as repo.

**To Reproduce**
Scan all repos in an organisation.

**Expected behavior**
Repo should be reported as <repo-name>.git
This worked in versions < 3.x. Scanning a single repo reports the expected repo correctly.

**Basic Info (please complete the following information):**
 - OS: MacOS 10.15.3
 - Gitleaks Version: 3.3.0 (Docker)

**Additional context**
N/A

cc @zricethezav

**Comment by zricethezav** [comment]
Thanks for bringing this up. I noticed that this past weekend too actually. Great first issue for anyone who wants to open a PR.

**Comment by NdagiStanley** [comment]
This issue is done, right?

**Comment by lghakamo-paf** [comment]
> This issue is done, right?

Yeah, seems to be fixed by https://github.com/zricethezav/gitleaks/pull/344. Verified with release 4.1.1 but probably fixed already with 4.0.
