### ISSUE TITLE
fatal error: runtime: out of memory while scanning Bitbucket repository

### ISSUE THREAD

**Issue by tdhavalikar** [zricethezav/gitleaks#336]
Hi @zricethezav,

**Describe the bug**
While scanning a private Bitbucket repository for leaks, following error occurs.
-> gitleaks --repo=***** --username=**** --password=**** --report=gitleaks.csv --report-format=csv --redact -v
[36mINFO[0m[2020-02-19T10:02:52Z] cloning... *****
Counting objects: 32003, done.
Compressing objects:   0% (1/12048)   
Compressing objects:   1% (121/12048)   
Compressing objects:   2% (241/12048)   
Compressing objects:   3% (362/12048)   
Compressing objects:   4% (482/12048)   
Compressing objects:   5% (603/12048)   
Compressing objects:   6% (723/12048)   
Compressing objects:   7% (844/12048)   
Compressing objects:   8% (964/12048)   
Compressing objects:   9% (1085/12048)   
Compressing objects:  10% (1205/12048)   
Compressing objects:  11% (1326/12048)   
Compressing objects:  12% (1446/12048)   
Compressing objects:  13% (1567/12048)   
Compressing objects:  14% (1687/12048)   
Compressing objects:  15% (1808/12048)   
Compressing objects:  16% (1928/12048)   
Compressing objects:  17% (2049/12048)   
Compressing objects:  18% (2169/12048)   
Compressing objects:  19% (2290/12048)   
Compressing objects:  20% (2410/12048)   
Compressing objects:  21% (2531/12048)   
Compressing objects:  22% (2651/12048)   
Compressing objects:  23% (2772/12048)   
Compressing objects:  24% (2892/12048)   
Compressing objects:  25% (3012/12048)   
Compressing objects:  26% (3133/12048)   
Compressing objects:  27% (3253/12048)   
Compressing objects:  28% (3374/12048)   
Compressing objects:  29% (3494/12048)   
Compressing objects:  30% (3615/12048)   
Compressing objects:  31% (3735/12048)   
Compressing objects:  32% (3856/12048)   
Compressing objects:  33% (3976/12048)   
Compressing objects:  34% (4097/12048)   
Compressing objects:  35% (4217/12048)   
Compressing objects:  36% (4338/12048)   
Compressing objects:  37% (4458/12048)   
Compressing objects:  38% (4579/12048)   
Compressing objects:  39% (4699/12048)   
Compressing objects:  40% (4820/12048)   
Compressing objects:  41% (4940/12048)   
Compressing objects:  42% (5061/12048)   
Compressing objects:  43% (5181/12048)   
Compressing objects:  44% (5302/12048)   
Compressing objects:  45% (5422/12048)   
Compressing objects:  46% (5543/12048)   
Compressing objects:  47% (5663/12048)   
Compressing objects:  48% (5784/12048)   
Compressing objects:  49% (5904/12048)   
Compressing objects:  50% (6024/12048)   
Compressing objects:  51% (6145/12048)   
Compressing objects:  52% (6265/12048)   
Compressing objects:  53% (6386/12048)   
Compressing objects:  54% (6506/12048)   
Compressing objects:  55% (6627/12048)   
Compressing objects:  56% (6747/12048)   
Compressing objects:  57% (6868/12048)   
Compressing objects:  58% (6988/12048)   
Compressing objects:  59% (7109/12048)   
Compressing objects:  60% (7229/12048)   
Compressing objects:  61% (7350/12048)   
Compressing objects:  62% (7470/12048)   
Compressing objects:  63% (7591/12048)   
Compressing objects:  64% (7711/12048)   
Compressing objects:  65% (7832/12048)   
Compressing objects:  66% (7952/12048)   
Compressing objects:  67% (8073/12048)   
Compressing objects:  68% (8193/12048)   
Compressing objects:  69% (8314/12048)   
Compressing objects:  70% (8434/12048)   
Compressing objects:  71% (8555/12048)   
Compressing objects:  72% (8675/12048)   
Compressing objects:  73% (8796/12048)   
Compressing objects:  74% (8916/12048)   
Compressing objects:  75% (9036/12048)   
Compressing objects:  76% (9157/12048)   
Compressing objects:  77% (9277/12048)   
Compressing objects:  78% (9398/12048)   
Compressing objects:  79% (9518/12048)   
Compressing objects:  80% (9639/12048)   
Compressing objects:  81% (9759/12048)   
Compressing objects:  82% (9880/12048)   
Compressing objects:  83% (10000/12048)   
Compressing objects:  84% (10121/12048)   
Compressing objects:  85% (10241/12048)   
Compressing objects:  86% (10362/12048)   
Compressing objects:  87% (10482/12048)   
Compressing objects:  88% (10603/12048)   
Compressing objects:  89% (10723/12048)   
Compressing objects:  90% (10844/12048)   
Compressing objects:  91% (10964/12048)   
Compressing objects:  92% (11085/12048)   
Compressing objects:  93% (11205/12048)   
Compressing objects:  94% (11326/12048)   
Compressing objects:  95% (11446/12048)   
Compressing objects:  96% (11567/12048)   
Compressing objects:  97% (11687/12048)   
Compressing objects:  98% (11808/12048)   
Compressing objects:  99% (11928/12048)   
Compressing objects: 100% (12048/12048)   
Compressing objects: 100% (12048/12048), done.
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xbd406b, 0x16)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc014000000, 0x8000000, 0x112aff8)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1112760, 0x8000000, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x1112760, 0x4000, 0xffffffff)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x1112760, 0x4000, 0x112b008, 0xc0001bdea8)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x1112760, 0x4000, 0x101, 0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x1112760, 0x4000, 0xc000010101, 0xc000000180)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x7fffe00, 0xc0001b0101, 0x436197)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:330 fp=0xc00690c010 sp=0xc00690c008 pc=0x4587d0
runtime.mallocgc(0x7fffe00, 0xa73620, 0xc0000e5301, 0xc00690c100)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/malloc.go:1032 +0x895 fp=0xc00690c0b0 sp=0xc00690c010 pc=0x40c325
runtime.makeslice(0xa73620, 0x7fffe00, 0x7fffe00, 0xc0cf31dbbe)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/slice.go:49 +0x6c fp=0xc00690c0e0 sp=0xc00690c0b0 pc=0x44351c
bytes.makeSlice(0x7fffe00, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/bytes/buffer.go:229 +0x77 fp=0xc00690c148 sp=0xc00690c0e0 pc=0x474647
bytes.(*Buffer).grow(0xc000206a80, 0x200, 0x7e00)
	/usr/local/Cellar/go/1.13.5/libexec/src/bytes/buffer.go:142 +0x15b fp=0xc00690c198 sp=0xc00690c148 pc=0x473f8b
bytes.(*Buffer).ReadFrom(0xc000206a80, 0x7fee023740d8, 0xc00008ce60, 0x7fee02374118, 0xc000206a80, 0x7fee021cc701)
	/usr/local/Cellar/go/1.13.5/libexec/src/bytes/buffer.go:202 +0x4b fp=0xc00690c208 sp=0xc00690c198 pc=0x47443b
io.copyBuffer(0xca48a0, 0xc000206a80, 0x7fee023740d8, 0xc00008ce60, 0xc0001c6000, 0x8000, 0x8000, 0xae0200, 0x45a700, 0x7fee023740d8)
	/usr/local/Cellar/go/1.13.5/libexec/src/io/io.go:388 +0x2ed fp=0xc00690c280 sp=0xc00690c208 pc=0x46ae7d
io.CopyBuffer(0xca48a0, 0xc000206a80, 0x7fee023740d8, 0xc00008ce60, 0xc0001c6000, 0x8000, 0x8000, 0x0, 0xe00000000000000, 0xc00690c368)
	/usr/local/Cellar/go/1.13.5/libexec/src/io/io.go:375 +0x82 fp=0xc00690c2e0 sp=0xc00690c280 pc=0x46ab22
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Scanner).copyObject(0xc000206990, 0xca48a0, 0xc000206a80, 0x0, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/format/packfile/scanner.go:335 +0x33e fp=0xc00690c408 sp=0xc00690c2e0 pc=0x6c350e
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Scanner).NextObject(0xc000206990, 0xca48a0, 0xc000206a80, 0x0, 0x19d0ccd8, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/format/packfile/scanner.go:314 +0x5a fp=0xc00690c468 sp=0xc00690c408 pc=0x6c310a
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).indexObjects(0xc00690c648, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/format/packfile/parser.go:221 +0x201 fp=0xc00690c590 sp=0xc00690c468 pc=0x6bf7f1
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Parser).Parse(0xc00690c648, 0x0, 0x0, 0x7fee00000000, 0xc0000592c0, 0xc0001ec300)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/format/packfile/parser.go:137 +0x61 fp=0xc00690c5f8 sp=0xc00690c590 pc=0x6bf201
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.UpdateObjectStorage(0x7fee02361298, 0xc0000592c0, 0xca5400, 0xc00008cd20, 0xc0000592c0, 0xca5400)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/plumbing/format/packfile/common.go:39 +0x1b3 fp=0xc00690c6e8 sp=0xc00690c5f8 pc=0x6b6063
gopkg.in/src-d/go-git%2ev4.(*Remote).fetchPack(0xc000113b00, 0xcb1a20, 0xc0000240c0, 0xc00048ea00, 0xcafd20, 0xc00000e6d8, 0xc000058180, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/remote.go:391 +0x1fb fp=0xc00690c790 sp=0xc00690c6e8 pc=0x8a127b
gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc000113b00, 0xcb1a20, 0xc0000240c0, 0xc00690ca00, 0x0, 0x0, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/remote.go:328 +0x62f fp=0xc00690c890 sp=0xc00690c790 pc=0x8a0bff
gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc0000edad0, 0xcb1a20, 0xc0000240c0, 0xc0001a2a00, 0xbca78e, 0x4, 0x0, 0x0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:877 +0xbc fp=0xc00690c918 sp=0xc00690c890 pc=0x8ab70c
gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc0000edad0, 0xcb1a20, 0xc0000240c0, 0xc0001567e0, 0xc0000edad0, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:744 +0x2a8 fp=0xc00690ca70 sp=0xc00690c918 pc=0x8aa738
gopkg.in/src-d/go-git%2ev4.CloneContext(0xcb1a20, 0xc0000240c0, 0xcb9260, 0xc0000592c0, 0x0, 0x0, 0xc0001567e0, 0x110d220, 0x7fee045ca008, 0x0)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:211 +0xb6 fp=0xc00690cac0 sp=0xc00690ca70 pc=0x8a6386
gopkg.in/src-d/go-git%2ev4.Clone(...)
	/Users/zacharyrice/Go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.13.1/repository.go:193
github.com/zricethezav/gitleaks/v3/audit.(*Repo).Clone(0xc0000a0630, 0x0, 0x2, 0x2e)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/audit/repo.go:78 +0x54b fp=0xc00690cc00 sp=0xc00690cac0 pc=0x8dffdb
github.com/zricethezav/gitleaks/v3/audit.runHelper(0xc0000a0630, 0xc0000a0630, 0x0)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/audit/audit.go:51 +0x31c fp=0xc00690d250 sp=0xc00690cc00 pc=0x8dfa3c
github.com/zricethezav/gitleaks/v3/audit.Run(0xc000158000, 0x0, 0x0)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/audit/audit.go:32 +0x47e fp=0xc00690d320 sp=0xc00690d250 pc=0x8df67e
main.Run(0xc000158000, 0x0, 0x0)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/main.go:90 +0xde fp=0xc00690d3e0 sp=0xc00690d320 pc=0x9ea48e
main.main()
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/main.go:43 +0x3bb fp=0xc00690df60 sp=0xc00690d3e0 pc=0x9e9c0b
runtime.main()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/proc.go:203 +0x21e fp=0xc00690dfe0 sp=0xc00690df60 pc=0x42f43e
runtime.goexit()
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00690dfe8 sp=0xc00690dfe0 pc=0x45a721

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/Cellar/go/1.13.5/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.13.5/libexec/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/zricethezav/gitleaks/v3/manager.(*Manager).receiveLeaks(0xc000158000)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:177 +0x8d
created by github.com/zricethezav/gitleaks/v3/manager.NewManager
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:135 +0x32a

goroutine 9 [chan receive]:
github.com/zricethezav/gitleaks/v3/manager.(*Manager).receiveMetadata(0xc000158000)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:206 +0x6d
created by github.com/zricethezav/gitleaks/v3/manager.NewManager
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:136 +0x34f

goroutine 10 [chan receive]:
github.com/zricethezav/gitleaks/v3/manager.(*Manager).receiveInterrupt(0xc000158000)
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:299 +0x3f
created by github.com/zricethezav/gitleaks/v3/manager.NewManager
	/Users/zacharyrice/Go/src/github.com/zricethezav/gitleaks/manager/manager.go:137 +0x374

goroutine 27 [select]:
net/http.(*persistConn).readLoop(0xc0002be6c0)
	/usr/local/Cellar/go/1.13.5/libexec/src/net/http/transport.go:2026 +0x999
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.13.5/libexec/src/net/http/transport.go:1574 +0xafe

goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc0002be6c0)
	/usr/local/Cellar/go/1.13.5/libexec/src/net/http/transport.go:2204 +0x123
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.13.5/libexec/src/net/http/transport.go:1575 +0xb23

**Basic Info (please complete the following information):**
 - OS: Amazon Linux 2
 - Gitleaks Version: v3.3.0

Other team members @arguptasec  @sdhanawade-tavisca-com

cc @zricethezav

**Comment by zricethezav** [comment]
@tdhavalikar try cloning to disk rather than in-memory. 
```
gitleaks --repo=***** --username=**** --password=**** --report=gitleaks.csv --report-format=csv --redact -v --disk
```

**Comment by tdhavalikar** [comment]
Hi @zricethezav,

Thanks for the suggestion! However, it works for only a few repositories. The error persists for other repositories. All the repositories in this case are private Bitbucket repositories of varying sizes.

**Comment by sdhanawade-tavisca-com** [comment]
@zricethezav - Can you please respond to this query as multiple decisions are blocked for resolution on this ticket?

**Comment by zricethezav** [comment]
@sdhanawade-tavisca-com you tryna pay me?

**Comment by zricethezav** [comment]
@tdhavalikar can you try running with the latest release and tell me if this is still an issue

**Comment by zricethezav** [comment]
Closing this with the release of https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0. Reopen if still getting this error.
