### ISSUE TITLE
Possile to add regex option to binary?

### ISSUE THREAD

**Issue by lochlainnw** [zricethezav/gitleaks#337]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd love to be able to run the latest binary with --regex=customregex.json option.  In the customregex.json we could have a list of our own regexes!

**Describe alternatives you've considered**
I tried to use truffleHog which has this option but doesn't work very well.  i find this one to be very good.

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@lochlainnw you can define your own regular expressions by creating a gitleaks config toml. See https://github.com/zricethezav/gitleaks/tree/master/examples for examples.

use the `--config=path-to-toml` option

**Comment by lochlainnw** [comment]
Ah that is great.  Sorry I didn't see that in the docs.  Thanks very much @zricethezav
