### ISSUE TITLE
Looking for improved output feature

### ISSUE THREAD

**Issue by lochlainnw** [zricethezav/gitleaks#338]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to run the binary as a for loop in a folder with 1000's of repos.  The output function overwrites itself in a loop.  Would it be possible to have a new option called --projects (or something that would better describe a large amount of repos) where it will run through all of the repos in the path and output to one file?

**Describe the solution you'd like**
Something like:
./gitleaks-linux-amd64 --projects=path-to-repos --branch=develop --exclude-forks --report=secrets --report-format=csv

Where the output is written to secrets.

**Describe alternatives you've considered**
A loop like so:
for d in */; do  ./gitleaks-linux-amd64 --repo-path="$d" --branch=develop --exclude-forks --report=secrets-$d --report-format=csv;  done

I have not been able to get this working yet but this is a workaround.

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@lochlainnw use --owner-path=path-to-repos this will run gitleaks on any directories with a .git sub directory

**Comment by lochlainnw** [comment]
Again @zricethezav thanks very much.  this is a great tool, appreciate your work on this!

regards,
Lochlainn

**Comment by lochlainnw** [comment]
Hey @zricethezav sorry again to bother you.  Do you know why a scan would not work on a some repo's that do have a .git directory?

I have a list of 10 repos for example, 8 are not working and 2 are. they all have ".git"

WARN[2020-02-19T15:55:54Z] ap107216-stash-playbook is not a git repo, skipping
WARN[2020-02-19T15:55:54Z] ap107216_bitbucket is not a git repo, skipping
WARN[2020-02-19T15:55:54Z] ap107216_bitbucket_elasticsearch is not a git repo, skipping
WARN[2020-02-19T15:56:18Z] limerick_is_great_too is not a git repo, skipping
WARN[2020-02-19T15:56:18Z] pr000595-ansible-dynatrace-playbook is not a git repo, skipping
WARN[2020-02-19T15:56:18Z] pr000595-ansible-git-playbook is not a git repo, skipping
INFO[2020-02-19T15:56:19Z] no leaks found, skipping writing report
INFO[2020-02-19T15:56:19Z] No leaks detected. 1161 commits audited in 3 minutes 7 seconds 642 milliseconds 590 microseconds

Here is the list of contents of one of the repos:
pwd
/a590125/ap107216-stash-playbook
bash-4.4# ls -la
total 40
drwxr-xr-x    8 root     root          4096 Feb  3 14:45 .
drwxr-xr-x   23 29005    users         4096 Feb 19 16:03 ..
drwxr-xr-x    8 root     root          4096 Feb  4 12:44 .git
-rw-r--r--    1 root     root          1451 Jan 31 17:14 Jenkinsfile

**Comment by lochlainnw** [comment]
I also notice the "repo-path" will work on repositories from the server.  but "owner-path" does not.  I am guessing owner path is looking at cloned repos.

**Comment by lochlainnw** [comment]
I have a for loop working like so:

for d in ../repositories/*/ ; do ./gitleaks-linux-amd64 --repo-path=$d --branch=master --exclude-forks --report=/home/secrets --report-format=csv --config=/home/regex.toml && cat /home/secrets >> /home/secrets.csv; done

an untidy workaround.

**Comment by zricethezav** [comment]
this can be scripted. I don't want gitleaks being responsible for merging reports
