### ISSUE TITLE
Android Keystore support

### ISSUE THREAD

**Issue by kaushalyap** [zricethezav/gitleaks#339]
**Is your feature request related to a problem? Please describe.**
Find if the keystore files ( ex: keystore.jks ) or `local.properties` with sensitive data committed to git

**Describe the solution you'd like**
If keystore files or `local.properties` with sensitive data committed to git, exit code should be 1 (these files should be git ignored)

**Describe alternatives you've considered**
Writing a shellscript

**Additional context**
Useful in android projects
Read for more info: https://stackoverflow.com/questions/20673378/where-does-local-properties-go-for-android-project

cc @zricethezav

**Comment by zricethezav** [comment]
@kaushalyap could you provide a regex that would capture the credentials you're trying to target? Otherwise you could write a simple rule to find a `keystore.jsk` or `local.properties` file.

**Comment by zricethezav** [comment]
closing as this is a configuration issue
