### ISSUE TITLE
Feature to scan only on added content

### ISSUE THREAD

**Issue by Chan9390** [zricethezav/gitleaks#341]
**Is your feature request related to a problem? Please describe.**

Gitleaks is doing a wonderful job to detect secrets in the history. Gitleaks gives the commits in which a secret is added and removed. 

If there are 3 commits:
commit1 - secret added
commit2 - secret deleted
commit3 - some random code

Gitleaks will detect the same secret which is present in commit1 and commit2. This works fine for a pentester interested in finding the secrets. But for security engineer trying to add gitleaks to a CI pipeline, alerting the same secret 

**Describe the solution you'd like**
The remediation from product security team will be to revoke the secret wherever it is used and also remove it from the repo code. Once the secret is removed from the code we again get Gitleaks alert because the deleted content contains the secret.

There can be two solutions
1) Add a wrapper around gitleaks alerts and check if the same secret for the same repo (and same file) was alerted earlier. If yes, dont alert again and/or pass the pipeline.
2) Make sure gitleaks only checks for secrets added to the repo (not the secrets that are removed)

The first solution is difficult as there can be scenarios we could miss. The second solution where gitleaks has an option to check for secrets that are only added to the code is really helpful.

cc @zricethezav

**Comment by sbarbeau-od** [comment]
There is a PR for what you are looking for: https://github.com/zricethezav/gitleaks/pull/268

**Comment by zricethezav** [comment]
@sbarbeau-od @Chan9390 
The default behavior now is to scan additions. `--include-deletions` to scan deletions as well as additions. See https://github.com/zricethezav/gitleaks/releases/tag/v5.0.0
