### ISSUE TITLE
Unable to clone private GitHub repository using token

### ISSUE THREAD

**Issue by GolanTrevize10** [zricethezav/gitleaks#349]
**Describe the bug**
GitLeaks is unable to clone a private GitHub repository using token when scanning a whole organization. It returns this error

INFO[2020-02-28T21:31:48+01:00] gathering github repos... progress: page 1 of 1
INFO[2020-02-28T21:31:48+01:00] cloning... https://mygitserver/XXXX/myrepo.git
WARN[2020-02-28T21:31:48+01:00] unable to clone via https and access token, attempting with ssh now
WARN[2020-02-28T21:31:48+01:00] unable to get ssh auth, skipping clone and audit for repo https://mygitserver/XXXX/myrepo.git: open C:\Users\user/.ssh/id_rsa: The system cannot find the file specified.
INFO[2020-02-28T21:31:48+01:00] cloning... git@mygitserver/XXXX/myrepo.git
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x89d4c2]

I checked the github.go file but I cannot see it is passing any credential when cloning via https

**To Reproduce**
1. Create a private repository in a GitHub organization
2. Generate a token for one of the organization owners and give repo and read:org permissions to the token
3. Run gitleaks '--access-token=xxxxxxx' '--host=Github' '--baseurl=https://mygitserver/api/v3' '--org=XXXX'

**Expected behavior**
GitLeaks scan all the repositories in the organization

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Windows and Linux
 - Gitleaks Version: 4.0.1

**Additional context**

cc @zricethezav

**Comment by GolanTrevize10** [comment]
I tried to run a git clone with same token and it works.

**Comment by zricethezav** [comment]
@GolanTrevize10 mmm not sure what is going on with this one. It's passing the token to an http client right here: https://github.com/zricethezav/gitleaks/blob/master/hosts/github.go#L37-L44

**Comment by GolanTrevize10** [comment]
But I think the http client is only used to call the github api. That part
works. But in the cloning I think it is not using token

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/350 should fix it. Turns out I was not passing an auth method when cloning in that github loop

**Comment by GolanTrevize10** [comment]
Yes, it works, thanks
