### ISSUE TITLE
Gitleaks --uncommitted fails on first commit

### ISSUE THREAD

**Issue by bryanlalexander** [zricethezav/gitleaks#352]
**Describe the bug**
Gitleaks fails with error `reference not found` when executed against a newly initialized repository with staged changes. 

**To Reproduce**

- create a new folder
- `git init`
- `touch file`
- `git add file`
- `gitleaks --uncommitted`

**Expected behavior**
Gitleaks should be able to handle the initial commit to a repository, this is even sometimes the most critical point in which leaks need to be detected. As a repository matures leaks are less likely to be detected.

**Basic Info (please complete the following information):**
 - OS: Windows
 - Gitleaks Version: v4.1.0

**Additional context**
This error seems to propagate up from go-git, and appears to be around lines `108-116` in `audit/repo.go`.

cc @zricethezav

**Comment by pburkholder** [comment]
Oh, wow, we're both at GSA :wave:

**Comment by pburkholder** [comment]
OS: Mac Mojave 10.14
Gitleaks version: v4.1.0 v3.3.0 v3.0.3

**Comment by zricethezav** [comment]
Kinda busy but this wouldn't be too difficult to fix if a community member wants to pick it up. I can provide some details after I do the dishes. 1 sec

**Comment by bryanlalexander** [comment]
Sure, if you know how to resolve it - I can probably pick it up.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/364 should take care of it

**Comment by zricethezav** [comment]
reopen if you need
