### ISSUE TITLE
False Positive - Findings in the Config File itself

### ISSUE THREAD

**Issue by 0xfabiof** [zricethezav/gitleaks#354]
**Describe the bug**
The tool flags the rule-set defining file (.toml file) as scannable and reports findings in it

**To Reproduce**
- Run the tool setting --config=PATH to be a PATH inside the repository scanned.

**Expected behavior**
The tool should ignore the loaded .toml file used for the rule-set

**Additional context**
An alternative fix would be enabling us to flag a file or directory as not-to-scan

cc @zricethezav

**Comment by zricethezav** [comment]
Good call, merged https://github.com/zricethezav/gitleaks/pull/362 to address this
