### ISSUE TITLE
SARIF report output

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#355]
**Is your feature request related to a problem? Please describe.**
I would like to add the ability to format the report output that is compliant with SAIRF.

**Describe the solution you'd like**
`--report-format=sarif` (default would be json)

**Additional context**
https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html

cc @zricethezav

**Comment by prabhu** [comment]
Perhaps supporting a standard such as SARIF is better. Note that [scan](https://github.com/ShiftLeftSecurity/sast-scan) automatically converts gitleaks json into SARIF

**Comment by zricethezav** [comment]
@prabhu great idea. Updating the issue title.
