### ISSUE TITLE
Gitleaks can not scan AWS SECRET KEY

### ISSUE THREAD

**Issue by mungmoong3** [zricethezav/gitleaks#357]
**Describe the bug**
Gitleaks can not scan AWS Secret key

**To Reproduce**
 - git init
 - create fake.py
```
fake-ak = "AKIAIO5FODNN7EXAMPLE"
fake-sk = "ABCDEF+c2L7yXeGvUyrPgYsDnWRRC1AYEXAMPLE"
```
 - git add ./fake.py
 - git commit -m 'fake'
 - gitleaks --repo-path=. --verbose --pretty

**Expected behavior**
The access key was detected but the secret key was not detected.
```
{
        "line": "fake-ak = \"AKIAIO5FODNN7EXAMPLE\"",
        "offender": "AKIAIO5FODNN7EXAMPLE",
        "commit": "17c95be857f5cd1af562ea1bb08095f47b024641",
        "repo": ".",
        "rule": "AWS Manager ID",
        "commitMessage": "fake\n",
        "author": "--",
        "email": "--",
        "file": "fake.py",
        "date": "2020-03-19T12:45:27+09:00",
        "tags": "key, AWS"
}
WARN[2020-03-19T12:45:33+09:00] 1 leaks detected. 2 commits audited in 1 millisecond 222 microseconds
```

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Gitleaks Version: v4.1.0

**Additional context**
The results were the same even if tested with a real secret key.

cc @zricethezav

**Comment by zricethezav** [comment]
This is not a default regex. If you want to search for a specific you need to add a new rule and use a custom gitleaks config. This is not a bug. See https://github.com/zricethezav/gitleaks/tree/master/examples for examples

**Comment by jreisinger** [comment]
Hi @zricethezav. So AWS access key ID is among the [default regexes](https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml) but AWS secret access key isn't? If so, what is the reason? Thanks 👍
