### ISSUE TITLE
Read access-token from file or environment

### ISSUE THREAD

**Issue by galitz** [zricethezav/gitleaks#360]
**Is your feature request related to a problem? Please describe.**
The access-token used to access to GitHub API and sometimes a private repo can be read from the process table when launched.  This can potentially leakthe token to access private repo data.

**Describe the solution you'd like**
A possible solution would be add an option to read the access-token from a file or environmental variable directly from gitleaks.  If this option exists now, the documentation should be updated to reflect this.

**Describe alternatives you've considered**
It should be possible to obfuscate this token when launching via the cli or a shell script, but it would great if it was not necessary to add this extra step.

cc @zricethezav

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/blob/master/options/options.go#L241-L249 you can use `GITLEAKS_ACCESS_TOKEN` which is the access token whatever host you are hitting (gitlab and github are currently the only ones supported).

Documentation is due for an overhaul and something I could use some help with if anyone has spare cycles.

**Comment by galitz** [comment]
Thanks for the following up!  I'll happily help update the docs.
