### ISSUE TITLE
Object Not Found

### ISSUE THREAD

**Issue by joshghent** [zricethezav/gitleaks#361]
**Describe the bug**
When running gitleaks against a single commit on the latest build it returns the error Object Not Found

**To Reproduce**
`docker run --rm --name=gitleaks -v $PWD:/repo-path zricethezav/gitleaks --verbose --repo-path=/repo-path --commit=latest --redact --threads=1 --verbose`

Tried it on two private repos at my company and both returned the same thing

**Expected behavior**
Return a list of gitleaks that were found

**Screenshots**
Output of the command above
![Screenshot 2020-04-02 at 13 14 47](https://user-images.githubusercontent.com/2934976/78248116-f2e95e80-74e3-11ea-953e-48dc2b698521.png)

**Basic Info (please complete the following information):**
 - OS: MacOS + Ubuntu (Travis)
 - Gitleaks Version: Docker Image V4.1.0

**Additional context**
Thanks for a great project! :tada: Let me know if you need any more information or if there is a fix I can do, just point me to the right place.

cc @zricethezav

**Comment by zricethezav** [comment]
Hey @joshghent thanks for bringing up this issue. Could you try running the binary directly? I'm able to reproduce this bug while using the docker image but when I use binary I'm not able to reproduce it.

**Comment by zricethezav** [comment]
whoops, nvm, i see the issue. submitting a pr now

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v4.1.1 includes the fix
