### ISSUE TITLE
Incorrect results with the --redact option

### ISSUE THREAD

**Issue by steeve85** [zricethezav/gitleaks#367]
**Describe the bug**
Similar issue than #332
When I use the --redact option, gitleaks found less secrets than when I omit this option

**To Reproduce**

```sh
$ go get github.com/zricethezav/gitleaks/v4@latest 
go: github.com/zricethezav/gitleaks/v4 latest => v4.1.1
$ gitleaks --repo-path .
WARN[2020-04-13T17:10:32-07:00] 69 leaks detected. 25 commits audited in 515 milliseconds 466 microseconds 
$ gitleaks --redact --repo-path . 
WARN[2020-04-13T17:10:38-07:00] 65 leaks detected. 25 commits audited in 436 milliseconds 890 microseconds
```

I used https://github.com/Plazmaz/leaky-repo for testing

**Expected behavior**

Number of findings with or without `--redact` should be the same

**Basic Info (please complete the following information):**
 - OS: Archlinux
 - Gitleaks Version: v4.1.1

cc @zricethezav

**Comment by zricethezav** [comment]
fix released in https://github.com/zricethezav/gitleaks/releases/tag/v4.2.0. Reopen this issue if needed.
