### ISSUE TITLE
Cannot write a report

### ISSUE THREAD

**Issue by cyberbiont** [zricethezav/gitleaks#369]
I might be missing something very obvious here, but how do I write a report file?
I'm running this command from Powershell against local repo, using Docker container: 
```ps
docker run --rm --name=gitleaks -v /e/projects/my_repository:/code/ zricethezav/gitleaks -v --repo-path=/code --report=${pwd} --pretty --depth=1
```
It shows me leaks info, and then:
INFO[2020-04-15T01:39:50Z] report written to E:\Projects\current_directory

But in fact nothing gets written.

**Comment by steeve85** [comment]
This should work:
`docker run --rm --name=gitleaks -v `pwd`:/code/ zricethezav/gitleaks -v --repo-path=/code/ --report=/code/report.json --pretty --depth=1`

**Comment by cyberbiont** [comment]
Indeed, it worked. Thank you very much! I'm closing this.
