### ISSUE TITLE
Add support for scanning an enterprise Github organization

### ISSUE THREAD

**Issue by trayo** [zricethezav/gitleaks#37]
Tried scanning an organization in our enterprise github and I get an error:

```bash
gitleaks -o https://github.enterprise.com/enterprisegithub
2018/02/23 09:32:43 Get https://api.github.com/orgs/enterprisegithub/repos: read tcp 10.152.32.109:52205->192.30.253.116:443: read: connection reset by peer
```

It's clear now it doesn't use the full url provided so when I attempt to provide the full url according the usage from the help message, nothing happens:

```bash
gitleaks -o enterprisegithub https://github.enterprise.com/

Uknown option https://github.enterprise.com/

usage: gitleaks [options] <url>
```

Scanning a single repo does work on the other hand, but has to be done to every repo in the org.

**Comment by gopinath6** [comment]
Is organization repo works?Itscans  only 1 repo i org
OS: win7

![image](https://user-images.githubusercontent.com/6551119/36644174-73654b9c-1a7c-11e8-85b4-6cb1fb6ebe32.png)

**Comment by zricethezav** [comment]
@gopinath6 Didn't test on windows but looks like this error is popping up cause `rm` is not found. This should be fixed in the version bump. Let me know your findings after a reinstall

**Comment by trayo** [comment]
@zricethezav Was the organization issue I asked about fixed in the version bump?
