### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#372]
**Is your feature request related to a problem? Please describe.**
The gitleaks documentation is severely lacking. I've added a lot of features without taking the time to document them.

**Describe the solution you'd like**
A wiki page or a HOWTO.md in the repo with a bunch of examples and documentation on the available options.

**Additional context**
If anyone wants to help me with this I'd happily consider making them a collaborator.

cc @zricethezav

**Comment by rgkobashi** [comment]
first of all, thanks!

About the docs, is there some of it? I saw some place it refers to the wiki but it is empty so far.

TIA

**Comment by NdagiStanley** [comment]
I just discovered this tool yesterday from [linuxsecurity](https://linuxsecurity.expert/tools/gitleaks/)
It's awesome!

Probably if @rgkobashi has picked this up I'll be happy to help.

**Comment by NdagiStanley** [comment]
One more thing, I was just about to integrate this into my GitHub actions but it's not verified.
I've not seen an issue on that, any reason why @zricethezav?

What would it take to have it verified? Can anyone help with that?

**Comment by zricethezav** [comment]
Hey folks, I started a wiki page https://github.com/zricethezav/gitleaks/wiki which is editable by anyone and everyone. I would love to have in depth documentation on the how to configure rules. Right now all I have is an example folder https://github.com/zricethezav/gitleaks/tree/master/examples which does not cut it. 

Two pages I need help with: https://github.com/zricethezav/gitleaks/wiki/Configuration and https://github.com/zricethezav/gitleaks/wiki/Options. 

cc @NdagiStanley @rgkobashi

**Comment by zricethezav** [comment]
> One more thing, I was just about to integrate this into my GitHub actions but it's not verified.
> I've not seen an issue on that, any reason why @zricethezav?
> 
> What would it take to have it verified? Can anyone help with that?

Hey @NdagiStanley I'm actually not sure what you mean by it not being verified. Could you elaborate? Thanks!

**Comment by NdagiStanley** [comment]
> > One more thing, I was just about to integrate this into my GitHub actions but it's not verified.
> > I've not seen an issue on that, any reason why @zricethezav?
> > What would it take to have it verified? Can anyone help with that?
> 
> Hey @NdagiStanley I'm actually not sure what you mean by it not being verified. Could you elaborate? Thanks!

@zricethezav, my bad. I've just found out that verification is just for apps and not actions:
compare [gitleaks](https://github.com/marketplace/actions/gitleaks) action and these [apps](https://github.com/marketplace?type=apps).

**Comment by zricethezav** [comment]
Feel free to contribute to the wiki, closing this issue now
