### ISSUE TITLE
cannot find package "github.com/google/go-github/v29/github"

### ISSUE THREAD

**Issue by boly38** [zricethezav/gitleaks#373]
**Describe the bug**
we have cicd simple stage to execute gitleak :
```
.gitleaks:
  stage: validate
  image: golang
  script:
    - echo "Scanning Git repository for leaking secrets"
    - go get -u github.com/zricethezav/gitleaks
    - gitleaks --repo-path="$PWD" --verbose $GITLEAKS_OPTS
```

**To Reproduce**

This stage was working well for a while, but recently we are facing the following issue
```
 $ go get -u github.com/zricethezav/gitleaks
 package github.com/google/go-github/v29/github: cannot find package "github.com/google/go-github/v29/github" in any of:
 	/usr/local/go/src/github.com/google/go-github/v29/github (from $GOROOT)
 	/go/src/github.com/google/go-github/v29/github (from $GOPATH)
 ERROR: Job failed: exit code 1
```
**Screenshots**
![image](https://user-images.githubusercontent.com/3100576/80097756-1eec8280-856c-11ea-9a55-54803fa72cd0.png)

**Basic Info (please complete the following information):**
 - GitLab Community Edition 12.8.8

cc @zricethezav

**Comment by tomi-roam** [comment]
I was able to workaround this in our CI environment with `export GO111MODULE=on;` while manually testing installs as root.

However, to get it to work in our automation for Ansible/Jenkins, the following was the magic incantation (for running under `jenkins` user):
```
shell: sudo su -c "export GO111MODULE=on; go get github.com/zricethezav/gitleaks" -s /bin/bash jenkins
```

**Comment by boly38** [comment]
@tomi-roam your workaround works well, thanks

sage used on our side become:
```
.gitleaks:
  stage: validate
  image: golang
  script:
    - echo "Scanning Git repository for leaking secrets"
    - export GO111MODULE=on;
    - go get github.com/zricethezav/gitleaks
    - gitleaks --repo-path=\"$PWD\" --verbose $GITLEAKS_OPTS
```

**Comment by zricethezav** [comment]
@boly38 @tomi-roam I just merged a PR that bumps the go-github version to v31.

does 
```
go get -u github.com/zricethezav/gitleaks
```
work for you now?

**Comment by boly38** [comment]
thank you @zricethezav I will tell you that on monday 👍

**Comment by boly38** [comment]
Hi @zricethezav ,

 I test it again and here are my tests results as today:

```
.gitleaks:
  stage: validate
  image: golang:1.14.2-alpine3.11
  script:
    - echo "Scanning Git repository for leaking secrets"
    - export GO111MODULE=on;
    - go get -u github.com/zricethezav/gitleaks
    - gitleaks --repo-path=\"$PWD\" --verbose $GITLEAKS_OPTS
```

- with `export GO111MODULE=on;` : go get downloads deps and **gitleaks execution ok** - I'll keep this state for now

- **without `export GO111MODULE=on;` line** : 

```
 $ go get -u github.com/zricethezav/gitleaks
 go: missing Git command. See https://golang.org/s/gogetcmd
 package github.com/zricethezav/gitleaks: exec: "git": executable file not found in $PATH
```

- **with `image: golang`** (solved with image `sha256:2421885b04daf2f5095c46fe1889887d89e5ab77157e54423d97ea6816db54b6`) && **without `export GO111MODULE=on;` line** : 

```
 $ go get -u github.com/zricethezav/gitleaks
 package github.com/go-git/go-billy/osfs: code in directory /go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"
>Running after_script
Uploading artifacts for failed job
> ERROR: Job failed: exit code 1
```
(I've no more details this this last one, took a little time after osfs line log)

**Comment by zricethezav** [comment]
Is this still an issue? @boly38 @tomi-roam

**Comment by boly38** [comment]
my side, a working way is enough to close it, then I'll let you manage this issue state. Thanks 👍

**Comment by tomi-roam** [comment]
@ zricethezav It's still failing for me based on a quick test without the workaround. Some details below:

**Ansible playbook steps**
```
- name: As jenkins user - go get -u github.com/zricethezav/gitleaks
  shell: sudo su -c "go get -u github.com/zricethezav/gitleaks" -s /bin/bash jenkins
```

**Build failure***
```
13:00:57      amazon-ebs: TASK [jenkins-worker : As jenkins user - go get -u github.com/zricethezav/gitleaks] ***
13:01:24      amazon-ebs: fatal: [jenkins_worker]: FAILED! => {"changed": true, "cmd": "sudo su -c \"go get -u github.com/zricethezav/gitleaks\" -s /bin/bash jenkins", "delta": "0:00:25.323057", "end": "2020-06-02 18:01:22.134342", "msg": "non-zero return code", "rc": 1, "start": "2020-06-02 18:00:56.811285", "stderr": "package github.com/go-git/go-billy/osfs: code in directory /home/jenkins/go/src/github.com/go-git/go-billy/osfs expects import \"github.com/go-git/go-billy/v5/osfs\"\npackage github.com/google/go-github/v31/github: cannot find package \"github.com/google/go-github/v31/github\" in any of:\n\t/usr/lib/go-1.13/src/github.com/google/go-github/v31/github (from $GOROOT)\n\t/home/jenkins/go/src/github.com/google/go-github/v31/github (from $GOPATH)", "stderr_lines": ["package github.com/go-git/go-billy/osfs: code in directory /home/jenkins/go/src/github.com/go-git/go-billy/osfs expects import \"github.com/go-git/go-billy/v5/osfs\"", "package github.com/google/go-github/v31/github: cannot find package \"github.com/google/go-github/v31/github\" in any of:", "\t/usr/lib/go-1.13/src/github.com/google/go-github/v31/github (from $GOROOT)", "\t/home/jenkins/go/src/github.com/google/go-github/v31/github (from $GOPATH)"], "stdout": "", "stdout_lines": []}
```

And with that cleaned out a bit the error is:
`package github.com/go-git/go-billy/osfs: code in directory /home/jenkins/go/src/github.com/go-git/go-billy/osfs expects import \"github.com/go-git/go-billy/v5/osfs`

Going to try a few more things and will update separately _if_ I find anything useful.

**Comment by Ndh-31** [comment]
go get -u github.com/zricethezav/gitleaks
 package github.com/google/go-github/v29/github: cannot find package "github.com/google/go-github/v29/github" in any of:
 	/usr/local/go/src/github.com/google/go-github/v29/github (from $GOROOT)
 	/go/src/github.com/google/go-github/v29/github (from $GOPATH)
 ERROR: Job failed: exit code 1


how to resolved this error.
thanks

**Comment by zricethezav** [comment]
@tomi-roam @Ndh-31 can you try the solution presented here https://github.com/zricethezav/gitleaks/issues/405#issuecomment-653691458 please and let me know if this issue can be closed out.

**Comment by tomi-roam** [comment]
> @tomi-roam @Ndh-31 can you try the solution presented here [#405 (comment)](https://github.com/zricethezav/gitleaks/issues/405#issuecomment-653691458) please and let me know if this issue can be closed out.

Just ran a successful build with that suggestion, so should be good to close with that.
