### ISSUE TITLE
local repo scan does not work with docker version?

### ISSUE THREAD

**Issue by dkmbw** [zricethezav/gitleaks#376]
**Describe the bug**
I cannot scan local repositories with the docker image.
**To Reproduce**

I pulled and ran the program with docker:

   docker pull zricethezav/gitleaks
   docker run zricethezav/gitleaks -v --repo-path="$(pwd)"

and get the error:

  ERRO[2020-05-04T11:24:54Z] repository does not exist    

**Expected behavior**
Either document that local scanning does not work with the docker image in the wiki or make it possible to scan local repositories with the docker image (atm now idea how to do that)

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04 latest update
 - Gitleaks Version: latest docker image, date 2020-05-04 13:29 CET

cc @zricethezav

**Comment by yzhou94** [comment]
Try mount?
docker run -v $PWD:/path zricethezav/gitleaks -v --repo-path=/path

**Comment by c6g4** [comment]
this works

**Comment by sharadpattanshetti** [comment]
Hi, trying the same thing in windows 10 cmd but keep getting below error, appreciate your help on this 
command -  docker run --rm -i  zricethezav/gitleaks gitleaks  --repo-path=C:/work/gitrepocloned

Error - repository does not exist

**Comment by yzhou94** [comment]
> Hi, trying the same thing in windows 10 cmd but keep getting below error, appreciate your help on this
> command - docker run --rm -i zricethezav/gitleaks gitleaks --repo-path=C:/work/gitrepocloned
> 
> Error - repository does not exist

Docker works like a VM. You need to mount the volume into the new VM. Otherwise, this volume will not exist in the created VM. That's why this error occurred. 
Try this: 
docker run --rm -i -v "C:\work\gitrepocloned":/path zricethezav/gitleaks gitleaks --repo-path=/path.

**Comment by sharadpattanshetti** [comment]
It worked, Thank you

**Comment by zricethezav** [comment]
closing this, reopen if needed
