### ISSUE TITLE
Facebook Secret Key in gitleaks/config/default.go causes false positives

### ISSUE THREAD

**Issue by Zeyshi** [zricethezav/gitleaks#381]
**Describe the bug**
Incorrect regex rule in gitleaks/config/default.go for Facebook Secret Key causes false positive alerts

**To Reproduce**
Match the rule on `sha256:08a96c641c3a74e44eb59afb61a24f2cb9f4d7188748e76ba4bb5edfa3cb7d1c"
` or `"sha256:fb77ce16570fe9965acd6d30101a28f62fb4a7f9e926b3bbc9b61f8b04247e72"`

**Expected behavior**
Facebook Secret Key rule should not match such patterns

**Basic Info (please complete the following information):**
 - OS: any
 - Gitleaks Version: 4.2.0

**Additional context**
Suggested fix: regex should be `(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]`

cc @zricethezav

**Comment by zricethezav** [comment]
Feel free to open a PR
