### ISSUE TITLE
GitLeaks (totalPatchTime) has dramatically different performance on two nearly-identical repos

### ISSUE THREAD

**Issue by ed-sulli** [zricethezav/gitleaks#384]
# Describe the bug
I have two repos called **ABC** and **ABC-clone** and they are ostensibly equivalent (please see below for a detailed comparison). However, when I invoke `/home/githook/gitleaks --debug --repo-path=. --commit=b372769d4025e174a5b1c367c2963823f8e1eea5 -v` on both repos in a server-side pre-receive hook on GitHub Enterprise using the same arguments, the performance is dramatically slower for **ABC** compared to **ABC-clone**.

According to the debugging/profiling output of Gitleaks (produced with the `--debug` option), the performance difference occurs when generating the patch/diff: during my most recent measurement, the `totalPatchTime` value for **ABC** was `4 seconds 228 milliseconds 541 microseconds`, whereas the `totalPatchTime` value for **ABC-clone** was only `59 milliseconds 463 microseconds`. 4 seconds seems like a VERY LONG time to generate a small patch.

The `totalPatchTime` value reflects the execution on a few lines of code in Gitleaks (https://github.com/zricethezav/gitleaks/blob/master/audit/util.go#L297-L302) that invoke Commit.Patch() from the **go-git** library (https://github.com/go-git/go-git/blob/master/plumbing/object/commit.go#L101-L107). I have created a separate ticket for the same issue in the **go-git** library here (https://github.com/go-git/go-git/issues/67).

**Does anyone know why GitLeaks (or go-git) might have different performance on my two ostensibly equivalent repos?** This slow performance may unfortunately prohibit me from using GitLeaks for my specific use case.

# Expected behavior
I'd expect Gitleaks to have similar fast performance for both repos (< 1 second for my particular push). I would not expect Gitleaks to take > 3 seconds for the `ABC` repo.

# Basic Info
 - Env: Pre-receive hook FireJail/chroot sandboxgith for GitHub Enterprise server hosted on Google Cloud
 - Host kernel: Linux 4.9.0-12-amd64
 - Host architecture: x86-64
 - Host OS: Debian GNU/Linux 9.12 (stretch)
 - Gitleaks Version: v4.2.0
 - Go-git Version: v5.0.0

# Additional context

### Are the repos actually the same?
* **Similarity**: when I visit the repos in the browser, they appear to be the same, because they both have 3,163 commits and 330 branches. The repos have the same content (ie. `git show COMMIT_ID` will return the same output for both repos).
* **Difference**: when I investigate the server-side instances of the repos and I execute `echo -e $(du -sh *)` in the `.git` directory, the repos appear quite different. The **ABC** repo (slow) has a server-side .git/objects directory of 1.0 MB whereas the **ABC-clone** repo (fast) has a server-side .git/objects size of 11.5 MB.....so I'm very confused. I would have expected their .git/objects directories to be the same size. See my `du` output below. My hypothesis is that, due to the gradual organic way in which the **ABC** repo was created over the course of a few years, compared to the rapid way in which I cloned it in a few minutes (using a combination of `git remote update`, `git fetch --all`, `git pull --all`, `git branch --track`, `git push --all`, etc.), the **ABC** repo more efficiently re-uses the same objects, whereas the **ABC-clone** repo probably has some duplicate objects that could be garbage collected with something like `git gc`. I'm still digging into this a bit.
* **Difference**: the **ABC** repo (slow) has a few different settings in GitHub Enterprise than the **ABC-clone** repo. Specifically, the **ABC** repo has a few webhooks installed and a few install GitHub Apps, whereas the **ABC-clone** repo has no webhooks and no apps installed. I'm investigating the behavior of the apps currently.

### Are the runtime environments the same, when invoking the `Commit.Patch()` for both repos? Do both invocations have similar CPU, RAM, disk, etc. resources?
Yes. I've done a modest amount of benchmarking, and all my tests indicate that both invocations have similar resources.
* IMPORTANT: notably `git show COMMIT_ID` runs just as fast server-side in both repos when I timed it for the same commit id!!!
* I used another test to very very roughly benchmark multiplication and division operations to ensure that CPU/ALU resource availability was approximately equivalent

### Output of `du -sh .git/*`
```
ABC (slow)                     ABC-clone (fast)
=================================================
4.0K FETCH_HEAD                -
4.0K HEAD                      4.0K HEAD
6.8M audit_log                 400.0K audit_log
4.0K config                    4.0K config
4.0K description               4.0K description
4.0K dgit-state                4.0K dgit-state
0 dgit-state.flock             0 dgit-state.flock
0 hooks                        0 hooks
20.0K info                     12.0K info
4.0K language-stats.cache.     4.0K language-stats.cache
2.8M logs                      1.3M logs
0 nw-sync.lock                 -
1.0M objects                   11.5M objects
88.0K packed-refs              4.0K packed-refs
4.0K refs                      1.3M refs
-                              0 nw-repack.flock
```

### What commit am I testing with?
The commit that I'm testing with is very small. For privacy, I've obfuscated it heavily, but the key aspects (size of changes, number of files modified, type of files, etc.) are the same.
```
commit c372960a4124f724e5b1c967c2913829f8e1eea1 (origin/some-branch-3)
Author: OMITTED <OMITTED>
Date:   OMITTED

    normal commit message blah blah blah

diff --git a/foo/bar/baz/qux-quux/corge.yaml b/foo/bar/baz/qux-quux/corge.yaml
index cc3fd755..4af4d258 100644
--- a/foo/bar/baz/qux-quux/corge.yaml
+++ b/foo/bar/baz/qux-quux/corge.yaml
@@ -30,7 +30, @@ egress:
      ijk.xyz.foobar.io/prox-body-key: "10"
      ijk.xyz.foobar.io/prox-read-limit: "900"
      ijk.xyz.foobar.io/prox-send-limit: "900"
-     ijk.xyz.foobar.io/prox-src-max-age: "100"
+     ijk.xyz.foobar.io/prox-src-max-age: "90"
   hosts:
     - waldo.fred.com
   tls:
@@ -53,7 +53,7 @@ abc:
   xyz:
     name: abc-xyz
     resources:
-      requests: 40G
+      requests: 200G

 variables: {}
```

cc @zricethezav

**Comment by ed-sulli** [comment]
I've discovered that the source of the slowness is likely `go-git`'s algorithm for accessing trees, specifically the a repo has been forked and uses the `.git/objects/info/alternates` file in conjunction with storage in `.git/objects/../../network.git`. 

For more explanation, please see my detailed comment for **go-git** here: https://github.com/go-git/go-git/issues/67#issuecomment-630903816

I'll leave this issue open for the moment, in case any other users of Gitleaks have experienced my same issue and can suggest workarounds.

**Comment by zricethezav** [comment]
Gonna remove the bug label but keep this open as it has useful information. Likely will throw this in a wiki page as well.

**Comment by zricethezav** [comment]
Captured here https://github.com/zricethezav/gitleaks/wiki/FAQs

closing

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Hi @zricethezav it seems that the link is broken, https://github.com/zricethezav/gitleaks/wiki/FAQs direct here https://github.com/zricethezav/gitleaks
Is possible still to see how is documented?

**Comment by zricethezav** [comment]
@RUBenGAMArrarodRiguEZ-ToMtOm I removed the wiki as the README/issue search is sufficient documentation. This issue is not a problem anymore since Gitleaks no longer relies on go-git
