### ISSUE TITLE
List of URLs can't run

### ISSUE THREAD

**Issue by cyrus43** [zricethezav/gitleaks#386]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
No description, closing

**Comment by azim254** [comment]
:joy::joy::joy::joy::joy::joy::joy::joy::joy::joy::joy:
   :joy::joy::joy::joy::joy::joy::joy::joy::joy: 
 :joy::joy::joy::joy::joy::joy::joy::joy::joy:
