### ISSUE TITLE
Consider adding a comparison with other alternatives

### ISSUE THREAD

**Issue by kaushalyap** [zricethezav/gitleaks#387]
Please consider adding a feature comparison table to the README with other alternatives like

- https://github.com/michenriksen/gitrob
- https://github.com/dxa4481/truffleHog
- https://github.com/awslabs/git-secrets

**Comment by zricethezav** [comment]
I like that idea. It would be better suited for the wiki here: https://github.com/zricethezav/gitleaks/wiki which anyone can contribute.

**Comment by gchib297** [comment]
Added comparison table to wiki [here](https://github.com/zricethezav/gitleaks/wiki/Comparison-with-other-tools) based on @codeEmitter slides:

![image](https://user-images.githubusercontent.com/11896766/89269659-ce4ef000-d657-11ea-9c76-77d04debd98c.png)

Reference:
[Token-Hunter and gitrob:  Hunting for Secrets - Black Hat USA 2020](https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/red-team-tech-notes/-/tree/master/blackhat2020-hunting-for-secrets)

**Comment by zricethezav** [comment]
@gchib297 thank you for adding the table to the wiki! 

Next item I'd like to tackle is comparing performance and accuracy between the tools but that could be opened in another issue.
