### ISSUE TITLE
Uknown option --report=

### ISSUE THREAD

**Issue by ishaq201** [zricethezav/gitleaks#388]
**Bug Description:**
Trying to run the gitleaks docker on an organisation and trying to create a report out of it but i am getting the error saying `Uknown option --report=`, without the report option the image seems to be running fine

**To Reproduce:**
`docker run --rm --name=gitleaks -v `pwd`:/code/ raphaelareya/gitleaks -o <github-org-url --report=/code/report.json --pretty --depth=1`

**Screenshots:**
[Screenshot](https://prnt.sc/sppval)

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Gitleaks Version:
- Docker Version: Docker version 19.03.8, build afacb8b7f0

cc @zricethezav

**Comment by zricethezav** [comment]
You are running the wrong docker image. This is the official image: https://hub.docker.com/r/zricethezav/gitleaks
