### ISSUE TITLE
whitelist commit doesn't work for first commit in repo history

### ISSUE THREAD

**Issue by pburkholder** [zricethezav/gitleaks#389]
**Describe the bug**

When I provide a list of commits to whitelist like this:

```
[whitelist]
  commits = [
    "c60cc343f4819d867ef2d6ec0b2b699b0f96e2d6",
    "daa2527782ee2ce5397d889019da9ca756c1accc"
  ]
```

If a listed commit is the initial commit, it's not whitelisted.

**To Reproduce**

Run this script:

https://gist.github.com/pburkholder/bdffb295bbac4caee4ae86d69671a3be

**Expected behavior**

It should find zero leaks. Instead it still finds one from the initial commit.

**Screenshots**

![image](https://user-images.githubusercontent.com/1211146/83258812-f700c800-a184-11ea-98a0-e7d76345d115.png)

**Basic Info (please complete the following information):**
 - OS: Mac
 - Gitleaks Version: 4.2.0

cc @zricethezav

**Comment by zricethezav** [comment]
Think I found the issue. https://github.com/zricethezav/gitleaks/blob/master/audit/repo.go#L285-L296 these two blocks should be switched.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/issues/377#issuecomment-630432655 duplicate issue for tracking
