### ISSUE TITLE
GITHUB_TOKEN environment variable doesn't seem to work since v.2.1.0

### ISSUE THREAD

**Issue by jdispiritoae** [zricethezav/gitleaks#391]
First, Thank you for writing this awesome software!!

**Describe the bug**
I'm passing the GITHUB_TOKEN environment variable to gitleaks (I've tried every version since v2.1.0) and it seems that when I try to clone a repository it gives me authentication required.

**To Reproduce**
using docker build --env-file=envs.txt 
My dockerfile runs a python script to gather all of my private repositories and run gitleaks on each one.   When I download the v2.1.0 release, it works perfectly.  When I use anything greater than v.2.1.0 I get:
INFO[2020-06-01T20:48:36Z] cloning... https://github.com/myorg/myrepo 
ERRO[2020-06-01T20:48:36Z] authentication required

**Expected behavior**
The repository should be cloned, and commits analyzed as normal.

**Screenshots**
Running v.2.1.0, passing GITHUB_TOKEN, no issue with authentication:
<img width="611" alt="gitleaks_v2 1 0" src="https://user-images.githubusercontent.com/49879235/83455126-597af200-a42b-11ea-862e-47936306af64.png">

Running v4.3.0 (or anything > v2.1.0) passing GITHUB_TOKEN, problem with authentication:
<img width="613" alt="gitleaks_v4 3 0" src="https://user-images.githubusercontent.com/49879235/83455183-757e9380-a42b-11ea-9aba-e7836ef253b9.png">

**Basic Info (please complete the following information):**
 - OS:  Windows 10, Docker  running Centos:7, python3,
 - Gitleaks Version: working version 2.1.0, affected version anything > v.2.1.0

cc @zricethezav

**Comment by zricethezav** [comment]
Access token authentication has been changed to the env var: `GITLEAKS_ACCESS_TOKEN`. Could you try using that and let me know if you are still experiencing issues?

**Comment by jdispiritoae** [comment]
That fixed it! Thanks.
I also doublechecked and don't see that documented anywhere,  unless I missed something.  It might save someone some trouble one day. 

Thank you again!
John.
