### ISSUE TITLE
commit-to/commit-from seems broken since v4.2.0

### ISSUE THREAD

**Issue by fmigneault** [zricethezav/gitleaks#392]
**Describe the bug**

I'm using the generated docker by this repo to run a custom action https://github.com/fmigneault/gitleaks-action. 

When using v4.1.1, I get the following (as expected) :
``` 
bash-5.0# GITHUB_HEAD_SHA=93f1863d2fc9b9831bc970db17bbf61d3a754529
bash-5.0# GITHUB_BASE_SHA=7e1c8f365ddc28a2f9a66da8103be302baaf29cf
bash-5.0# GITHUB_REF_NAME=merge
bash-5.0# gitleaks -v --exclude-forks --redact --threads=1 \
>             --commit-from=${GITHUB_HEAD_SHA} \
>             --commit-to=${GITHUB_BASE_SHA} \
>             --repo-path=/github/workspace
INFO[2020-06-03T01:56:05Z] No leaks detected. 4 commits audited in 45 milliseconds 996 microseconds 
```

But starting with v4.2.0: 
```
bash-5.0# GITHUB_HEAD_SHA=93f1863d2fc9b9831bc970db17bbf61d3a754529
bash-5.0# GITHUB_BASE_SHA=7e1c8f365ddc28a2f9a66da8103be302baaf29cf
bash-5.0# GITHUB_REF_NAME=merge
bash-5.0# gitleaks -v --exclude-forks --redact --threads=1 \
>             --commit-from=${GITHUB_HEAD_SHA} \
>             --commit-to=${GITHUB_BASE_SHA} \
>             --repo-path=/github/workspace
ERRO[2020-06-03T01:54:38Z] invalid commit options set 
```

The commands are exactly the sames, as the error seems related to incorrect parsing/resolution of `commit-to` and `commit-from` parameters.

**To Reproduce**
Run some gitleaks command with `commit-to` and `commit-from` parameters.

**Expected behavior**
Should still work as before.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: running in linux-musl docker image
 - Gitleaks Version: error with v4.2+

cc @zricethezav

**Comment by zricethezav** [comment]
Woof, thats a big one. Pushed a fix now and deploying new version momentarily. Thanks for finding this!

**Comment by zricethezav** [comment]
Fixed in https://github.com/zricethezav/gitleaks/releases/tag/v4.3.1

**Comment by fmigneault** [comment]
@zricethezav Thanks

**Comment by gregoriB** [comment]
This fixes the "invalid commit options set" error, but now I get "object not found" instead

**Comment by zricethezav** [comment]
@gregoriB could you open an additional issue if you think this is a bug?
