### ISSUE TITLE
Integrate GitLeaks with Patrowl

### ISSUE THREAD

**Issue by MaKyOtOx** [zricethezav/gitleaks#393]
Hello,
What about integrate GitLeaks with Patrowl ? (see: https://github.com/Patrowl/PatrowlManager and https://github.com/Patrowl/PatrowlEngines)
With this new engine, it will enable users to have a continuous overview of data/secret leaks and mix these findings collected from other source code scanners (Checkmark, OWASP-DC, Retire.JS, SonarQube, ...) -> Great enhancement in Secure SDLC and SAST processes

Ready to help :)
Cheers

**Comment by zricethezav** [comment]
I'm open to it but this seems like something the maintainers of patrowl would implement. I don't have the time to do something like this unless we are talking $

**Comment by zricethezav** [comment]
@MaKyOtOx Opening an issue on the Patrowl project would be more appropriate. Closing this as I have no plans to work on this integration.
