### ISSUE TITLE
go.sum triggers AWS leak rule

### ISSUE THREAD

**Issue by adamdecaf** [zricethezav/gitleaks#394]
**Describe the bug**

The following leak is detected when scanning [moov-io/customers](https://github.com/moov-io/customers):

```json
{
	"line": "github.com/aws/aws-sdk-go v1.31.11 h1:Uz7VGg3giOV9Z4SlLdXO6RHafArHbK59vSc6mnzYjGU=",
	"offender": "aws-sdk-go v1.31.11 h1:Uz7VGg3giOV9Z4SlLdXO6RHafArHbK59vSc6mnzY",
	"commit": "e80c0333ab600a35ba07b9b4ac994b4aa8fadf17",
	"repo": "customers",
	"rule": "AWS Secret Key",
	"commitMessage": "chore(deps): update all\n",
	"author": "Renovate Bot",
	"email": "bot@renovateapp.com",
	"file": "go.sum",
	"date": "2020-06-05T15:45:05Z",
	"tags": "key, AWS"
}
```

This commit: https://github.com/moov-io/customers/commit/e80c0333ab600a35ba07b9b4ac994b4aa8fadf17 

**To Reproduce**

`./bin/gitleaks --depth=10 --repo-path=$(pwd) --pretty --verbose`

**Expected behavior**

No leak should be found as this is from a `go.sum` file (dependency tracking).

**Additional context**
This looks like https://github.com/zricethezav/gitleaks/issues/366 but perhaps the rules changed from v4.2.0? 

cc @zricethezav

**Comment by zricethezav** [comment]
@adamdecaf Thanks for pointing that out. The rule defined here https://github.com/zricethezav/gitleaks/blob/master/config/default.go#L16 does not include quotes which would help reduce false positives.

This also brings up another good idea: `go.mod` and `go.sum` files should be whitelisted by default.

**Comment by adamdecaf** [comment]
Awesome, thanks!
