### ISSUE TITLE
Two secrets in same line do not get scanned

### ISSUE THREAD

**Issue by tdhavalikar** [zricethezav/gitleaks#395]
**Describe the bug**
If there are more than one secrets in single line, only one secret gets scanned. The other secrets do not get detected.

**To Reproduce**
1.  Introduce more than one secrets in same line and scan with gitleaks

**Expected behavior**
All secrets in the same line should be detected.

**Basic Info (please complete the following information):**
 - OS: Amazon Linux
 - Gitleaks Version: v4.1.0

cc @zricethezav

**Comment by zricethezav** [comment]
@tdhavalikar could you run with the latest version and tell me if its still an issue. Thanks 👍

**Comment by zricethezav** [comment]
with v5.0.1 this shouldn't be an issue anymore. Reopen if it is.
