### ISSUE TITLE
How to scan only pull request of a particular organisation repository

### ISSUE THREAD

**Issue by strikergoutham** [zricethezav/gitleaks#396]
First of everything, i would like to thank you for such an awesome project! I tried `--pr` option
to scan a particular PR by giving url of the pull request. It still gives me an error "Specified repo not found" can somebody please let me know how to use this feature? what options does this need precisely? Thanks!

Edit 1 : I was able to audit a PR. but the problem is it always results in zero leaks. am i doing something wrong? it does not scan the commits at all( 0 commits)

ex : `gitleaks-windows-amd64.exe /config rules.toml /host github /debug /pr "https://www.github.com/repo/test/pull/4"`

cc @zricethezav

**Comment by zricethezav** [comment]
@strikergoutham in order to scan a PR you need to use the github api which requires an access token. Are you providing a github access-token via env var `GITLEAKS_ACCESS_TOKEN` or the option `--access-token`?

**Comment by strikergoutham** [comment]
Thank you :) ! Got to know eventually. I forgot to update here.

**Comment by alteral** [comment]
Hi @zricethezav, I've tried `--pr` argument on macOS with `--access-token` and `GITLEAKS_ACCESS_TOKEN` env variable:

`gitleaks --redact --pretty --debug --pr="https://github.com/repo/test/pull/15" --access-token="$TOKEN"`

But still getting:

```
totalAuditTime:  3 seconds 615 milliseconds 335 microseconds
totalPatchTime:  0 seconds
totalCloneTime:  0 seconds
totalCommits:  0
```

Thanks in advance!

**Comment by strikergoutham** [comment]
Hey @alteral ,

 you need to add "--host github" along with your current command. Hope this helps.

**Comment by alteral** [comment]
> Hey @alteral ,
> 
> you need to add "--host github" along with your current command. Hope this helps.

Thank you, now it works 🚀
