### ISSUE TITLE
Enable traversing multi-level project groups in GitLab

### ISSUE THREAD

**Issue by crunchtime-ali** [zricethezav/gitleaks#399]
**Is your feature request related to a problem? Please describe.**

GitLab supports multi-level organizations (project groups) and therefore I would like to be able to traverse the complete organization (or even GitLab instance) with gitleaks

**Describe the solution you'd like**
There should be a `traverse` option which traverses the organization to the most specific level and checks all projects for secrets when set to `true` (default would be `false`)

**Describe alternatives you've considered**
Right now I am collecting a list of all organizations (by calling the GitLab v4 API via cURL) before calling `gitleaks` for each individual one of them.

cc @zricethezav

**Comment by matsskoglund** [comment]
I want this too. 
It can easily be done by adding in gitlab.go from line 63 to something like:

var recursive = true
	glOpts := &gitlab.ListGroupProjectsOptions{
	ListOptions:      listOpts,
	IncludeSubgroups: &recursive,
}

Need to get the traverse flag into the function and fix the argument flags though to make it an option. 

I am pretty new at Go but if I can get some assistance and suggestions how to proceed I could probably manage to create a pull request for this feature if wanted.

cc @zricethezav

**Comment by zricethezav** [comment]
I am not supporting scans that use gitlab/github apis. See https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
