### ISSUE TITLE
Support other git url types

### ISSUE THREAD

**Issue by fd** [zricethezav/gitleaks#4]
these are not properly supported 

```
git://...
user@host:...
```

**Comment by zricethezav** [comment]
👍 will look into this

**Comment by bestform** [comment]
Here is my proposal for a solution. It generates the local repo name based on the URL.

An alternative solution would be to generate a random folder name and just explicitly clone into this one. But my solution has minimal impact on the current implementation and it should work for the given test cases.

**Comment by fd** [comment]
A random folder name under `$TMPDIR` is probably the most logical solution.

**Comment by bestform** [comment]
Yeah, that's probably what should be done. So feel free to close my PR or merge it and substitute it with the alternative later.

**Comment by zricethezav** [comment]
Thanks @bestform and @fd I'll merge the PR to support different url types then implement @fd's solution at a later time.
