### ISSUE TITLE
Any custom rules files ?

### ISSUE THREAD

**Issue by CargaisonTuba** [zricethezav/gitleaks#401]
Hi guys !
For some reasons I would like to know if there are available custom rulepack ?
Because the default config only looks for aws and some websites..?
Any place I can find kind of a "starter pack rules" that includes most commons keywords ? Like "password", email, regex, etc etc 
Sorry maybe it's not the good place to ask this question
Thanks for your time !

**Comment by zricethezav** [comment]
Hey @CargaisonTuba there are some example rules located [here](https://github.com/zricethezav/gitleaks/tree/master/examples) and an explanation of how the rules works is in the wiki [here](https://github.com/zricethezav/gitleaks/wiki/Configuration).

That said, I would encourage folks to create their own rulepacks and open a PR or add them to the wiki which is editable by anyone.

**Comment by CargaisonTuba** [comment]
Yeah well finally I create some really basic regex about password, MD5 hash (cause it's a weak hash), email (very basic, will detect dzadzaadz@dzadzazd.ckd) here it is : 
`[[rules]]
	description = "Basic email regex"
	regex = '''\w{4,36}@[a-z]{3,20}.[a-z]{0,5}'''
	tags = ["email", "address"]

[[rules]]
	description = "Password basic regex"
	regex = '''(?i)pass\w{0,10}\s*:?=+\s*("|'){1,3}.*("|'){1,3}'''
	tags = ["password"]

[[rules]]
	description = "MD5 Hash"
	regex = '''[^a-f0-9-][a-f0-9]{32}[^a-f0-9-]'''
	tags = ["hash", "md5"]`

I also wanted to look for .conf files, so I made this one 
`[[rules]]
	description="config file"
	regex='''\.conf'''
	tags = ["config file"]`
But it doesn't seem to work. Does Gitleaks check filenames ?
That would be great :)

**Comment by zricethezav** [comment]
@CargaisonTuba you can create a rule that checks the `.conf` file name:
```
[[rules]]
	description="config file"
	filenameregex='''.conf'''
	tags = ["config file"]
```
See https://github.com/zricethezav/gitleaks/wiki/Configuration for more info. 

closing the issue, reopen if that doesn't answer your question
