### ISSUE TITLE
Can't load package: package gitleaks-linux-amd64: cannot find package "gitleaks-linux-amd64"

### ISSUE THREAD

**Issue by bearsystems** [zricethezav/gitleaks#402]
**Describe the bug**
I tried to download the latest installer and then I attempted to run through the posted GO command to build from the latest repository but, in both cases I received the following error on my Linux machine:

can't load package: package gitleaks-linux-amd64: cannot find package "gitleaks-linux-amd64" in any of:
        /usr/local/go/src/gitleaks-linux-amd64 (from $GOROOT)
        /home/kali/go/src/gitleaks-linux-amd64 (from $GOPATH)

Do I need to download a separate package and/or set a path?

**To Reproduce**

Run **go get github.com/zricethezav/gitleaks/v4**
```
package github.com/zricethezav/gitleaks/v4: cannot find package "github.com/zricethezav/gitleaks/v4" in any of:
        /usr/local/go/src/github.com/zricethezav/gitleaks/v4 (from $GOROOT)
        /home/kali/go/src/github.com/zricethezav/gitleaks/v4 (from $GOPATH)
```

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Kali Linux
 - Gitleaks Version: v4

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
`gitleaks-linux-amd64` is not an installer, its an actual binary. You don't need to run `go get` in order to get it to run. @bearsystems
