### ISSUE TITLE
Couldn't install with go-get

### ISSUE THREAD

**Issue by ogogceloglu** [zricethezav/gitleaks#405]
Hello all,

For some reason when we try to install gitleaks via go, we've got error as below;
`package github.com/zricethezav/gitleaks/v4: cannot find package "github.com/zricethezav/gitleaks/v4" in any of`

When we try with `go get github.com/zricethezav/gitleaks` it gives us;
`package github.com/google/go-github/v31/github: cannot find package "github.com/google/go-github/v31/github" in any of:`

We get errors in both the local and the devops pipeline as explained. Is there a part we missed?

Thank you,

**Comment by nitzango** [comment]
Same here. 
github.com/zricethezav/gitleaks/v4 gets 404

**Comment by CargaisonTuba** [comment]
Yeah had the same problem, just download the source code and build it yourself you'll gain time and you'll be able to custom your rules

**Comment by ogogceloglu** [comment]
> Yeah had the same problem, just download the source code and build it yourself you'll gain time and you'll be able to custom your rules

Yeah you're right. I can run it this way from the beginning. However, when GO task added in Azure DevOps pipeline, not possible to run. I wonder if there is anything else that needs to be done here, but I see that everyone has this problem.

**Comment by zricethezav** [comment]
Folks, looks like ya'll are right. This has to do with installing w/ go modules. I was toying around with some things might've got something to work:

Can you try 
```
 RUN GO111MODULE=on go get github.com/zricethezav/gitleaks/v4
```

cc @ogogceloglu @camaya  @nitzango

**Comment by ShivamRai2003** [comment]
> Hello all,
> 
> For some reason when we try to install gitleaks via go, we've got error as below;
> `package github.com/zricethezav/gitleaks/v4: cannot find package "github.com/zricethezav/gitleaks/v4" in any of`
> 
> When we try with `go get github.com/zricethezav/gitleaks` it gives us;
> `package github.com/google/go-github/v31/github: cannot find package "github.com/google/go-github/v31/github" in any of:`
> 
> We get errors in both the local and the devops pipeline as explained. Is there a part we missed?
> 
> Thank you,

Same Here I am getting error

**Comment by ShivamRai2003** [comment]
> Folks, looks like ya'll are right. This has to do with installing w/ go modules. I was toying around with some things might've got something to work:
> 
> Can you try
> 
> ```
>  RUN GO111MODULE=on go get github.com/zricethezav/gitleaks/v4
> ```
> 
> cc @ogogceloglu @camaya @nitzango

Great ! Appreciated ! Worked For me :)
