### ISSUE TITLE
No secrets identified

### ISSUE THREAD

**Issue by rrupesh** [zricethezav/gitleaks#406]
_user@mbpro % git clone https://github.com/Plazmaz/leaky-repo.git **--depth=1**_

Cloning into 'leaky-repo'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 85 (delta 4), reused 62 (delta 1), pack-reused 0
Receiving objects: 100% (85/85), 37.01 KiB | 6.17 MiB/s, done.
Resolving deltas: 100% (4/4), done.

_user@mbpro % cd leaky-repo 
user@mbpro leaky-repo % gitleaks --repo-path=. --debug -v (tried several variations and no luck!)_
               
DEBU[2020-07-03T18:26:09+01:00] -------------------------                    
DEBU[2020-07-03T18:26:09+01:00] | Times and Commit Counts|                   
DEBU[2020-07-03T18:26:09+01:00] -------------------------                    
totalAuditTime:  2 milliseconds 530 microseconds
totalPatchTime:  0 seconds
totalCloneTime:  0 seconds
totalCommits:  1
DEBU[2020-07-03T18:26:09+01:00] --------------------------                   
DEBU[2020-07-03T18:26:09+01:00] | Individual Regex Times |                   
DEBU[2020-07-03T18:26:09+01:00] --------------------------                   
INFO[2020-07-03T18:26:09+01:00] No leaks detected. 1 commits audited in 2 milliseconds 530 microseconds 

gitleaks is unable to identify any secrets when a repo is cloned with `--depth=1`

**Basic Info (please complete the following information):**
 - OS: MacOSX, Ubuntu
 - Gitleaks Version: v4.3.1

cc @zricethezav

**Comment by zricethezav** [comment]
@rrupesh should you be expecting secrets? I don't see any in this [commit](https://github.com/Plazmaz/leaky-repo/commit/2e951359cac53addbee56437da3ffb546e3dfe24) which is scanned when depth=1

Closing this issue.
