### ISSUE TITLE
Bug in line number feature

### ISSUE THREAD

**Issue by steeve85** [zricethezav/gitleaks#413]
**Describe the bug**
Gitleaks v5 is great, again thanks for this tool! I found a bug in the new line number feature. In some cases, `-1` is returned as a line number even if the operation is an `addition` and not `deletion`.

**To Reproduce**

```
❯ git clone git@github.com:thoughtworks/talisman.git
❯ cd talisman
❯ gitleaks --repo-path=. --verbose --pretty
```

Sample output:
```
{
	"line": "{\"summary\":{\"types\":{\"filecontent\":1044,\"filesize\":0,\"filename\":0,\"warnings\":0,\"ignores\":0}},\"results\":[{\"filename\":\"detector/base64_detector_test.go\",\"failure_list\":[{\"type\":\"filecontent\",\"message\":...",
	"lineNumber": -1,
	"offender": "AWS key :\",\"commits\":[\"af07fc983236d46ef51067a1b9da46e5fdc5992f\"",
	"commit": "b6f13ba79c420fac9661dcbe2e1c4b614adc6851",
	"repo": ".",
	"rule": "AWS Secret Key",
	"commitMessage": "Merge branch 'master' of https://github.com/thoughtworks/talisman\n",
	"author": "Aaquib Zama",
	"email": "aaquibza@thoughtworks.com",
	"file": "talisman_reports/report.json",
	"date": "2019-03-11T23:16:07+05:30",
	"tags": "key, AWS",
	"operation": "addition"
}
{
	"line": "{\"summary\":{\"types\":{\"filecontent\":1044,\"filesize\":0,\"filename\":0,\"warnings\":0,\"ignores\":0}},\"results\":[{\"filename\":\"detector/base64_detector_test.go\",\"failure_list\":[{\"type\":\"filecontent\",\"message\":...",
	"lineNumber": -1,
	"offender": "AWS key :\",\"commits\":[\"af07fc983236d46ef51067a1b9da46e5fdc5992f\"",
	"commit": "23ae90a12bd88723ce0817241b4e0174c45817c4",
	"repo": ".",
	"rule": "AWS Secret Key",
	"commitMessage": "Adds summary in the JSON and refactoring the code\n\nAdds summary in the JSON and refactoring the code\n\n- Adds summary section into the JSON\n- Refactors the code for extensibility\n\nRevert \"Adds summary in the JSON and refactoring the code\"\n\nThis reverts commit 86c5a845e2a05af5c5f5c9500b7236d08f717e88.\n\nRevert \"Revert \"Adds summary in the JSON and refactoring the code\"\"\n\nThis reverts commit f0064e87800e40707dd350a9acfab9f81eca42bf.\n",
	"author": "Aaquib Zama",
	"email": "aaquibza@thoughtworks.com",
	"file": "talisman_reports/report.json",
	"date": "2019-03-11T20:33:44+05:30",
	"tags": "key, AWS",
	"operation": "addition"
}
[...]
{
	"line": "{\"summary\":{\"types\":{\"filecontent\":1044,\"filesize\":0,\"filename\":0,\"warnings\":0,\"ignores\":0}},\"results\":[{\"filename\":\"detector/base64_detector_test.go\",\"failure_list\":[{\"type\":\"filecontent\",\"message\":...",
	"lineNumber": -1,
	"offender": "AWS key :\",\"commits\":[\"af07fc983236d46ef51067a1b9da46e5fdc5992f\"",
	"commit": "af0c9642f5ae18b9bd4098bf320c089fbe24dc9e",
	"repo": ".",
	"rule": "AWS Secret Key",
	"commitMessage": "Fixing conflicts in README\n",
	"author": "Harinee",
	"email": "harineem@thoughtworks.com",
	"file": "talisman_reports/report.json",
	"date": "2019-04-03T00:32:05+05:30",
	"tags": "key, AWS",
	"operation": "addition"
}
```

**Expected behavior**

The line number should be different from `-1`

**Basic Info (please complete the following information):**
 - OS: MacOS
 - Gitleaks Version: v5

**Additional context**

I think the issue might be somewhere else than in the line number feature. Because based on the following output, we should find a secret in this commit https://github.com/thoughtworks/talisman/commit/af0c9642f5ae18b9bd4098bf320c089fbe24dc9e.
```
{
	"line": "{\"summary\":{\"types\":{\"filecontent\":1044,\"filesize\":0,\"filename\":0,\"warnings\":0,\"ignores\":0}},\"results\":[{\"filename\":\"detector/base64_detector_test.go\",\"failure_list\":[{\"type\":\"filecontent\",\"message\":...",
	"lineNumber": -1,
	"offender": "AWS key :\",\"commits\":[\"af07fc983236d46ef51067a1b9da46e5fdc5992f\"",
	"commit": "af0c9642f5ae18b9bd4098bf320c089fbe24dc9e",
	"repo": ".",
	"rule": "AWS Secret Key",
	"commitMessage": "Fixing conflicts in README\n",
	"author": "Harinee",
	"email": "harineem@thoughtworks.com",
	"file": "talisman_reports/report.json",
	"date": "2019-04-03T00:32:05+05:30",
	"tags": "key, AWS",
	"operation": "addition"
}
```

But the commit https://github.com/thoughtworks/talisman/commit/af0c9642f5ae18b9bd4098bf320c089fbe24dc9e only contains change for README.md file and not `talisman_reports/report.json`.

cc @zricethezav

**Comment by zricethezav** [comment]
This is odd. 
From the commit thoughtworks/talisman@af0c964 I see: 
`2 parents e1a8a9d + 0b60a3e commit af0c9642f5ae18b9bd4098bf320c089fbe24dc9e`

I went into the debugger and saw this scenario While iterating through the commits in `git log` I see `af0c9642f5ae18b9bd4098bf320c089fbe24dc9e` with two parents `e1a8a9d` and `0b60a3e`. Gitleaks will then generate a patch between `af0c9642f5ae18b9bd4098bf320c089fbe24dc9e` and `e1a8a9d` THEN `af0c9642f5ae18b9bd4098bf320c089fbe24dc9e` and `0b60a3e`. 

I compared the patch I was seeing in my debugger versus the one generated by `git diff 0b60a3e af0c9642f5ae18b9bd4098bf320c089fbe24dc9e` and saw the same patch (different than the patch shown here thoughtworks/talisman@af0c964). The curious thing is that the diff: `git diff e1a8a9d af0c9642f5ae18b9bd4098bf320c089fbe24dc9e` match the diff here thoughtworks/talisman@af0c964.

So maybe the solution is to pick the most recent parent? Gotta think some more about this. 

@steeve85

**Comment by zricethezav** [comment]
FWIW the code in question is around here: https://github.com/zricethezav/gitleaks/blob/master/scan/scan.go#L104-L154

**Comment by zricethezav** [comment]
Additionally this commit is a merge, which can make things a bit goofy

**Comment by steeve85** [comment]
FYI commits `b6f13ba79c420fac9661dcbe2e1c4b614adc6851` and `23ae90a12bd88723ce0817241b4e0174c45817c4` also returns -1, it might be for a different reason

**Comment by zricethezav** [comment]
Yea I saw that I think that is a bug with the extract line function. I'm thinking maybe to skip scanning commits with more than one parent since that is indicative of a merge request which really just consolidates multiple commits and doesn't contain any new reachable information. WDYT?

**Comment by steeve85** [comment]
I don't think you should skip commits with more than 1 parent because if you do, it could miss some secrets. Imagine if that commit https://github.com/thoughtworks/talisman/commit/af0c964 was containing a secret, by skipping it because it has 2 parents you would have missed it.

**Comment by zricethezav** [comment]
hmmm maybe pick the most recent commit then? Not sure exactly how to handle this. Thanks for providing this example, working through some things now

**Comment by zricethezav** [comment]
https://github.com/thoughtworks/talisman/commit/af0c964.patch and https://patch-diff.githubusercontent.com/raw/thoughtworks/talisman/pull/111.patch 

make me think this is the correct behavior actually. While iterating through commits it should diff each parent. Not sure why github displays https://github.com/thoughtworks/talisman/commit/af0c964 that way versus the patch generated: https://github.com/thoughtworks/talisman/commit/af0c964.patch

**Comment by zricethezav** [comment]
Futhermore, https://github.com/thoughtworks/talisman/compare/e1a8a9d..af0c9642f5ae18b9bd4098bf320c089fbe24dc9e and https://github.com/thoughtworks/talisman/compare/0b60a3e..af0c9642f5ae18b9bd4098bf320c089fbe24dc9e?diff=split shows the changes gitleaks is tracking based on that thoughtworks/talisman@af0c964 commit... not entirely sure why github doesn't display the output of both diffs that in the commit

**Comment by zricethezav** [comment]
Okay so upon some further investigation looks like we should only be generating a patch between the first parent of a commit if that commit has multiple parents (ie a merge commit). This is because the second+ parent exists as the HEAD of the branch that is part of the merge request. The first parent is the commit that gets picked as part of the merge. 

Doing some testing and it looks like this is what we want. 

cc @steeve85

**Comment by steeve85** [comment]
Cool that you found how to fix the problem! Git can definitely get complicated

**Comment by zricethezav** [comment]
Got a PR for this issue that should handle both. Just need to add some tests.

**Comment by zricethezav** [comment]
@steeve85 feel free to re-open the issue if you think it's still a problem
