### ISSUE TITLE
Error when start pre-commit hook

### ISSUE THREAD

**Issue by nbublikov** [zricethezav/gitleaks#415]
**Describe the bug**
When i test pro-commit hook, i got it error
![image](https://user-images.githubusercontent.com/68223804/88562760-c4b30000-d039-11ea-8e0c-6f8977050d76.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/68223804/88563204-5de21680-d03a-11ea-9579-84b04dd1febe.png)

**Expected behavior**
wait that i get alert about AWS KEY

**Screenshots**
added

**Basic Info (please complete the following information):**
 - OS: uname -a
Linux ubuntu 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Gitleaks Version: latest from repo

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@nbublikov can you post the actual hook file? Otherwise I cannot help debug this.

**Comment by nbublikov** [comment]
[pre-commit.txt](https://github.com/zricethezav/gitleaks/files/4983683/pre-commit.txt)

**Comment by nbublikov** [comment]
Basically, this is the original pre commit with no changes

**Comment by nbublikov** [comment]
Some say, Most likely, the $ gitleaksEnabled variable turns out to be empty on line 4. Nothing goes into it.

But I don't know what to do with it and how to fix it.

**Comment by maennel** [comment]
@nbublikov You should be able to replace the line
`if [ $gitleaksEnabled == "true" ]; then`
with 
`if [ "$gitleaksEnabled" == "true" ]; then`.

**Comment by jkbszpg** [comment]
there are two issues with in that pre-commit.example file

- test in sh uses one '='
- remove the "--pretty" parameter (it will fail the scan with "unknown flag `pretty'")

```
cmd="/Users/zrice/go/src/github.com/zricethezav/gitleaks/gitleaks --verbose --redact"
if [ $gitleaksEnabled = "true" ]; then
```

**Comment by zricethezav** [comment]
new script should fix https://github.com/zricethezav/gitleaks/blob/master/scripts/pre-commit.py
