### ISSUE TITLE
Wiki instructions to install via Go results in error

### ISSUE THREAD

**Issue by Asuza** [zricethezav/gitleaks#425]
**Describe the bug**
Wiki [installation instructions](https://github.com/zricethezav/gitleaks/wiki/Installation) to install `gitleaks` via the command `GO111MODULE=on go get github.com/zricethezav/gitleaks/v5` result in the following error:
```
⟩ env GO111MODULE=on go get github.com/zricethezav/gitleaks/v5 
package github.com/zricethezav/gitleaks/v5: cannot find package "github.com/zricethezav/gitleaks/v5" in any of: 
        /usr/lib/go-1.10/src/github.com/zricethezav/gitleaks/v5 (from $GOROOT)
        /home/john/go/src/github.com/zricethezav/gitleaks/v5 (from $GOPATH)
```

**To Reproduce**
Run `env GO111MODULE=on go get github.com/zricethezav/gitleaks/v5`

**Expected behavior**
`gitleaks` gets installed.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Gitleaks Version: 5

**Additional context**
The go version is: go1.10.4 linux/amd64

I have no experience with go. I just installed it to try `gitleaks`. I also changed the version in the command to 6, hoping to install the latest version, and the same error occurred.

Thank you!

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @Asuza !

I believe that this bug is old and has been fixed.

Can we close this issue?

cheers!

**Comment by Asuza** [comment]
If it's been fixed, then sure! I haven't tried it lately, but my issue is so old at this point it might as well be cleaned up. Thanks!
