### ISSUE TITLE
Allow custom config on top of the default config

### ISSUE THREAD

**Issue by stone-z** [zricethezav/gitleaks#429]
**Is your feature request related to a problem? Please describe.**
Normally, I want to use a set of default detection rules (either the gitleaks default or my own), but some projects have files which I know I want to ignore.

I'd like to be able to use the default configuration as a baseline and supply only the allowlist items I want _in addition to_ the default allowlist. This way I can use the same config for many repos but tweak individual behaviors as needed.

Such a merge behavior could also be used to supply additional rules on top of the default (but I don't currently need this).

**Describe the solution you'd like**
A parameter allowing me to give a partial config file which will be applied on top of the default (or a specified config or repo-config file as a baseline).

Something like: 
Use the default config plus my overrides
`gitleaks --verbose --pretty --redact --extra-config=/my/config.toml` 

or

Use a common config plus my overrides
`gitleaks --verbose --pretty --redact --config=/my/base/config.toml --extra-config=/my/override/config.toml`

or

Use the repo's baseline plus my overrides
`gitleaks --verbose --pretty --redact --repo-config --extra-config=/my/override/config.toml`

**Describe alternatives you've considered**
I currently use a config file which consists of the entire contents of the default config, plus one additional line with one allowlist path. This is functionally fine, it just means I have to manually keep this config file up to date with changes in the default.

I would also be open to supplying exceptions as separate arguments but that seems like more implementation work.

cc @zricethezav

**Comment by Twanislas** [comment]
Hi !

Thanks for the great work on Gitleaks !

I'm also interested in this, and will use @stone-z 's workaround in the meantime.

Cheers !
