### ISSUE TITLE
Issue with regex

### ISSUE THREAD

**Issue by vishnujanardhanan** [zricethezav/gitleaks#430]
**Describe the bug**
I seem to have issues with the regex. If you think what i'm doing is wrong kindly let me know

my regex: (.*?=)([0-9a-zA-Z-_!{}=]{4,120})
what i'm trying to match the regex against as a potential leak where the string at the right hand side of equal to sign is the secret: spring.couchbase.bucket.password=password
error: ERRO[2020-08-27T04:28:01Z] Near line 5 (last key parsed 'rules.regex'): expected value but found '(' instead 

If i use regex: '''(.*?=)([0-9a-zA-Z-_!{}=]{4,120})''' - none of my configurable values are matches because of '''

**To Reproduce**
As above

**Expected behavior**
Pattern to match with regex

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Mac
 - Gitleaks Version: latest docker

command: docker run -v $PWD:/path -v gitleaks/config/:/configpath  zricethezav/gitleaks --repo-path=/path --threads 10 --verbose --pretty --uncommitted --config=/configpath/default.go

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
You command is pointing to a go file not a gitleaks config

**Comment by zricethezav** [comment]
`--config=/configpath/default.go` the config needs to be a toml file

**Comment by vishnujanardhanan** [comment]
thanks for the quick one @zricethezav . Much appreciated. My bad, didnt notice.
