### ISSUE TITLE
Scan only all files in the last revision of my code.

### ISSUE THREAD

**Issue by GolanTrevize10** [zricethezav/gitleaks#431]
**Is your feature request related to a problem? Please describe.**
I want to scan only the last version of my code. No, previous commits. For example, if I had in some previous revision a plain text password but it was already removed and it is not in the last revisions of my code, I don't want gitleaks to show it. 

**Describe the solution you'd like**
Some option to tell getleaks to scan all files of the last revision of the code instead to scan only files changed in a specific commit or a range of commits or all commits

**Describe alternatives you've considered**
None

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@GolanTrevize10 `--files-at-commit=latest`  is what you're looking for

**Comment by vishnujanardhanan** [comment]
@zricethezav I'm trying to run gitleaks against uncommitted code with --uncommitted flag. gitleaks tries to flag a leak for the new config's added, but not for the old config's where only the secret has changed.

for ex:
aws_secret=dfaadasdadadadaad (existing) changed to aws_secret=sdffsdfsfdsfsfsdf is not flagged as a leak, where as on adding a new secret like aws_secret_1=sdfsfsdfsdfsfsdfsdf it is flagged as a leak against same regex. Is this expected?

**Comment by GolanTrevize10** [comment]
@zricethezav thanks I will try that

**Comment by zricethezav** [comment]
@vishnujanardhanan your question is unrelated to this issue, please open a new issue for your question.

**Comment by vishnujanardhanan** [comment]
@zricethezav thanks, raised #435

**Comment by saileshWB** [comment]
> @GolanTrevize10 `--files-at-commit=latest` is what you're looking for

@zricethezav i tried using the above command, but it only scans the latest commit and not the entire respository. Please help to scan the latest version of the repository irrespective of commit history.

**Comment by kiblik** [comment]
+1

**Comment by zricethezav** [comment]
@saileshWB  @GolanTrevize10  @vishnujanardhanan Added a `--no-git` option in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0. This scans a directory or file specified in `--path`.
