### ISSUE TITLE
Scanning with commit-from and commit-to includes whole commit history

### ISSUE THREAD

**Issue by stone-z** [zricethezav/gitleaks#432]
**Describe the bug**
I'm trying to scan a range of commits, but `gitleaks` is unexpectedly scanning the whole commit history.

This works fine on other repositories, so I don't know why this PR is different. In this case, `master` was merged back into a feature branch, but that doesn't seem like it should make a difference.

Hopefully I am just doing something wrong?

**To Reproduce**
Here is [the PR](https://github.com/giantswarm/aws-operator/pull/2706) and [the workflow](https://github.com/giantswarm/aws-operator/pull/2706/checks?check_run_id=1042667345) in question.

The action reports running this command:
```
running gitleaks v6.0.0 with the following command👇
gitleaks --pretty --repo-path=/github/workspace --verbose --redact --commit-from=d2209e8ae2e72ea6d45f22c45939f23bce03c5f4 --commit-to=fa608c1dd6a9d76481818d3fc1f9abeb9a7918d9
```
Running the docker image locally produces the same result (see below).

The SHAs are correct. Running `git log` also shows the expected range of commits:
```
$ git log --left-right --cherry-pick --pretty=format:"%H" d2209e8ae2e72ea6d45f22c45939f23bce03c5f4...fa608c1dd6a9d76481818d3fc1f9abeb9a7918d9
d2209e8ae2e72ea6d45f22c45939f23bce03c5f4
726fe9366babf18a7aa69656bf0905180e00afc1
180dd4602e108e148cbb7a7df1b4cd13cfccdfab
08d91a8431b1b1c6b49f1b03dfb25dfc48cb1506
dafb15625f719d75f63d75e1cd0ef7b3567fca52
8957726a16941f4ac7a6ecc4695bbdf9f40bcd39
bb0ba8975d9b22dcdcf02105c5af1473147af6f5
a818296da02b320874ba066fc1afb51b60a99675
990bcf1e7c58fd4bc7b11fc95cc85509d1f5b72a
89fd87327f67027c26b8dbee13c9da143ff9eabe
f1277fab0cb5082a5d54417d39605346123b060c
525f1e0f805c810cdec4651bcd4598f1004483c7
d04bbf3fc78b20ce6eb4740b74cab63bfacebe0d
075663ba6e80c60ef2c7eb3b38aea32fdf6c029b
b5dfa1e94bdf6125ce9ad50eeca490fd64dab61d
126726a2b0160c232c6246844db9ebf9f2600d2e
dbf0b22aff3b2edfd3d9de5726035e5141ba9deb
02d8199912361284bffde9d6d034998baa6fe5ba
b5905554a063a777c37ca9a8886ddd9b85dfe758
862cecfd26c468ff1d4a5946bb5c4c3ebcc6d288
1671ea282a3b17c613854577dc82a24c759d7546
50f5f11bf9cb241bd5ef67af2a74dc214c49dfe8
```

However, when running with `commit-to` and `commit-from`, `gitleaks` scans and reports findings from much older commits (for example, `229b6f2caee50e11de55fa3bef076a6dc51f083a`).
```
$ docker run -v /project/path:/project -it --rm zricethezav/gitleaks:latest --repo-path=/project -v --pretty --redact --commit-to=d2209e8ae2e72ea6d45f22c45939f23bce03c5f4 --commit-from=fa608c1dd6a9d76481818d3fc1f9abeb9a7918d9
...
{
	"line": "It is based on that package at [cf2c2ea8](https://REDACTED/src/text/tabwriter) and inherits its license.",
	"lineNumber": 3,
	"offender": "REDACTED",
	"commit": "229b6f2caee50e11de55fa3bef076a6dc51f083a",
	"repo": "project",
	"rule": "Github",
	"commitMessage": "Update to kubernetes-1.15.4 (#1964)\n\n",
        ...
	"file": "vendor/github.com/liggitt/tabwriter/README.md",
	"date": "2019-10-11T09:49:56+02:00",
	"tags": "key, Github",
	"operation": "addition"
}
...
```

**Expected behavior**
I expected only the commits between the `commit-from` and `commit-to` arguments to be included.

**Screenshots**
If it helps, a `gitk` representation of the history.
![image](https://user-images.githubusercontent.com/10408416/91708622-dc722c80-eb81-11ea-8160-72029fe40e78.png)

**Basic Info (please complete the following information):**
 - OS: official docker image (alpine)
 - Gitleaks Version: v6.0.0

cc @zricethezav

**Comment by zricethezav** [comment]
Is `fa608c1dd6a9d76481818d3fc1f9abeb9a7918d9` a merge commit? Can you set up a test repo or give me access to your test repo for me to test this against

**Comment by zricethezav** [comment]
Thanks for bringing this bug up. There is some issues with `git log`s reachability in the `go-git` library. I'm thinking of deprecating `commit-from` and `commit-to` to be replaced with `--commit-range=<comma sep list of commits>`. Working on that right now, look for a 6.1.0 release with this shortly. I'll then update the gitleaks action

**Comment by zricethezav** [comment]
cc @stone-z

**Comment by stone-z** [comment]
Ok fantastic, thanks for the quick followup @zricethezav. I'll be on the lookout and give the new version a shot

**Comment by zricethezav** [comment]
@stone-z example using new `commits-file` option in gitleaks-action@v1.1.3 https://github.com/zricethezav/gronit/runs/1051742650.

Could you give the latest version of gitleaks-action a shot?

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gronit/pull/4/checks?check_run_id=1051831203 use v1.1.4 actually

**Comment by stone-z** [comment]
It is working on that problematic PR with v1.1.4 :rocket:

**Comment by zricethezav** [comment]
hell yea, think this can be closed out then?

**Comment by stone-z** [comment]
For sure -- huge thanks once again
