### ISSUE TITLE
Regex match not working

### ISSUE THREAD

**Issue by vishnujanardhanan** [zricethezav/gitleaks#435]
**Describe the bug**
I'm trying to run gitleaks against uncommitted code with --uncommitted flag. gitleaks tries to flag a leak for the new config's added, but not for the old config's where only the secret has changed.

for ex:
aws_secret=dfaadasdadadadaad (existing) changed to aws_secret=sdffsdfsfdsfsfsdf is not flagged as a leak, where as on adding a new secret like aws_secret_1=sdfsfsdfsdfsfsdfsdf it is flagged as a leak against same regex. Is this expected?
**To Reproduce**

**Expected behavior**
gitleaks glags all leaks in the file

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
Can you provide the output of the gitleaks run and the rule you think should be detecting this leak.

**Comment by vishnujanardhanan** [comment]
@zricethezav Please find the requested info

git leaks output
-----------------

$ gitleaks --repo-path=/Users/xxxx/xxxxx/xxx-xxx-xxx/ --verbose --pretty --config=/Users/xxxxx/xxxxxxx/gitleaks/config/rules.toml --threads 10 --uncommitted --debug
DEBU[2020-09-08T19:07:32+05:30] -------------------------                    
DEBU[2020-09-08T19:07:32+05:30] | Times and Commit Counts|                   
DEBU[2020-09-08T19:07:32+05:30] -------------------------                    
totalScanTime:  1 second 413 milliseconds 619 microseconds
totalPatchTime:  0 seconds
totalCloneTime:  0 seconds
totalCommits:  0
DEBU[2020-09-08T19:07:32+05:30] --------------------------                   
DEBU[2020-09-08T19:07:32+05:30] | Individual Regexes Times |                 
DEBU[2020-09-08T19:07:32+05:30] --------------------------                   
(?i)(=)((\{([^}]+)\})|([0-9a-zA-Z_!{}.,@' '+\/:-]{1,600}))......25 microseconds
INFO[2020-09-08T19:07:32+05:30] No leaks detected in staged changes

**************
Rule to match
--------------

[[rules]]
	description = "Potential secret in application*.properties"
	regex = '''(?i)(=)((\{([^}]+)\})|([0-9a-zA-Z_!{}.,@' '+\/:-]{1,600}))'''
	file = '''(application.*?)(properties|yaml|yml)$'''
	tags = ["secret"]
    [[rules.Entropies]]
        Min = "2"
        Max = "8"
        Group = "2"
	[rules.allowlist]
        description = "Allow configs list"
		#Allows configs like uri, bucket name, mime types, enabled flag, hosts - matching by suffix of property name ex: price-bucket-name, product-api-uri
		regexes = ['''(\burl|path|mime-types|port|\bname|enabled|hosts|inclusion|schedule|path |endpoints|size|consistency|url |fields|retry.config|roles)(=)(?i)''']

*********************
content of application.properties
--------------------------------
spring.couchbase.bucket.password=password123

**Comment by vishnujanardhanan** [comment]
@zricethezav also figured out one more issue where the above regex and entropy doesnt flags password123 and password14555666 as a leak and not password22222

**Comment by zricethezav** [comment]
Likely fixed in most recent version of gitleaks
