### ISSUE TITLE
How to Scan private Gitlab repository from gitleaks

### ISSUE THREAD

**Issue by nidhisi** [zricethezav/gitleaks#439]
I am unable to scan the private Gitlab repository from gitleaks tool. It's give me an error (authentication required). So please give me the step by step solution for the above problem.

**Comment by LinqLover** [comment]
As far as I understand the docs, you could clone the repository and do a [local repo scan](https://github.com/zricethezav/gitleaks/wiki/Scanning#local-repo-scan), does this work?

**Comment by ethanwlo** [comment]
I have the same problem. Is it possible to scan private repo without cloning?

**Comment by LinqLover** [comment]
@ethanwlo As written [right above](https://github.com/zricethezav/gitleaks/issues/439#issuecomment-737308769), you can do a [local repo scan](https://github.com/zricethezav/gitleaks/wiki/Scanning#local-repo-scan) ... Please contact if you encounter a problem doing so.

**Comment by mrjoss19** [comment]
It is true @LinqLover that cloning and scanning locally works perfectly, but I do agree that if a scan could be done without cloning it would be less intrusive and a great improvement when you have different teams and significant amount of repositories (even heavies). Great job :)

**Comment by mrjoss19** [comment]
Hello, I tried:

gitleaks --repo-url=INTERNAL_SERVER --username=USER_NAME --password=PASSWORD -v 

and it works fine for me.

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

Gitleaks is not responsible for cloning
