### ISSUE TITLE
Git Hook Invalid checksum

### ISSUE THREAD

**Issue by bkuhlmann** [zricethezav/gitleaks#441]
**Describe the bug**

I am getting an `invalid checksum` error when running `gitleaks --verbose --redact --pretty`.

**To Reproduce**

Run the following to reproduce:

``` 
https://github.com/bkuhlmann/dotfiles.git
cd dotfiles
gitleaks --verbose --redact --pretty
```

**Expected behavior**

I would expect this to come back as valid according to docs, especially when used in a Git Hook.

**Screenshots**

<img width="682" alt="iTerm2--WU6CpswO" src="https://user-images.githubusercontent.com/50245/94343085-ef3a1e80-ffd2-11ea-9243-fffacadd0cd9.png">

**Basic Info (please complete the following information):**
 - OS: Mac OS X 10.15.6 (19G2021)
 - Gitleaks Version: 6.1.2

**Additional context**

My only other guess is that this has something to do with my [Global Git Config](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.gitconfig.tt). Maybe there is a setting that conflicts with a Git Leaks configuration?

cc @zricethezav

**Comment by bkuhlmann** [comment]
:information_source: I'm closing this issue as it looks like this project has been abandoned and want to clean up my Inbox.

**Comment by zricethezav** [comment]
@bkuhlmann lol abandoned?

**Comment by zricethezav** [comment]
Im unable to reproduce your bug.

**Comment by bkuhlmann** [comment]
@zricethezav Ah, sorry. I was going through my Inbox and realized this was 25 days old and figured I should close this. 😅 Maybe this is an issue on my side still, not sure, but I'm fine with leaving this closed for now.
