### ISSUE TITLE
Scan current files in the repository irrespective of commit history

### ISSUE THREAD

**Issue by saileshWB** [zricethezav/gitleaks#445]
A clear and concise description of what the problem is. 
I am trying to scan a repository.But the gitleaks report shows obsolete files based on older commits. I am looking for a report which scans the latest files in the repository. 

I saw your comment to use #431 to use --files-at-commit=latest, but that scans only the files in the last commit and not the entire repository. 

Consider the below example: 
    - file1 is committed during initial commit
    - file2 and file3 are committed next
    - file2 is removed in next commit
I am looking for a solution so that gitleaks scans only file1 and file3 as file2 doesn't exist any longer. Please guide.

cc @zricethezav

**Comment by zricethezav** [comment]
See comment in https://github.com/zricethezav/gitleaks/issues/431
