### ISSUE TITLE
Simple password not detected

### ISSUE THREAD

**Issue by buckleyGI** [zricethezav/gitleaks#447]
Excuse my ignorance but I was expecting that the following would trigger the default rules
`password=1234567890123456789012345678901`
It doesn't in version 6.1.2

At some point it was detected but it got reverted by #379 

I get that there were too many false positives which is a good conclusion based on experience which I don't have at this point.

But to be clear, and excuse my ignorance again if it is stated somewhere that I missed, do we really want to ignore something like the following?

`password=1234567890123456789012345678901`

Just checking because the retraction of the more generic rule that included a scan for  `password `is recent.

I can use the \examples\leaky-repo.toml to let it trigger on this password but that is not the default behavior.
I think this wil trip some newbies as they will start testing against this fine project with something like `password=12345 `and see how gitleaks react.

Is the plan still to come with an `--expanded` option that does a more liberal matching?

**Comment by zricethezav** [comment]
Reducing FPs by default is the goal. You can always supply your config. No plan for `--expanded` at the moment

**Comment by buckleyGI** [comment]
Thanks for the clear response. Conclusion: works as expected.
