### ISSUE TITLE
Option for exit code to always return 0 if no error occures 

### ISSUE THREAD

**Issue by paulschmelzer** [zricethezav/gitleaks#450]
**Problem**
I am trying to integrate the gitleaks scanner with the SecureCodeBox project. SecureCodeBox runs on kubernetes. When a container exits with a non zero return code kubernetes thinks the container crashed. But for gitleaks return code 0 and 1 this is not the case.

**Possible solution**
The solution could be a comand line option to tell gitleaks to return 0 for both 'no leaks' and 'leaks present' and a non zero value for 'error encountered'.

cc @zricethezav

**Comment by kiblik** [comment]
+1

**Comment by zricethezav** [comment]
This will be the default behavior in v7

**Comment by zricethezav** [comment]
@paulschmelzer this is the default behavior in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
