### ISSUE TITLE
Add reportGroup option to config

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#451]
**Is your feature request related to a problem? Please describe.**
Users might want to fine tune the "offender" field in the report to a specific capture group in their regex.

**Describe the solution you'd like**
A config that supports `reportGroup`:
```
[[rules]]
	description = "AWS Secret Key"
	regex = '''(?i)aws(.{0,20})?(?-i)(['\"][0-9a-zA-Z\/+]{40}['\"])'''
	tags = ["key", "AWS"]
    reportGroup =  2
```
If the leak contained the line: `awsSecretKey = "thiswillmatchexampleawskey11111111111111"` only `"thiswillmatchexampleawskey11111111111111"` would be reported in the `Offender` field of the report

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

cc @zricethezav

**Comment by squaresurf** [comment]
Heads to future readers, I'm hoping to work on this over the next few days.
