### ISSUE TITLE
Wrong Line Numbers

### ISSUE THREAD

**Issue by suryanuddhi20** [zricethezav/gitleaks#453]
Two issues with the Line Number:
1) If there are more than one offender in the same line, one of the offenders get the correct line number but the others take "-1" value.
2) In the same file if the leak is repeated for more than one time, all other fields are correct except for the line_number field which tends to duplicate the line number for repeated offenders.

**To Reproduce**
_MY_CONFIG_FILE.toml_
```
title = "gitleaks config"

[[rules]]
	description = "Asymmetric Private Key"
	regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
	tags = ["key", "AsymmetricPrivateKey"]

[[rules]]
	description = "Passwords"
	regex = '''(?i)password=(?i)'''
	tags = ["key", "Generic"]

[[rules]]
	description = "secret secret.com"
	regex = '''(?i)secret\.com'''
	tags = ["key", "custom"]
```

_Command to reproduce the output:_
`gitleaks --repo https://github.com/merakana/RK.git --verbose --commits f0f7296e31fa89922e7d88f0c6fbc9aa1416b374,c7aa00b76837ff2f36bf3e2021d97dcfddd3fd07 --config MY_CONFIG_FILE.toml`

**Expected behavior**
Correct Line numbers for the attached cases.
In the attached screenshot, the issues are numbered accordingly and highlighted fields are showing duplicate line_number (although they are leaks from different lines)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/70654933/96871231-9d7c9b00-148f-11eb-8ae9-6c876b66dfb9.PNG)

**Basic Info (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Gitleaks Version: v6.1.2

cc @zricethezav

**Comment by zricethezav** [comment]
@suryanuddhi20 thanks for bringing this up. We are tracking this at Gitlab as well here https://gitlab.com/gitlab-org/gitlab/-/issues/267389. Unfortunately I don't have any spare cycles to work on this at the moment so it would be great if a community member could contribute if anyone is feeling ambitious :P

It's quite a tricky bug

**Comment by zricethezav** [comment]
https://github.com/sourcegraph/go-diff may be of use

**Comment by suryanuddhi20** [comment]
Sure. Will look into it. Thanks!

**Comment by zricethezav** [comment]
@suryanuddhi20 I opened a branch with what I think is a fix for this: https://github.com/zricethezav/gitleaks/commit/af4c746fd2746c9b4bf5135a5050a46ca1b72442

**Comment by zricethezav** [comment]
@suryanuddhi20 fixed in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0

**Comment by suryanuddhi20** [comment]
Thanks @zricethezav !
