### ISSUE TITLE
dynatrace now has regex to identify if their token was leaked

### ISSUE THREAD

**Issue by caleb15** [zricethezav/gitleaks#457]
Just letting you know that dynatrace changed their token format so it a leak can easily be identified with a regex:

https://www.dynatrace.com/news/blog/further-enhance-security-by-easily-automating-your-api-token-protection/

**Comment by zricethezav** [comment]
Added as part of the default checks in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
