### ISSUE TITLE
Add support for 'git clone --depth'

### ISSUE THREAD

**Issue by diegobernardes** [zricethezav/gitleaks#460]
**Is your feature request related to a problem? Please describe.**
During the analysis of big repositories where the important feature is to detect the secrets at the HEAD, it's important to be able to use the `git clone --depth` in order to reduce the size of the repository that needs to be downloaded.

**Describe the solution you'd like**
`gitleaks` already have an `--depth` option, if `gitleaks` would have to clone the repository and have the `depth` config set, it would be nice to pass this configuration to the git command clone too. https://pkg.go.dev/github.com/go-git/go-git/v5#CloneOptions

cc @zricethezav

**Comment by zricethezav** [comment]
@diegobernardes added in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0. Thanks for this optimization
