### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by diegobernardes** [zricethezav/gitleaks#461]
**Describe the bug**
I'm getting out of memory errors. I think `gitleaks` is not respecting the `--disk` option and downloading everything to memory, that's the only thing that comes to my mind that could eventually give that error.

**To Reproduce**
I'm using the following command at GitHub Actions `gitleaks --config config.toml --disk --access-token *** --redact --pretty --host github --org company`:
```
INFO[2020-11-07T09:23:46Z] gathering github repos... progress: page 1 of x
...
INFO[2020-11-07T09:23:51Z] cloning... https://github.com/...
... after some git clone
fatal error: runtime: out of memory
```

**Expected behavior**
I would expect to execute the program until the end without any problem.

**Basic Info (please complete the following information):**
 - OS: `ubuntu-20-10`
 - Gitleaks Version: `go get github.com/zricethezav/gitleaks/v6`

cc @zricethezav

**Comment by diegobernardes** [comment]
Related/duplicate: #336

**Comment by zricethezav** [comment]
As I am not supporting gitlab/github apis anymore I won't be fixing this. See https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0
