### ISSUE TITLE
Regex to get match from particular file

### ISSUE THREAD

**Issue by tavisca-ashinde1** [zricethezav/gitleaks#462]
Hi @zricethezav,

Requirement:
modify toml file in such a way that it can handle match specific to particular file.
Ex:

i have match "4111111111111111" which exists in 3 files(prod.csv,main.csv,test.csv) in repo. but i have to allow only one file ex: test.csv which contains above match.

cc @zricethezav

**Comment by zricethezav** [comment]
@tavisca-ashinde1 
```
[[rules]]
  description = "https://github.com/zricethezav/gitleaks/issues/462"
  regex = '''4111111111111111''' 
  [rules.allowlist]
    description = "allow test.csv"
    files = ['''test.csv''']
```

**Comment by tavisca-ashinde1** [comment]
Thanks @zricethezav  That worked.
