### ISSUE TITLE
allowlist.paths is not ignoring files

### ISSUE THREAD

**Issue by AndrewMasalski** [zricethezav/gitleaks#467]
**Describe the bug**
I am setting a specific file by allowlist.paths to skip gitleaks scan of this file.

**To Reproduce**
* Clone https://github.com/AndrewMasalski/gitleaks-issues
* Execute command:
```
gitleaks --repo-path=. --config=gitleaks-config.toml --files-at-commit=latest --pretty --debug --verbose --redact
```

**Actual behavior**
a leak in 'src/readme.md'  file is found

**Expected behavior**
no leaks should be found ('src/readme.md' file should be ignored by paths config)

**Basic Info (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Gitleaks Version: 6.2.0

**Comment by zricethezav** [comment]
@AndrewMasalski this should be fixed in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0. reopen if not
