### ISSUE TITLE
Add option to use git index only with –cached

### ISSUE THREAD

**Issue by AndrewMasalski** [zricethezav/gitleaks#468]
**Is your feature request related to a problem? Please describe.**
We have huge mono-repo and the proposed pre-commit hook command is too slow.
```
$ gitleaks --uncommitted --verbose --redact --pretty --debug --config=gitleaks-config.toml
DEBU[2020-11-30T13:12:43+01:00] -------------------------                    
DEBU[2020-11-30T13:12:43+01:00] | Times and Commit Counts|                   
DEBU[2020-11-30T13:12:43+01:00] -------------------------                    
totalScanTime:  38 seconds 387 milliseconds 747 microseconds
totalPatchTime:  0 seconds
totalCloneTime:  0 seconds
totalCommits:  0
DEBU[2020-11-30T13:12:43+01:00] --------------------------                   
DEBU[2020-11-30T13:12:43+01:00] | Individual Regexes Times |                 
DEBU[2020-11-30T13:12:43+01:00] --------------------------                   
INFO[2020-11-30T13:12:43+01:00] No leaks detected in staged changes  
```

**Describe the solution you'd like**
I think git options: --cached, --untracked, --no-index can help to reduce the scan time.

**Describe alternatives you've considered**
Maybe I am missing some other options, but I didn't find a way to reduce scan time for pre-commit hook.

cc @zricethezav

**Comment by zricethezav** [comment]
@AndrewMasalski it's a known issue with a proposed solution https://github.com/zricethezav/gitleaks/pull/463. However I'm not sold on the idea of shelling out a exec within gitleaks.

**Comment by zricethezav** [comment]
@AndrewMasalski did you notice an improvement since https://github.com/zricethezav/gitleaks/pull/463 was merged? Can this be closed?

**Comment by AndrewMasalski** [comment]
@zricethezav, thank you for the update
I did check this command as pre-commit hook: `gitleaks --verbose --redact -c secrets-config.toml --files-at-commit=latest`
Now scan takes only couple of seconds:
```
INFO[0000] opening . 
INFO[0002] scan time: 2 seconds 763 milliseconds 423 microseconds 
WARN[0002] leaks found: 14 
```
I think this ticket can be closed now.
