### ISSUE TITLE
--path + --repo-config-path + --no-git = segmentation violation

### ISSUE THREAD

**Issue by paul-m** [zricethezav/gitleaks#473]
**Describe the bug**
```
gitleaks --path . --repo-config-path ./gitleaks.toml --no-git
```
This command results in:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140c47c]
```

I get that having `--repo-config-path` and `--no-git` together kind of doesn't make sense.

But it seems like there is probably a better error message than a go exception. :-)

**To Reproduce**

Issue a command like this inside a git repo:
```
gitleaks --path . --repo-config-path ./gitleaks.toml --no-git
```

**Expected behavior**

Probably an error message about `--no-git` being in conflict with `--repo-config-path`.

**Screenshots**
```
% gitleaks --path . --repo-config-path ./gitleaks.toml --no-git   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140c47c]

goroutine 1 [running]:
github.com/go-git/go-git/v5.(*Repository).Config(...)
	github.com/go-git/go-git/v5@v5.2.0/repository.go:497
github.com/zricethezav/gitleaks/v7/config.LoadRepoConfig(0x0, 0x7ffeefbffc55, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/zricethezav/gitleaks/v7/config/config.go:262 +0x5c
github.com/zricethezav/gitleaks/v7/scan.NewScanner(0x0, 0x0, 0x0, 0x7ffeefbffc40, 0x1, 0x0, 0x0, 0x7ffeefbffc55, 0xf, 0x0, ...)
	github.com/zricethezav/gitleaks/v7/scan/scan.go:83 +0x9ad
main.main()
	github.com/zricethezav/gitleaks/v7/main.go:46 +0x33b
```

**Basic Info (please complete the following information):**
 - OS: Mac OS X
 - Gitleaks Version: 7.0.1

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
Nice find! I'll add some logic to prevent this from happening

**Comment by zricethezav** [comment]
Fixed in https://github.com/zricethezav/gitleaks/releases/tag/v7.0.2. This behavior is now prevented
