### ISSUE TITLE
Add option to exit code 1 on detected leak

### ISSUE THREAD

**Issue by coolacid** [zricethezav/gitleaks#478]
**Is your feature request related to a problem? Please describe.**
After #450 was implemented, gitleaks returns 0 unless an actual error occurred. I can fully understand that requirement. However, while running this in a gitlab docker container, it expects an error code to fail a test. 

**Describe the solution you'd like**
Add `--error-on-leak` option to throw an error code 1 when a leak is found. Optionally, accept a number and return that number on leak found.

**Describe alternatives you've considered**
I'm not aware of an alternative to return an error. 

**Additional context**
No additional context. 

cc @zricethezav

**Comment by coolacid** [comment]
If I had to guess, this change also broke the pre-commit hook listed here: https://github.com/zricethezav/gitleaks/wiki/Scanning

**Comment by pburkholder** [comment]
I came here to create this same issue. The 7.x behavior likely breaks everyone's pre-commit hooks. I might be so bold as to suggest the original behavior was correct, like `grep -q`, and that the K8s should case should be the one with the `--no-error-on-leak` option.

**Comment by zricethezav** [comment]
@pburkholder I think you're right. Likely will change this next release. 

proposed default behavior:
```
0 - no leaks, successful run
1 - leaks or errors were encountered. Up to the user to figure out what went wrong
```

`--no-error-on-leak`
```
0 - leaks/no leaks detected, successful run
1 - errors were encountered
```

**Comment by pburkholder** [comment]
Thanks for taking this into consideration. Different exit statuses for leaks vs errors is pretty useful, i.e.:

```
0 - no leaks, successful run
1 - leaks were encountered
2 - errors were encountered
```

In my case, I write tests before updating my patterns, https://github.com/cloud-gov/caulking/blob/master/development.bats, and if we start lumping leaks _and_ errors into file exit status 1, I could have tests passing because an error in my pre-commit, not because I'm detecting leaks. 

So -- could we rewind entirely to the old statuses?  (please?)

**Comment by zricethezav** [comment]
@pburkholder I'm actually thinking now:

`--leaks-exit-code=` which allows you to set whatever code you want. Default behavior will still be what is proposed above.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v7.1.0 @coolacid @pburkholder here ya go

**Comment by coolacid** [comment]
Wow! Thanks for the quick turn around, Working here in my local gitlab pipeline. Cheers!
