### ISSUE TITLE
Allowlist seems broken post v7.0.*

### ISSUE THREAD

**Issue by ramimac** [zricethezav/gitleaks#482]
**Describe the bug**
The allowlisting does not appear to be working - either rules-level or global.

**To Reproduce**

I am using the docker 7.1.0 container, but believe I saw the same thing in 7.0.2

The command I'm using is of the form
```
docker run --rm -v $(git rev-parse --show-toplevel)/gitleaks.toml:/tmp/gitleaks.toml -v $(git rev-parse --show-toplevel):/toscan zricethezav/gitleaks:v7.1.0 gitleaks --config-path=/tmp/gitleaks.toml  --verbose --no-git -p=/toscan --leaks-exit-code=2
```

The ruleset has the following rules (note, I tried .git and .git$ ... just to be sure):
```
[[rules]]
	description = "Block dangerous filetypes"
	file = '''(.*?)(pdf|doc|docx|zip|xls|tfplan|tfstate|tfvars|vault_pass|vagrant|pyc|key|cache)$'''
	tags = ["key", "extensions"]
	[rules.allowlist]
		paths = ['''.git''']
		description = "ignore known locations and files"

[allowlist]
	description = "Allowlisted files"
	paths = ['''.git$''']
```

Plus with `--no-git` the .git directory should be ignored globally.

However, gitleaks still reports leaks within the .git directory. Additionally, I've observed allowlisting to be broken not just with `.git` but seemingly completely. For example, without `--no-git` and instead with `--files-at-commit` I see allowlisted files and paths (globally and rules-level) still detected as leaks.

**Expected behavior**
I would expect gitleaks to allowlist the .git directory. In other cases, I would expect gitleaks to respect allowlisting. 

**Basic Info (please complete the following information):**
 - Docker `zricethezav/gitleaks:v7.1.0` 

**Additional context**
I'm very confused. Are all the test cases from the repo passing? I've done a lot of troubleshooting locally to see if I have borked my config - but the `--no-git` + `.git` allowlisted explicitly seems like the best minimal proof this is a bug

cc @zricethezav

**Comment by zricethezav** [comment]
@ramimac thanks for raising this issue, already found the problem. 7.1.1 coming soon 😅

**Comment by zricethezav** [comment]
@ramimac and for those curious, I forgot to add an additional check: https://github.com/zricethezav/gitleaks/blob/2bdf74a2a29775820b9b2d0ade75d82667c2a35b/config/rule.go#L82-L84 when iterating through file/path ONLY rules

**Comment by zricethezav** [comment]
reopening until v7.1.1 released

**Comment by zricethezav** [comment]
@ramimac released https://github.com/zricethezav/gitleaks/releases/tag/v7.1.1. Lemme know if that works for ya. Reopen if still broken

**Comment by ramimac** [comment]
@zricethezav thanks again for the quick fix! `no-git` appears to be working. With `files-at-commit`, the rules-specific allowlists seem to be working, but global allowlisting still appears broken.

**Comment by zricethezav** [comment]
@ramimac yep, already see the issue. Thanks for verifying!

**Comment by zricethezav** [comment]
@ramimac should be good now

**Comment by ramimac** [comment]
Bug == Squashed!
