### ISSUE TITLE
Scan the entire org 

### ISSUE THREAD

**Issue by moshealon76** [zricethezav/gitleaks#483]
In a previous version it was possible to scan all the repos within a particular org, does this option still exist?

Thanks

**Comment by zricethezav** [comment]
@moshealon76 sorry it does not, I am not supporting github/gitlab integrations. Feel free to use this script https://github.com/zricethezav/gitleaks/issues/312#issuecomment-667128234 if you need to interact with a git provider

**Comment by thecybermafia** [comment]
@moshealon76 I created a small bash script that does the org scanning, saves individual repo's reports and it can pass any arguments to gitleaks as well, take a [look at it here](https://github.com/thecybermafia/orgleaks)
