### ISSUE TITLE
.git Regex Overmatching

### ISSUE THREAD

**Issue by ramimac** [zricethezav/gitleaks#486]
**Describe the bug**
Gitleaks appears to allowlist all files with the string "git" in their name OR path 

I happen to use a directory "gitleaks_testcases" for my tests, and found leaks were not reported

**To Reproduce**
create a 3 test files that contain a leak:
1. gitleaks/testfile.txt
2. leaks/gitfile.txt
3. leaks/testfile.txt

Run gitleaks with `no-git`. Note that only the leak in file 3 is flagged. 

**Expected behavior**
All three leaks should be detected. 

**Screenshots**

**Basic Info (please complete the following information):**
 - zricethezav/gitleaks:v7.1.2

**Additional context**
I suspect the problem is the use of `.git` as a regex - do you need to escape the `.`? Also, could it match to `\.git\/" to be sure we don't catch a possible ".gitother" directory in an edge case?

cc @zricethezav

**Comment by zricethezav** [comment]
@ramimac good catch, 

> I suspect the problem is the use of .git as a regex - do you need to escape the .? 

I bet that's the case, I'll try to look at this this afternoon
