### ISSUE TITLE
more filters and options

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#49]
Here are some filters and options that would be nice to have:
* ignore filetypes
* commit depth
* commit range (HASH1 - HASH2)
* scan PR # 
* Redact offending string from report/output
* ~include commit url in leaks~

**Comment by zricethezav** [comment]
@crazyvikas23 absolutely!

**Comment by ljohnston** [comment]
Any particular reason this issue was closed? I don't see these options have been implemented (other than redacting things in the reports). The 'commit depth' option would be extremely useful.

**Comment by zricethezav** [comment]
These options have been implemented. Use `--commit`
