### ISSUE TITLE
[Question] Missing couple options

### ISSUE THREAD

**Issue by c0rvax** [zricethezav/gitleaks#492]
Hey, I have been skipping many updates (specifically, since 2.0.0), and right now I can't find some very important options: `--exclude-forks` and `--github-user`. I have been using them heavily in the past and now can't find a way to make similar behaviour. Is there a way to do this?

**Comment by zricethezav** [comment]
@c0rvax sorry there is not. v7.x.x removed github/gitlab integrations and I don't plan on supporting them in the future.

You can use v6.2.0 if you want to use a more recent version with github/gitlab integrations
