### ISSUE TITLE
[Feature Request] Add option to include deletion in v7

### ISSUE THREAD

**Issue by jpweiser** [zricethezav/gitleaks#493]
**Is your feature request related to a problem? Please describe.**
I want to be able to optionally scan deletion commits in the version 7 stream.

**Describe the solution you'd like**
Using a flag similar to `include-deletion` in prior releases, include deletion in v7.

cc @zricethezav

**Comment by zricethezav** [comment]
I'm not going to be pursuing this, I only want gitleaks to detect when secrets were introduced.
