### ISSUE TITLE
Add a --commit-since-duration option to configure durations instead of date strings

### ISSUE THREAD

**Issue by rseedorff** [zricethezav/gitleaks#497]
Hi @zricethezav,

thx for your awesome project 👍 

**Is your feature request related to a problem? Please describe.**
We have integrated `gitleaks` in the [OWASP secureCodeBox](https://github.com/secureCodeBox/secureCodeBox) project which has its focus on security scanner automation and orchestration based on kubernetes. This enables users to run large scale security scans on a regular (scheduled) basis.

If a user runs `gitleaks` based on a time schedule (e.g. one scan per day) with a cronjob or even the secureCodeBox project it would be enough to scan all git-commits since the last executed schedule. Instead of scanning all commits in the complete git history every day it would safe a lot of resources to scan only all commits of the last day. 

```bash
crontab * * 1 * * gitleaks --commit-since="2021-01-04"
```

In such a scenario the problem is that the `--commit-since` option needs to be a fixed point in time datetime string. And therefore this must be adjusted every day what is not suitable...

**Describe the solution you'd like**
Add a `--commit-since-duration` option which accepts a `duration` instead of a point in time date string.

```bash
crontab * * 1 * * gitleaks --commit-since-duration="-24h"
```

**Additional context**
The [ParseDuration function](https://golang.org/src/time/format.go?s=40605:40651#L1364) can be a good starting point for this...

> ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

cc @zricethezav

**Comment by zricethezav** [comment]
You can use `--log-opts` now to manage what commits get scanned
