### ISSUE TITLE
Git leaks - Usability feedback 

### ISSUE THREAD

**Issue by keirans** [zricethezav/gitleaks#50]
Hey There,
Thanks again for a really great tool.  I'm providing this feedback here, as per our discussions on reddit DM's.

I've got a bit of feedback that i think would help greatly with general usability. I'm slightly selfish in that these would greatly help me, however, I think it would also help other peoples adoption as well.

* Customise the datadir / workdir directory on the CLI
Currently all data produced by the tool goes into ~/.gitleaks/ , however, for larger audits, it would be really great to be able to specify this directory so that the user could target a different location for performance or archival reasons. 

* JSON data output enhancements 
This is a really great capability, possibly one of the killer features of your implementation.
Right now, for repositories that contain no results, you create a JSON file with a null value.
Ideally this should either not be created, or it should contain an empty array. This would ease parsing capabilities for those using your tool to generate large batches of results then post process them using something like Ruby (Which is what I am doing). My general feeling is that no report should be created if there are no matches, however, I think consistency is key however.

* --quiet mode / --logfile 
A quiet mode or logfile capability would help with automating your tool further, alongside more detailed exit codes as detailed below.

* Return code definitions / Extended return code capability ?
Right now, from what I understand, the tool returns 0 for successful execution, and non-zero for unsuccessful execution. It would be great to have a bit more detail exposed as exit codes for different circumstances, such as if a scan executed, and returned matches, etc.

This would help greatly with automating your tool further. However, I'd love to hear what you and other users think about this.
A good example of this implemented well is in [Puppet's --detailed-exit-codes](https://puppet.com/docs/puppet/5.4/man/agent.html) functionality.

* Externalising the regex matches ?
I'm not sure if this is something that will greatly affect performance, but it would be great to externalise the REGEX matches into a configuration file so that you don't have to rebuild the binary when updating rules. Putting them into a runtime configuration file (Maybe YAML) would really help usability. Being able to specify the datadir / workdir in this same file would also be great.

A very basic example could look like this:

```
---
config:
  workdir: /somewhere/else
regex:
  AWS:
    pattern: <REGEX>
```

Once again, thanks again for a great tool :)

K

**Comment by zricethezav** [comment]
Hey K,

Thanks so much for the detailed feedback. This is exactly what I was looking for and will help direct me during my next code jam. I think these four features would really help folks integrate gitleaks into whatever CI/pipeline/infra they have. Perhaps we could work together on defining exit codes?

Cheers 👍

**Comment by zricethezav** [comment]
Tackled the simplest of the bunch and now no reports will be generated if no leaks are found.

**Comment by keirans** [comment]
Absolutely.

Let me get a sample set of exit codes over to you tomorrow.

I'll take the latest build for a spin then as well.

This is going to be great when its in, escpecially for pipelines and audits.


K

**Comment by keirans** [comment]
Morning!,
OK how does this sound. I have reworked Puppet's --detailed-exitcodes option and when present, git leaks would return:

```
--detailed-exitcodes
Provide extra information about the scan via exit codes;  If enabled, 'gitleaks' will use the following exit codes:

0: The scan succeeded with no findings

1: The scan failed, or wasn't attempted due to an execution failure.

2: The scan succeeded, and secrets / patterns were found.

```

When this option is not used, the tool will by default  return 0 for execution success and 1 for all failure types. Thus keeping current functionality unchanged.

We can then add further detailed exit codes 3+ later if required.

Feedback welcome,

K

**Comment by zricethezav** [comment]
Hey @keirans, just wanted to let you know I'm still working on implementing all of these features. Progress here: https://github.com/zricethezav/gitleaks/tree/feature/usability 
quite a big refactor

**Comment by keirans** [comment]
All good mate.
Just had a quick look, it's looking great.

I had another bit of feedback to add around when cloning , looping through all branches rather than operating off master as well. I think that will give you more coverage. Whats easiest for you ? Add it to my original suggestions at the top for tracking for the time being ?

Let me know if you want some help atleast with some of the doco, etc. My Markdown is better than my go ;)

K

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/55 should do the trick on most of what you requested 👍 still need to implement externalizing regex... yaml has some goofy escape sequences so i might just opt for writing regex into a straight txt file...

**Comment by keirans** [comment]
I'm taking this for a spin now and will let you know how I go :)

Thanks again for your enhancements.

K

**Comment by keirans** [comment]
Hey There,
I've taken the new version for a run, it's looking pretty good.

I did find that the -r option that I was using on a [bare repository, local repository](http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/) was no longer working for me, however i solved this by just pre-cloning the repo and then using the -l option on the clone which got me solved. It would be nice if that could be fixed, but its nothing too major.

Apart from that, the report dir switch works very well and have really helped make the tool much friendlier to use, thanks for adding this, alongside not creating reports when there are no results.

Some of the other smaller things I think could help general usability is maybe explaining what some of the switches do in a little more detail:

```
*  --concurrency=<INT>    Upper bound on concurrent diffs
*  --since=<STR>          Commit to stop at
*  --b64Entropy=<INT>     Base64 entropy cutoff (default is 70)
 * --hexEntropy=<INT>     Hex entropy cutoff (default is 40)
*  -e --entropy           Enable entropy
```

If you want to drop a little bit of information my way, i'll happily update the README and tidy it up a little to help where I can.

I do have another feature that I think would make yours stand out from the other tools, and that is scanning all the branches of a repository (local and remote , via additional flags) rather than just the master branch. Let me know your thoughts on this, and I can open a feature request alongside how i'd suggest to implement it's logic.

Let me know what you think, and thanks as always :)

K
