### ISSUE TITLE
Invalid usage or flags provided results in 0 exit code

### ISSUE THREAD

**Issue by kowalczykp** [zricethezav/gitleaks#500]
**Describe the bug**

Specifying invalid parameters to gitleaks results in help/usage being printed and 0 exit code

**To Reproduce**
```
gitleaks --repo-path=.

echo $?
```

**Expected behavior**

Ideally misconfiguration should result in error and be marked with non-zero exit code, to allow easy identification in CI

**Basic Info (please complete the following information):**
 - OS: macos/linux
 - Gitleaks Version: 7.2.0

cc @zricethezav

**Comment by zricethezav** [comment]
![Screen Shot 2021-01-07 at 1 52 03 PM](https://user-images.githubusercontent.com/15034943/103932238-8b55e480-50ef-11eb-8923-2b392de3c660.png)

@kowalczykp odd, works for me. This is what you are expecting correct?

**Comment by zricethezav** [comment]
ah, now i see. invalid options should result in exit code `1`. I agree with this I think

**Comment by kowalczykp** [comment]
another common exit code could be: `127`, but it would require a bit more changes in the code I think. I've opened a PR in case you think this should be adjusted to return non-zero code on bad input.
