### ISSUE TITLE
--depth flag behaviour

### ISSUE THREAD

**Issue by bhornsby** [zricethezav/gitleaks#502]
**Possible Awareness for Community**
Just wondering if gents/ladies need to be made aware of this slight behaviour change

**To Reproduce**
With `v7.2.0` use `--depth` flag on a project that had a secret on another branch's commit history. In my case value passed to flag was 2.

**Expected behavior**
Was initially expecting the secret to be found just like normally occurs in `v6.2.0` but alas, that was not the case. This led me to #460. There I realized that the `--depth` option was being passed directly to the `git clone` command as such after reading the [docs](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) I realized when using the `--depth` flag on `git clone` the behaviour is slightly different from what used to occur before. 

This new behaviour is not a problem at all since I know it is just a difference in how git **walks** down the tree in collecting parent information. 

Just wanted to bring this difference to the attention of folks and the powers that be. 

Good day!

**Basic Info (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Gitleaks Version: 7.2.0

cc @zricethezav

**Comment by zricethezav** [comment]
you can pass `git log -p` option into gitleaks with the `--log-opts` flag. So to set a depth you can pass `--log-opts -1` which execute `git log -p -1` under the hood
