### ISSUE TITLE
--files-at-commit fails for nested repos

### ISSUE THREAD

**Issue by TehWebby** [zricethezav/gitleaks#509]
**Describe the bug**
We use gitleaks in a project that contains multiple repos inside. Example

- Main directory (point gitleaks to here)
    - Repo 1
    - Repo 2

When the "--files-at-commit=latest" flag is set it only checks the Main directory repo for .git, if it doesn't find it ends.
But on old versions the behavior is different, it would recursively go through each inner repo (.git exists inside each Repo dir)
If the flag is omitted then it works 

**To Reproduce**
Point gitleaks to a main directory with nested repos inside.
Set --files-at-commit=latest

**Expected behavior**
Should (based on old versions) allow each nested repo to be scanned collectively.

**Basic Info (please complete the following information):**
 - OS: Win 10 and Linux
 - Gitleaks Version: 7 onwards

Error Msg (modified path for example):
INFO[0000] opening ./path_to_project              
ERRO[0000] repository does not exist

cc @zricethezav

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.
