### ISSUE TITLE
Multiple instances of the same rule in one line

### ISSUE THREAD

**Issue by wakeman83** [zricethezav/gitleaks#514]
Multiple rules matching in one line are supported.
How about getting each instance of the same rule in the same line being flagged?

Example:
For a line with multiple secret types and two passwords, I get only one match as follows - I assume that the leftmost match is taken into account below:

```
{
        "line": "AKIAIOSFODNN7EXAMPLE ambition LinkedInterconnectAttachment cambridge cambridge password=\"%s\" password=\"wokwoekwokgjg\" no-ambition",
        "lineNumber": 1,
        "offender": "password=\"%s\" password=\"wokwoekwokgjg\" no-ambition",
        "commit": "986613474438b5614b59ba0c57be93b437db3919",
        "repo": ".",
        "repoURL": "",
        "leakURL": "",
        "rule": "Passwords 3",
        "commitMessage": "test\n",
        "author": "XXX",
        "email": "YYY",
        "file": "test_file",
        "date": "2021-01-26T04:38:42-05:00",
        "tags": "key, Generic"
}
```

Justification: Different secret instances may have different criticality. One of them can be false positive, another one may be relevant. This gains more significance if further triaging is performed in automated fashion and only a human would notice that there are actually more than 1 secret in the "offender" column.

I understand that this use case may not be needed by everyone, so it could be implemented as an optional switch.

**Comment by zricethezav** [comment]
This should be fixed in the most recent version of gitleaks as it uses `findallindex` for matching regex
