### ISSUE TITLE
Options --files-at-commit and --commit results in error

### ISSUE THREAD

**Issue by AndrewMasalski** [zricethezav/gitleaks#515]
I am trying to run the scan on our CI using this command:
```
docker run \
  --tty --rm \
  --name=gitleaks \
  --mount type=bind,source="./",target="/scan" \
  "zricethezav/gitleaks:v7.2.0" \
  --path="/scan" \
  --files-at-commit="latest" \
  --config-path="scan/gitleask-config.toml" \
  --redact \
  --verbose
```
If I use `--files-at-commit` or `--commit` option, gitleaks throws error:
```
INFO[0000] opening /scan
ERRO[0000] object not found
```
When I remove `--files-at-commit` option gitleaks does not throw any error, but it doesn't find any secrets.
Locally the same command works just fine.

**Basic Info (please complete the following information):**
 - Gitleaks Version: v7.2.0

cc @zricethezav

**Comment by raoel** [comment]
could this be related? since it's related to git, and go-git is used in the code? (I don't code Go myself, so I can't patch it :-/  )
https://github.com/go-git/go-git/issues/305

**Comment by raoel** [comment]
I'm getting the same error;  the last 40-50 commits or so everything worked perfectly, but it stops working on my last commit

**Comment by w0rmr1d3r** [comment]
Hello!

Can you try with the new version? 7.6.0

It seems that this issue is related to an old version of gitleaks.

Cheers!

**Comment by raoel** [comment]
I don't know why, but the issue disappeared? :-/ 

I upgraded from 7.5.0 to 7.6.0, so it wasn't that old :-)  but we'll see how it goes

**Comment by w0rmr1d3r** [comment]
Okai!
Closing the issue for now, since it seems that it's been fixed :)
