### ISSUE TITLE
Any plans to enable scanning an existing cloned repo?

### ISSUE THREAD

**Issue by willfaught** [zricethezav/gitleaks#52]
I don't need a separate copy of a repo cloned, I already have one locally, and want to scan it in place for leaks. Useful for CI stages like linting. Arguably this should be the default, since it's trivial to clone a repo yourself and `cd` into it or give the path to it.

**Comment by zricethezav** [comment]
This is in the works, doing a fairly large refactor and some feature implementations described here: https://github.com/zricethezav/gitleaks/issues/50. stay tuned

**Comment by orrc** [comment]
I know it's not the same as scanning an existing clone, but I've been doing this, which at least saves on network traffic:
`./gitleaks -j file://$HOME/code/some-repo`

**Comment by zricethezav** [comment]
v0.3.0 introduces this. `gitleaks --local path/to/repo`

**Comment by paulfantom** [comment]
@zricethezav `--local` mode is not working or I'm doing sth wrong.

1. I ran everything in docker container [`golang`](https://hub.docker.com/_/golang/) with mounted volume (`/mnt/repo`) with git repository. (`docker run -it -v `pwd`:/opt/repo golang bash`)
2. Downloaded gitleaks with `go get -u github.com/zricethezav/gitleaks` as it is described in README.md
3. Ran: `gitleaks --local /opt/repo`
4. Got this error:
```sh
2018/03/05 23:49:46 fetching repo from /opt/repo ...
cannot fetch  from /opt/repo
```

**Comment by thearthur** [comment]
I also get this with the --local option when using docker: the image id is in :latest right now is:
961c61f679f8

**Comment by thearthur** [comment]
this seams to be related to the user id of the files being checked not having a matching user inside the docker container

**Comment by zricethezav** [comment]
new version should take care of all these issues
