### ISSUE TITLE
Bitbucket enterprise URL scan

### ISSUE THREAD

**Issue by gupta-pooja-xo** [zricethezav/gitleaks#520]
**Describe the bug**
I want to scan all the repositories in a workspace / enterprise but I am getting error as "authentication required". I tried connecting with ssh as well as username/password. If I run the same commands only on a single repo it works.

So there are two workspace I am trying to connect to. One is the enterprise bitbucket URL but since that was not working I tried the https://username@bitbucket.org/<workspace-name>" and that too is giving error

**To Reproduce**
1. gitleaks --ssh-key=~/.ssh/keyname --repo-url="https://username@bitbucket.org/workspace-name/“ -v 
2. gitleaks --ssh-key=~/.ssh/keyname --repo-url="https://enterprise-bitbucket-url“ -v 

Using SSH option gives error authentication required, well thats because this a http URL. And with username/password option I get repository not found error in bitbucket.org. 

cc @zricethezav

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

Gitleaks is not responsible for cloning
