### ISSUE TITLE
Gitleaks generates empty report (0KB)

### ISSUE THREAD

**Issue by brownrw8** [zricethezav/gitleaks#524]
**Describe the bug**
On Windows, gitleaks writes an empty (0KB) report file to whichever directory I specify, regardless of number of leaks found.  This occurs for both both JSON and CSV report format.

After running the following command: 
`> gitleaks.exe --path=<PATH_TO_REPO> --branch=master --report=report.csv --format=CSV --config-path=scanner.config`

Log output is the following: 
```
time="2021-02-10T09:28:43-11:00" level=info msg="opening <PATH_TO_REPO>\n"
time="2021-02-10T09:59:53-11:00" level=info msg="scan time: 37 minutes 19 seconds 343 milliseconds 912 microseconds"
time="2021-02-10T09:59:53-11:00" level=info msg="commits scanned: 5971"
time="2021-02-10T09:59:53-11:00" level=warning msg="leaks found: 203"
```

The report.csv or report.json is always 0KB.

**To Reproduce**
Run gitleaks on local git repository with either `--report=report.csv --format=CSV` or `--report=report.json --format=JSON` flags set.

**Expected behavior**
I expect the report.csv or report.json to contain data, but it always generates an empty file (0KB)

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise Edition
 - Gitleaks Version: v7.2.2

**Additional context**
Assume CMD calling gitleaks.exe from the same directory, and git repository is one level down.

cc @zricethezav

**Comment by c3101** [comment]
+1

**Comment by acheronstyix** [comment]
Hi,

try to change `--format=CSV` by `--format=csv` (lowercase).

It worked for me

**Comment by schattenbaum** [comment]
The answer from @acheronstyix definitively helped me as well. a simple to lowercase would probably help many others in the future as well. ;)

**Comment by zricethezav** [comment]
@schattenbaum 😬 you're absolutely right. https://github.com/zricethezav/gitleaks/blob/master/scan/report.go#L21-L99 needs a lil rework. I see some redundant logic at a glance. Happy to accept PRs if anyone wants to tackle this. Basically, we want to normalize all `ReportFormat` values to lowercase before checking them. Also that second https://github.com/zricethezav/gitleaks/blob/master/scan/report.go#L50 check is unnecessary as we are checking for `!=""` earlier.
