### ISSUE TITLE
Git Cloning Connection Refused

### ISSUE THREAD

**Issue by rahulvinodsharma** [zricethezav/gitleaks#526]
**Describe the bug**

Getting lots of connection refused.

```
time="2021-02-18T08:31:33Z" level=error msg="Get \"https://github.com/...info/refs?service=git-upload-pack\": dial tcp: lookup github.com on 10.56.0.10:53: read udp 10.52.1.3:46760->10.56.0.10:53: read: connection refused"
```
**To Reproduce**
Happens on any attempt, inconsistent.

**Expected behavior**
Git Clone without Error

**Basic Info (please complete the following information):**
 - OS: Alpine
 - Gitleaks Version: v7.2.2

**Additional context**

It would be good if there is the option of the re-attempt parameter.

Thanks

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @rahulvinodsharma !
It seems there's a connection issue with GitHub, have you tried cloning the repo yourself (without using gitleaks) where it's running, to see if the problem persist?
Could it be due to your SSH keys to connect to GitHub? Or maybe due to your internet connection?

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.
