### ISSUE TITLE
False positive Github token in Terraform module

### ISSUE THREAD

**Issue by adamdecaf** [zricethezav/gitleaks#531]
**Describe the bug**
Our CI failed due to gitleaks detecting the following block as a Github API key. It's not, but I assume the pattern matches similar enough that the regex matched the line. This code block is [Terraform](https://www.terraform.io/) config to deploy a docker image inside Kubernetes. 

The `source` attribute [references a commit that doesn't introduce secrets](https://github.com/moov-io/infra/commit/a436c10a95a71de7854079411ff9411ddfbb1de1) and has been scanned without issue. 

```hcl
module "github-exporter" {
  source = "github.com/moov-io/infra//modules/github-exporter?ref=a436c10a95a71de7854079411ff9411ddfbb1de1"

  namespace = var.namespace

  orgs = "moov-io"
  github_token_filepath = "./conf/github-token"
}
```

**Expected behavior**
False positives to not occur. 

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS - GitHub Actions
 - Gitleaks Version: `zricethezav/gitleaks:v7.2.0` 

**Additional context**
```
{
	"line": "  source = \"github.com/moov-io/infra//modules/REDACTED\"",
	"lineNumber": 142,
	"offender": "REDACTED",
	"commit": "fe8988f2702d79142c47f2f5433e1592198a6bbf",
	"repo": "workspace",
	"repoURL": "",
	"leakURL": "",
	"rule": "Github",
	"commitMessage": "veridian/infra: better cpu/mem resources\n",
	"author": "Adam Shannon",
	"email": "adamkshannon@gmail.com",
	"file": "veridian/infra/main.tf",
	"date": "2021-02-23T10:49:02-06:00",
	"tags": "key, Github"
}
	"line": "  source = \"github.com/moov-io/infra//modules/REDACTED\"",
	"lineNumber": 142,
	"offender": "REDACTED",
	"commit": "fe8988f2702d79142c47f2f5433e1592198a6bbf",
	"repo": "workspace",
	"repoURL": "",
	"leakURL": "",
	"rule": "Github",
	"commitMessage": "veridian/infra: better cpu/mem resources\n",
	"author": "Adam Shannon",
	"email": "adamkshannon@gmail.com",
	"file": "veridian/infra/main.tf",
	"date": "2021-02-23T10:49:02-06:00",
	"tags": "key, Github"
}
```

cc @zricethezav

**Comment by tesharp** [comment]
Have a very similar case with false positive in `yarn.lock` file on this entry:

https://registry.yarnpkg.com/github-slugger/-/github-slugger-1.3.0.tgz#9bd2a95c5efdfc46225e82a926ef8e2a259124c9

Because package has github in name it matches the Github rule. Looks like pretty much same problem

**Comment by zricethezav** [comment]
@adamdecaf @tesharp thanks for bringing this up. I'll try to work on a stricter github rule. Happy to accept PRs for this as well!

**Comment by kstarzyk** [comment]
> Because package has github in name it matches the Github rule. Looks like pretty much same problem
Same here.

Link to the rule: https://github.com/zricethezav/gitleaks/blob/4544156b448ee5152f7e4c1c3ad8eec7e5d3d5d6/config/default.go#L46

@zricethezav what's the purpose of this rule? What kind of leaks it might prevent?

**Comment by zricethezav** [comment]
@kstarzyk ideally this would prevent github access tokens from being leaked

**Comment by adamdecaf** [comment]
GitHub personal access tokens are 40 characters and so are the commit hashes. Was the regex designed to catch instances where a token is supplied as an HTTP header? I've got `Authorization: token $GITHUB_TOKEN` as the format for that. 

I'm thinking any `https://(.*)(github.)([0-9a-zA-Z]{35,40})` matching string is safe, but it seems there's an example I'm missing?

**Comment by zricethezav** [comment]
@adamdecaf, the regex was designed to catch things like 
```
GITHUB_TOKEN = "a436c10a95a71de7854079411ff9411ddfbb1de1" 
```

However the regex is too tolerant. I'm thinking something like 

```
(?i)github.{0,3}((?i)token|api|key).{0,10}?(?-i)([0-9a-zA-Z]{35,40})
```

WDYT @adamdecaf @kstarzyk. Give it a try https://regex101.com/r/81pntG/1

I'm in the process of rewriting some of the more loose rules to make them more strict

**Comment by adamdecaf** [comment]
That looks a lot better. I tried a few other `github....` common strings and it's not matching. https://regex101.com/r/VVpIXJ/1

**Comment by zricethezav** [comment]
@adamdecaf thanks for doing some additional testing!
