### ISSUE TITLE
Problem loading config in Windows platform

### ISSUE THREAD

**Issue by amrityam** [zricethezav/gitleaks#532]
Hi,

I am trying to load config .toml file using below command in windows.
**_gitleaks --path="F:\Test\secret_scan\vuln_app" --no-git --report="F:\Test\secret_scan\scan_report.json" --config-path="F:\Test\secret_scan\gitleaks\examples\leaky-repo.toml"_**

But it is giving me below error.
_**time="2021-02-24T10:46:49+05:30" level=error msg="problem loading config: error parsing regexp: invalid escape sequence: `\\T`"**_

I have tried with multiple .toml files however nothing works. Even for a blank .toml file also it gives same error.
However same command works fine in linux platform.

![config_loading_error_windows](https://user-images.githubusercontent.com/27488677/108952380-5e559500-768f-11eb-97d4-079d40e2680e.png)

cc @zricethezav

Best Regards

**Comment by amq** [comment]
Can be mitigated by running in git bash

**Comment by marian-craciunescu** [comment]
any toml config manifested the same way actually.

**Comment by zricethezav** [comment]
I unfortunately do not have a windows machine to test on. If someone could provide a solution that would be great

**Comment by JoostVoskuil** [comment]
Reverse the slashes will work. Use / instead of \

**Comment by JoostVoskuil** [comment]
Problem does not exist anymore with Gitleaks v8
