### ISSUE TITLE
Output from stdout is not valid json no comma between found entries

### ISSUE THREAD

**Issue by EliSchleifer** [zricethezav/gitleaks#537]
**Describe the bug**
The output in json mode is not printing a valid group of json. 

Looks like 
{
....
}
{
...
}

Should be
{
...
}**,**
{
....
}

**To Reproduce**
Lint file with multiple issues

**Expected behavior**
stdout should have valid parsable json

cc @zricethezav

**Comment by ghostsquad** [comment]
It doesn't output anything when nothing is found. This is also a problem, as you can't reliably pipe to `jq`

**Comment by w0rmr1d3r** [comment]
Hello @EliSchleifer and @ghostsquad !

Is this still happening on v7.6.0 ?

Thank you!

**Comment by EliSchleifer** [comment]
Yes it is

**Comment by EliSchleifer** [comment]
For example - this outtput from 7.6.0. Changing the json output to properly push "[]" on empty and to create properly formatted json would be a simple enough PR - but also a breaking change for any consumers of the product. I am happy to put a PR together - but the implications of the fix are rough.

{"line":"aws_access_key_id = \"AKIAIO5FODNN7EXAMPLE\"","lineNumber":1,"offender":"AKIAIO5FODNN7EXAMPLE","offenderEntropy":-1,"commit":"","repo":"","repoURL":"","leakURL":"","rule":"AWS Access Key","commitMessage":"","author":"","email":"","file":".","date":"0001-01-01T00:00:00Z","tags":"key, AWS"}
{"line":"aws_access_key_id = \"AKIAIO5FODNN7EXAMPLE\"","lineNumber":4,"offender":"AKIAIO5FODNN7EXAMPLE","offenderEntropy":-1,"commit":"","repo":"","repoURL":"","leakURL":"","rule":"AWS Access Key","commitMessage":"","author":"","email":"","file":".","date":"0001-01-01T00:00:00Z","tags":"key, AWS"}

**Comment by zricethezav** [comment]
@EliSchleifer happy to review an PR. I think the vast majority of users consume the reports via report file rather than stdout so this wouldn't be considered a breaking change imo.

If you're willing, would you mind sharing how you are consuming the output of gitleaks? I'm curious

**Comment by EliSchleifer** [comment]
@zricethezav - We're integrating gitleaks into our universal check tool. Would love for you to check it out if you're interested. We'll be launching in about a months time, but happy to give you a sneak peek. You can reach me directly at eli@trunk.io

By the way gitleaks is a super cool tool and a really important piece, IMO, of good engineering workflows.

**Comment by k0ral** [comment]
The `stdout` output is pretty convenient to consume huge amounts of leaks in a streaming manner. That is: the consumer processes one stdout line at a time, with constant memory usage throughout the process. For this use case, having a standalone JSON object per line is more convenient than having to strip each line of the extra comma-separator.

Thus, I would argue that sending a big standalone JSON object through `stdout`, should be an optional feature :) .

**Comment by EliSchleifer** [comment]
I'm really interested in the use case of a repository that has so many leaks that they need to be consumed by a stream. @k0ral  - is this a scenario you've come across?

**Comment by k0ral** [comment]
@EliSchleifer Using a set of custom rules, I've seen cases with tens of thousands of leaks. Each leak includes the full line that matched the regex (in case it's a content regex and not just a filepath regex), which is an unbounded piece of information. (By the way, this probably warrants a distinct issue.)

Granted, this may not be the common scenario, but I sleep better at night knowing that when this happens, memory usage won't go through the roof :) .

**Comment by zricethezav** [comment]
should be fixed in v8, reopen if not
