### ISSUE TITLE
False leak reported?

### ISSUE THREAD

**Issue by andybeet** [zricethezav/gitleaks#538]
**Describe the bug**
I believe gitleaks-action is producing a false alarm

**To Reproduce**
Both of these repos were passing when i added the action on Jan 30, 2021. Then on Feb 22, 2021 after no significant changes in content. Both repos failed. Here are the logs from two of our repos.
1. [repo1](https://github.com/NOAA-EDAB/ms-keyrun/runs/1989245657)
2. [repo2](https://github.com/NOAA-EDAB/tech-doc/runs/1989629958)

**Expected behavior**
This image the leak is relating to in `repo1` is produced using R code. Not sure why this would be considered a leak although it is reporting an AWS Access Key. The leak in `repo2` seems to be related to a travis CI key.

**Screenshots**
See links above

**Basic Info**
 - Gitleaks Version: 7.2.2

cc @zricethezav
I posted this in the `gitleaks-action` repo too, since i wasn't sure which repo was responsible.

**Comment by melg8** [comment]
I've encountered same issue.
Reports:
"rule": "AWS Secret Key",
where
"line": "      \"integrity\": \"sha512-GDHVin2EJ9PGJ33VMGlqtPcvUlY+pkTbaWs4jWv8oBaEK8UUBzS5ZpEc4xi7Xp5vIXnVsCSLKNC6bgvR9X/AoQ==\",",
"offender": "aWs4jWv8oBaEK8UUBzS5ZpEc4xi7Xp5vIXnVsCSLKNC6bgvR9X/AoQ",

So just sha512 with aWs symbols were detected as AWS leak.

**Comment by zricethezav** [comment]
Thanks for bringing this up. @andybeet @melg8. https://github.com/zricethezav/gitleaks/blob/master/config/default.go#L14-L17 is probably too lenient. I can look into changing this rule. Meanwhile, you can write [your own rules](https://github.com/zricethezav/gitleaks#rules-summary) with stricter regexes.

**Comment by zricethezav** [comment]
v8 has updated rules
