### ISSUE TITLE
Exclude directory argument in --no-git mode

### ISSUE THREAD

**Issue by prabhu** [zricethezav/gitleaks#543]
**Is your feature request related to a problem? Please describe.**
slscan now use gitleaks in `--no-git` mode by default. This is currently parsing all the directories including .venv, node_modules etc that can be safely ignored.

**Describe the solution you'd like**
By supporting an argument such as `--exclude-dir`, `--exclude-regex` tools such as slscan can ignore known directories to speed up the analysis

**Describe alternatives you've considered**
Iterating the directories and invoking gitleaks multiple times is not elegant.

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@prabhu There is the ability to exclude regexes and directories using the [config toml file](https://github.com/zricethezav/gitleaks#rules-summary). I like the separation of scanning options and rule configuration. This encourages folks to write their own gitleaks configuration files and not rely on the default config.

**Comment by prabhu** [comment]
@zricethezav Thank you. Will explore the config file further. However, would it offer performance benefits by completely ignoring those directories or only used for suppressing findings? node_modules, venv are large in modern apps so an option to entirely ignore them is preferable. I have users reporting that gitleaks is currently taking over 2.5 hours for certain apps which is not ideal.

**Comment by zricethezav** [comment]
> However, would it offer performance benefits by completely ignoring those directories or only used for suppressing findings?

@prabhu the former. Gitleaks prevents scanning and files/paths founds in the global allowlist.

> I have users reporting that gitleaks is currently taking over 2.5 hours for certain apps which is not ideal.

If those repos are public I'd be happy to take a look 😄

**Comment by jboler** [comment]
I'm seeing something similar. I've tried various different regexes to exclude all `node_modules` directory and the `.git` directories but I can't get anything to work. Do you have any suggestions of what regex to use here?

MacOS 11.4
gitleaks 7.5.0

```
$ gitleaks -v --config-path=gitleaks.toml --no-git --path=./
ERRO[0000] open node_modules/.cache/babel-loader/6d8063beb61e7aeac6d81316036a7468.json: too many open files
INFO[0000] scan time: 59 milliseconds 48 microseconds
ERRO[0000] open node_modules/.cache/babel-loader/6d8063beb61e7aeac6d81316036a7468.json: too many open files
```

gitleaks.toml
```
title = "gitleaks config"

[[rules]]
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*?'''
tags = ["key", "jwt"]

[allowlist]
description = "Allowlisted files"
files = [
  '''.*node_modules.*''',
  '''\.git''',
]
```
