### ISSUE TITLE
[Documentation] Dockerfile comment is wrong.

### ISSUE THREAD

**Issue by mercuriete** [zricethezav/gitleaks#544]
If you go to this line:

https://github.com/zricethezav/gitleaks/blob/d353ac510878c743df7d5ebfdfc823be574f8e8f/Dockerfile#L15
```
# docker run --rm --name=gitleaks gitleaks --repo=https://github.com/zricethezav/gitleaks
```

it fails with the following error:
```
unknown flag `repo'
```

and it should be repo-url:
```
# docker run --rm --name=gitleaks gitleaks --repo-url=https://github.com/zricethezav/gitleaks
```

Thanks

**Comment by zricethezav** [comment]
@mercuriete care to make a PR? happy to accept community contributions

**Comment by mercuriete** [comment]
ok! I'll do it

**Comment by mercuriete** [comment]
@zricethezav done

can you review the PR?

thanks for this project! :smile:
