### ISSUE TITLE
Docker Tag v7.4.0 is missing 🤔

### ISSUE THREAD

**Issue by rseedorff** [zricethezav/gitleaks#548]
**Describe the bug**
As a gitleaks user i would like to decide which release version of gitleaks is currently running in my infrastructure.

In an fully automated docker container based setup it is somehow a little bit risky to always reference a `latest` docker tag image instead of specific versions.

**To Reproduce**

The latest release version is currently: `v7.4.0`
* see: https://github.com/zricethezav/gitleaks/releases

Trying to pull this release version fails 🤭 `docker pull zricethezav/gitleaks:v7.4.0`
* see: https://hub.docker.com/r/zricethezav/gitleaks/tags?page=1&ordering=last_updated

**Expected behavior**
It would be great if your release process will be extended to create stable semantic version tags as docker image tags and push them to dockerhub. There are some helpful GitHub actions that could do the job easily 😊

cc @zricethezav

**Comment by zricethezav** [comment]
@rseedorff 7.4.0 is available now. I don't have plans to automate the release process at this time.
