### ISSUE TITLE
Better support as a library

### ISSUE THREAD

**Issue by ghostsquad** [zricethezav/gitleaks#556]
**Is your feature request related to a problem? Please describe.**
If someone want to integrate gitleaks into another tool, it is not trivial to do without shelling out. I believe this scenario could be made easier with some changes to Scan

**Describe the solution you'd like**
Allow Scan to take a `context.Context` and quit when that context is cancelled. Scan should return just the results, and possibly some "progress information". The `main.go` of gitleaks can consume those outputs and decide to write to stdout/stderr etc as needed.

**Describe alternatives you've considered**
I can shell out within my go application and capture stdout/stderr, but it's not as clean.

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
This might be something I pursue in the future but currently I do not want to support it as a library
