### ISSUE TITLE
No .pre-commit-hook.yaml file in any current release

### ISSUE THREAD

**Issue by jonathanio** [zricethezav/gitleaks#557]
**Describe the bug**

In adding the recommended configuration from the README file, the `pre-commit` run fails:

```shell
$ pre-commit run
An error has occurred: InvalidManifestError:
=====> /home/{username}/.cache/pre-commit/repomp04lde_/.pre-commit-hooks.yaml does not exist
Check the log at /home/{username}/.cache/pre-commit/pre-commit.log
```

Both the `v7.4.0` release linked to in the documentation and the `v.7.4.1` current release is older than the commit which adds the `.pre-commit-hooks.yaml` file to the repository, so the run fails. If I target the repository directly with the latest commit (e7553b0168aac548d8858c30b67194a4928285e3), it works:

```yaml
  - repo: https://github.com/zricethezav/gitleaks.git
    # The latest release does not include the hook file, so target the commit
    rev: e7553b01
    hooks:
      - id: gitleaks
```

As such, it looks like the README.md will need to be updated with reference to `v7.4.2` instead and a point release made so that when `pre-commit` clones the repository into the cache, that version has the requiset `.pre-commit-hooks.yaml` file to allow the checks to run:

```shell
$ git commit
[INFO] Installing environment for https://github.com/zricethezav/gitleaks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Detect hardcoded secrets.........................................................Passed
```

**To Reproduce**

Implement the recommended configuration from the README into `.pre-commit-config.yaml` in a repository.

**Expected behavior**

`pre-commit` runs successfully.

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@jonathanio just released https://github.com/zricethezav/gitleaks/releases/tag/v7.5.0. Lemme know if that works

**Comment by jonathanio** [comment]
@zricethezav Just tested with the `v7.5.0` tag and I had no issues. Thanks for that.
