### ISSUE TITLE
Hide access token from command line arguments

### ISSUE THREAD

**Issue by maurofaccenda** [zricethezav/gitleaks#563]
**Is your feature request related to a problem? Please describe.**

When running gitleaks the access token is exposed to anyone who can list processes on the system (`ps`, `top`).

**Describe the solution you'd like**

I've seen some solutions that can mask the secret replacing the actual value with something like `*****` or `<hidden secret>`.
If I remember right, mysql command line does that.

An alternative is to be able to provide an env var name (or even have a default) where gitleak would read the value from the env var where the secret would be stored.

**Describe alternatives you've considered**

Could not find any.

**Additional context**

I need to scan several organizations and the process takes too long, so I need to run it from a server where multiple users has access and they can see my process by just running a `ps` command which can expose the arguments, including my access token.

cc @zricethezav

**Comment by zricethezav** [comment]
Gitleaks is not responsible for cloning
