### ISSUE TITLE
Can't use config-path flag

### ISSUE THREAD

**Issue by marcelo321** [zricethezav/gitleaks#571]
sorry I don't know if im stupid or what but I can't add a local config.go file.

I am trying:

```
gitleaks -r https://somerepo.com/ -q --config-path="/root/githubsearch/"
gitleaks -r https://somerepo.com/ -q --config-path="/root/githubsearch/default.go"
gitleaks -r https://somerepo.com/ -q --config-path=/root/githubsearch/default.go
gitleaks -r https://somerepo.com/ -q --config-path=default.go
```

I tried all the ways It is common to select a path.. but none work

Can somebody please help me?

**Comment by marcelo321** [comment]
The usual that most golang tools use is `-c config.go` or `-c /path/to/file.yaml` and that's it, none of them working here

**Comment by w0rmr1d3r** [comment]
Hello @marcelo321 !
I'd try without the `-q` mode, and use `-v` or `--verbose` instead, to have a better look of what's the error.
However, the _config path_  it refers to, the path to the gitleaks config file, not the config file of your application.

If you want to scan that file, use it as it's shown in this example -> https://github.com/zricethezav/gitleaks#scan-a-file
Here you have more info about the `--config-path` option you are using -> https://github.com/zricethezav/gitleaks#configuration

Cheers!

**Comment by zricethezav** [comment]
@w0rmr1d3r thanks for helping out!

**Comment by marcelo321** [comment]
@zricethezav @w0rmr1d3r,

I am trying to load a gitleaks configuration using my own regexs, but I am unable to pass it as an argument using the mentioned flag.

`--config-path loads a local gitleaks configuration`

I am trying the following:

```
gitleaks -r https://github.com/marcelo321/repo -q 
```

Works as expected, scans perfectly. Now I am trying to pass my own set of rules/regexs so gitleaks uses them instead of the default one here: https://github.com/zricethezav/gitleaks/blob/master/config/default.go

So I created my own `config.go` with my own regexs and I am trying to pass it like:

```
gitleaks -r https://github.com/marcelo321/repo -q --config-path= config.go
```

But I get no error there and the file full of regexs is not even proccessed. How do I pass my own default.go? does it need to be .go?

**Comment by marcelo321** [comment]
Ok so the config file had to be .toml.. damn.

**Comment by marcelo321** [comment]
Also I noticed that regex matching more than 1 line aren't working. Is there a way to do it?

Trying: 

```
regex = '''((?i)someword)((\S|\s*)?){0,75}anotherword'''
```

I used that regex a lot, trying to switch from shhgit to gitleaks but can't manage how to change the regexs

**Comment by w0rmr1d3r** [comment]
Hello @marcelo321 !
About this:
> Ok so the config file had to be .toml.. damn. Is there any public `.toml` file we can take a look? I just have it with rules and Idk If I can add blacklist strings and others.

Yes, there're examples here and you can add blacklist strings -> 
https://github.com/zricethezav/gitleaks#rules-summary

Regarding the comment about regex, you have an example here -> https://github.com/zricethezav/gitleaks#example-1
However, can you provide us the full `toml` file? Maybe there's something else we are missing.

Thank you!

**Comment by marcelo321** [comment]
I missed your comment. Basically I want to generate a rule/regex that matches the following words:

```
word1
word2
```

In the config.yaml of shhgit I was using a regex like this one: `((?i)someword)((\S|\s*)?){0,75}anotherword` to match spaces, but it doesn't work with gitleaks.

If you find an example to match words from 2 or more different lines like with my example, let me know

**Comment by HotThoughts** [comment]
@marcelo321 
You probably want to put your regex in square brackets. This is a toml syntax. 
```toml
regex = ['''((?i)someword)((\S|\s*)?){0,75}anotherword''']
```

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

This issues are likely resolved with the latest version of gitleaks
