### ISSUE TITLE
Not detecting certificates

### ISSUE THREAD

**Issue by w0rmr1d3r** [zricethezav/gitleaks#572]
**Describe the bug**
I used gitleaks to review a small repo which had a private key and a certificate.
gitleaks detected the key (yay!) but not the certificate.
The string containing the certificate started with -> `-----BEGIN CERTIFICATE-----`
and ended with -> `-----END CERTIFICATE-----\n` 
Between those lines, you can find the usual "random" characters.

**To Reproduce**
1. Run gitleaks and try to detect a string with a certificate such as the one said above.

**Expected behavior**
I believe the certificate should've been detected as a leak.

**Screenshots**
Can't give any.

**Basic Info (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Gitleaks Version: 7.5.0 (installed from brew)

**Additional context**
I ran gitleaks with `--verbose`, but only showed the key leaked, not the certificate.

cc @zricethezav

**Comment by zricethezav** [comment]
Hey @w0rmr1d3r this would be easy enough to add. We would just need an additional rule similar to https://github.com/zricethezav/gitleaks/blob/master/config/default.go#L76-L79.

Something like 
```toml
        [[rules]] 
            description = "Asymmetric Private Key"
            regex = '''-----BEGIN CERTIFICATE-----'''    
```

Care to test that out and see if it works? If it does, feel free to open a PR 😄

**Comment by w0rmr1d3r** [comment]
Alright! Will do in the following days!

**Comment by w0rmr1d3r** [comment]
Hello @zricethezav !
I can't build a custom docker image in order to test it, it's giving me errors.
What I've tried is to use a custom config file and put that rule there, but it's not detecting anything.

I've put this:
```
[[rules]]
  description = "Certificate"
  regex = '''-----BEGIN CERTIFICATE-----'''
```
in the custom config file, and trying to scan a "bad file" with that in in, and nothing is found.

Any help here?

**Comment by lutzwillek-tomtom** [comment]
Hello @w0rmr1d3r, 
gitleaks did not detected the [certificate](https://en.wikipedia.org/wiki/Public_key_certificate) as a [certificate is not a secret](https://stackoverflow.com/questions/28446654/why-certificate-is-not-a-secret-in-ssl-authentication).  This means merging #656 would cause a lot of false positives.

In case there is a specific reason why a certificate should be detected, then a using a locally adapted [configuration](https://github.com/zricethezav/gitleaks#configuration) would be the better way, but not updating the default config for everyone.

**Comment by w0rmr1d3r** [comment]
Hi @lutzwillek-tomtom !
Agree, since @zricethezav suggested how to create the rule, I went for it.
Will close both the issue + PR.

Thanks
