### ISSUE TITLE
Avoid getting many alerts of the same leak

### ISSUE THREAD

**Issue by marcelo321** [zricethezav/gitleaks#574]
I wanted to know if it is possible to add a flag so we don't get tons of alerts of the same "leak"

Right now if somebody pushes a secret and keeps modifying that file, gitleaks will match that same secret the number of times the user modified the file. So we might get 1 or 50 jsons of the same "leak" in the same file but in different lines.

Wanted to know if there is a way to do this before I try to add my own script to do it

**Comment by w0rmr1d3r** [comment]
Hello @marcelo321 !
I understand that `the user modified the file` refers to each commit and all those json refer to each finding in each commit.
Have you tried the `--no-git` option?

**Comment by zricethezav** [comment]
Likely fixed in v8.0.0 although gitleaks should only report leaks when they are introduced
