### ISSUE TITLE
Add blacklist of custom words to config.toml

### ISSUE THREAD

**Issue by marcelo321** [zricethezav/gitleaks#576]
Would it be possible to add a blacklist of custom words that we do not want gitleaks to get us when scanning?

let's say I have a regex that will match "test:example", I would want to add to the blacklist the word "example" so I don't get any alerts of leak containing that word.

Example from shhgit here: https://github.com/eth0izzle/shhgit/blob/master/config.yaml

**Comment by w0rmr1d3r** [comment]
Hello @marcelo321 !
In here, before the examples -> https://github.com/zricethezav/gitleaks#rules-summary
You can find an `[allowlist]` , and put the `example` so you don't get findings regarding that word.

**Comment by zricethezav** [comment]
@marcelo321 similar issue: https://github.com/zricethezav/gitleaks/issues/579
