### ISSUE TITLE
SARIF output report doesn't contain "ruleId" string

### ISSUE THREAD

**Issue by cyrusmatsumori** [zricethezav/gitleaks#578]
**Describe the bug**
When use sarif output format, it generates report using  particular schema: "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json".
In this schema there is a "ruleId" parameter, but Gitleaks report doesn't contain it.

**To Reproduce**
* Perform Gitleaks secret search with `-f sarif` parameter on source code, which contains some leaked secrets.
* Compare generated report with schema it uses. Try to find "ruleId" parameter.

**Expected behavior**
* If SARIF report based on particular schema, report should corresponds to it.

**Screenshots**
<img width="924" alt="sarif" src="https://user-images.githubusercontent.com/9370889/120199987-81628880-c22c-11eb-9479-72665942b12b.png">

**Basic Info (please complete the following information):**
 - OS: gitleaks-darwin-amd64
 - Gitleaks Version: v.7.4.1

**Additional context**

cc @zricethezav

**Comment by cyrusmatsumori** [comment]
Such behavior comes to parsing problems while importing results (for ex. into DefectDojo) using SARIF output.

**Comment by zricethezav** [comment]
fixed in v8.0.0
