### ISSUE TITLE
Idea: port the leak checker to Hercules

### ISSUE THREAD

**Issue by vmarkovtsev** [zricethezav/gitleaks#58]
[Hercules](https://github.com/src-d/hercules) is a nice extensible Git repo analysis engine on top of [go-git](https://github.com/src-d/go-git). Should be very easy to write a [plugin](https://github.com/src-d/hercules/blob/master/PLUGINS.md) and effectively do not depend on GitHub API.

**Comment by zricethezav** [comment]
hey @vmarkovtsev that's a great idea. I have plans to at the very least replace shelling out all the git commands with go-git. I'll have to check out Hercules. Thanks for the suggestion!

**Comment by vmarkovtsev** [comment]
Feel free to ping me if anything is unclear - documenting things is not my strongest skill.

**Comment by zricethezav** [comment]
@vmarkovtsev next release of gitleaks will be using go-git. Thanks for the suggestion. I think I'm able to do everything I need to do without using Hercules from go-git. Will let you know if I run into any roadblocks

**Comment by vmarkovtsev** [comment]
Cool!
