### ISSUE TITLE
Is a snap package available?

### ISSUE THREAD

**Issue by 030** [zricethezav/gitleaks#581]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A snap package so I could install gitleaks by issuing `snap install gitleaks`.

**Describe alternatives you've considered**

**Additional context**

https://snapcraft.io/search?q=gitleaks

cc @zricethezav

**Comment by zricethezav** [comment]
@030 I haven't added anything to snap before, do you have a guide on how I could add it to snap?

**Comment by 030** [comment]
Snapcraft examples:
* https://github.com/030/informado/blob/master/build/package/snap/snapcraft.yaml
* https://github.com/030/dip/blob/master/build/package/snap/snapcraft.yaml
* https://github.com/030/n3dr/blob/master/build/package/snap/snapcraft.yaml

Snapcraft pipelines:
* https://github.com/030/informado/blob/master/.github/workflows/snapcraft.yml

**Comment by zricethezav** [comment]
Closing this as I'm not planning on introducing gitleaks to snap atm
