### ISSUE TITLE
Gitleaks marks Chromedriver as a potential leak 

### ISSUE THREAD

**Issue by zac11** [zricethezav/gitleaks#582]
**Describe the bug**
Gitleaks considers Chromedriver executable for potential leaks (Twitter ID) check.

**To Reproduce**
1. Add chromedriver version (ChromeDriver 91.0.4472.19) in your git repo.
2. Run gitleaks in the repo.

**Expected behavior**
Gitleaks should not actually classify Chromedriver as a leak.

**Screenshots**

**Basic Info (please complete the following information):**
 - Mac OS Catalina:
 - Gitleaks Version: `v7.5.0`

**Additional context**
The error message that is being given 
`{
	"line": "Many artistspoweredperformfictiontype ofmedicalticketsopposedCouncilwitnessjusticeGeorge Belgium...\u003c/a\u003eREDACTED Other rankingphrasesmentionsurvivescholar\u003c/p\u003e\r",
	"lineNumber": 2,
	"offender": "REDACTED",
	"offenderEntropy": -1,
	"commit": "0000000000000000000000000000000000000000",
	"repo": "Repo_path",
	"repoURL": "",
	"leakURL": "",
	"rule": "Twitter Client ID",
	"commitMessage": "",
	"author": "",
	"email": "",
	"file": "resources/drivers/chromedriver_mac",
	"date": "1970-01-01T00:00:00Z",
	"tags": "client, Twitter"
}
`
However, if you open Chromedriver executable in a file mode (in eclipse), the line `58804`, shows this
<img width="1046" alt="Screenshot 2021-06-11 at 11 02 58 AM" src="https://user-images.githubusercontent.com/8002297/121637366-e6c53d80-caa6-11eb-8598-51c34482a63c.png">

I don't think this is an expected behaviour.

cc @zricethezav

**Comment by zricethezav** [comment]
@zac11 This is a false positive which is hard to avoid since we are just using regex for the twitter rule.  Feel free to use your own config where you tweak the twitter regex or add an entropy constraint. If you come up with a more accurate rule I'd be happy to review it in a PR
