### ISSUE TITLE
gitleaks not working with submodules "is a directory " error

### ISSUE THREAD

**Issue by Adnan0o7** [zricethezav/gitleaks#583]
**Describe the bug**
gitleaks local repo scan doesn't work with repos with submodules

**To Reproduce**
Scan a local repo with pre included git submodule
gitleaks -v --redact

**Expected behavior**
Should scan and return leaks or success 

**Basic Info (please complete the following information):**
 - OS: mac 11.2.3
 - Gitleaks Version: 7.5.0
- repo link: https://github.com/Adnan0o7/PyYelp

**Additional context**

cc @zricethezav

**Comment by leonitousconforti** [comment]
has this been fixed? The issue is closed but I am experiencing the same problem running gitleaks 7.6.0 installed from homebrew

**Comment by w0rmr1d3r** [comment]
Hello @leonitousconforti ,
It seems the issue got closed by its opener.
Can you provide more info about the bug?

Thank you!

**Comment by Adnan0o7** [comment]
> has this been fixed? The issue is closed but I am experiencing the same problem running gitleaks 7.6.0 installed from homebrew

> has this been fixed? The issue is closed but I am experiencing the same problem running gitleaks 7.6.0 installed from homebrew

This is not an issue, you can use the command below:
`gitleaks --path=./ --verbose --redact --repo-config-path=.gitleaks.toml`

This resolves the problem with submodules but it does not detect the secrets in uncommitted files (Both staged or unstaged).

**Comment by w0rmr1d3r** [comment]
Alright!
Thank you @Adnan0o7 !

Regarding `staged` and `unstaged`, there are other issues opened with that bug, we will try to fix them :)

**Comment by leonitousconforti** [comment]
Thank you @Adnan0o7 
That solved my problem
