### ISSUE TITLE
Node Module

### ISSUE THREAD

**Issue by leroux-p** [zricethezav/gitleaks#584]
I am trying to run gitleaks as part of "pre-commit" and I would like for this to run as an npm script so I can commit the node dependency.

I would like an npm package that allows me to inject gitleaks into my package,json.

cc @zricethezav

**Comment by zricethezav** [comment]
@leroux-p sounds cool, I don't plan on adding an npm package but feel free to do it yourself

**Comment by b12k** [comment]
Hello,

I had the same use case, so I created a slim npm wrapper around Gitleaks. It downloads the official binary for the current platform and exposes it as a local CLI command - everything else is plain gitleaks. No extra bells and whistles. 

- [npm package](https://www.npmjs.com/package/@b12k/gitleaks)
- [GitHub repository](https://github.com/b12k/gitleaks)

A big thank you to the Gitleaks maintainers for creating and maintaining such an important tool!
