### ISSUE TITLE
Staged not used in pre-commit

### ISSUE THREAD

**Issue by jkbszpg** [zricethezav/gitleaks#585]
**Describe the bug**
staged changes and not scanned by pre-commit after changing working directory

**To Reproduce**

```
$ git init
$ echo 'hello' > readme.md
$ git add readme.md
$ git commit -m "added readme.md"

$ echo "aws_access_key_id='AKIAIO5FODNN7EXAMPLE'" >> readme.md
$ git add readme.md
$ git commit -m "aws key"

# secret is detected and commit fails

# lets remove it from working directory but keep the original change in staged

$ echo 'hello' > readme.md
$ git commit -m "aws key"
INFO[0000] opening .
INFO[0000] scan time: 36 milliseconds 6 microseconds
INFO[0000] No leaks found
[master 54ae6d4] aws key
 1 file changed, 1 insertion(+)

# check history

$ git log -p
commit 54ae6d4c6054248b9f7ebc4e8d07f1dcc316f346 (HEAD -> master)
Date:   Tue Jun 29 10:26:39 2021 +0200

    aws key

diff --git a/readme.md b/readme.md
index ce01362..1c2a7a5 100644
--- a/readme.md
+++ b/readme.md
@@ -1 +1,2 @@
 hello
+aws_access_key_id='AKIAIO5FODNN7EXAMPLE'

```

**Expected behavior**
Stage version should be scanned and commit prevented

**Screenshots**

Status before commit that passes
```
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   readme.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   readme.md

$ git diff
diff --git a/readme.md b/readme.md
index 1c2a7a5..ce01362 100644
--- a/readme.md
+++ b/readme.md
@@ -1,2 +1 @@
 hello
-aws_access_key_id='AKIAIO5FODNN7EXAMPLE'
$ git diff --staged
diff --git a/readme.md b/readme.md
index ce01362..1c2a7a5 100644
--- a/readme.md
+++ b/readme.md
@@ -1 +1,2 @@
 hello
+aws_access_key_id='AKIAIO5FODNN7EXAMPLE'
```

**Basic Info (please complete the following information):**
 - OS: Windows 10, WSL Ubuntu 20.04.2 LTS
 - Gitleaks Version: v7.5.0

**Additional context**
pre-hook from examples/pre-commit.example

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @jkbszpg ,

Can this be the same bug found in https://github.com/zricethezav/gitleaks/issues/622 ?

Thank you

**Comment by jkbszpg** [comment]
I don't use '--unstaged' option in [pre-commit](examples/pre-commit.example),

my issue is - stage contains a secret that is detectable by rules
gitleaks will only find it if staged and workspace are the same,
if you stage a change with a secret and not have it in workspace during pre-commit-hook - it will be committed - seems like the wrong thing is scanned

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/blob/master/scripts/pre-commit.py likely fixes this
