### ISSUE TITLE
Supplement rules with actual password strings

### ISSUE THREAD

**Issue by eschrader** [zricethezav/gitleaks#586]
Hi,

I am using the leaky toml rules file to find my passwords. However, with some digging and removing false positives I have a list of about 60 passwords. How can I pass in these exact strings into TOML or a config file? I found some passwords while digging that were not in the original report. Regex is a bit too fluid. Can I add a rule without regex and just an escaped string?
```
[[rules]]
	description = "Exact Password Match"
	regex = '''P@s\$w0rd1'''
```
or multiple passwords on a single rule
`"password1","P@ssw0rd",etc.`

If I make up my own tags, would they be read correctly into the gitleaks scan? Example:
```
[[rules]]
	description = "Exact Password Matches"
	pwd1= '''P@s\$w0rd1'''
	pwd2= '''An0ther1'''
	pwd3= '''Puppies123'''
	pwd4= '''dontgooglecats!'''
```

**Comment by w0rmr1d3r** [comment]
Hello @eschrader !
Gitleaks should find those passwords for you, I guess, you shouldn't need those regex to find your passwords...
Are we missing some info here?

Cheers!

**Comment by eschrader** [comment]
Some weak passwords dont look like passwords, like a color or animal or persons name for example. If there I could add my exact strings as a rule, it would solve my issue. The tool detects a ton of the passwords, but mainly picked up the connection string for example as a leaky environment var but not a simple password in the string.

**Comment by eschrader** [comment]
I might have figured it out with my friends help, We can just copy the Generic Credential and file extension examples and replace the names with our escaped passwords.
`[[rules]]
	description = "Generic Credential"
	regex = '''(?i)(pass\$word|P@ssw0rd|small|longlonglonglong|andmoregohere)$'''`

**Comment by eschrader** [comment]
I was able to solve it, just use triple single quotes surrounding your string. Be sure to escape regex special characters with a single slash \, such as \$ for an actual $. I added each string to its own line,
```
[[rules]]
	description = "pwd1"
	regex = '''P@s\$w0rd1'''
[[rules]]
	description = "pwd2"
	regex = '''anotherpass'''
[[rules]]
	description = "pwd3"
	regex = '''pass@word'''
```
Thanks everyone!

**Comment by eschrader** [comment]
I was able to solve it, just use triple single quotes surrounding your string. Be sure to escape regex special characters with a single slash , such as $ for an actual $. I added each string to its own line,

```
[[rules]]
	description = "pwd1"
	regex = '''P@s\$w0rd1'''
[[rules]]
	description = "pwd2"
	regex = '''anotherpass'''
[[rules]]
	description = "pwd3"
	regex = '''pass@word'''
```
Thanks everyone!
