### ISSUE TITLE
Scan all repos of an organization

### ISSUE THREAD

**Issue by rubyman** [zricethezav/gitleaks#587]
Hi guys,

I can't find this feature. (maybe I didn't search enough!) I mean you get organization name from the user and scan all repositories' of that organization for any leaks.

example:
_gitleaks --org-name=github -v_

output:

found 27 repos.
Scanning repo 1 ...
Scanning repo 2 ..._

Thanks

cc @zricethezav

**Comment by fzipi360** [comment]
@rubyman Did you tried with `--github-org=....` ?

**Comment by GolanTrevize10** [comment]
That was possible before, but it looks like it was removed in version 7. I cannot see anything in the release notes.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v7.0.0 i aint supportin it no mo
