### ISSUE TITLE
Ability to ignore path

### ISSUE THREAD

**Issue by mustafaakin** [zricethezav/gitleaks#59]
I would really like ability to ignore paths

**Comment by zricethezav** [comment]
Could you elaborate on that please?

**Comment by keirans** [comment]
I am guessing that @mustafaakin would like to be able to specify filenames , or patterns of filenames that would be filtered from the results.

An example would be to remove matches if the file name or path contained '*example*.json or similar.
AWS SDK's often contain files containing sample API keys and other invalid secrets that cause positive results.

Hope this helps.

K

**Comment by mustafaakin** [comment]
Yes, I purposefully inject pseudo keys sometimes on specific paths for some evil copropate purpose, so ability to filter by regexes would be great

**Comment by zricethezav** [comment]
Added whitelist functionality in latest release
