### ISSUE TITLE
Gitleaks ignore new line character in rule regex section

### ISSUE THREAD

**Issue by cyrusmatsumori** [zricethezav/gitleaks#591]
**Describe the bug**
Trying to use regexp, which contain 'new line' character. Seems Gitleaks can't process it.

**To Reproduce**
1. Use Regexp to fing credentials in Gradle files: `'''(credentials).*?\n*.*?[username|password]\s*[:=]?\s*['\"]([0-9a-zA-Z-_]{3,32})['\"]'''`
2. Full rule description:
```
...
[[rules]]
    description = "Gradle credentials"
    regex = '''(credentials).*?\n*.*?[username|password]\s*[:=]?\s*['\"]([0-9a-zA-Z-_]{3,32})['\"]'''
...
```
3. Use below content of a file to analyze:
```
repositories {
    maven {
        url "http://repo.mycompany.com/maven2"
        credentials {
            username "user"
            password "pass"
        }
    }
}
```
4. Try to find credentials in the file. 
5. Result: No Leaks Found.

**Expected behavior**
As you may see [in regexp online emulation](https://regex101.com/r/poHeKv/1/), it had to find such string.

**Basic Info (please complete the following information):**
 - OS: OSX 10.15.7
 - Gitleaks Version: 7.5.0

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@cyrusmatsumori I do not have any plans to add multi-line support as determining line-numbers numbers is quite the task. If you want to fork and implement this feature yourself I'd be happy to review it.

**Comment by cyrusmatsumori** [comment]
Thanks for info.
Maybe it should be mentioned in the README.md **feature** section?
