### ISSUE TITLE
Plans on adding more regexes like Github scanning or Gitguardian scanning?

### ISSUE THREAD

**Issue by gps-drone** [zricethezav/gitleaks#599]
**Is your feature request related to a problem? Please describe.**
Not a problem, per se. But having more regexes to scan is always appreciated and really helpful.

**Describe the solution you'd like**
More exhaustive list of regexes like [github scanning](https://docs.github.com/en/code-security/secret-security/about-secret-scanning) or [gitguardian](https://docs.gitguardian.com/secrets-detection/detectors/specifics/index). 

**Describe alternatives you've considered**
Best option rn is looking at entropy strings. 

**Additional context**
Nothing.

cc @zricethezav

**Comment by zricethezav** [comment]
@gps-drone I will be more than happy to review PRs folks open that add to the default regexes provided they have an example key/token and matching rule. I do not have the resources/time to figure out all those rules on my own.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml **air horn sounds**
