### ISSUE TITLE
--commit-from and --commit-to flags don't work

### ISSUE THREAD

**Issue by emmahsax** [zricethezav/gitleaks#602]
**Describe the bug**
The `--commit-from` flag doesn't seem to work. If I run:

```
gitleaks --quiet --repo-url=https://github.com/emmahsax/test-repo --access-token=GITHUB-ACCESS-TOKEN --commit-from=LONG-COMMIT-SHA
```

It doesn't properly find the secret leaks that I'd expect it to find. On some examples, it seems continues to scan the entire project's complete history (but that could just be because I don't have the patience to parse long lines and lots of vulnerabilities). On some examples, it seems to work as the `commit-to` flag would work (as described in the README). AKA it grabs all leaks up until the `commit-from` SHA.

And then when using the `--commit-to` flag, it returns all leaks, the ones before _and_ after the SHA entered.

**To Reproduce**
1. Navigate to a test repository that has a few long-ago past secrets revealed and run:
```
gitleaks --quiet --repo-url=https://github.com/emmahsax/test-repo --access-token=GITHUB-ACCESS-TOKEN
```
2. In the same repository as before, grab a SHA that's a few commits past, and run:
```
gitleaks --quiet --repo-url=https://github.com/emmahsax/test-repo --access-token=GITHUB-ACCESS-TOKEN --commit-from=LONG-COMMIT-SHA
```
2. In the same repository as before, grab a SHA that's a few commits past, and run:
```
gitleaks --quiet --repo-url=https://github.com/emmahsax/test-repo --access-token=GITHUB-ACCESS-TOKEN --commit-to=LONG-COMMIT-SHA
```

**Expected behavior**
`--commit-to` should find vulnerabilities from the beginning of time up until the commit SHA date. `--commit-from` should find all vulnerabilities from the commit SHA date up until present.

**Screenshots**
With no commits passed (finds 5 vulnerabilities):
![image](https://user-images.githubusercontent.com/7562793/129593141-9335c50b-7be0-4fd2-9be8-38dca944bf82.png)

With `--commit-from` used (note the commit passed is dated 2021-06-01), but the vulnerabilities found are from 2020-11, meaning it's finding vulnerabilities from _before_ the commit SHA date, when it should find vulnerabilities from _after_ the date:
![image](https://user-images.githubusercontent.com/7562793/129593421-7983e918-e247-4287-99c0-f1351d66cfb4.png)

With `commit-to` used (finds 5 vulnerabilities, the same 5 as without any SHA passed at all), when it should only find past vulnerabilities:
![image](https://user-images.githubusercontent.com/7562793/129593246-ef363c7f-5ec6-4df5-995f-6ff1aa9762dc.png)

**Basic Info (please complete the following information):**
 - OS: MacOS
 - Gitleaks Version: 7.5.0

**Additional context**

cc @zricethezav

**Comment by emmahsax** [comment]
Ah. According to [this issue](https://github.com/zricethezav/gitleaks/issues/432#issuecomment-683782867), it seems that these flags have been deprecated in version 7.5.0:

> Thanks for bringing this bug up. There is some issues with `git log`s reachability in the `go-git` library. I'm thinking of deprecating `commit-from` and `commit-to` to be replaced with `--commit-range=<comma sep list of commits>`. Working on that right now, look for a 6.1.0 release with this shortly. I'll then update the gitleaks action

_Originally posted by @zricethezav in https://github.com/zricethezav/gitleaks/issues/432#issuecomment-683782867_.

I'll close this issue because it's expected behavior in this new version.

In another note, it'd be nice to have the documentation updated.

**Comment by w0rmr1d3r** [comment]
Hello @emmahsax , can you open a PR updating the documentation?

Thank you! :)

**Comment by emmahsax** [comment]
@w0rmr1d3r @zricethezav Here you go! https://github.com/zricethezav/gitleaks/pull/605

**Comment by w0rmr1d3r** [comment]
Thank you @emmahsax !
