### ISSUE TITLE
Pull image from ECR/GitHub Packages instead of Docker Hub

### ISSUE THREAD

**Issue by w0rmr1d3r** [zricethezav/gitleaks#608]
**Is your feature request related to a problem? Please describe.**
If I reach the Docker Hub rate limit I don't have any other option to use gitleaks from (remotely speakiing).
Since I'm using AWS with ECR, I'd like to pull directly my image from ECR instead of Docker Hub.
At the same time, could there be, instead of a public ECR, to use GitHub Packages?

**Describe the solution you'd like**
A public image in ECR o in GitHub Packages.

**Describe alternatives you've considered**
I found this -> https://gallery.ecr.aws/zomato/zricethezav/gitleaks
Is this the official for ECR?

**Additional context**
Thank you!

cc @zricethezav

**Comment by zricethezav** [comment]
Being added in v8 https://github.com/zricethezav/gitleaks/blob/v8/.github/workflows/release.yml#L28-L33

**Comment by zricethezav** [comment]
donzo

**Comment by bmbferreira** [comment]
👋 is the docker image being pushed to ECR? Seems it was removed ? 😕  can we have it again?
