### ISSUE TITLE
No difference when using --threads option with docker image

### ISSUE THREAD

**Issue by w0rmr1d3r** [zricethezav/gitleaks#609]
**Describe the bug**
I'm scanning a repo which takes aprox, 1min to get scanned.
I'm using gitleaks as follows:
```bash
docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" --no-git --verbose
```

And wanted it to perform better, so I came accross the `--threads` option ([from here](https://github.com/zricethezav/gitleaks/#usage-and-options)).
I used it many times with different values, but no different outcome in time it takes to scan the repo.

**To Reproduce**
1. execute it like this -> `docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" --no-git --verbose`
2. Try to increment the time by using it like this -> `docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" --no-git --verbose --threads=100`
3. Change the `100` value by any value, I put 10, 20, 100 and 1000.
4. No difference in time it takes to scan the repo.

**Expected behavior**
It should take less time to scan the repo, unless that option is only useful when using gitleaks outside Docker.

**Screenshots**
Forgot to take screenshots :(

**Basic Info (please complete the following information):**
 - OS: docker for mac, tried in different machines, same result, time it takes doesn't change
 - Gitleaks Version: latest docker image

**Additional context**
Shall I open a PR saying that the option is deprecated or only available outside docker? I searched for open/closed issues, found nothing related to this topic.

cc @zricethezav

**Comment by zricethezav** [comment]
@w0rmr1d3r if you are using Docker for mac you can throttle the number of CPUs dedicated to Docker. I'm curious if bumping the CPU value would fix your problem?

![Screen Shot 2021-09-02 at 10 20 23 AM](https://user-images.githubusercontent.com/15034943/131871015-fe58f04e-5af8-407d-87d4-8a43115b4bde.png)

**Comment by w0rmr1d3r** [comment]
Hello @zricethezav !
I actually did and nothing changed. I tried this locally, to see if I missed something, but I want it to work on my CI.
And there, it did the same, no changes even though I put more than 100 threads.
Always using docker.

Are we missing something?

**Comment by zricethezav** [comment]
@w0rmr1d3r I believe this is related to https://github.com/zricethezav/gitleaks/pull/619. 

> --nogit scans previously did not limit the number of goroutines being spun up so the --threads option was non functioning 😬. Because of this, the default behavior would essentially max out all available cpu resources assuming the target was large enough. Sorry bout that folks.

**Comment by w0rmr1d3r** [comment]
It is!
I ran some tests again and with the `--threads` option it decreases the time it takes!

Thank you!

Closing the issue

**Comment by w0rmr1d3r** [comment]
However, tested it in a Jenkins machine and got no significant changes.
Previously it took 1min 15sec, I forced to download latest (v7.6.0) and it takes 1min 14sec.

In my local it's showing progress, so I will say that it's limited to how Jenkins runs docker images
