### ISSUE TITLE
Anomaly in SARIF report

### ISSUE THREAD

**Issue by damiencarol** [zricethezav/gitleaks#610]
**Describe the bug**
SARIF1001: The two identity-related properties of a SARIF rule must be consistent. The required 'id' property must be a "stable, opaque identifier" (the SARIF specification ([3.49.3](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317839)) explains the reasons for this). The optional 'name' property ([3.49.7](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317843)) is an identifier that is understandable to an end user. Therefore if both 'id' and 'name' are present, they must be different. If both 'name' and 'id' are opaque identifiers, omit the 'name' property. If both 'name' and 'id' are human-readable identifiers, then consider assigning an opaque identifier to each rule, but in the meantime, omit the 'name' property.

**To Reproduce**
1. generate a report with `-f sarif` option

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
`ruleID` has been added to the sarif report. See https://github.com/zricethezav/gitleaks/blob/master/report/sarif.go#L47-L48

Closing issue

**Comment by damiencarol** [comment]
@zricethezav awesome!
