### ISSUE TITLE
Go not building/installing

### ISSUE THREAD

**Issue by arcsector** [zricethezav/gitleaks#62]
Hello, 

This is my first time installing a go repo. I did `sudo go get -u -v -t github.com/zricethezav/gitleaks` and it only came back with this response:

`github.com/zricethezav/gitleaks (download)`

So I'm not quite sure if I'm not building correctly or what else I could be doing wrong. My go version is 1.8.3 and I'm on linux/amd64 Ubuntu 17.10. Sorry about my incompetence!

And I did try installing the binaries but I'm not sure how to do those either.

**Comment by zricethezav** [comment]
You installed correctly and should be able to use `$ gitleaks` right out of the box. What happens when you  `$ which gitleaks`? You may need to add `GOPATH/bin` to your `PATH`:
`export PATH=$PATH:$GOPATH/bin`



how to use binaries (linux):
```
$ wget https://github.com/zricethezav/gitleaks/releases/download/v0.4.0/gitleaks-linux-amd64
$ chmod +x gitleaks-linux-amd64 && ./gitleaks-linux-amd64 --help
```

Let me know if that works/you have any confusion.

**Comment by arcsector** [comment]
Thank you so much for your help.

If I do `echo $GOPATH` it's `$HOME/go`, and if I do `echo $PATH` it's:

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin/:/bin:/usr/games:/usr/local/games:/snap/bin:$HOME/go/bin:/usr/local/go/bin`

It appears I have two go things. I can run individual scripts normally, but now whenever I type `gitleaks` it gives:

`$HOME does not exist`

For clarification, it doesn't literally say "$HOME", I'm just putting the variable there; it actually says my home directory spelled correctly.

**Comment by arcsector** [comment]
Maybe `$PWD/.git does not exist`? Also, thank you so much it super works. I can't wait to use this tool!
