### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#625]
**Describe the solution you'd like**
I'd like to go back to using a CHANGELOG.md to track changes. This will be the first step in updating the ci/cd process to increase the frequency of patches/deploys.  

**Additional context**
Go through https://github.com/zricethezav/gitleaks/releases and create a CHANGELOG.md file 

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Will take a look at it @danielorihuela !

Thank you 😄

**Comment by zricethezav** [comment]
Gonna close this issue, I dont want to keep a changelog since tags/releases keep track of the changes. reducing the amount of bookkeeping during the release process is a priority of mine
