### ISSUE TITLE
A how-to for first timers, for scanning full code or repository and setting up a git hook

### ISSUE THREAD

**Issue by soulcurrymedia** [zricethezav/gitleaks#629]
**Is your feature request related to a problem? Please describe.**

I have gone through the README and a couple of issues before writing this. I'm scanning a legacy repo and want to set up the hook for future commits. My expectation is to quickly scan the files are not all the commits to find leaks. I used this command and the below-given .gitleaks.toml file (which is at the root of the repo).

The expectation is to simply ignore the node_modules, .git, and .log files and scan the files for the leak. I think this would be the minimum for anyone trying `gitleaks` for the first time. I might be wrong on in config etc. 

```
gitleaks --path=. -v --no-git --report=gitleaks_results.csv --threads=2 -v --repo-config-path ".gitleaks.toml" --append-repo-config
```
and below in .gitleaks.toml
```toml
[whitelist]
  description = "global allowlists"
  files = [
    '(.*?)(jpg|gif)$',
    '(.*?)(doc|pdf|bin|log)$',
    '''(.*?)(node_modules)(.*?)''',
    '''(.*?)(log)(.*?)''',
    '''(.*?)(.git)(.*?)'''
    ]
  regexes = [
      '(.*?)gitleaks:allow'
  ]
```
**Describe the solution you'd like**
I suggest having a wiki that helps in quickly using this tool for the first scan of code and setting it up for later as a git hook.

**Describe alternatives you've considered**
Copied the code files, and removed tmp, node_modules, log, .git folders in a new directory and executed, the command given below and it was done for me.

```bash
gitleaks --path=. -v --no-git --report=gitleaks_results.csv --threads=2
```

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @soulcurrymedia ,

Have you read this section?
https://github.com/zricethezav/gitleaks#docker
Or tried some basic examples?
https://github.com/zricethezav/gitleaks#scanning

I believe what you are requesting already exists in the readme of the repo.
More precisely, you are doing this -> https://github.com/zricethezav/gitleaks#scan-local-directory
But with some custom options as well.

Cheers!

**Comment by katrinleinweber** [comment]
Hello @soulcurrymedia,

you're missing the `detect` command, I think ;-) `gitleaks detect --no-git` will essentially "quickly scan the files [but] not all the commits".

Cheers!

**Comment by zricethezav** [comment]
Closing this as the comments by @katrinleinweber sum up how to quickly get started. Additionally, better documentation has been added to the README

**Comment by huornlmj** [comment]
> Closing this as the comments by @katrinleinweber sum up how to quickly get started. Additionally, better documentation has been added to the README

In 2024 this is still not the case.  Struggling with simple ignore / whitelist concept.
