### ISSUE TITLE
Can we cut a release with symlink fix?

### ISSUE THREAD

**Issue by EliSchleifer** [zricethezav/gitleaks#632]
**Is your feature request related to a problem? Please describe.**
Symlink following for uncommitted files can we get that fix in a new dot release 

**Describe the solution you'd like**
Bump release to main 

**Describe alternatives you've considered**

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@EliSchleifer https://github.com/zricethezav/gitleaks/releases/tag/v.7.6.1 there ya go
