### ISSUE TITLE
Support go install to install gitleaks

### ISSUE THREAD

**Issue by massongit** [zricethezav/gitleaks#636]
https://golang.org/doc/go-get-install-deprecation

We should use `go install` because `go get`  in module mode is deprecated.
However, when I try to use `go install` to install gitleaks, I get the following error:

```
$ GO111MODULE=on go install github.com/zricethezav/gitleaks/v7@v7.6.1

go install: github.com/zricethezav/gitleaks/v7@v7.6.1 (in github.com/zricethezav/gitleaks/v7@v7.6.1):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by zricethezav** [comment]
Closing this. Cloning and building the binary is the preferred method. Feel free to open a PR if you want to add documentation on installing via go

**Comment by Aankhen** [comment]
Just to clarify for anyone following the issue, as I was a tad confused myself: while cloning and building might be the preferred method, <kbd>go install github.com/zricethezav/gitleaks/v8@latest</kbd> **does work** now (and, of course, so do versions like <kbd>v8@v8.0.3</kbd>). I believe @zricethezav is strictly referring to opening a PR to document this.
