### ISSUE TITLE
Scan for "secret_key"

### ISSUE THREAD

**Issue by ybabel** [zricethezav/gitleaks#64]
This should be added to scan beacause we can have some recaptcha_secret_key and stuff like that in the repositories.

**Comment by zricethezav** [comment]
you can extend that yourself with the `regex-file` option:
``` echo secret_key > ybabels_regex.txt && gitleaks --regex-file=ybabels_regex.txt {url}``` or something of that flavor

**Comment by zricethezav** [comment]
closing, reopen if that doesnt work for you @ybabel
