### ISSUE TITLE
v7.6.1 is tagged as v.7.6.1 in Docker Hub

### ISSUE THREAD

**Issue by ashokm** [zricethezav/gitleaks#641]
Release `v7.6.1` (see https://github.com/zricethezav/gitleaks/releases) is tagged as `v.7.6.1` (note the extra `.` after `v`) in Docker Hub (see https://hub.docker.com/r/zricethezav/gitleaks/tags)

cc @zricethezav

**Comment by zricethezav** [comment]
@ashokm thanks for pointing that out, pushing fix now

**Comment by zricethezav** [comment]
@ashokm https://hub.docker.com/layers/zricethezav/gitleaks/v7.6.1/images/sha256-66a8b46e267c4331b2902c7354ca6b31833603fbe35b9ab443c9b00d9ebee100?context=repo
