### ISSUE TITLE
Go installation fails

### ISSUE THREAD

**Issue by barrerajl** [zricethezav/gitleaks#646]
**Describe the bug**
When running `GO111MODULE=on go get github.com/zricethezav/gitleaks/v7` it fails with
```
build github.com/zricethezav/gitleaks/v7: cannot load embed: malformed module path "embed": missing dot in first path element
```

**To Reproduce**
Just try to install it

**Expected behavior**
Gitleaks should be installed

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: linux
 - Gitleaks Version: v7

**Additional context**

cc @zricethezav

**Comment by dustinsand** [comment]
What version of go are you using? The embed package is part of go1.16+

**Comment by barrerajl** [comment]
> What version of go are you using? The embed package is part of go1.16+

I can close the bug, it seems that new 7.6.1 needs go 1.16 but not before. (Should be stated in the version notes maybe?)

**Comment by noloader** [comment]
Add a mee too. We are working on Ubuntu 20, and it cannot build the tool.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

And:

```
$ apt-cache show golang
Package: golang
Architecture: amd64
Version: 2:1.13~1ubuntu2
Priority: optional
Section: devel
Source: golang-defaults
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
```

We use Ubuntu 20 because it is an approved image at the organization. Cutting over to Fedora 35 for Golang 1.16 is going to cause a fair amount of trouble for us. We need a security exception to run non-approved software and images. We will need to fast track it, so we have to go to a VP for approval.

Perhaps the GitLeaks team can consider supporting operating systems found in the field, like Ubuntu 18 and Ubuntu 20.

**Comment by zricethezav** [comment]
@noloader what are you asking

**Comment by zricethezav** [comment]
@noloader Golang 1.16 is out of the release cycle anyways https://github.com/golang/go/security/policy

> Perhaps the GitLeaks team can consider supporting operating systems found in the field, like Ubuntu 18 and Ubuntu 20.

Until very recently the "gitleaks team" has been just me. I do this in my free time, for free mostly.

> We will need to fast track it, so we have to go to a VP for approval.

Sounds important. If you want Gitleaks to be "buildable" on 1.16, I recommend you contact us via https://gitleaks.io/contact.html where we could explore a maintenance and support agreement.

**Comment by noloader** [comment]
Thanks @zricethezav.

I believe Go version is 1.13 (if I am parsing Apt output correctly). That's the version supplied by Ubuntu 20.

We ended up moving on to another tool. We don't have the time to invest into GitLeaks at the moment. Management wants a quick turnaround on the task the team is working on.

And great job on the tool. It looks very useful. I'm sorry we were not able to use it for this task.

**Comment by weineran** [comment]
For anyone else trying to build gitleaks on Ubuntu 20, you can remove old versions of go and install a later version like so:
```
rm -rf /usr/local/go && tar -C /usr/local -xzf go<version>.linux-amd64.tar.gz
```
Full instructions: https://go.dev/doc/install

If you just need to _use_ gitleaks on Ubuntu 20, you have some additional options:
* Use the gitleaks docker image: https://github.com/zricethezav/gitleaks#installing
* Download the appropriate gitleaks binary for your OS: https://github.com/zricethezav/gitleaks/releases

And, finally, shameless plug for the paid product, if you want to run gitleaks in your GitHub Actions CI/CD pipeline, checkout Gitleaks-Action:
* https://gitleaks.io/products.html
* https://github.com/gitleaks/gitleaks-action
