### ISSUE TITLE
docker run not detecting git repo

### ISSUE THREAD

**Issue by Jelzman** [zricethezav/gitleaks#648]
**Describe the bug**
The docker version of gitleaks doesn't detect any git repo properly, when using the --path flag. (Have not tried it with the --repo-url flag)

```
user % docker run --volume ${PWD}/repo:/repo \
--volume ${PWD}/scan:/scan --rm zricethezav/gitleaks:latest \
--path=/repo -v 
time="2021-09-29T19:32:36Z" level=debug msg="scanning repos in /repo\n"
time="2021-09-29T19:32:36Z" level=info msg="scan time: 3 milliseconds 68 microseconds"
time="2021-09-29T19:32:36Z" level=info msg="commits scanned: 0"
time="2021-09-29T19:32:36Z" level=info msg="No leaks found"
user % gitleaks --path=${PWD} -v
INFO[0000] opening redacted/repo
{ leak info here}
INFO[0000] scan time: 158 milliseconds 897 microseconds 
INFO[0000] commits scanned: 3                           
WARN[0000] leaks found: 6 
```

**To Reproduce**
Run these two commands and compare their output, when running on a local repo known to have secrets in it.

```
docker run --volume ${PWD}/repo:/repo \
--rm zricethezav/gitleaks:latest \
--path=/repo -v 

gitleaks --path=${PWD} -v
```
**Expected behavior**
I expected both commands to find the 6 leaks. Instead, the docker command doesn't see the git repo at all. 
**Screenshots**

**Basic Info (please complete the following information):**
 - OS: MacOS 11.6, CentOS 7.9
 - Gitleaks Version: latest (I believe that is 7.6.1)

**Additional context**

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @Jelzman !
That's weird... Can you try using `" "` on the `--path` option as it's shown here -> https://github.com/zricethezav/gitleaks#docker
That is, to run the command that doesn't work like this:
```
docker run --volume ${PWD}/repo:/repo \
--rm zricethezav/gitleaks:latest \
--path="/repo" -v 
```

Anyhow, if I'm not wrong, there's a difference between `--volume ${PWD}/repo:/repo` and `--path=${PWD}` isn't it?
Can you (when using the docker) go to the repo and use the volume like `--volume ${PWD}:/repo` instead?

Hope it works!
Thank you!

**Comment by Jelzman** [comment]
Let's say PWD=/u/username/project. In the project folder, there are a bunch of files, which are all checked into git, so there is also a .git file in the directory. Then the docker flag --volume ${PWD}:/repo mounts the directory project from the host OS to the directory /repo in the container. gitleaks runs in the container, so it can only see the container's filesystem. Therefore gitleaks must be given the path /repo. 

Mounting the volume ${PWD}/repo:/repo doesn't change anything important. It just maps the directory ${PWD}/repo from the host OS to the directory /repo on the container OS. 

What is really bizarre about this bug is that I know that gitleaks is seeing the right files. When I run the command 
```
docker run --volume ${PWD}/repo:/repo \
--rm zricethezav/gitleaks:latest \
--path="/repo" -v --no-git
``` 
gitleaks will scan the appropriate directory, and find leaks. 

So I am guessing that however gitleaks processes the .git file is failing on certain OS versions? In this case, MacOS and CentOS 7.

**Comment by zricethezav** [comment]
@Jelzman I don't really have a fix but maybe the new version fixes this issue? https://github.com/zricethezav/gitleaks#docker

**Comment by zricethezav** [comment]
closing this issue as it should be fixed in latest version
