### ISSUE TITLE
runtime: failed to create new OS thread (have 15 already; errno=11)

### ISSUE THREAD

**Issue by GolanTrevize10** [zricethezav/gitleaks#655]
**Describe the bug**
We are using the official gitleaks image for version 7.5.0. We are scanning thousands of repositories and sometimes we get an error like this

runtime: failed to create new OS thread (have 15 already; errno=11)

**To Reproduce**
Not sure how to reproduce it. Maybe it happens when a repository with a lot of commits is scanned. We are running this command
gitleaks --access-token=$token --config-path=custom.toml --leaks-exit-code=2 --format=json --report=${repo}.json -r https://mygitrepo/${repo} --threads=2

**Expected behavior**
No error is thrown

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Gitleaks docker image
 - Gitleaks Version: 7.5.0

**Additional context**

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @GolanTrevize10 !

It seems you are using an old version of gitleaks.
Currently gitleaks is on version `v7.6.1`:
https://github.com/zricethezav/gitleaks/releases/tag/v7.6.1

And version `v7.6.0` seems to fix some issues with the `--threads` option (which you are using).

Can you try using that newer version to see if the error still pops up?
Another thing that can be tested is to either modify the value passed to the `--threads` option or not use it at all?

Cheers!

**Comment by GolanTrevize10** [comment]
Hi, we solved already the issue. It has nothing to do with gitleaks but with some reused environment variables running several gitleaks scans in parallel
