### ISSUE TITLE
sometimes stucks at cloning if --repo-url passed

### ISSUE THREAD

**Issue by Dentrax** [zricethezav/gitleaks#666]
**Describe the bug**
I am not sure whether this is a bug or retry mechanism. In some cases or situations, gitleaks stuck at `cloning...` stage.

**To Reproduce**

```bash
$ gitleaks --report /tmp/report.json --repo-url GITHUB_REPO --leaks-exit-code 0 --no-git --access-token=ACCESS_TOKEN --clone-path=/tmp/foo --config-path /tmp/gitleaks.toml --debug --verbose
```

**Expected behavior**
It should not stuck at cloning stage?

I manually ran the `$ git clone ...` command to check if there are really any problem related to repo, but it cloned almost in a few seconds, whereas gitleaks awaits almost 5-6 mins in cloning stage.

**Screenshots**

![Screen Shot 2021-10-18 at 17 15 25](https://user-images.githubusercontent.com/16493751/137748697-2d46e346-19dd-419c-bebf-7c3381f83b96.png)

**Basic Info (please complete the following information):**
 - OS: `macOS 11`
 - Gitleaks Version: `7.6.1`

**Additional context**

Any ideas? Thanks! 🙏 

cc @zricethezav

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

Gitleaks v8.0.0 does not support cloning anymore

**Comment by asmaier** [comment]
I think the fact that gitleaks does not support cloning anymore and the rational behind it should be described in the Readme. 

It is really confusing to figure out that quite recent documentation of the usage of this tool e.g. 

https://computingforgeeks.com/gitleaks-audit-git-repos-for-secrets/ 

doesn't work anymore. To add to the confusion an option `--version` is not available anymore (see https://github.com/zricethezav/gitleaks/issues/773), so a user can only guess that the missing feature of cloning a repo  might be related to a newer version.
