### ISSUE TITLE
Update Slack Webooks to include Workflows

### ISSUE THREAD

**Issue by cribdragg3r** [zricethezav/gitleaks#669]
https://github.com/zricethezav/gitleaks/blob/5afe59d2fa53737d449729f01582cf28497dbc3c/config/gitleaks.toml#L118

This seems to work okay:

```text
https://hooks.slack.com/(?:services%7Cworkflows)/T[a-zA-Z0-9_]{8,10}/(?:A%7CB)[a-zA-Z0-9_]{8,12}(?:[/0-9]{19}%7C)/[a-zA-Z0-9_]{24}
```

**Comment by w0rmr1d3r** [comment]
Hello @cribdragg3r !

Feel free to open a PR with those changes 😄 

cheers!

**Comment by zricethezav** [comment]
Closing this issue as it is not describing an issue
