### ISSUE TITLE
Can't Install GitLeaks on Windows

### ISSUE THREAD

**Issue by Ketan987** [zricethezav/gitleaks#670]
**Describe the bug**
Hi,
I am trying to run exe file of GitLeaks ([Latest Version of GitLeaks](https://github.com/zricethezav/gitleaks/releases/download/v7.6.1/gitleaks-windows-386.exe)) on my windows machine but it's not working.

When I double tap and try to install nothing happens nor it get installed. 

**To Reproduce**
1) Download the exe file from windows ([Latest Version of GitLeaks](https://github.com/zricethezav/gitleaks/releases/download/v7.6.1/gitleaks-windows-386.exe)) 
2)  try to run exe file.

**Basic Info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprice
 - Gitleaks Version: v7.6.1

**Comment by mhazimaqlan** [comment]
@Ketan987 You don't need to install gitleaks on windows, you can just run gitleaks.exe file with CLI (command prompt or powershell)

**Comment by Ketan987** [comment]
Hi @mhazimaqlan 
I tried running `.exe` file with command prompt and PowerShell, did not work

![image](https://user-images.githubusercontent.com/35922826/141929279-f7fe41cb-35f9-4ef9-9f1f-f9d64e00c983.png)
 
 only screen just blinked once.
 I tried running with
start .\gitleaks-windows-amd64.exe

**Comment by mhazimaqlan** [comment]
try to run without "start" 
`PS C:\Users\Users\GitLeaks> ./gitleaks-windows-amd64.exe /help`

![image](https://user-images.githubusercontent.com/83561905/141951865-2ea984aa-116a-405f-92a4-64a4fa9bf203.png)

**Comment by Ketan987** [comment]
Hi @mhazimaqlan , @w0rmr1d3r ,

it is working.
Thank you. :-)

**Comment by w0rmr1d3r** [comment]
Hi @mhazimaqlan !

Can we add this "how-to" to the README.md ?

Thanks!
