### ISSUE TITLE
Pre-commit scan always returns "lineNumber": 2

### ISSUE THREAD

**Issue by blenolopes** [zricethezav/gitleaks#676]
**Describe the bug**
I'm using gitleaks (v.7.6.1) windows version x64 in git pre-commit (v2.33.1.windows.1) and the scan result always returns "lineNumber": 2.

**To Reproduce**
I'm using the pre-commit script with hooks.gitleaks true:
```
#!/bin/sh
gitleaksEnabled=$(git config --bool hooks.gitleaks)
cmd="C:/scanner/gitleaks.exe --verbose --config-path=C:/scanner/leaky-repo.toml"
if [ "$gitleaksEnabled" = "true" ]; then
    $cmd
    if [ $? -eq 1 ]; then
cat <<\EOF
--
-- sample drop message!
--
EOF
exit 1
    fi
fi
```

Sample source code with credential:

```
// hello world credential sample.
class HelloWorld {
    public static void main(String[] args) {

	// line with credential test.
	String password = "passwd123test";
		
        System.out.println("Hello, World!");
    }
}
```

In output report, "lineNumber" always returns 2... no matter where the line with the credential is. If on line 20, it returns 2. If on line 15, it returns 2.

```
{
        "line": "\t\tString password = \"passwd123test\";\r",
        "lineNumber": 2,
        "offender": "password = \"passwd123test\"",
        "offenderEntropy": -1,
        "commit": "0000000000000000000000000000000000000000",
        "repo": "test-repo",
        "repoURL": "",
        "leakURL": "",
        "rule": "Generic Credential",
        "commitMessage": "",
        "author": "",
        "email": "",
        "file": "tmp\\helloworld.java",
        "date": "1970-01-01T00:00:00Z",
        "tags": "key, API, generic"
}

````

**Expected behavior**
When the credential was found in line 15, the output would inform the "lineNumber": 15.

**Basic Info (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.19014
 - Gitleaks Version: v.7.6.1 (for windows, x64)
- Git version: v2.33.1.windows.1

**Additional context**
Would it be a bug?

cc @zricethezav

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

See new pre-commit hook example https://github.com/zricethezav/gitleaks/blob/master/scripts/pre-commit.py
