### ISSUE TITLE
provide `ignorelist` in the config file

### ISSUE THREAD

**Issue by Dentrax** [zricethezav/gitleaks#677]
**Is your feature request related to a problem? Please describe.**

To prevent and as decrease as possible the _false positives_, we might need to _ignore_ some directories or file extensions. To do that, `ignorelist` would be a great case in this scenario. We scanned over 1000 projects across entire internal git repositories by using _default_ config, the followings are what we have found mostly:

```
(378+ results from venv)
venv/lib/python3.8/site-packages/pip/_vendor/...
venv/lib/python3.9/site-packages/pip/_vendor/...

(435+ results from node_modules)
node_modules/aws-sdk/apis/sts-2011-06-15.examples.json (at line: 36) 

(675+ results from yarn.lock)
src/fragments/foo/1.0.0/yarn.lock (at line: 22)

(752+ results from yarn.lock)
yarn.lock (at line: 342)
```

**Describe the solution you'd like**
Provide a `ignorelist` like the [allowlist](https://github.com/zricethezav/gitleaks/blob/master/config/allowlist.go). We can follow the [gitignore](https://git-scm.com/docs/gitignore) standards to write ruleset.

```toml
[ignorelist]
  description = "Ignored files"
  files = ['''venv/lib''',
  '''node_modules''',
  '''vendor'''
  ]
```

Just using `allowlist` to cover all-ignore-cases may not a good scenario in this case since we need to cover all edge cases to prevent false-positives.

cc @zricethezav @developer-guy @kursatoguzhanakinci

**Comment by Dentrax** [comment]
Hey @tomdavidson, I forgot here! In case `.gitignore` file does not include in the repository, even I passed the `--no-git`, gitleaks still scans the vendor folders (i.e., `vendor`, `node_modules`, `venv`, etc.) and no behavioral change observed. So this is why we proposed the `ignorelist` key to override unwanted dirs/files on top level.

**Comment by zricethezav** [comment]
@Dentrax You can use the global allowlist to accomplish this. Setting `paths` to the files/directories you want to ignore will do the trick
```
# This is a global allowlist which has a higher order of precendence than rule-specific allowlists.
# If a commit listed in the `commits` field below is encountered then that commit will be skipped and no 
# secrets will be detected for said commit. The same logic applies for regexes and paths.
[allowlist]
description = "ignore commit A"
commits = [ "commit-A", "commit-B"]
paths = ['''one-file-path-regex''']
regexes = ['''one-regex-within-the-already-matched-regex''']
```

**Comment by sharath-sequoia** [comment]
@Dentrax, here's what worked for us:
gitleaks --path=. -v --no-git --additional-config=.gitleaks.toml

And that config file contains the paths to ignore as described by @zricethezav. It wasn't clear how to use it as additional config (instead of the only config). Running the gitleaks -h helped.

**Comment by Dentrax** [comment]
Nice! Should we add this usage scenario in the README? @zricethezav

**Comment by zricethezav** [comment]
@Dentrax Closing this as a `.gitleaksignore` feature as been added as well as better documentation in the README
