### ISSUE TITLE
porting the semgrep & github ruleset

### ISSUE THREAD

**Issue by Dentrax** [zricethezav/gitleaks#679]
**Is your feature request related to a problem? Please describe.**
I'm just coming from the [GitLab conversation](https://gitlab.com/gitlab-org/gitlab/-/issues/340002#note_671440863) to drop an issue for the GitHub side, so we do not forget!

**Describe the solution you'd like**
Determine which secrets from the [semgrep ruleset](https://github.com/returntocorp/semgrep-rules/tree/develop/generic/secrets/security) would be worthwhile to include. Porting the semgrep rules to gitleaks rules is simple since they are mostly just regex.

**Describe alternatives you've considered**

@Taylor4484 have dropped a nice reference:
> GitHub has kindly also provided a list of these API key slugs here:
https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#about-secret-scanning-for-private-repositories

cc @zricethezav @developer-guy @kursatoguzhanakinci

**Comment by zricethezav** [comment]
Thank you @Dentrax, the most recent version of Gitleaks introduced 60+ new secrets. Adding new secrets will be a top priority for the project moving forward
