### ISSUE TITLE
Doesn't work with submodules as a pre-commit hook: `is a directory` error

### ISSUE THREAD

**Issue by infokiller** [zricethezav/gitleaks#682]
**Describe the bug**
This is the same as https://github.com/zricethezav/gitleaks/issues/583 which was closed but not fixed.
It mentions a workaround, but it doesn't work for uncommitted files.

**To Reproduce**

With docker:

```sh
docker run --rm --interactive --tty --entrypoint=bash zricethezav/gitleaks -c 'cd /home/gitleaks && mkdir repo && cd repo && git init && git submodule add https://github.com/zricethezav/gitleaks sub && gitleaks .'
``````

Manually:

- Create repo with submodules
- Run `gitleaks .`

**Expected behavior**
Not failing, whether scanning the submodule or not.

**Basic Info (please complete the following information):**
 - OS: `Linux 5.14.14-hardened1-1-hardened`
 - Gitleaks Version: `7.6.0`

**Additional context**

cc @zricethezav
cc @w0rmr1d3r

**Comment by w0rmr1d3r** [comment]
Hello @infokiller 

Is it giving the same error with `v7.6.1`?

Thank you

**Comment by infokiller** [comment]
Yes:

```
❯ docker run --rm -i --entrypoint=bash zricethezav/gitleaks <<'EOF'
  gitleaks --version
  cd /home/gitleaks && mkdir repo && cd repo
  git -c init.defaultBranch=master init
  git submodule add https://github.com/zricethezav/gitleaks sub
  gitleaks .
EOF

v.7.6.1
Initialized empty Git repository in /home/gitleaks/repo/.git/
Cloning into '/home/gitleaks/repo/sub'...
time="2021-11-14T20:52:31Z" level=info msg="opening ."
time="2021-11-14T20:52:31Z" level=info msg="scan time: 2 milliseconds 372 microseconds"
time="2021-11-14T20:52:31Z" level=error msg="read /home/gitleaks/repo/sub: is a directory"
```

**Comment by w0rmr1d3r** [comment]
Thank you @infokiller !
I might be missing something, regarding the documentation -> https://github.com/zricethezav/gitleaks#usage-and-options
You are using gitleaks such as `gitleaks .` but it needs options

What am I missing?

**Comment by infokiller** [comment]
Is `gitleaks .` not a valid usage of gitleaks? Options are not required, right?
Can you please show me a command that works with a submodule in that docker command?
Thanks

**Comment by infokiller** [comment]
BTW, my use case it to run gitleaks in a git precommit hook. I want it to run on the staged changes that are about to be committed, but nothing else (for example if there's another file in the repo that is not staged in that commit, gitleaks shouldn't analyze it). If there is a better way to use gitleaks for this I would be happy to learn about it.

**Comment by w0rmr1d3r** [comment]
Well, for that particular case, you can:

https://github.com/zricethezav/gitleaks#as-a-pre-commit-hook

Or for unstaged changes:
https://github.com/zricethezav/gitleaks#scan-unstaged-changes

See if it helps :)

**Comment by infokiller** [comment]
I don't use pre-commit (I use a custom bash script) so it's not relevant for me. But even if I did use it, I don't understand why it would work and still fail in the simple docker command I posted above.

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

In v8 you can provide the flag `--log-opts="--submodule=log"` to scan submodules.
