### ISSUE TITLE
Announcement: v8.0.0 changes

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#683]
# v8.0.0
Gitleaks v8.0.0 introduces some breaking changes and feature removals. My vision for gitleaks is for the project to
follow the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) -- do one thing and one thing well. 
That one thing is detecting secrets efficiently.

Sorry if this causes any inconveniences. You can always fork. 

### What's changed
- Swapped `go-git` for shelling out `git log -p` and `git diff` commands when scanning/protecting git repos
    - See comparison [metrics/chart](https://github.com/zricethezav/gitleaks/issues/683#issuecomment-969168273) for why this is a good thing (hint its more eco friendly 🌎 🍃 )
    - Memory Usage from running gitleaks on the [rails](https://github.com/rails/rails) repo: **54MB -> 8.5MB**
    - Simplified call stack
    - Faster scans 
- Added `detect`, `protect`, `help`, and `version` commands to reduce number of options
- Support for multiline regular expressions in rules
- Added `StartLine`, `EndLine`, `StartColumn`, `EndColumn` to report findings
- Added `RuleID` to report findings
- CLI powered by `spf13/cobra`
- Removed `repo-config` support
    - This can be scripted 
- Default config path added `(--source/-s)/.gitleaks.toml`, see usage for more details
- Removed cloning support
    - I do not want gitleaks to be responsible for cloning repositories
- Removed `files at commit` support
    - This can be accomplished by `git checkout`
- Removed all `commit` options
    - All commit options can be supported by the `--log-opts` argument. `--log-opts` accepts any `git log` options.
- All log messages sent to stderr
- Finding output (enabled with `-v`/`--verbose`) sent to stdout.
    - This can be paired with `jq` to do additional filtering
- **Added 60+ rules** to best maintain parity with https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#about-secret-scanning-for-private-repositories

--- 
See https://github.com/zricethezav/gitleaks/tree/v8 for WIP

Feedback welcomed

**Comment by zricethezav** [comment]
### Left Gitleaks v7.6.1 | Right Gitleaks v8.0.0
Running against the gitleaks repo... more details to come

![Screen Shot 2021-11-10 at 1 22 09 PM](https://user-images.githubusercontent.com/15034943/141830478-3111e32c-6b9c-424a-83e4-1a2c840594cb.png)

![Screen Shot 2021-11-10 at 1 21 56 PM](https://user-images.githubusercontent.com/15034943/141830491-eb2c26e3-36c0-4a37-a683-286869121d60.png)

**Comment by scottschreckengaust** [comment]
Added a minor PR for the `Description` to the output as many `RuleID` values are not present yet in the default #699

**Comment by zricethezav** [comment]
@pab1it0 is there anything I need to do regarding the gitleaks precommit? The new pre-commit script for v8 is https://github.com/zricethezav/gitleaks/blob/v8/scripts/pre-commit.py

**Comment by zricethezav** [comment]
@chenrui333 since you have so graciously been helping out with keeping the brew formula up to date, is there anything that needs to be done to make sure brew has gitleaks v8.0.0 available?
