### ISSUE TITLE
Object Not Found or Invalid delta

### ISSUE THREAD

**Issue by shawnz88** [zricethezav/gitleaks#685]
**Describe the bug**
When running gitleaks in Azure DevOps self hosted agent with flag **files-at-commit=latest**, it returns the error **Object Not Found** or **Invalid delta**

**To Reproduce**
D:\Agents\mybuildserver-Agent5\_work\_tool\gitleaks\7.6.1\x64\gitleaks-windows-amd64.exe --path=D:/Agents/mybuildserver-Agent5/_work/3074/s --report=D:/Agents/mybuildserver-Agent5/_work/_temp/gitleaks-report-0578feb5-60b2-7747-335a-af7998b23871.json --config-path=D:/Agents/mybuildserver-Agent5/_work/_tasks/Gitleaks_62320d4f-5d0e-4cff-bd09-435719e41878/1.2.34/configs/UDMSecretChecks.toml --verbose --files-at-commit=latest

**Expected behavior**
Return the leaks found in code.

**Screenshots**

time="2021-11-05T08:39:36-05:00" level=info msg="scan time: 16 seconds 232 milliseconds 756 microseconds"
time="2021-11-05T08:39:36-05:00" level=error msg="invalid delta"

time="2021-11-04T13:00:57-05:00" level=info msg="opening D:/Agents/mybuildserver-Agent5/_work/3074/s\n"
time="2021-11-04T13:01:13-05:00" level=info msg="scan time: 16 seconds 232 milliseconds 944 microseconds"
time="2021-11-04T13:01:13-05:00" level=error msg="object not found"

**Basic Info (please complete the following information):**
 - OS: Windows x64
 - Gitleaks Version: 7.6.1

**Additional context**
For the same application, scan with version gitleaks 7.5.0 works as expected and doesn't return any of these two errors.

cc @zricethezav

**Comment by asaini11** [comment]
@shawnz88 I have just submitted a similar issue https://github.com/zricethezav/gitleaks/issues/686 although we've not seen `Invalid delta`

**Comment by w0rmr1d3r** [comment]
Hello @shawnz88 

It seems to me that the error is quite straight forward.

This:
`--path=D:/Agents/mybuildserver-Agent5/_work/3074/s` 
doesn't exist...

Need more info.

Thank you
