### ISSUE TITLE
Private Repositories - API Token

### ISSUE THREAD

**Issue by mikailtunc** [zricethezav/gitleaks#69]
Hello!
First I'd like to express my thanks for this awesome project so thank you :)

Is there a reason why I cannot search private repos after providing gitleaks with a read-only API token? It still asks me for my github.com username and password after passing in my --token.

e.g., command:

./gitleaks --temp --token=<token> --verbose --org https://github.com/myOrg

**Comment by zricethezav** [comment]
This issue will be fleshed out in the next version of gitleaks. This might be broken. I'll take a look and get back to you

**Comment by zricethezav** [comment]
Released new version, please follow examples in the wiki and try now
