### ISSUE TITLE
Gitleaks reports "LinkedIn Client ID" errors on some public LinkedIn profiles

### ISSUE THREAD

**Issue by gmacario** [zricethezav/gitleaks#694]
**Describe the bug**

I have a Markdown file which contains links to people profiles on LinkedIn.
Some of those links are reported as errors even though their profile can be browsed anonymously.

**To Reproduce**

Inside an empty directory create a file `test.md` with the following contents:

```text
# Test gitleaks

Testing some LinkedIn profiles:

* [Gianpaolo Macario](https://www.linkedin.com/in/gmacario)
* [Olivier Charra](https://www.linkedin.com/in/oliviercharra)

<!-- EOF -->
```

then commit the file to git and run gitleaks inside a container

```bash
git init
git add -A
git commit -m "Add file"
docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo"
```

**Expected behavior**

I would expect that no leaks are reported.

**Screenshots**

Actual result from executing the commands listed above:

```text
gmacario@gmpowerhorse:~/tmp/test-linkedin (master)$ docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" -v
time="2021-11-14T16:22:10Z" level=info msg="opening /my-repo\n"
{
        "line": "* [Olivier Charra](https://www.linkedin.com/in/oliviercharra)",
        "lineNumber": 6,
        "offender": "linkedin.com/in/oliviercharra",
        "offenderEntropy": -1,
        "commit": "e3ea3c0692c5d10a727a0bb332332fd8701566cd",
        "repo": "my-repo",
        "repoURL": "",
        "leakURL": "",
        "rule": "LinkedIn Client ID",
        "commitMessage": "Add file\n",
        "author": "Gianpaolo Macario",
        "email": "gmacario@gmail.com",
        "file": "test.md",
        "date": "2021-11-14T17:22:01+01:00",
        "tags": "client, LinkedIn"
}
time="2021-11-14T16:22:10Z" level=info msg="scan time: 1 millisecond 514 microseconds"
time="2021-11-14T16:22:10Z" level=info msg="commits scanned: 1"
time="2021-11-14T16:22:10Z" level=warning msg="leaks found: 1"
gmacario@gmpowerhorse:~/tmp/test-linkedin (master)$
```

**Basic Info (please complete the following information):**
 - OS: Ubuntu Server 20.04.3 LTS 64-bit
 - Gitleaks Version: Docker latest

**Additional context**

N.A.

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @gmacario !
I'm a little bit confused, you say first:
`Some of those links are reported as errors even though their profile can be browsed anonymously.`
I understand that gitleaks shouldn't report the links as a leak.
Yet, then you say:
`I would expect to leaks found.`
Which is actually what's happening.

If you want gitleaks *not* to report those links as a leaks you can always use an Allowlist, explained here:
https://github.com/zricethezav/gitleaks#example-4-using-allowlist-regex

I can see you pointed this issue to another one -> https://github.com/github/super-linter/issues/2129
Pointing to this file -> https://github.com/github/super-linter/blame/main/TEMPLATES/.gitleaks.toml#L56-L59

gitleaks is behaving as it should.

From here, possible solutions:
1. As said earlier, create an allowlist
2. If this has to do with the file pointed in that other issue, it's not an issue with gitleaks, but with that other repo instead

Cheers!

**Comment by gmacario** [comment]
> Hello @gmacario !

Hello @w0rmr1d3r, thank for your quick reply.

> I'm a little bit confused, you say first: `Some of those links are reported as errors even though their profile can be browsed anonymously.` I understand that gitleaks shouldn't report the links as a leak. Yet, then you say: `I would expect to leaks found.` Which is actually what's happening.

I actually made a typo when in my previous comment I wrote what I would expect.
I just edited my comment to state "I would expect that no leaks are reported".

More specifically, I could not understand why the second URL in my test file is reported

```text
"offender": "linkedin.com/in/oliviercharra"
```

while the first URL is not.

> If you want gitleaks _not_ to report those links as a leaks you can always use an Allowlist, explained here: https://github.com/zricethezav/gitleaks#example-4-using-allowlist-regex

Thanks for the hint, I will re-read it carefully and try to whitelist the false positives.

I should confess I am relatively new to gitleaks which I just came to know was invoked by [Super-Linter](https://github.com/github/super-linter) in some of my git repositories.

> I can see you pointed this issue to another one -> [github/super-linter#2129](https://github.com/github/super-linter/issues/2129) Pointing to this file -> https://github.com/github/super-linter/blame/main/TEMPLATES/.gitleaks.toml#L56-L59

This is more the other way round. I mean: Super-Linter uses gitleaks, but as far I can tell the used gitleaks.toml looks exactly the same as the one available here in <https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml>.
By the way, the test case I provided does not invoke Super-Linter but directly the official Docker container of gitleaks.

Best regards,
Gianpaolo

**Comment by w0rmr1d3r** [comment]
Perfect @gmacario !

Closing the issue since it can be solved with an allowlist.

Cheers!
