### ISSUE TITLE
Archive gitleaks .exe binary files into zip (blocked when downloading exe file)

### ISSUE THREAD

**Issue by mhazimaqlan** [zricethezav/gitleaks#695]
**Is your feature request related to a problem? Please describe.**
I'm pulling download link from GitHub Releases to download gitleaks for windows but unable to download .exe file due to internet policy. The policy is blocking internet request to download exe files.

**Describe the solution you'd like**
https://github.com/zricethezav/gitleaks/releases/tag/v7.6.1
Would be great if you could provide additional release assets in zip file for windows environment by archive the gitleaks-windows-386.exe / gitleaks-windows-amd64.exe into zip file. 

**Additional context**
Direct download URL from GitHub: https://github.com/zricethezav/gitleaks/releases/download/v7.6.1/gitleaks-windows-386.exe 

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @mhazimaqlan !

Can you try downloading the source code and compile it?
What about using Docker?

Cheers!

**Comment by mhazimaqlan** [comment]
@w0rmr1d3r,

Yes I can do to that on my machine (download and compile the source code). But, this is not the best solution for other people who can't compile the source code. For instance, an application that download gitleaks during runtime by fetching the download link from the release in github. In my case, the internet policy is blocking any request to download exe files on windows, so I'm thinking if the exe file is zipped, then we can extract the file after download it.

**Comment by zricethezav** [comment]
@mhazimaqlan I'm switching the release process to goreleaseer which will provide a zip in the v8 release

**Comment by zricethezav** [comment]
zips are available in https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0
