### ISSUE TITLE
--verbose

### ISSUE THREAD

**Issue by jaikishantulswani** [zricethezav/gitleaks#70]
--verbose switch giving error 
2018/06/11 17:34:15 cannot clone https://github.com/xxx into /root/go/src/gitleaks/xxx

**Comment by BondAnthony** [comment]
@jaikishantulswani could you provide mode detail? This works for me and I'm running off of source.

**Comment by jaikishantulswani** [comment]
@BondAnthony,
it stuck on cloning the repo while using it with -v -o

./gitleaks -v -o https://github.com/xyz
2018/06/18 17:16:48 cloning https://github.com/xyz/abc.git into /root/go/src/gitleaks/abc...
2018/06/18 17:16:48 cannot clone https://github.com/xyz/abc.git into /root/go/src/gitleaks/abc

**Comment by jaikishantulswani** [comment]
Hello @BondAnthony, 
Sorry for bothering you, it works fine after removing the old binary and installing the new again, one more thing could you please let me know how we can add more signatures.
