### ISSUE TITLE
Recent regex update too greedy

### ISSUE THREAD

**Issue by julianoborba** [zricethezav/gitleaks#700]
**Describe the bug**
[Updated rule](https://github.com/zricethezav/gitleaks/blob/714c0bef1e953710c039deb6e15a0bdd5f6ed532/config/gitleaks.toml#L11) `(?i)aws_(.{0,20})?=?.[\'\"0-9a-zA-Z\/+]{40}` match the follow string in a terraform file:

```
40 }
41 
42 data "aws_iam_policy_document" "SecretsManagerRDSPostgreSQLRotationSingleUserRolePolicy" {
43   statement {
44 
```

```
{
  "line": "data \"REDACTEDleUserRolePolicy\" {",
  "lineNumber": 42,
  "offender": "REDACTED",
  "offenderEntropy": -1,
  "commit": "XXXX",
  "repo": "XXXX",
  "repoURL": "",
  "leakURL": "",
  "rule": "AWS Secret Key",
  "commitMessage": "XXXX",
  "author": "XXXX",
  "email": "XXXX",
  "file": "XXXX",
  "date": "2021-09-01T08:14:33-03:00",
  "tags": "key, AWS"
 }
```

**To Reproduce**
Scan a terraform script file containing
```data "aws_iam_policy_document" "SecretsManagerRDSPostgreSQLRotationSingleUserRolePolicy" {```

**Expected behavior**
No match, it's not a AWS Secret Key.

**Screenshots**
Not applicable.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Gitleaks Version: v.7.6.1

**Additional context**
Maybe remove `\'\"` from `[\'\"0-9a-zA-Z\/+]` should be enough. Don't need to seek for quotation marks as delimiters.

But a sanity check is needed, and want to discuss first with community, understand if it really is a bug.

Thank you for that very nice tool :).

cc @zricethezav

**Comment by zricethezav** [comment]
@julianoborba I actually deleted this rule in the latest version of gitleaks. I will be providing community contribution guidelines and best practices on how to submit new rules soon. AWS needs to be revisited

**Comment by julianoborba** [comment]
Thank you very much.

**Comment by agonzalez-plume** [comment]
Just updated from 7.6.1 to latest master and my regex's are really greedy now. Almost the entire file is being detected in each run.  Before 1Mb json output file w/842 detections, now 47Mb output file w/42 detections.  

What's the new trick for regex's?

**Comment by zricethezav** [comment]
@agonzalez-plume what rule is bloating the report?

**Comment by agonzalez-plume** [comment]
Can't say my regex is perfect, I have a .* in there, and a pretty liberal [\x20-\x7e], as well as a not expression for anything except '*'
encryption[\\]+",.*[\\]+"key[-\d+]*[\\]+",[\\]+"[\x20-\x7e][^*]+[\x20-\x7e][\\]+.*]]]

**Comment by zricethezav** [comment]
@agonzalez-plume having a `.*` means all bets are off as I'm not limiting the output by character length like I was before

**Comment by alangonzalez** [comment]
Yeah, like most regexes there a couple of other ways I can write it.  Will take a look at making it simpler.

**Comment by agonzalez-plume** [comment]
An update, it wasn't the .*, it was the [^*].  It's gobbling up the characters.  To fix, I added to not like closing brackets too (since it's a section delimiter for my text) -> [^*\]] and now it's detecting it the same as 7.6.1
