### ISSUE TITLE
CLI support for ignoring rules

### ISSUE THREAD

**Issue by adamdecaf** [zricethezav/gitleaks#709]
**Is your feature request related to a problem? Please describe.**
I'm seeing some false positives after attempting an upgrade to v8.0.2. 
Example: https://github.com/moov-io/infra/pull/233 

```
{
	"Description": "Generic API Key",
	"StartLine": 133,
	"EndLine": 133,
	"StartColumn": 18,
	"EndColumn": 49,
	"Context": "                key = \"transit-local-base64-key\"",
	"Secret": "key = \"transit-local-base64-key\"",
	"File": "modules/customers/deployment.tf",
	"Commit": "",
	"Entropy": 3.8553886,
	"Author": "",
	"Email": "",
	"Date": "",
	"Message": "",
	"Tags": [],
	"RuleID": "generic-api-key"
}
```

**Describe the solution you'd like**
A solution like [shared config files](https://github.com/zricethezav/gitleaks/issues/596) could work, but it would also work to support CLI arguments when ignoring default rules.

**Describe alternatives you've considered**
`generic-api-key` could be made a bit more robust. I could also ignore some `*.tf` files, but that could expose secrets in the future. 

cc @zricethezav

**Comment by zricethezav** [comment]
@adamdecaf as a stop-gap I removed the generic rule in https://github.com/zricethezav/gitleaks/releases/tag/v8.0.5. I left it commented in the default config in case folks want to enable it.

**Comment by adamdecaf** [comment]
Sounds good, thanks!
