### ISSUE TITLE
Sarif schema version is set to v8.0.0, should be 2.1.0 

### ISSUE THREAD

**Issue by JoostVoskuil** [zricethezav/gitleaks#712]
Tested on Gitleaks v8.0.3:
When --format=sarif is provided to Gitleaks a sarif report is generated. 
The version information of the schema is set to V8.0.0 while it should be 2.1.0. This leads to an incorrect sarif report

**Output from Gitleaks V7.6.x:**
 "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
 "version": "2.1.0",

**Output from Gitleaks v8.0.3:**
 "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
 "version": "v8.0.0",

**Comment by JoostVoskuil** [comment]
Proposed fix at #713

**Comment by zricethezav** [comment]
released in v8.0.4
