### ISSUE TITLE
Errors Running in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by MichaelDenwood** [zricethezav/gitleaks#718]
**Describe the bug**
When Running version 8.0.4 from an Azure DevOps build pipeline, the following errors are generated:
`8.0.4

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

1:05PM DBG No gitleaks config found, writing default gitleaks config to F:\Agents\SaaSProdW2\_work\1656\s\.gitleaks.toml
1:05PM DBG executing: F:\Agents\SaaSProdW2\externals\git\cmd\git.exe -C F:\Agents\SaaSProdW2\_work\1656\s log -p -U0 --full-history --all
{
[**This section removed**]
}
1:05PM ERR error: cannot spawn astextplain: No such file or directory
1:05PM ERR fatal: unable to read files to diff`

**To Reproduce**
Create a Yaml Pipeline in Azure DevOps as shown below:

`trigger:
- main

pool: 
  name: default
  demands:
   - agent.os -equals Windows_Nt
steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_MYUSERNAME'
    userRepository: 'zricethezav/gitleaks'
    defaultVersionType: 'latest'
    itemPattern: '*x64.zip'
    downloadPath: '$(Agent.ToolsDirectory)\gitleaks'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Agent.ToolsDirectory)\gitleaks\*.zip'
    destinationFolder: '$(Agent.ToolsDirectory)\gitleaks'
    cleanDestinationFolder: false
    overwriteExistingFiles: true
- task: CmdLine@2
  inputs:
    script: |
      $(Agent.ToolsDirectory)\gitleaks\gitleaks.exe version
      $(Agent.ToolsDirectory)\gitleaks\gitleaks.exe detect --source $(Build.SourcesDirectory) --verbose --redact -f sarif -r $(Common.TestResultsDirectory)\SecretScanning.sarif -l debug
`

**Expected behavior**
`    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

{
[**This section removed**]
}
[90m11:52AM[0m [31mWRN[0m leaks found: 3
[90m11:52AM[0m [32mINF[0m scan completed in 10.021199s`

**Basic Info (please complete the following information):**
 - OS: Azure DevOps Agent is Windows Server 2016
 - Gitleaks Version: 8.0.4

cc @zricethezav

**Comment by zricethezav** [comment]
Hi @MichaelDenwood, I unfortunately don't have a azure pipeline to test on or a windows machine. Looks like this error is something to do with the way git is configured based on the discussions on this stackoverflow post https://stackoverflow.com/questions/60371641/git-error-cannot-spawn-more-no-such-file-or-directory

This issue is likely an issue with git configuration, not gitleaks.

**Comment by JoostVoskuil** [comment]
Can you run the same pipeline on an hosted agent? I believe 2016 is still available at the moment but It will be gone in a couple of weeks. If 2016 hosted does not work, can you try on a Windows 2019 machine?

**Comment by MichaelDenwood** [comment]
Thanks to both @zricethezav  and @JoostVoskuil  for the troubleshooting tips.  These helped lead me to the solution.

For anyone else with this issue:

1.) This only occurs on Self-Hosted agents (because MS-Hosted agents already have the solution in place systemwide)
2.) The self-hosted agent is attempting to use its own distribution of GIT (Agent.HomeDirectory\externals\git).  If you drill down into the Agent.HomeDirectory\externals\git\usr\bin folder you will see astextplain does not exist.  This explains why we have the error running the command.
3.) Your self-hosted agent most likely has Git For Windows installed and if not please install it.  The solution to the issue is to instruct Azure DevOps to use the OS Git For Windows instead of the Git provided by the agent.  To do this, add a variable to your pipeline called **system.prefergitfrompath** and set the value to **true**.  This is how the MS-Hosted agents work.

reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml
