### ISSUE TITLE
Note: Gitleaks rewrite coming

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#72]
Hey all,

First of all, thanks for all the support. I'll be honest - I made gitleaks as an exercise to learn Go so it's a pretty novice code base. Since then I've learned some things and am working on a rewrite that will add some cool features such as branch and PR targeting, as well as support for any remote target (gitleaks will no longer be github specific when cloning remote). Additionally, I'm making use of src-d's go-git plumbing to make the audits quicker with an 'in-memory' option -- no more shelling out `git x` commands. 

I'd like to open the floor for feature requests here. Shout out to @keirans who has already come up with some features:

- externalizing regex
- cleaner options
- white listing commits
- regex matching on commit messages

Please add a comment if there is a feature you would like to see in the next gitleaks version

**Comment by keirans** [comment]
Hey @zricethezav ,
Looking forward to version 2, I think we have all learnt a bit about how to scan git repos via this tool, and i really do appreciate you releasing your work, it has helped me quite a bit.

Here are my thoughts on some enhancements that could make the tool even better, i've put a bit of deail in place below to help flesh them out as features for development to make things easier for you.

* Externalizing regex 
As mentioned, the fact that the expression logic is contained within the code means that small changes mean a new build of the binary. If we can solve this by storing the search patterns into a configuration file it would make the user experience much better, especially with those using the docker images, where they can use the latest official builds of the tool, but bring their own configuration file.

* Regex matching on commit messages
Being able to search for specific patterns in commit messages could also help identify possible bad practices in the development phase. These would ideally be externalised into a different configuration file or section of a centralised gitleaks configuration file.

* White listing features 
One feature I implemented myself in my own wrapper was the ability to filter out certain SHA hashes from results if they were encountered in gitleaks results. This would be a nice feature to have, as would a feature to be able to whitelist files in repos, such as README.md , or *.example.

* Performance options (Threading concurrency)
I found the performance quite good, however I think you will find that your rewrite using a dedicated go library even faster, which will be great. What would be great is to have some of the configuration of the concurrency and other attributes (ie, memory usage for in memory scanning) exposed and configurable if required. This would be great for scanning large amounts of data in AWS environments where you have access to large servers with lots of RAM.

* Branch scanning support
Currently the tool supports only scanning of the master branch of a cloned repo.
Having a boolean to turn on/off non master branch scanning (or scan only a set of branches that match a pattern) would be a huge win.

* Clean, well documented options 
Happy to help with this, the more documentation the better, as well as some example use cases.

* Report file options (YAML / JSON / Summary Text / Scanning time in the report ?)
I think we'll find the report structure in v1 needs to evolve, especially when we are going to be adding scanning of messages, and commits.

Being able to output the results in a number of other formats (JSON / YAML) would be a big win.
It would also be great to return performance metrics associated with the scan in the same result, such as time it took to scan and maybe even the start / finish dates in UTC.

Looking forward to helping where i can and taking it for a spin :)

K

**Comment by zricethezav** [comment]
@keirans as always, thanks so much for the detailed responses. 

I think I hit most of the items. Need to do a little more testing but opening a PR so folks can begin to track the changes: https://github.com/zricethezav/gitleaks/pull/74

**Comment by keirans** [comment]
Looking forward to checking out the first release.

One other thing I missed is following Semver for all releases and tagging each release for easier release management and bug reporting.

This will help with docker image labelling as well.

:)

**Comment by zricethezav** [comment]
@keirans if you wanna play around:
`docker run zricethezav/gitleaks:gitleaksv1 gitleaks --help`

**Comment by zricethezav** [comment]
Closing this, I will open issues for all the items that I missed. v1.0.0 released
