### ISSUE TITLE
Exit code is 0 on unknown flag error

### ISSUE THREAD

**Issue by PSanetra** [zricethezav/gitleaks#720]
Gitleaks v8.0.4 exits with code 0 when it detects an unknown flag although it just prints an error message.

**To Reproduce**
* Execute `gitleaks --non-supported-flag`
* Then output the exit code via `echo $?`

**Expected behavior**
* Gitleaks prints `Error: unknown flag: --non-supported-flag`
* The exit code should not be `0`

**Actual behavior**
* Gitleaks prints `Error: unknown flag: --non-supported-flag`
* The exit code is `0`

**Basic Info:**
 - OS: Linux (Docker Image)
 - Gitleaks Version: v8.0.4

cc @zricethezav

**Comment by zricethezav** [comment]
good catch

**Comment by zricethezav** [comment]
fixed in https://github.com/zricethezav/gitleaks/releases/tag/v8.0.5
