### ISSUE TITLE
Not finding passwords anymore?

### ISSUE THREAD

**Issue by codekuu** [zricethezav/gitleaks#721]
**Describe the bug**
I ran the exact same command two days ago and got a report on my fake project.
Tried again today without any success.

Never changed anything in the gitleaks config, always used the auto generated one.

Gitleaks output:
```
fake-project-with-fake-secrets-in-it$ gitleaks detect --verbose --log-level debug

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

10:51AM DBG Using existing gitleaks config .gitleaks.toml
10:51AM DBG executing: /usr/bin/git -C . log -p -U0 --full-history --all
10:51AM DBG 3 commits scanned. Note: this number might be smaller than expected due to commits with no additions
10:51AM INF no leaks found
10:51AM INF scan completed in 194.852746ms
```

The commit where the passwords are:
```
fake-project-with-fake-secrets-in-it$ git show 4a65fa90508250cbf9494e2bee41dc7d49bd4fc7
commit 4a65fa90608150cbf5494e3bee41dc7d49bd4fc7 (HEAD, origin/main, origin/HEAD, main)
Author: XXXXXXXXXXXXXX
Date:   Wed Nov 24 10:29:36 2021 +0100

    Committing passwords

diff --git a/app/api/dependencies/authentication.py b/app/api/dependencies/authentication.py
index 7a3b101..e463e45 100644
--- a/app/api/dependencies/authentication.py
+++ b/app/api/dependencies/authentication.py
@@ -107,7 +107,7 @@ async def _get_current_user_optional(
 ) -> Optional[User]:
     if token:
         return await _get_current_user(repo, token, settings)
-    super_password_hardcoded_WHAAT = "TokenIsNotP4assw0rd_rick_r0o0o0lleeed"
+    super_password_hardcoded_WHAAT = "TokenIsNotP4assw0rd_r1ck_r0o0o0lleeed"

diff --git a/app/api/routes/authentication.py b/app/api/routes/authentication.py
```

Cat'ing the file to show that passwords are actually there.
```
fake-project-with-fake-secrets-in-it$ grep -r "password=\|password_" *  | grep "\""
app/api/dependencies/authentication.py:    super_password_hardcoded_WHAAT = "TokenIsNotP4assw0rd_r1ck_r0o0o0lleeed"
app/api/routes/authentication.py:            password="WhatDontReturnTheP4SSw0RD",
app/api/routes/authentication.py:            password="123AliceInTheWonderLandWasHere45671",

```

**To Reproduce**
None in particular.

**Expected behavior**
Should receive 3 passwords found. 

**Screenshots**
X

**Basic Info (please complete the following information):**
 - OS: Linux Mint 20.0
 - Gitleaks Version: 8.0.4

**Additional context**
No specific comments, just wondering why it doesn't work. Any ideas?

cc @zricethezav

**Comment by zricethezav** [comment]
@codekuu 
Post your config file and provide a repo for me to reproduce this with. 

Note that I removed the [generic rule](https://github.com/zricethezav/gitleaks/commit/172459102961fc34d334093a59769bb968176f7e) from the default config since it was detecting lots of duplicate keys. If you cloned and built the gitleaks binary since that commit then it would make sense why you are not detecting these secrets.

**Comment by codekuu** [comment]
Hi @zricethezav  sorry for the late response. Yes it works now, thanks for what ever you did!👯‍♂️
