### ISSUE TITLE
Broken Link for default config in README

### ISSUE THREAD

**Issue by billabongrob** [zricethezav/gitleaks#725]
https://github.com/zricethezav/gitleaks/blob/5e51da600b5f6c08e5a02bc50a3147941db41825/README.md?plain=1#L212

**Describe the bug**
The link to the default config in the readme file results in a GitHub 404 not found error.  

**To Reproduce**
Click link "gitleaks config" on line 212 

**Expected behavior**
Takes me to a default config:  https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml 

**Basic Info (please complete the following information):**
 - OS:  N/A
 - Gitleaks Version:

**Additional context**
N/A

cc @zricethezav

**Comment by zricethezav** [comment]
fixed, thanks @billabongrob
