### ISSUE TITLE
Does not work correctly with the flag (--commit-since) when using the other flag (--branch)

### ISSUE THREAD

**Issue by galazat** [zricethezav/gitleaks#728]
When using the flag (--commit-since) without the flag (--branch), everything works correctly. Scans 'commits' that are newer than the date. Request example:
[# gitleaks --path=<some-path> --config-path=rules.html --verbose --report=report.on --commit-sense='2021-09-01' ]

But when you add the flag (--branch), the program starts scanning all the 'commits', from the newest to the very first. Request example:
[# gitleaks --path=<some-path> --config-path=rules.html --verbose --report=report.on --commit-sense='2021-09-01' --branch=master ]

Info:
- gitleaks version = v.7.6.1
- OS = Linux 5.4.0-90-generic #101-Ubuntu SMP GNU/Linux

**Comment by zricethezav** [comment]
Hi @galazat I am not supporting bug fixes on releases prior to v8. Sorry for the inconvenience

**Comment by galazat** [comment]
Yes, of course I understand. Thanks for the great product anyway)
