### ISSUE TITLE
Document How Configuration Works

### ISSUE THREAD

**Issue by paul-m** [zricethezav/gitleaks#732]
**Describe the bug**

I have a gitleaks.toml file in each of my repos.

They no longer work with gitleaks 8.x.

I modify them to be more like the default configuration.

They still don't work, because they have a lot of false positives and they ignore the allow lists.

Now I have .gitleaks.toml files everywhere, too because gitleaks is being helpful.

I take the hint and move my toml files to be dot files.

Still no joy, because gitleaks doesn't seem to care.

The CLI documentation for `-c` says I need a `.gitleaks.toml/gitleaks.toml` file. I waste some time on making that file, and then realize it's not actually a path, but poor documentation.

So: How?

Thanks.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@paul-m you are right, the documentation is wrong.

it should be 
```
config file path
order of precedence: 
1. --config/-c 
2. (--source/-s)/.gitleaks.toml
if --config/-c is not set and no (--source/s)/.gitleaks.toml present 
then .gitleaks.toml will be written to (--source/-s)/.gitleaks.toml for future use`

```

**Comment by paul-m** [comment]
Right, that's still completely unclear.

What's the distinction between a `-c` and an `-s`?

**Comment by zricethezav** [comment]
- `-c` is the path to a config `-c/--config`
- `-s/--source` is the path to the source, aka what is being scanned

**Comment by zricethezav** [comment]
Fixed in https://github.com/zricethezav/gitleaks/commit/9358e845883077591b8d4107c452d7aa70cd60ab and https://github.com/zricethezav/gitleaks/commit/958c18f0b721e125da5a4c5e25a6bbce0ea629ea.

Closing this issue but feel free to continue discussing in case it's still not clear.
