### ISSUE TITLE
Unable to ignore paths with --no-git and --source .

### ISSUE THREAD

**Issue by nvuillam** [zricethezav/gitleaks#737]
**Describe the bug**

Unable to ignore paths with --no-git and --source .
I tried with regexes, path, files... but I didn't succeed to have a folder ignored ... maybe it's just a toml config error ?

This issue has been detect while integrating gitleaks within [MegaLinter](https://megalinter.github.io/v6-alpha/descriptors/repository_gitleaks/), for the next major version (v6)

**To Reproduce**

Have a folder `.automation/test` with files in error within

.gitleaks.toml config:

```toml
[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports'''
    ]
    files = ['''^\.?gitleaks.toml$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']
```

call: `gitleaks detect -c .gitleaks.toml --no-git --verbose --source .`

Error can be seen in [this Github action log](https://github.com/megalinter/megalinter/runs/4414155191?check_suite_focus=true) (filter log on `[gitleaks]` )

**Expected behavior**
No error because `.automation/test` should be ignored

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Linux alpine
 - Gitleaks Version: `zricethezav/gitleaks:latest` docker image

cc @zricethezav

**Comment by llaville** [comment]
Issue confirmed here locally with 
- OS: Ubuntu 18.04 LTS
- Docker: 20.10.11, build dea9396

Strange, because I've a local git clone of my project. I've also tried with sudo without any results.

All info in screenshot

![gitleaks_detect](https://user-images.githubusercontent.com/364342/144699740-7036d66f-671b-440c-926b-a2903508a9df.png)

**Comment by nvuillam** [comment]
@llaville i had this problem too, it's not exactly the one I describe ^^ For your case, I think that using `--source /path` will do the job... then bring you to my problem :)

**Comment by llaville** [comment]
@nvuillam No way 😕, relative or absolute path give me the same results

![gitleaks](https://user-images.githubusercontent.com/364342/144705511-8dde3075-39da-4c41-82c9-3a36fba0dcda.png)

**Comment by zricethezav** [comment]
@llaville please open another issue. The one you are describing is not related to the one @nvuillam opened.

**Comment by zricethezav** [comment]
@nvuillam I'm unable to reproduce this

[![asciicast](https://asciinema.org/a/453618.svg)](https://asciinema.org/a/453618)

**Comment by zricethezav** [comment]
And fwiw, this is the bit of code that prevents allowlisted files from being scanned: https://github.com/zricethezav/gitleaks/blob/master/detect/detect.go#L23-L26

**Comment by nvuillam** [comment]
@zricethezav I use absolute path for config file, maybe it changes something ? 

`[gitleaks] command: ['gitleaks', 'detect', '-c', '/github/workspace/.gitleaks.toml', '--no-git', '--verbose', '--source', '.']`

**Comment by zricethezav** [comment]
@nvuillam If you run the command with `--log-level=debug` you will be able to see what config is being used

**Comment by nvuillam** [comment]
Thanks, i'll do that and keep you posted :)

**Comment by llaville** [comment]
@nvuillam Something like
```
docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --source /path/src -l debug

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

4:05PM DBG No gitleaks config found, writing default gitleaks config to /path/src/.gitleaks.toml
4:05PM DBG executing: /usr/bin/git -C /path/src log -p -U0 --full-history --all
4:05PM DBG 329 commits scanned. Note: this number might be smaller than expected due to commits with no additions
4:05PM INF no leaks found
4:05PM INF scan completed in 361.7316ms
```

**Comment by nvuillam** [comment]
@zricethezav I have better results, I succeeded to ignore paths, but now it's... .gitleaks.toml files that don't succeed to ignore :/ ( I tried with regexes and files )

I have several .gitleaks.toml files in the repo

Any tip ? )

Config:

```toml
[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''']
    regexes = ['''(.*?)gitleaks\.toml$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']
```

job:

https://github.com/megalinter/megalinter/runs/4418273978?check_suite_focus=true

**Comment by zricethezav** [comment]
@nvuillam please reference the configuration example in the readme: https://github.com/zricethezav/gitleaks#configuration 

Your config is wrong. If you want to ignore `.gitleaks.toml`s you need to add that to your `allowlist.paths`. This probably should be the default behavior which I'll open a PR for that soon.

So something like:
```
[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''',
    '''.gitleaks.toml''']
```

**Comment by nvuillam** [comment]
I looked in gitleaks own gitleaks.toml... and we have regExp in `regexes` and in `paths` ... that's not crystal clear, I think that documentation should contain more examples to avoid other users to be lost like I've been ^^

Also, if `paths` can contain regex, how is it possible that a dot is sometimes recognized as a dot without escape character (ex: `'''.automation/test'''`), or as a dot with escape character ( ex: `'''(.*?)gitleaks\.toml$'''`  ) ? 

Anyway... finally working with the config below (that could be used as example in your doc ^^) , thanks a lot for your help ! :)

```toml
[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''',
    '''(.*?)gitleaks\.toml$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']
```
