### ISSUE TITLE
Ability to merge / extend / append the default config

### ISSUE THREAD

**Issue by jantari** [zricethezav/gitleaks#741]
**Is your feature request related to a problem? Please describe.**

I want to be able to change/override just a few settings from the default configuration for our needs without the need to keep and maintain a copy of the entire settings for gitleaks locally.

As per #740 that is currently not possible, specifying a custom configuration file always fully replaces all configuration.

**Describe the solution you'd like**

Being able to extend and partially override the default config with one or more custom configuration files.
I don't have a specific preference for how this should be implemented, unfortunately I am not even that familiar with TOML and whether it offers any syntax or capabilities that would be useful for this. I would perhaps expect that TOML go libraries already provide this capability?

There would have to be a way for someone to append to a list such as `[[rules]]` but also to replace it entirely or update/overwrite only an individual rule by id. Similarly there are tables such as `[allowlist]` where someone might want to add to the default `paths =[]` list rather than repalce it, as it is currently not possible to simply define multiple `[allowlist]` sections.

**Describe alternatives you've considered**

dumping the current default config with `mkdir empty && gitleaks detect -s ./empty` then trying to edit together the config we'd want with a tool like [dasel](https://github.com/TomWright/dasel) prior to running `gitleaks detect` for real.

**Additional context**

Follow up on #740

cc @zricethezav

**Comment by k0ral** [comment]
Would you consider adopting [Dhall](https://dhall-lang.org/) as a configuration file language ?
It has an active [Golang binding](https://github.com/philandstuff/dhall-golang) and, I believe, would essentially answer all refactoring/modularity needs for `gitleaks` configuration.

**Comment by derekmurawsky** [comment]
I am +1 ing this. This functionality previously existed with the `--additional-config` CLI option. We were integrating gitleaks into our CI/CD process and were relying on this functionality to allow development teams to manage an exception list. I would either like that old capability back, or the ability to merge configs as noted by @zricethezav here https://github.com/zricethezav/gitleaks/issues/740#issuecomment-987966379.

Conversely, there is a use case where strict teams may not want to allow exceptions. That can probably be supported by specifying the config file as a cli argument, thus ignoring a developer supplied .gitleaks file.

**Comment by zricethezav** [comment]
@jantari @derekmurawsky the ability to extend and override the default config has been available since https://github.com/zricethezav/gitleaks/releases/tag/v8.9.0. Closing issue
