### ISSUE TITLE
No ARM Release After v8.0.0

### ISSUE THREAD

**Issue by rodrigoramosrs** [zricethezav/gitleaks#743]
**Describe the bug**
There are no arm version after v8.0. The latest version with arm build is v7.6.1

cc @zricethezav

**Comment by zricethezav** [comment]
@rodrigoramosrs good call, i'll add this back in next release. this was an unfortunate casualty from switch my ci/cd setup

**Comment by zricethezav** [comment]
@rodrigoramosrs https://github.com/zricethezav/gitleaks/releases/tag/v8.1.3 here you go
