### ISSUE TITLE
to support scan remote github repos

### ISSUE THREAD

**Issue by leoxhj** [zricethezav/gitleaks#748]
**Is your feature request related to a problem? Please describe.**
For some reason, organization in github need scan all their repos for code security.

**Describe the solution you'd like**
Parameters to support scan remote github repos

for example:
```bash
# scan one repo
gitleaks --remote-repo git@github.com:<org>/<repo_name>.git --github-token 123456

# scan multiple repos
gitleaks --file repos.txt -github-token 123456 --parallel-no=10 --branch=[main, develop]

repos.txt include all repos you want scan (better use multiple threads, say if there are 100 repos, scan 10 parallel. 
also would be better if we can choose which branches to scan, say if we have 10 branches, we only want for main, develop branches, if --branch not present (by default), then scan all branches. 

output would be like:

output/repos/repo_name_a
output/repos/repo_name_b
......
output/reports/repo_name_a.json
output/reports/repo_name_b.json
......
```
@zricethezav

**Comment by zricethezav** [comment]
hi @leoxhj as stated in the v8 announcement I do not want gitleaks to be responsible for cloning repos. A simple script similar to the one presented here https://github.com/zricethezav/gitleaks/pull/667/files would do the trick
