### ISSUE TITLE
Different results 

### ISSUE THREAD

**Issue by dineshchand1984** [zricethezav/gitleaks#755]
**Describe the bug**
scan the same code, with release 7.2.1 and 8.2.1.
Both give out different results.

**To Reproduce**
Scan the same code with 7.2.1 and 8.2.1 release

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:Linux
 - Gitleaks Version: 7.6.1 & 8.2.1

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@dineshchand1984 not a bug, many changes have gone into gitleaks between v7.2.1 and v8.2.1 including a new config with 70+ new rules

**Comment by dineshchand1984** [comment]
But why old leaks ( with release 7.2.1 ) are not getting detected in 8.2.1.
e.g. "offender": "AIDAAAAAAAAAAAAAAAAA" was a leak in 7.2.1 as "rule": "AWS Access Key" but no more in 8.2.1>

**Comment by zricethezav** [comment]
@dineshchand1984 part of the AWS rules were unintentionally dropped but have been readded in https://github.com/zricethezav/gitleaks/commit/f4d37a2c0d9892bdffb4c61093a06767e4a33504. 

Those changes will go out in the next release.

You can always roll your own config if you don't like the defaults.
