### ISSUE TITLE
Gitleaks can't handle files with CRLF terminated lines

### ISSUE THREAD

**Issue by mickutz** [zricethezav/gitleaks#762]
**Describe the bug**
When scanning files with CRLF terminated lines gitleaks will not detect secrets.

**To Reproduce**

- Create a new file and add a secret to it. Check that end of line sequence is set to LF first. In VSCode it's indicated in the bottom bar on the right hand side.
Running a scan will detect the secret.
- Change end of line sequence to CRLF and save the file.
Running a scan now will not return any wanings.

**Expected behavior**
Gitleaks should return warnings for files with CRLF.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 21.10
 - Gitleaks Version: v8.2.5

cc @zricethezav

**Comment by zricethezav** [comment]
@mickutz It's because of https://github.com/zricethezav/gitleaks/blob/master/detect/files.go#L54-L56. That check has caused some issues elsewhere so probably best to just remove it. Allowlist filtering can be the responsibility of the user
