### ISSUE TITLE
Running "protect" scripts via Husky pre-commit hook fails on Windows with CRLF line endings

### ISSUE THREAD

**Issue by JPStrydom** [zricethezav/gitleaks#766]
**Describe the bug**
When running `protect` via a pre-commit hook using husky, it fails with errors:
```
ERR warning: CRLF will be replaced by LF in xxx
ERR The file will have its original line endings in your working directory
...
husky > pre-commit hook failed (add --no-verify to bypass)
```

Running the `protect` script manually works, it only fails in pre-commit hooks.

My `package,json`:
```
...
  "scripts": {
    ...
    "scan-secrets:protect:windows": "docker run -v %cd%:/path zricethezav/gitleaks:latest protect --source=\"/path\" -v -c /path/gitleaks.toml",
    ...
  }
...
```

**To Reproduce**
Run the `protect` script on a project in the Windows file system as a Husky pre-commit hook. 

My `huskyrc.js`:
```
module.exports = {
  hooks: {
    'pre-commit': 'docker run -v %cd%:/path zricethezav/gitleaks:latest detect --source=\"/path\" -v -c /path/gitleaks.toml",'
  }
};
```

**Expected behavior**
The commit should pass if no secrets are present.

**Screenshots**
![image](https://user-images.githubusercontent.com/25905330/148740065-1acaed84-276d-4936-91bb-10518d0e20fb.png)

**Basic Info (please complete the following information):**
 - OS: Windows 10 Pro (Build 19044.1415)
 - Gitleaks Version: 8.2.7 (used via `docker run zricethezav/gitleaks:latest`

cc @zricethezav

**Comment by JPStrydom** [comment]
Just to clarify, the `protect` scripts works when running it in isolation. It only fails when running in a Husky pre-commit hook. See this output below where I first run the script manually and then via a pre-commit hook (I've hilighted the scripta steps in yellow)
![image](https://user-images.githubusercontent.com/25905330/148756147-06d683eb-f4d5-441b-8e98-65a1105877a7.png)

**Comment by zricethezav** [comment]
@JPStrydom this error is coming from `git`. What happens when you run `git log -p`? I also don't know what Husky and don't claim to support it. Sounds like this issue should be opened for Husky. Closing this.

**Comment by JPStrydom** [comment]
Husky is just a pre commit tool. Regular pre commit hooks (as you specify in your readme) gives the same issue. Will have a look at the git issue, but if your tool is causing pre-commit hooks on Windows, it might be worth checking out.

**Comment by JPStrydom** [comment]
For those looking for a sollution/workaround - manually changing the line endings on all files to `LF` fixed the issue for me. Still wish they could add a propper fix for this, because the manual change can be quite tedious.

**Comment by zricethezav** [comment]
Try messing with the git config

from https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace

```
Formatting and Whitespace

Formatting and whitespace issues are some of the more frustrating and subtle problems that many developers encounter when collaborating, especially cross-platform. It’s very easy for patches or other collaborated work to introduce subtle whitespace changes because editors silently introduce them, and if your files ever touch a Windows system, their line endings might be replaced. Git has a few configuration options to help with these issues.
core.autocrlf

If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas macOS and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.

Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem. You can turn on this functionality with the core.autocrlf setting. If you’re on a Windows machine, set it to true — this converts LF endings into CRLF when you check out code:

$ git config --global core.autocrlf true

If you’re on a Linux or macOS system that uses LF line endings, then you don’t want Git to automatically convert them when you check out files; however, if a file with CRLF endings accidentally gets introduced, then you may want Git to fix it. You can tell Git to convert CRLF to LF on commit but not the other way around by setting core.autocrlf to input:

$ git config --global core.autocrlf input

This setup should leave you with CRLF endings in Windows checkouts, but LF endings on macOS and Linux systems and in the repository.

If you’re a Windows programmer doing a Windows-only project, then you can turn off this functionality, recording the carriage returns in the repository by setting the config value to false:

$ git config --global core.autocrlf false


```
