### ISSUE TITLE
Scan on precommit still not working

### ISSUE THREAD

**Issue by IyotakeTatanka** [zricethezav/gitleaks#767]
The precommit scan is not working. Therefore secrets are getting committed.

This is not working [video](https://asciinema.org/a/455683).
I am using husky to run gitleaks as pre-commit hook:

```
"husky": {
    "hooks": {
      "pre-commit": "gitleaks detect -c gitleaks.toml -v"
    }
  },
```

**Comment by zricethezav** [comment]
I don't know what husky is and you haven't provided any details. Closing this issue.
