### ISSUE TITLE
Error when running git push : git:2: = not found on MacOS

### ISSUE THREAD

**Issue by JensVanhulstSolita** [zricethezav/gitleaks#768]
**Describe the bug**

1. Installed gitleaks with : `brew install gitleaks`
2. Created config file : https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
3. Run Gitleaks with : `gitleaks detect -s . -v -c ~/gitleaks-config.toml && git exitloop "$@"`

**BUG** :
Installing gitleaks brakes the `git push` command and produces the following error: 

<img width="615" alt="Screenshot 2022-01-11 at 11 12 22" src="https://user-images.githubusercontent.com/91960333/148923690-57d45180-e122-48cf-932e-078a49a42eaa.png">

**To Reproduce**
Followed the getting started

**Expected behavior**
Complete the push

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Mac Os Big Sur 11.6.1
 - Gitleaks Version: 8.2.7
 - Git version : 2.34.1
 - Homebrew version : 3.3.9

cc @zricethezav

**Comment by zricethezav** [comment]
I'm unable to reproduce this. I would guess something funky is going on with your $PATH

**Comment by JensVanhulstSolita** [comment]
Magically started working after a restart. Closing now.
