### ISSUE TITLE
Out Of Memory issue is seen during 'commit'

### ISSUE THREAD

**Issue by bj185023** [zricethezav/gitleaks#770]
**Describe the bug**
Out Of Memory error is seen during commit.

**To Reproduce**
Executing 'commit' is throwing Out Of Memory error.

**Basic Info (please complete the following information):**
 - OS: Win10
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by bj185023** [comment]
*** pre-commit ***
HooksPath=C:\Work\GitHub_Source\finplat-tools-shared\git-hooks
WorkingDir=/c/Work/GitHub_Source/finplat-feature-pcusbtch_1
Running gitleaks with default config C:\Work\GitHub_Source\finplat-tools-shared\git-hooks/gitleaks-ncr-config.toml
time="2022-01-13T11:25:39+05:30" level=info msg="opening .\n"
runtime: out of memory: cannot allocate 394264576-byte block (989691904 in use)
fatal error: out of memory

goroutine 1 [running]:
runtime.throw(0x8ba4d4, 0xd)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:1117 +0x64 fp=0x142e6990 sp=0x142e697c pc=0x4b32f4
runtime.(*mcache).allocLarge(0x1500088, 0x1761c000, 0x100, 0x48b59e)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/mcache.go:226 +0x250 fp=0x142e69c0 sp=0x142e6990 pc=0x4946d0
runtime.mallocgc(0x1761c000, 0x0, 0x0, 0x4c6413)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/malloc.go:1078 +0x738 fp=0x142e6a08 sp=0x142e69c0 pc=0x48b898
runtime.rawruneslice(0x5d86d31, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/string.go:291 +0xa8 fp=0x142e6a28 sp=0x142e6a08 pc=0x4c9fe8
runtime.stringtoslicerune(0x142e6bd0, 0x14480000, 0xb43384c, 0x1, 0x2, 0x13e04000)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/string.go:190 +0x116 fp=0x142e6a50 sp=0x142e6a28 pc=0x4c9ac6
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCleanupMerge(0x142e702c, 0x13caa000, 0x1, 0x1, 0x35400000, 0x5d86d31, 0x5d87000)
        /Users/zacharyrice/Go/pkg/mod/github.com/sergi/go-diff@v1.1.0/diffmatchpatch/diff.go:1013 +0xcd4 fp=0x142e6cd0 sp=0x142e6a50 pc=0x66faa4
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).diffMainRunes(0x142e702c, 0xb9cf1c, 0x0, 0x0, 0x35400000, 0x5d86d31, 0x5d87000, 0x539e0500, 0x539e05e4, 0xc0700da5, ...)
        /Users/zacharyrice/Go/pkg/mod/github.com/sergi/go-diff@v1.1.0/diffmatchpatch/diff.go:129 +0x271 fp=0x142e6d5c sp=0x142e6cd0 pc=0x66a0b1
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffMainRunes(0x142e702c, 0xb9cf1c, 0x0, 0x0, 0x35400000, 0x5d86d31, 0x5d87000, 0x611a000, 0x0, 0x0, ...)
        /Users/zacharyrice/Go/pkg/mod/github.com/sergi/go-diff@v1.1.0/diffmatchpatch/diff.go:95 +0xa2 fp=0x142e6dcc sp=0x142e6d5c pc=0x669db2
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffMain(...)
        /Users/zacharyrice/Go/pkg/mod/github.com/sergi/go-diff@v1.1.0/diffmatchpatch/diff.go:85
github.com/zricethezav/gitleaks/v7/scan.(*UnstagedScanner).Scan(0x13d128c0, 0xc0700d96, 0x16d1299, 0x0, 0xb7f6a0, 0x13c1a2ae, 0x4d)
        /Users/zacharyrice/code/gitleaks/scan/unstaged.go:200 +0x64b fp=0x142e7bbc sp=0x142e6dcc pc=0x7f868b
main.main()
        /Users/zacharyrice/code/gitleaks/main.go:52 +0x3da fp=0x142e7fc8 sp=0x142e7bbc pc=0x80125a
runtime.main()
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225 +0x237 fp=0x142e7ff0 sp=0x142e7fc8 pc=0x4b59c7
runtime.goexit()
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_386.s:1315 +0x1 fp=0x142e7ff4 sp=0x142e7ff0 pc=0x4df7e1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/sigqueue.go:168 +0x132
os/signal.loop()
        /usr/local/Cellar/go/1.16.5/libexec/src/os/signal/signal_unix.go:23 +0x1a
created by os/signal.Notify.func1.1
        /usr/local/Cellar/go/1.16.5/libexec/src/os/signal/signal.go:151 +0x33

goroutine 7 [chan receive]:
main.listenForInterrupt(0x13c4f8c0)
        /Users/zacharyrice/code/gitleaks/main.go:71 +0x29
created by main.main
        /Users/zacharyrice/code/gitleaks/main.go:21 +0xb8
COMMIT FAILED - Gitleaks failed.

**Comment by zricethezav** [comment]
looks like your running an old version of gitleaks, I recommend upgrading. Reopen if you still find this is an issue
