### ISSUE TITLE
Gitleaks not scanning Readme.md and yaml files for secrets

### ISSUE THREAD

**Issue by sindhujarudra** [zricethezav/gitleaks#771]
Describe the bug
I have gitleaks extension installed on my AzureDevops. I have added the stage in my yaml file for repo to detect the secrets.
Repo has different file types with hardcoded secrets ( AZURE PAT tokens).
1. .ps1
2. cs
3. yml
4. Readme.md
5.json

When I run my pipeline, it detects the secrets in .json/cs/.ps1 files and it is ignoring Readme.md/yml files. Is this expected. 
I have attached screenshots of  the logs and the sample yml file  with hardcoded PAT token.

To Reproduce
Create a repo with above file extensions with some secrets and run the AzureDevops pipeline.

Expected behavior
It should detect the secrets in the yml and Readme.md files.

Screenshots
![image](https://user-images.githubusercontent.com/46533139/150589473-ec98b3ec-b14d-45e7-9dc1-c2c21340e0b1.png)

<img width="709" alt="issue" src="https://user-images.githubusercontent.com/46533139/149411346-56125074-6045-42a1-977e-f339d874a3cd.png">

cc @zricethezav

**Comment by JoostVoskuil** [comment]
Hi @sindhujarudra , can you raise this issue at: https://github.com/JoostVoskuil/azure-devops-gitleaks. You are using the Azure DevOps extension. That uses Gitleaks. I will look into this issue

**Comment by zricethezav** [comment]
Thanks @JoostVoskuil, looks like you got it. Closing this issue 🙇🏻
