### ISSUE TITLE
Pull Request with scan Mode "smart" is throwing an Error: "Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by sindhujarudra** [zricethezav/gitleaks#776]
Hi, I using smart mode for my azure task in my repo. When I run the smart mode scan from my working branch, it works fine but I create a PR to merge it to master, it is throwing me 

Error : "##[error]Cannot read property 'length' of null".

![image](https://user-images.githubusercontent.com/46533139/150238749-78275438-5646-47d9-9a31-e82e48f1ef14.png)

Any inputs here?

@zricethezav

**Comment by JoostVoskuil** [comment]
Hi @sindhujarudra , can you raise this issue at: https://github.com/JoostVoskuil/azure-devops-gitleaks. You are using the Azure DevOps extension. That uses Gitleaks. I will look into this issue

**Comment by zricethezav** [comment]
Thanks @JoostVoskuil, looks like you got it. Closing this issue 🙇🏻
