### ISSUE TITLE
Improve generic regex

### ISSUE THREAD

**Issue by raro42** [zricethezav/gitleaks#778]
**Describe the solution you'd like**

I have the following secret in my secret.json file in a repo:
{
    "client_id" : "0afae57f3ccfd9d7f5767067bc48b30f719e271ba470488056e37ab35d4b6506",
    "client_secret" : "6da89121079f83b2eb6acccf8219ea982c3d79bccc3e9c6a85856480661f8fde",
    "response_type" : "id_token"
}

I would like to recognize it with the default regex provided in your repo.

The following regex would do so:
```(?i)((key|api|token|secret|password)[a-z0-9 .\-,]{0,25})(=|>|:=|||:|<=|=>|:|).{0,5}[\'\"]([0-9a-zA-Z-=]+)[\'\"]```

What's the difference:
(=|>|:=|||:|<=|=>|:|)  ... the last "|" makes null hits be positiv and continue on regex
([0-9a-zA-Z-=]+) ... the "+" ... makes the limit of 64 disappear. I am not sure if this is a good idea. As time flies by, I guess we will soon see longer secrets

**Additional context**
My questions:
* is that something you would like to see as a contribution?
* I did not understand how you are testing. Do you have testcases that the secret should be added to?
* How could I test the new regex against existing testcases?

cc @zricethezav

**Comment by varac** [comment]
I was surprised that a simple yaml file with the content `password: aghoh8oubu1obin9Cagae0u` is not recognized (this is a test password, please don't try to hack me based on this :) ). Is this a bug or is `password` really not in the default regex (it should!) ?

**Comment by zricethezav** [comment]
@varac there is a small bug where I need to include EOL regex in the secret suffix. Will be pushing out a fix tonight hopefully.

**Comment by varac** [comment]
I don't understand, but that's not important. looking forward for the fix. 
@zricethezav could you please answer the questions from @raro42, I'm also interested how you are testing.

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/blob/master/cmd/generate/config/rules/generic.go

**Comment by zricethezav** [comment]
@varac @raro42 see fix in https://github.com/zricethezav/gitleaks/pull/847

**Comment by Janne-Nykanen** [comment]
The "Generic API Key" rule now (v8.7.2) matches lines similar to this (Terraform):
"client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.client-vpn-endpoint.id"

How is that leaking anything...?

**Comment by Janne-Nykanen** [comment]
> @Janne-Nykanen because it matches the regular expression and passes the heuristics that are written for the generic rule. It can use some work like being dismissed if the secret contains a stop word. What would be useful is pointing me to a list of stop words.

@zricethezav I'm not fully getting the regexp logic in question, but it seems to ignore, say, "client_cidr_block". In a similar way, "client_vpn_endpoint_id" should be overridden.

**Comment by zricethezav** [comment]
@Janne-Nykanen 
`client_cidr_block` has a low entropy. (3.45)

`client_vpn_endpoint_id` has a high enough entropy to be considered a secret. (3.7)

**Comment by Janne-Nykanen** [comment]
> @Janne-Nykanen https://github.com/zricethezav/gitleaks/releases/tag/v8.8.0 by default this should fix your false positive. However if you want to further configure your stopwords you can do so either per rule or globally with `Allowlist.StopWords`:
> 
> * https://github.com/zricethezav/gitleaks#configuration
> * https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L19-L25

Thanks @zricethezav you are my hero :)

**Comment by varac** [comment]
> @varac @raro42 see fix in #847

I tried with gitleaks `8.7.2` but I could commit `password: aghoh8oubu1obin9Cagae0u` in a yaml flle once again without gitleaks complaining. Should I create a seperate issue for this ?

**Comment by zricethezav** [comment]
@varac are you using your own config?

**Comment by zricethezav** [comment]
@varac it's because `aghoh8oubu1obin9Cagae0u` does not have a high enough entropy (3.64) to be considered a secret (3.7). I'll consider dropping it down to 3.6 once I have more stopwords.

**Comment by varac** [comment]
@zricethezav Interesting - testing this password with [dwolfhub/zxcvbn-python](https://github.com/dwolfhub/zxcvbn-python) shows 100000000000000000000001 guesses are needed (and falls in the `centuries` crack category).
`dwolfhub/zxcvbn-python` is the python port of the original [dropbox/zxcvbn](https://github.com/dropbox/zxcvbn), which [dropped using entropy in favor of guesses a some time ago](https://github.com/dropbox/zxcvbn/commit/a1be663b7533f990d094ae9a4f76ae51491ee0f4). Did you consider this as well ? 
Anyhow, I think this example pw is a strong password, and gitleaks should not only protect (super) strong passwords, but also weak ones (which is still a sad reality). And on top of that, why doesn't `password: ` alone ring the bell ?

**Comment by zricethezav** [comment]
@varac 
> And on top of that, why doesn't password: alone ring the bell ?

It does. `password: aghoh8oubu1obin9Cagae0u` fails on the entropy heuristic. 

>  Did you consider this as well ?

No I haven't. I maintain gitleaks in my free time and don't have the ability to do everything. I will look at this.

**Comment by zricethezav** [comment]
using `zxcvbn-python` for this doesn't entirely make sense since there could be a lot of false positives give that gitleaks is trying to extract credentials from code. Passing `this.secret.function` into zxcvbn would result is a strong password, I'm assuming.

**Comment by varac** [comment]
Is there an easy way to measure/tune entropy thresholds ? I.e. how did you find out the entropy for this password that you mentioned above ?
