### ISSUE TITLE
Ignore lines/blocks/files containing `gitleaks-disable` or listed in `.gitleaksignore` file

### ISSUE THREAD

**Issue by rasa** [zricethezav/gitleaks#779]
**Is your feature request related to a problem? Please describe.**

I want to ignore scanning files that have example secrets in them.

**Describe the solution you'd like**

Have gitleaks ignore files that have a specific string, such as `gitleaks-disable` appearing somewhere before the example secrets.

**Describe alternatives you've considered**

Hack the config file. This is difficult when called from super-linter. Hard for non-technical users, too.

**Additional context**

This could be expanded to ignore individual lines:

```txt
ignore this line <!-- gitleaks-disable-line -->
```

or blocks:

```txt
<!-- gitleaks-disable -->
ignore this block
<!-- gitleaks-enable -->
```

**Edit**: Another, more user-friendly, solution might be to ignore files listed in a `.gitleaksignore` file. Parsed in the same way as how `.gitignore` is parsed.

An admin may want to disable these options in the config, to keep users from using them when they shouldn't be.

Forgive me if this feature already exists. If it does, I can create a PR to add it to the readme.

cc @zricethezav

**Comment by rasa** [comment]
See https://github.com/secretlint/secretlint/blob/master/docs/configuration.md#ignoring-error-by-comments and
https://github.com/secretlint/secretlint/blob/master/docs/configuration.md#secretlintignore

**Comment by De-Luxis** [comment]
For `.gitleaksignore` can use the package https://github.com/iriri/minimal.
If no one will do it, then I'll try to do PR.

**Comment by alexgit2k** [comment]
This is a very good idea, like other security analyzers are doing it:

- Semgrep
  - In line: `// nosemgrep: <rule>` (see https://semgrep.dev/docs/ignoring-files-folders-code/#reference-summary)
  - Before line: `// nosemgrep: <rule>` (see https://semgrep.dev/docs/ignoring-files-folders-code/#reference-summary)
  - File: `.semgrepignore`
- ESLint
  - In line: `// eslint-disable-line <rule>` (see https://eslint.org/docs/latest/user-guide/configuring/rules#using-configuration-comments-1)
  - Before line: `// eslint-disable-next-line <rule>` (see https://eslint.org/docs/latest/user-guide/configuring/rules#using-configuration-comments-1)
  - Block: Before with `/* eslint-disable <rule> */` after with `/* eslint-enable <rule> */` (see https://eslint.org/docs/latest/user-guide/configuring/rules#using-configuration-comments-1)
  - File: `.eslintignore`
- njsscan
  - In line: `// njsscan-ignore: <rule>` (see https://github.com/ajinabraham/njsscan#suppress-findings)
  - File: `.njsscan` (YAML-Format, Key: ignore-paths) (see https://github.com/ajinabraham/njsscan#configure-njsscan)

IMO the rule-option to ignore a specific rule is not needed for gitleaks as it is very unlikely to have more than one leak in a line.

**Comment by zricethezav** [comment]
You can use [allowlists](https://github.com/zricethezav/gitleaks#configuration) to achieve this or use [`gitleaks:allow`](https://github.com/zricethezav/gitleaks/blob/master/detect/detect.go#L35) in a comment. Using `gitleaks:allow` is currently not documented. Note that `gitleaks:allow` does not work retroactively. I,e. if you introduce a commit _without_ `gitleaks:allow` and then later add a `gitleaks:allow` and commit that, the secret will still be flagged. 

I have plans for a `.gitleaksignore` already which would solve https://github.com/zricethezav/gitleaks/issues/888. `.gitleaksignore` would give users the ability to flag certain findings as false positives.

**Comment by alexgit2k** [comment]
> You can use [allowlists](https://github.com/zricethezav/gitleaks#configuration) to achieve this or use [`gitleaks:allow`](https://github.com/zricethezav/gitleaks/blob/master/detect/detect.go#L35) in a comment.

I have seen `allowlists`, this is a powerfull feature with a lot of configuration possibilities but overkill for a single ignore and it is more readable for a developer when having the ignore comment in the same line.

Just tried `gitleaks:allow`, works perfectly. I have seen that it has been introduced in [!809](https://github.com/zricethezav/gitleaks/pull/809) with v8.5.0. Of course it should not work retroactively. Thanks!

**Comment by zricethezav** [comment]
Just added some docs for this `gitleaks:allow` feature: https://github.com/zricethezav/gitleaks/pull/941

Gonna close this issue out and focus on https://github.com/zricethezav/gitleaks/issues/888
