### ISSUE TITLE
Error when secretGroup is less than len(groups)

### ISSUE THREAD

**Issue by dfernandezvalero** [zricethezav/gitleaks#784]
You can only use the last group from a multiline regex when you set the `secretGroup` config. The error is found in the line https://github.com/zricethezav/gitleaks/blob/v8.2.7/detect/detect.go#L87.

The condition should be `if len(groups)-1 < r.SecretGroup || len(groups) == 0`

cc @zricethezav

**Comment by dfernandezvalero** [comment]
https://github.com/zricethezav/gitleaks/blob/991223ababf9675cb7d92f55ee46b08762822581/detect/detect.go#L87

**Comment by zricethezav** [comment]
@dfernandezvalero good catch, although I'm confused as to why multiline regexes are of concern here. I was seeing this behavior for non-multiline regexes as well

**Comment by zricethezav** [comment]
reopening until new release
