### ISSUE TITLE
AllowList for false-positive regex does not work

### ISSUE THREAD

**Issue by maciej-redzik** [zricethezav/gitleaks#787]
**Describe the bug**

When I add custom regex to [allowList] to provide custom flags to my code, gitleaks still counts that as positive.
I've created my solution based on discussion from here [Link](https://github.com/zricethezav/gitleaks/issues/579)

**To Reproduce**
My [allowlist] (in custom *.toml file):
```
[allowlist]
description = "Allowlisted files"
regexes = ['''219-09-9999''', '''078-05-1120''', '''(9[0-9]{2}|666)-\d{2}-\d{4}''', '''allow:gitleaks''']
files = ['''(.*?)(png|jpg|gif|tif|tiff|doc|docx|pdf|bin|xls|pyc|zip)$''',
'''buildsearchers.xml''',
'''^\.?gitleaks.toml$''',
'''^\.?UDMSecretChecks.toml$''',
'''^\.?GitleaksUDMCombo.toml$''']
paths = [
    '''pipeline\/assets\/gitleaks\/UDMSecretChecks\.toml$''',
    '''pipeline\/assets\/gitleaks\/GitleaksUDMCombo\.toml$''',
]
```
My source code (Program.py):
```python
class CustomClass:
    discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ'  #allow:gitleaks
```
I'm invoking gitleaks using following command-line:
```bash
./gitleaks detect --no-git --source=<path_to_source> --verbose --config=custom_gitleaks.toml
```

**Expected behavior**
Gitleaks should print "no leaks", but it is still founding same leak:
```
    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

{
	"Description": "Discord client secret",
	"StartLine": 2,
	"EndLine": 2,
	"StartColumn": 6,
	"EndColumn": 63,
	"Match": "discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ'",
	"Secret": "8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ",
	"File": "../../src/Program.py",
	"Commit": "",
	"Entropy": 0,
	"Author": "",
	"Email": "",
	"Date": "",
	"Message": "",
	"Tags": [],
	"RuleID": "discord-client-secret"
}
9:20PM WRN leaks found: 1
9:20PM INF scan completed in 8.696744ms

```

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Gitleaks Version: 8.2.7 & 7.6.1

**Additional context**
[Old discussion](https://github.com/zricethezav/gitleaks/issues/579)

cc @zricethezav

**Comment by zricethezav** [comment]
@maciej-redzik good catch, taking a look at this. This likely isn't working due to the fact that `allow:gitleaks` is outside the regex capture. As such, I'm not sure I would consider this a bug as `"Match": "discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ'"` does not contain `allow:gitleaks`.

Perhaps we should re-frame this issue as an `enhancement` to support commented/inline "allows"? WDYT? Have any thoughts on the behavior you would like to see? 

I'm thinking it would make sense to introduce something like 
```
IF "allow:gitleaks" is in `Match` OR  "allow:gitleaks" is in {line(s) content}
THEN ignore finding
```

Or we could extend all `allowlist.regexes` to extend to the `{line(s) content}`...

**Comment by eduardofavarato** [comment]
Hey @zricethezav, first of all thanks for maintaining gitleaks 🙏🏼
I just to upvote this and say we could really use this feature as currently there is no way to ignore a line.
Thanks again!

**Comment by zricethezav** [comment]
I have a draft of this feature available on this branch/pr:

https://github.com/zricethezav/gitleaks/pull/809

cc @eduardofavarato @maciej-redzik

**Comment by eduardofavarato** [comment]
Hi @zricethezav, thanks a lot! I have tested it locally and it's working perfectly. 👏🏼👏🏼👏🏼

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/941 just added some docs. gonna close this one out
