### ISSUE TITLE
 specified branch

### ISSUE THREAD

**Issue by C1ph3R-s** [zricethezav/gitleaks#788]
Hi,

I used v7.6.1 version until now, but I have to update it.
I would like to know, how can i run on a specified branch in the latest version?

Thanks,

**Comment by zricethezav** [comment]
@C1ph3R-s you can pass a `--log-opts` value to specify the branch name.

Say you want to scan _only_ commits for the `feature-1` branch which is branched off `develop` _and_ you don't want to include commits from `develop`, you could run `gitleaks detect source={path to source} --log-opts="develop^..feature-1"`,

Or, if you're certain that the currently checked out branch on `source` is the base ref you could shorthand the log-opts option to `--log-opts=..feature-1`

https://git-scm.com/docs/git-log for more documentation

**Comment by C1ph3R-s** [comment]
Thank you :)
