### ISSUE TITLE
Consumes a lot of memory when running against an org

### ISSUE THREAD

**Issue by pdparchitect** [zricethezav/gitleaks#79]
Interesting project. I was testing it against uber's github org and it effectively run out of memory twice, even when the --disk option was specified. I did not investigate the cause but it is likely to be a mem leak.

**Comment by zricethezav** [comment]
@pdparchitect thanks for bringing that up. I hadn't done any huge stress testing. Mem leakage is definitely a possibility -- or could just be too much loaded up into mem as uber has a couple large repos. 

Right now gitleaks pulls all the repos into memory, then performs the audit one by one. A better solution would be to fire off audits one at a time as soon as it gets a response from github.

**Comment by keirans** [comment]
Hey @pdparchitect ,
Would I be able to get an idea of how much memory we are talking about ? 

I'm using gitleaks to audit quite a bit of code, and am looking to move to the 1.x release soon, and this will help me understand if i'll hit this.

Thanks!

K

**Comment by zricethezav** [comment]
@pdparchitect @keirans Made quite a few performance upgrades since this issue was opened. Care to try now and see if you notice an improvement? https://github.com/zricethezav/gitleaks/releases/tag/v1.6.0 details some of the issues.

**Comment by zricethezav** [comment]
closing this, memory issues have been handled. the problem was some dangling goroutines
