### ISSUE TITLE
HashiCorp Vault secretid and roleid

### ISSUE THREAD

**Issue by sergiomarotco** [zricethezav/gitleaks#796]
I using regex: `(?i)(secretID|RoleId)(=|>|:=|\|\|:|<=|=>|:).{0,10}['\"]([0-9a-zA-Z]{8})(-)([0-9a-zA-Z\-]{4})(-)([0-9a-zA-Z]{4})(-)([0-9a-zA-Z]{4})(-)([0-9a-zA-Z]{12})['\"]`

Exmple  SecretID and RoleID format: **1234567n-35h7-123c-12m3-123456789g12** ( 8-4-4-4-12)

https://regex101.com/r/8fNQfz/3

Rule:

[[rules]]
id = "HashiCorp Vault parameters"
description = "HashiCorp Vault SecretID and RoleID"
regex = '''(=|>|:=|\|\|:|<=|=>|:).{0,10}['\"]([0-9a-zA-Z]{8})(-)([0-9a-zA-Z\-]{4})(-)([0-9a-zA-Z]{4})(-)([0-9a-zA-Z]{4})(-)([0-9a-zA-Z]{12})['\"]'''

**Comment by zricethezav** [comment]
@sergiomarotco Closing this issue as it is not descriptive enough. If the vault/hashicorp rules need to be updated, feel free to open a PR
