### ISSUE TITLE
Organization/User Scan

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#8]
Retrieve organization/user repos using `https://api.github.com/orgs/<org name>/repos` or `https://api.github.com/users/<username>/repos`. Iterate through repos, clone repo, generate report.

usage:
`$ gitleaks -u https://github.com/<username>`
`$ gitleaks -o https://github.com/<org name>`

**Comment by JustinAzoff** [comment]
I think to make this even more useful, you would want to do something like skipping the `rm -rf` step and leave the repo on disk, and then use some method to only scan new revs as they show up.

This way gitleaks could just be ran from cron and continually scan all repos in the org without having to clone them from scratch each time.

Main thing that would need to be worked out is how to tell what revs are new. I'm not sure if git has a good way of doing this, one simple approach would be to just store each commit from `git rev-list --all --remotes --topo-order` in a boltdb/bbolt database after it is checked.

**Comment by zricethezav** [comment]
I like this idea. Adding better support for scheduled runs is definitely a feature that should be added. Boltdb seems like a good data store to track commits.

Another enhancement I want to implement is using https://github.com/src-d/go-git instead of shelling out the git commands for two reasons: minimize disk writes (go-git can clone in memory) and remove the `rm -rf` cleanup step.

**Comment by zricethezav** [comment]
starting work here: https://github.com/zricethezav/gitleaks/tree/org_user_scan
