### ISSUE TITLE
Need to look for Android keystore objects

### ISSUE THREAD

**Issue by pylapp** [zricethezav/gitleaks#803]
**Is your feature request related to a problem? Please describe.**
Of a repository has leaked is keystore file and the credentials to access it, the scan does not see it.

**Describe the solution you'd like**
As a developer making scan of repositories
I wan to check in Android-projects-related files like keystores have leaked
So that I can contact colleagues and remove such files

**Describe alternatives you've considered**
Use _Shell_ script with recursive `ls` command and `grep`. Or `find` command.

**Additional context**
Files to look for are like **.keystore.jks**.
In build files, like _build.gradle_ files, loke for items like:

```groovy
signingConfigs {
        debug {
            storeFile file("debug.keystore.jks")
            storePassword "the-password-for-store"        //   <--- leak
            keyAlias "package.name.of.app"                     //   <--- leak
            keyPassword "key-password"                        //   <--- leak
        }
        unsigned {
            storePassword = ""
            keyAlias = ""
            keyPassword = ""
        }
    }
```
cc @zricethezav

**Comment by sergiomarotco** [comment]
@pylapp  As I see it, @zricethezav does not write regular expressions, you need to write a regular expression yourself and commit with your regular expression

**Comment by zricethezav** [comment]
The generic rule should catch most secrets of the forms:
```
            storePassword "the-password-for-store"        //   <--- leak
            keyAlias "package.name.of.app"                     //   <--- leak
            keyPassword "key-password"    
```

Since this is a config issue I am closing it as you can define your own gitleaks configuration rules
