### ISSUE TITLE
Generic api key rule is leaky

### ISSUE THREAD

**Issue by mmanski** [zricethezav/gitleaks#805]
### Is your feature request related to a problem? Please describe.
Yes, the Generic API Key fails to detect some obvious secret patterns, like passwords with special characters or Basic Auth credentials. It also does not detect secrets longer than 64 characters.

### Describe the solution you'd like
The Generic API Key rule regexp should catch special characters, like `@` and `:` and detect secrets longer than 64 characters (which is a case i.e. in SAP CDC API keys). Also, it should detect secrets described by `auth` and `cred` keys.

### Additional context
The cases below are not being detected by `giteaks`:

```
password: 'P@ssword1234'
usernamePassword: 'admin:admin'
serviceUserCredential:  '62940aab-b9f9-49e3-a2ed-884f5fc64d7e'
basicAuth: 'admin:admin'
apiKey: '62940aab-b9f9-49e3-a2ed-884f5fc64d7e-62940aab-b9f9-49e3-a2ed-884f5fc64d7e'
```

cc @zricethezav

**Comment by sergiomarotco** [comment]
haha, I found about 40 variants of secrets in my code that Gitleaks does not find.  I have not written regular expressions yet, then I plan to push them.

**Comment by sergiomarotco** [comment]
I met authorization JWTs right in the code, they are 200 characters long

**Comment by svyotov** [comment]
Same here @zricethezav, the default rules are too lenient. These here are a good starting point IMHO : https://github.com/GSA/odp-code-repository-commit-rules/blob/master/gitleaks/rules.toml

**Comment by sergiomarotco** [comment]
"Pure Entropy" looks interesting

**Comment by zricethezav** [comment]
Thank you for the suggestions, I have plans to update the generic rule with a new regex. Something like 
```
(?i)(?:'|"){0,1}(?:[a-z0-9\-_.]{0,25})(?:key|api|token|secret|client|password|pat|auth|cred)(?:[0-9a-z\-_\s.]{0,20})(?:'|"){0,1}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=){0,5}([0-9a-z\-_\.=:@]{10,200})['|\"|\n|\r|\s]
```

which should catch most of what is missed here

**Comment by Izzmo** [comment]
@zricethezav when will this be in a release?

**Comment by zricethezav** [comment]
@Izzmo that regex will be part of a larger feature, so idk, maybe in a month or something

**Comment by zricethezav** [comment]
The generic rule was updated a while ago, sorry for not updating this issue.https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L1139-L1147
