### ISSUE TITLE
new global allowlist prevents regex matches where key contains 'secret' (or any allowlist variable)

### ISSUE THREAD

**Issue by kbroughton** [zricethezav/gitleaks#816]
**Describe the bug**
The new addition in #808 of stopwords like "secret" is designed to eliminate noise from values with "secret" on the RHS of an assignment which indicate further substitution, like "AWS_KEY" = {{aws_secret}}. However, if the identifier (LHS) on the line includes one of the stopwords, then you will skip over that as well. I think it's actually quite common to use "secret" or "token" in the identifier of a config file like:

```
"client_secret": "s092if00*********alkas"               # the rhs could match any default secret pattern but not be detected
"my_saas_api_token": "29292923939499595"
``` 

I believe both these would now be skipped due to stopwords

```
[allowlist]
description = "global allow lists"
regexes = [
...
	'''token''',
	'''password''',
	'''secret''',
...
```

The only rule in config/gitleaks.toml which currently has "secret" in it is the following, but it is uppercase and thus perhaps would not be affected by the allowlist. `regex = '''AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}'''`.

The allowlist needs to be smarter and only apply to the secrets portion of the (identifier, assignment, secret) tuple.

**To Reproduce**

Create a test file 't-reg' with contents below. This is similar to the existing GCP detection on `"type": "service_account"`.
```
"client_secret": "x"
```

Add the following custom secret to .gitleaks.toml . (I was trying to add a new detection for gcp default creds which don't include a "type": "service_account" string.)

```
[[rules]]
id = "gcp-service-account-default-credentials"
description = "Google (GCP) Service-account default credentials"
regex = '''\"client_secret\"'''
```
You will not see a detection for the t-reg test file but we should.
To sanity check, change the rule regex to client_fecret and the t-reg identifier to client_fecret and you will now get a detection.

**Expected behavior**
Stopwords should only apply to the secret of (identifier, assignment, secret) tuple, not to the identifier.

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Osx M1
 - Gitleaks Version: v8.5.1
 - git version: git version 2.32.0 (Apple Git-132)

**Additional context**
I'm running gitleaks in a container built on the master branch from yesterday.

cc @zricethezav

**Comment by zricethezav** [comment]
@kbroughton you are right, thanks for filing this issue. I've reverted this and released v8.5.2. I'll have to think about a better way to implement this feature.
