### ISSUE TITLE
Segmentation violation error when forbidding certain files

### ISSUE THREAD

**Issue by anotherbridge** [zricethezav/gitleaks#820]
**Describe the bug**

When trying to include certain files only with a path I get a runtime error telling me that there is a segmentation violation. As a baseline I used the [path_only.toml](https://github.com/zricethezav/gitleaks/blob/master/testdata/config/path_only.toml) from the test data. 

However, when adding a regex there is no error and gitleaks runs as expected.

**To Reproduce**
[path_only.toml](https://github.com/zricethezav/gitleaks/blob/master/testdata/config/path_only.toml):

```
title = "gitleaks config"

[[rules]]
description = "Python Files"
id = "python-files-only"
path = '''.py'''
```

I'm using gitleaks as follows (currently being inside my repo):

```
gitleaks -c ./gitleaks_test.toml detect -v . 
```

**Expected behavior**
Gitleaks should give me all python files in the commit history of my repo.

**Actual behavior**

```

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100466e5c]

goroutine 39 [running]:
regexp.(*Regexp).allMatches(0x0, {0x14000244600, 0x474}, {0x0, 0x0, 0x0}, 0x475, 0x1400027d650)
	regexp/regexp.go:782 +0xac
regexp.(*Regexp).FindAllStringIndex(0x140002800cd?, {0x14000244600?, 0x0?}, 0x1400021a690?)
	regexp/regexp.go:1139 +0x5c
github.com/zricethezav/gitleaks/v8/detect.(*Detector).detectRule(0x14000264000, {{0x14000244600, 0x474}, {0x140002800cd, 0x21}, {0x1400021a307, 0x28}, {0x14000260400, 0x2a, 0x2a}}, ...)
	github.com/zricethezav/gitleaks/v8/detect/detect.go:152 +0x2e8
github.com/zricethezav/gitleaks/v8/detect.(*Detector).Detect(0x14000264000, {{0x14000244600, 0x474}, {0x140002800cd, 0x21}, {0x1400021a307, 0x28}, {0x14000260400, 0x2a, 0x2a}})
	github.com/zricethezav/gitleaks/v8/detect/detect.go:371 +0x1b0
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectGit.func1()
	github.com/zricethezav/gitleaks/v8/detect/detect.go:283 +0x134
github.com/fatih/semgroup.(*Group).Go.func1()
	github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0x8c
created by github.com/fatih/semgroup.(*Group).Go
	github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x294
```

**Basic Info (please complete the following information):**

    OS: macOS Monterey v12.3
    Gitleaks Version: 8.5.2

**Additional info**
In a previous version I already tried this and it worked without any problem.

cc @zricethezav

**Comment by zricethezav** [comment]
Fixed with https://github.com/zricethezav/gitleaks/releases/tag/v8.5.3, reopen if you're still experiencing problems
