### ISSUE TITLE
Hardware specifications, os , dependencies 

### ISSUE THREAD

**Issue by Krelen** [zricethezav/gitleaks#822]
Hello guys, 

I am trying to find a tool for a secret scanning ( locally about 500mb repos) 
May you tell me if there are any hardware  specifications for potential server ,OS , CPU cores etc. 
Also any network configurations like ports and tunnels ?

Thank you in advance!

**Comment by zricethezav** [comment]
Hi @Krelen, I'm not sure what you're requesting. Gitleaks can be used cross-os on most popular architectures. See the releases page. Gitleaks does not make any network connections.

**Comment by Krelen** [comment]
HI, 
Any hardware requirements like ram, cpu cores etc ?
