### ISSUE TITLE
Default gitleaks config file doesn't detect all the generic api secrets

### ISSUE THREAD

**Issue by imaditiagg** [zricethezav/gitleaks#824]
**Describe the bug**
Default gitleaks config file (gitleaks.toml) doesn't detect all the generic api secrets e.g generic secrets where secret key is enclosed within quotes.

**To Reproduce**
e.g "testSecret" : "test" - This secret doesn't get detected by gitleaks.

**Expected behavior**
An additional rule can be added to detect such secrets as well. 
e.g One possible regex could be : 
'''['\"](?i((key|api[^Version]|token|secret|password|dbpasswd|dbuser|dbname|dbhost|api_key|apikey|user|hostname|pw|auth)[a-z0-9_ .\-,]{0,25})['\"](=|>|:=|\|\|:|<=|=>|:).{0,5}['\"]([0-9a-zA-Z\-_=]{8,64})['\"]'''

cc @zricethezav

**Comment by zricethezav** [comment]
Hi @imaditiagg, this is not a bug since you can configure the regex with a custom gitleaks.toml. The generic rule doesn't claim to capture all secrets as it has to maintain a healthy balance of True Positives to False Positives.
