### ISSUE TITLE
Flags "-no_msg" to disable print "Message"

### ISSUE THREAD

**Issue by sergiomarotco** [zricethezav/gitleaks#826]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Add a possible start flag that would allow not to display the Message field
![image](https://user-images.githubusercontent.com/29877074/161889640-f8fb1a33-75ec-4298-8286-b48bf54045f4.png)
This will reduce the log size

cc @zricethezav

**Comment by zricethezav** [comment]
I don't plan on implementing this feature. Limiting the message length is something I have planned though.
