### ISSUE TITLE
Generic regex matches but Gitleaks doesn't detect secret

### ISSUE THREAD

**Issue by va1entin** [zricethezav/gitleaks#828]
**Describe the bug**
The [generic regex](https://github.com/zricethezav/gitleaks/blob/v8.6.0/config/gitleaks.toml#L630) matches the following pattern:

`secret = "super_secret"`

Gitleaks does not detect that secret though.

**To Reproduce**
Add the secret above to a repo and run gitleaks detect on it.

**Expected behavior**
Gitleaks detects the secret, because the regex matches the secret.

**Basic Info (please complete the following information):**
 - OS: Container from https://hub.docker.com/r/zricethezav/gitleaks
 - Gitleaks Version: 8.6.0

cc @zricethezav

**Comment by zricethezav** [comment]
`super_secret` has an entropy value of 2.86. To be considered a secret it needs an entropy value of 3.7

**Comment by va1entin** [comment]
Thanks for the heads-up! I think 3.7 is quite a high default for the generic regex, which is probably why it felt like a bug. Be that as it may - it'd be great, if we could extend the config as requested in #741 to just set the entropy to 0 and keep all the other defaults.
Is a config extension feature on the roadmap currently?
