### ISSUE TITLE
--github-org leaving with blank

### ISSUE THREAD

**Issue by jaikishantulswani** [zricethezav/gitleaks#83]
Hello,
The flag "--github-org=some org url" not working and leaving with blank ?

**Comment by eripa** [comment]
I noticed this as well when using, there's some error handling that's causing the program to prematurely exit if there are cloning errors for any of the repos. I've submitted a PR for GitHub Enterprise support in #85 that also fixes this error handling. Might be related.

**Comment by jaikishantulswani** [comment]
Hello @zricethezav any updates on this issue !

**Comment by zricethezav** [comment]
@jaikishantulswani could you pull the latest release and see if you this issue is fixed. Run with `--log=debug -v` for debugging output and verbose mode. You should see some movement

**Comment by jaikishantulswani** [comment]
Hello @zricethezav ,
Thank you ! it works without any issue :) :+1:
