### ISSUE TITLE
15 vulns in base image

### ISSUE THREAD

**Issue by sergiomarotco** [zricethezav/gitleaks#831]
![Снимок веб-страницы_6-4-2022_23443_app snyk io](https://user-images.githubusercontent.com/29877074/162018456-e08b2bac-612a-4e15-a955-fafab267a8ca.jpeg)

**Comment by lutzwillek-tomtom** [comment]
Thank you @sergiomarotco for opening this issue. 
This should be fixed meanwhile by #848  - I could not find an issue anymore: ![Screenshot 2022-04-23 at 17 14 28](https://user-images.githubusercontent.com/72460064/164912146-3c9c72b9-164d-4344-a7d2-24404c0f2f6c.png)

Would you mind to re-check on your side as well?

**Comment by zricethezav** [comment]
feel free to reopen if you feel this isn't resolved @sergiomarotco
