### ISSUE TITLE
separate gitleaks from git so any tool that feed unified diff log can be used as source

### ISSUE THREAD

**Issue by pijoter** [zricethezav/gitleaks#836]
**Is your feature request related to a problem? Please describe.**
gitleaks is a great tool but is limited to git as a scm; would be nice if gitleaks (as security detection engine) could be separated from source log data (git or raw files if --no-git option is used)

**Describe the solution you'd like**
something like: 
`git log -p --ancestry-path "$(git rev-parse HEAD~1)".."$(git rev-parse HEAD~0)" | gitleaks detect -v`
`hg log -g -p -r -2..tip | gitleaks detect -v`
`diff -ubwi file_a file_b | gitleaks detect -v`

**Describe alternatives you've considered**
as far as I know, there is no such universal tool around

cc @zricethezav

**Comment by zricethezav** [comment]
Hi @pijoter, I don't have any intention of separating `git` from `gitleaks` but I do plan on supporting what you are requesting at some point in the near future. What I am envisioning is a `--pipe` option that operates similar to `--no-git` on the `detect` command in that is changes the default scan type from `git` to accepting `stdin`. So you could do things like 
`git log -p --ancestry-path "$(git rev-parse HEAD~1)".."$(git rev-parse HEAD~0)" | gitleaks detect -v --pipe`

**Comment by rverenich** [comment]
Hello!

Is there any update with `--pipe` option?

**Comment by rommi4** [comment]
It would be great to have same scan as for git, but from Stdin (hense the name `gitleaks`). And implement additional universal scanners later. Let's move incrementally :)

**Comment by zricethezav** [comment]
@rommi4 @pijoter closing this as the `--pipe` feature has been introduced. I understand that the description in this issue is asking for additional features `pipe` scans but at the moment I do not plan on introducing them. That said, if someone wanted to open a new issue or open a PR that could auto-detect diff syntax then I would happily consider it.
