### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by eripa** [zricethezav/gitleaks#84]
When scanning single repositories it's possible to provide a custom URL to a GitHub Enterprise instance, however when running the Org/User scan the tool assumes the public GitHub instance.

It would be create to have an option like "Base GitHub URL" to override this to support GitHub Enterprise deployments.

**Comment by zricethezav** [comment]
use the `--private` flag for org/user scans

**Comment by eripa** [comment]
Thanks @zricethezav, but that would only cover private repos at GitHub.com. I meant [GitHub Enterprise](https://enterprise.github.com/home) which companies use to host GitHub on their own domain, for example like `github.example.com`.

In order to support that this part needs to be optional:
https://github.com/zricethezav/gitleaks/blob/master/main.go#L512

and have support for:
https://godoc.org/github.com/google/go-github/github#NewEnterpriseClient

I might be able to find time to make a PR for this if you want.

**Comment by zricethezav** [comment]
That would be swell. There are some issues I need to tackle before taking a crack at this

**Comment by eripa** [comment]
Submitted #85 yesterday that implements this.
