### ISSUE TITLE
v8.7.2 detects Kubernetes RBAC as a generic secret

### ISSUE THREAD

**Issue by adamdecaf** [zricethezav/gitleaks#850]
**Describe the bug**
Version v8.7.2 of gitleaks returns a false positive on the following file. (Highlighted area)

https://github.com/moov-io/infra/blob/master/lib/lb/10-traefik-rbac.yml#L31-L32 

**To Reproduce**
Run gitleaks v8.7.2 on the following file. 

**Expected behavior**
No error to be returned. 

**Screenshots**

```
gitleaks version: 8.7.2

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

{
	"Description": "Generic API Key",
	"StartLine": 31,
	"EndLine": 32,
	"StartColumn": 4,
	"EndColumn": 1,
	"Match": "apiGroup: rbac.authorization.k8s.io",
	"Secret": "rbac.authorization.k8s.io",
	"File": "lib/lb/10-traefik-rbac.yml",
	"Commit": "",
	"Entropy": 3.7230742,
	"Author": "",
	"Email": "",
	"Date": "",
	"Message": "",
	"Tags": [],
	"RuleID": "generic-api-key"
}
7:50AM INF scan completed in 252.680655ms
7:50AM WRN leaks found: 1
make: *** [check] Error 1
```

**Basic Info (please complete the following information):**
 - Gitleaks Version: v8.7.2

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
This https://github.com/zricethezav/gitleaks/blob/master/cmd/generate/config/rules/rule.go#L31-L37 list

**Comment by zricethezav** [comment]
Another list: https://github.com/XingyuGit/RepoSimilarity/tree/ac956c9ab18cfac5ad45e4a245f51eb6dce9c11c/text_based

**Comment by zricethezav** [comment]
@adamdecaf Should be fixed with https://github.com/zricethezav/gitleaks/releases/tag/v8.8.1. Please add any other stop words you think are helpful here https://github.com/zricethezav/gitleaks/blob/master/cmd/generate/config/rules/stopwords.go

**Comment by adamdecaf** [comment]
Will do, thanks @zricethezav!
