### ISSUE TITLE
Can we build images for arm64 so users on Apple Silicon can run the docker-image version of gitleaks via pre-commit?

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [zricethezav/gitleaks#861]
Can we build images for arm64 so users on Apple Silicon can run the docker-image version of gitleaks via pre-commit?
cc @zricethezav

**Comment by zricethezav** [comment]
certainly, ill try to get it into next release

**Comment by zricethezav** [comment]
err wait, sorry, I already support this: https://github.com/zricethezav/gitleaks/releases/tag/v8.8.4

**Comment by evanstucker-hates-2fa** [comment]
I mean here - there is no ARM64 image:

https://hub.docker.com/r/zricethezav/gitleaks

By comparison, you can see that the alpine docker image supports multiple architectures:

https://hub.docker.com/_/alpine

**Comment by zricethezav** [comment]
I gotcha, I can look into adding that

**Comment by evanstucker-hates-2fa** [comment]
I might be able to provide code too. I attempted to do multi-architecture docker builds with "buildx" once and failed, but I think there's a tool called "buildah" that might work well. I have to focus on my day job, but I can look into this later today.

**Comment by zricethezav** [comment]
<img width="1236" alt="Screen Shot 2022-09-16 at 9 41 12 AM" src="https://user-images.githubusercontent.com/15034943/190665574-7d6ed2b3-5226-4671-9ef1-7211ec4abb5d.png">


forgot to close this one
