### ISSUE TITLE
gitleaks ignores default config and doesn't merge configs

### ISSUE THREAD

**Issue by adamdecaf** [zricethezav/gitleaks#876]
**Describe the bug**
If I have a config like the following zero secrets are detected. I'm unable to specify a few allow directives. 

```toml
[allowlist]
paths = ["testdata/malformed_key.pem"]
```

gitleaks reports no secrets, but there are some. This is likely due to gitleaks thinking `--config` should _replace_ the default config, but that's not what I want.
```
gitleaks version: 8.8.5

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

9:39AM INF scan completed in 4.701718ms
9:39AM INF no leaks found
finished gitleaks check
```

**Expected behavior**
It would be nice to have a way to allow a few entries as many projects require dummy keys. 

**Basic Info (please complete the following information):**
 - OS: macOS 12.x 
 - Gitleaks Version: 8.8.5 

cc @zricethezav

**Comment by adamdecaf** [comment]
That would be great. I've got ~100 repositories to manage and while we do template codebases I was hoping to rely on the default config. Having overrides would be a big help to us.

**Comment by foolioo** [comment]
relates to #741

**Comment by Dingjie-Daniel-Yang** [comment]
@zricethezav, I am echoing with @adamdecaf. It will be great if there is a **separate config** to allow users to customize the global allowlists.

**Comment by zricethezav** [comment]
Thanks, I hear you guys. I'm thinking of ways to introduce this. In the meantime if you want this feature expedited consider reaching out to me for a maintenance and support agreement https://gitleaks.io/products.html

**Comment by zricethezav** [comment]
@adamdecaf certainly, if you're up for it. I probably won't be able to get to this for at least another week or two

**Comment by wolfch-elsevier** [comment]
Can you tell us how to access/list the default config so we can create a custom config based on the default?

**Comment by very-doge-wow** [comment]
What's the current status on this? I'm undecided wether or not to implement a workaround as long as extending configs is not yet available.

**Comment by mazlum** [comment]
Hello, 
Are there any updates?

**Comment by zricethezav** [comment]
I have a branch I'm working on locally and still deciding on the design of this. Next month or two probably, or maybe next week. idk

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/tree/extend-config wip

**Comment by zricethezav** [comment]
@adamdecaf @very-doge-wow @foolioo @wolfch-elsevier I just merged https://github.com/zricethezav/gitleaks/pull/926. Check out the updated https://github.com/zricethezav/gitleaks#configuration section for instructions on how to use this new feature. Feel free to pull down master and try it out before I release it sometime this week with `8.9.0`

**Comment by very-doge-wow** [comment]
@zricethezav Awesome, thanks! Will test it out.

**Comment by very-doge-wow** [comment]
@zricethezav Is there a way to extend from a default config which is hosted somewhere else than GitHub? The reason being that I'm running gitleaks inside an isolated CI/CD environment which doesn't have access to GitHub directly, but only to a generic github mirror inside an Artifactory server. Meaning: I would need to be able to use something like this:
```toml
[extend]
path = "https://some.artifactory.internal/artifactory/some-repo/gitleaks-config.toml"
```

**Comment by zricethezav** [comment]
@very-doge-wow not at the moment. What I recommend is pulling in `https://some.artifactory.internal/artifactory/some-repo/gitleaks-config.toml` prior to running gitleaks in your CI/CD and adding `includeDefault=true` to that config

**Comment by very-doge-wow** [comment]
> @very-doge-wow not at the moment. What I recommend is pulling in `https://some.artifactory.internal/artifactory/some-repo/gitleaks-config.toml` prior to running gitleaks in your CI/CD and adding `includeDefault=true` to that config

But won't `includeDefault=true` try and download the default config from GitHub? Because that's exactly the problem, there's no access to public GitHub repositories. The Artifactory repository is a mirror of GitHub. That's why I wanted to use `path` instead and simply supply a reference to the remote default config inside Artifactory. Sorry if I didn't explain that clearly 😄

**Comment by zricethezav** [comment]
@very-doge-wow, nope. `includeDefault` will use what is already baked into the binary

https://github.com/zricethezav/gitleaks/blob/master/config/config.go#L186-L206

https://github.com/zricethezav/gitleaks/blob/master/config/config.go#L13-L14

**Comment by very-doge-wow** [comment]
Okay perfect. Then that solves my problem! Thanks. 🏅

**Comment by maltemorgenstern** [comment]
@zricethezav awesome!
We just tested this feature and it is working just as expected/hoped 🥇

Looking forward to upgrading to a new version with this feature included 😄

**Comment by zricethezav** [comment]
With the release of https://github.com/zricethezav/gitleaks/releases/tag/v8.9.0 I'm gonna close out this issue. Thanks for being patient and hope you get some value out of the new feature. Feel free to re-open or continue the discussion 👍🏻
