### ISSUE TITLE
generic-api-key detected erroneously

### ISSUE THREAD

**Issue by dcb-imvaria** [zricethezav/gitleaks#877]
**Describe the bug**
The text "username/password combination." is detected as a generic-api-key leak erroneously using the latest docker image.

**To Reproduce**
1. The text "username/password combination." followed with any additional text will trigger the problem.

**Expected behavior**
This text should not trigger detection.

**Basic Info (please complete the following information):**
 - OS: gitlab CI
 - Gitleaks Version: latest docker image

**Additional context**
Adding "combination" to the stopwords list (https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) ought to eliminate the error.

cc @zricethezav

**Comment by zricethezav** [comment]
@dcb-imvaria nice! Thanks for raising this issue. Reducing false positives for the generic rule is something that can always be improved and I think the best way to do it is adding to the list of stopwords -- you're right on the money. Want to open a PR for the change to get contributor credit? If not I'm happy to open a PR tomorrow or when I get some free time.

**Comment by dcb-imvaria** [comment]
I ran the latest docker image this morning. The problem still exists. Is it possible that the edited config/gitleaks.toml file is not included in the docker image or is ignored?

**Comment by dcb-imvaria** [comment]
Here is the error message:
gitleaks 
{
	"Description": "Generic API Key",
	"StartLine": 44,
	"EndLine": 46,
	"StartColumn": 83,
	"EndColumn": 20,
	"Match": "password combination.\n\nR5: Regulatory--21 ",
	"Secret": "Regulatory--21",
	"File": "",
	"Commit": "",
	"Entropy": 3.6644979,
	"Author": "",
	"Email": "",
	"Date": "2021-03-13T18:00:26Z",
	"Message": "add complete docs and reorganize",
	"Tags": [],
	"RuleID": "generic-api-key"
}

**Comment by zricethezav** [comment]
@dcb-imvaria During the build process (like `go build`, the file is loaded using `embed`), so it's almost certainly not an issue of the wrong configuration file being used. I tried recreating this locally but was unable to. Could you run with `--log-level=debug` to see if a local config is being used instead?

**Comment by dcb-imvaria** [comment]
Using docker image sha256:1b2a4d9ec5d4e31ed243904f0f71d871367ca465643515b03412c82a56a14409 for zricethezav/gitleaks with digest zricethezav/gitleaks@sha256:8dc0ef7acc9d3f2cad825baa5d60ddfefa2bfd68d8733211cc76e97c1c8d5771 ...
...
3:31PM DBG No gitleaks config found in path .gitleaks.toml, using default gitleaks config
DBG executing: /usr/bin/git -C . log -p -U0 --full-history --all

**Comment by dcb-imvaria** [comment]
gitleaks:
  stage: Secrets Detection
  before_script: []
  image:
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - gitleaks detect -v --log-level=debug

**Comment by zricethezav** [comment]
@dcb-imvaria ah, right. Just refreshed myself on the code and the stop words only prevent secrets if the matched _secret_ contains a stop word, not the base regex match. So in this case the secret is `Regulatory--21`. The _match_ is on

```
password combination.

R5: Regulatory--21
```

So, if we wanted to prevent this leak we should add `regulatory` or maybe `regula` to the stop word list.

Another improvement I could see to the generic rule would be to prevent newlines after the initial "credential" group and before the "assignment" group.


Either way, I'll get a fix for this in shortly unless you want to open another PR for adding `regula` or `regulatory` to the stop word list

**Comment by dcb-imvaria** [comment]
Actually in this case preventing newlines after the initial "credentials" group would be better. Since you know the code better you probably ought to add that fix. In the meantime I will create a PR that adds regula as a quick fix.
