### ISSUE TITLE
Ignore false positive on properties files

### ISSUE THREAD

**Issue by anasoid** [zricethezav/gitleaks#887]
There is no way to ignore false positive on properties file as properties file doesn't accept comment on the same line.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Gitleaks Version: V8.8.7

cc @zricethezav

**Comment by zricethezav** [comment]
@anasoid you can specify the false positive in a rule-specific allowlist or change the false positive's rule regex
