### ISSUE TITLE
Add option to mark results as false positive in the scan report

### ISSUE THREAD

**Issue by namanpreetsingh** [zricethezav/gitleaks#888]
It'll be great if there's an option to mark the results as false positive in the scan report. Once the report is audited and false positives are marked, it can be fed as an input to the new scan so the results from new scan can be compared against false positives in the audited report and accordingly ignored.

**Comment by zricethezav** [comment]
@namanpreetsingh you can do this with adding a `.gitleaksignore` file to the root of the repo: 
PR : https://github.com/zricethezav/gitleaks/pull/938
Docs: https://github.com/zricethezav/gitleaks#gitleaksignore
