### ISSUE TITLE
flag --path / --config 

### ISSUE THREAD

**Issue by arulmanoharan** [zricethezav/gitleaks#894]
Hi , when I was using 7.4.0 version of gitleaks I was able to use   $gitleaks_path/gitleaks --path=. --config-path=gitleaks.toml --report=gitleaksReport/gitleaks_report_generated.json --files-at-commit=latest --verbose

but when I tried using 8.8.8 version it throws error flag --path is there any change I need to make in this line because when I saw there were changes made to ignore gitleaks.toml and use --config string and env variable but still I am clueless on has to how to procced 

@zricethezav

**Comment by zricethezav** [comment]
@arulmanoharan It's all documented in the readme. See the usage section: https://github.com/zricethezav/gitleaks#usage

Use `--source`
