### ISSUE TITLE
Exclude organization repository

### ISSUE THREAD

**Issue by duraki** [zricethezav/gitleaks#90]
Can we somehow exclude forked repositories or skip the list of repo names?

```
$ gitleaks --github-org=companyltd --exclude-forks
... cloning: ...
... skipping: [fork] repo
```

or (combination):

```
$ gitleaks --github-org=companyltd --exclude=redhat,other-name
... cloning: ...
... skipping: redhat
```

**Comment by zricethezav** [comment]
good call, this could easily be implemented

**Comment by zricethezav** [comment]
@duraki sorry for the delay, i added a whitelist repo functionality. Add this to your gitleaks config
```
repos = [
	"skipThisRepo"
]
```

**Comment by zricethezav** [comment]
@duraki better yet... what you actually asked for:
https://github.com/zricethezav/gitleaks/pull/106

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v1.9.0 @duraki enjoy

**Comment by duraki** [comment]
@zricethezav thank you for packing the release. Appreciate the update. Testing/ip, will get back.

**Comment by zricethezav** [comment]
@duraki gonna close this out, reopen if it doesn't meet your requirements.
