### ISSUE TITLE
Unable to execute gitleaks command 

### ISSUE THREAD

**Issue by venkatn087** [zricethezav/gitleaks#913]
Hi Team,
I have installed gitleaks from the Source as per gitleaks github document 

From Source
Step1. Download and install Go from https://golang.org/dl/
step 2. Clone the repo
          git clone https://github.com/zricethezav/gitleaks.git
step 3. Build the binary
         cd gitleaks
         make build
after executing of step 3. i could see  new "gitleaks" file created in the same folder. I have attached the screenshot for the same.
 
[brsubbareddy123@rhel7 gitleaks]$ ls -ltr
total 9176
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123     559 Jul  5 06:46 Makefile
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123    1069 Jul  5 06:46 LICENSE
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123     502 Jul  5 06:46 Dockerfile
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123    4291 Jul  5 06:46 CONTRIBUTING.md
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123   12515 Jul  5 06:46 README.md
drwxrwxr-x. 3 brsubbareddy123 brsubbareddy123      90 Jul  5 06:46 cmd
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123    1398 Jul  5 06:46 go.mod
drwxrwxr-x. 3 brsubbareddy123 brsubbareddy123     115 Jul  5 06:46 detect
drwxrwxr-x. 2 brsubbareddy123 brsubbareddy123     211 Jul  5 06:46 report
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123     611 Jul  5 06:46 main.go
-rw-rw-r--. 1 brsubbareddy123 brsubbareddy123   60946 Jul  5 06:46 go.sum
drwxrwxr-x. 6 brsubbareddy123 brsubbareddy123      60 Jul  5 06:46 testdata
drwxrwxr-x. 2 brsubbareddy123 brsubbareddy123     142 Jul  5 06:48 config
-rwxrwxr-x. 1 brsubbareddy123 brsubbareddy123 9289000 Jul  5 07:02 gitleaks   ----> new file got created, after execution of step 3.
drwxrwxr-x. 2 brsubbareddy123 brsubbareddy123      27 Jul  5 07:44 scripts

[brsubbareddy123@rhel7 gitleaks]$ pwd
/home/brsubbareddy123/gitleaks
[brsubbareddy123@rhel7 gitleaks]$ ./gitleaks detect --source="../WebGoat/"

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

9:16AM ERR Unknown option: -C
9:16AM ERR usage: git [--version] [--help] [-c name=value]
9:16AM ERR            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
9:16AM ERR            [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
9:16AM ERR            [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
9:16AM ERR            <command> [<args>]
[brsubbareddy123@rhel7 gitleaks]$ ^C
[brsubbareddy123@rhel7 gitleaks]$ 

here "../WebGoat" is a git repository which is cloned into the parent directory . in other words the repo which need to scan is "https://github.com/WebGoat/WebGoat.git"

could you please let me know which command need to provide here.

brsubbareddy123@rhel7 gitleaks]$ ./gitleaks version
v8.8.11
[brsubbareddy123@rhel7 gitleaks]$ 

thanks & regards
venkat
<img width="950" alt="gitleaks_3" src="https://user-images.githubusercontent.com/52975559/177296035-9f0ead32-7919-4db2-936c-2abc1e5ca3f9.PNG">

<img width="806" alt="gitleaks" src="https://user-images.githubusercontent.com/52975559/177295431-ca245e96-3bdc-41f5-b395-d53f63870e0f.PNG">
<img width="902" alt="gitleaks_2" src="https://user-images.githubusercontent.com/52975559/177295578-c6b890d3-558f-45a5-be39-d7d8b6f5cd8d.PNG">

**Comment by venkatn087** [comment]
Hi Team,
Thanks a lot for your reply. 
I am using git version as 1.8.3.1. Please refer to the same from screenshot.
Could you please let me know the required git version .

And also could you please let me know the syntax to execute the gitleaks command  with one or 2 example as per my scenario as am unable to find it from the github document

Thanks
venkat
<img width="418" alt="gitleaks_4" src="https://user-images.githubusercontent.com/52975559/177357124-22b5b565-dbda-4c09-b39f-39432ae2332f.PNG">

**Comment by zricethezav** [comment]
> [brsubbareddy123@rhel7 gitleaks]$ ./gitleaks detect --source="../WebGoat/" 

This is a valid command and should work.

Try updating your git version to at least git `2.x.x`

**Comment by venkatn087** [comment]
Hi Team,

Thank you so much for your quick response.


If i want to see all types of log errors, could you please let me know what value do i  need to specify for the "--log-level" parameter?

If i select log-level as "info", does the gitleaks will show info, debug,warn,error,fatl (all types of errors) will be shown or only "Info" messages alone will be shown?
-l, --log-level string       log level (debug, info, warn, error, fatal) (default "info")

<img width="919" alt="gitleaks_5" src="https://user-images.githubusercontent.com/52975559/177382947-d3cd1866-e72e-44b9-a1f1-3a9b39ab6346.PNG">


Is it possible to specify gitleaks as a system level command. Everytime i have to go inside the gitleaks folder and need to specify "./gitleaks detect --source="../WebGoat/". Do we have any way to execute gitleaks  from the git repo level itself?

**Comment by venkatn087** [comment]
Hi Team,
I have one more query. sorry to ask much questions here.
I am , trying to scan single file to detect the secrets as per the screenshot.
I have created a sampel file named "password.txt" where it will contain the username and password and executed the below command to scan. but seems it's not detected the secrets . Please let me know if anything wrong with my command.
$ ./gitleaks detect --source="../password.txt" --no-git
<img width="898" alt="gitleaks_6" src="https://user-images.githubusercontent.com/52975559/177387180-7a7cba42-21a8-4dea-aef3-29630a30738c.PNG">

**Comment by weineran** [comment]
Hi @venkatn087,

Many of these questions are general questions about software development, rather than questions about gitleaks, but I'll try to point you in the right direction.

> If i select log-level as "info", does the gitleaks will show info, debug,warn,error,fatl (all types of errors) will be shown or only "Info" messages alone will be shown?

Short answer: If you set log level as "info", it will show any logs that are "info" _or higher_.
You can learn more about how log levels work in general by googling. e.g. Here is a blog post I found that should help: https://sematext.com/blog/logging-levels/

> Is it possible to specify gitleaks as a system level command. Everytime i have to go inside the gitleaks folder and need to specify "./gitleaks detect --source="../WebGoat/". Do we have any way to execute gitleaks from the git repo level itself?

Yes, you just need to add the location of your gitleaks binary to your PATH.
linux instructions: https://linuxize.com/post/how-to-add-directory-to-path-in-linux/
macos instructions: https://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/

> I have created a sampel file named "password.txt" where it will contain the username and password and executed the below command to scan. but seems it's not detected the secrets

The password "helegf" is below the [default entropy threshold of 3.5](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L1144). If you want to set a lower entropy threshold, you can write your own secret detection rules. See here: https://github.com/zricethezav/gitleaks#configuration
However, be advised that setting the entropy threshold too low can result in false positives.
