### ISSUE TITLE
GitLeaks fails on git rename warning

### ISSUE THREAD

**Issue by anotherbridge** [zricethezav/gitleaks#915]
**Describe the bug**
This is related to issue #750.  
When I run gitleaks on a large repository it gives me the following warning and quits:
```
9:01AM ERR warning: inexact rename detection was skipped due to too many files.
9:01AM WRN warning: you may want to set your diff.renameLimit variable to at least 19618 and retry the command.
```

**Expected behavior**
Gitleaks should still continue to run without the exiting with status 1.

**Basic Info (please complete the following information):**
 - OS: Debian 11 
 - Gitleaks Version: 8.8.11

cc @zricethezav

**Comment by anotherbridge** [comment]
@zricethezav Unfortunately I cannot share the repo... 
Anyways I can provide some other insight that I gained, namely that on a different machine with more resources this issue does not arise. So could it be that it's just a hardware related problem in my case?

**Comment by zricethezav** [comment]
@anotherbridge no worries actually. I misread and thought the error messages were the same, they are not. So the fix will be as simple as adding your error message to https://github.com/zricethezav/gitleaks/blob/master/detect/git/git.go#L98-L103
