### ISSUE TITLE
Using --branch option does not seem to work

### ISSUE THREAD

**Issue by whyisdifficult** [zricethezav/gitleaks#917]
**Describe the bug**

I'm passing the `--branch` option to detect secrets in a specific branch but I'm getting the following error:

```shell
Error: unknown flag: --branch
```

**To Reproduce**
```
docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest detect --branch="feature-1" --source="my-repo/dir-to-scan" -f json --no-git
```

**Expected behavior**

The `--branch` option should be understood.

**Screenshots**

N/A

**Basic Info (please complete the following information):**
 - OS: Mac OS X 12.3.1
 - Gitleaks Version: 8.8.12 ( I tried with v8.8.11 and I get the same error)

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0 removes `--branch`. Use `--log-opts="{your branch}"`. If you want to scan _only_ commits on your branch you can do `--log-opts="{your branch}..{base branch}"`

You can pass any `git log` arguments into `--log-opts` if you need to tweak it further.
