### ISSUE TITLE
How to set GITHUB_TOKEN in Docker env?

### ISSUE THREAD

**Issue by mwargan** [zricethezav/gitleaks#92]
Hey! Thanks for this great and important tool!

I'd like to scan my private repositories, and according to your wiki, I need to set the GITHUB_TOKEN. My question is, how do I do that running your app with the one-liner for docker? Where/how can I access the env file to configure it?

Thanks!

**Comment by zricethezav** [comment]
https://docs.docker.com/engine/reference/run/#env-environment-variables

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v1.13.0 see example here
