### ISSUE TITLE
Not able to scan remote repo

### ISSUE THREAD

**Issue by AvaniAModak** [zricethezav/gitleaks#923]
**Describe the bug**
I am using gitleaks 8.8.11 locally.
I want to give the path of a remote git repo in the source parameter. However, when I do that, I am getting an error as pasted below. Is there something I am doing wrong or would I have to clone the repo if I want to scan it?

**To Reproduce**

avani@Avanis-MacBook-Pro ~ % gitleaks detect --source https://github.com/zricethezav/gitleaks.git

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

11:55AM FTL stat https://github.com/zricethezav/gitleaks.git: no such file or directory

**Expected behavior**
A clear and concise description of what you expected

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: MacOS Monterey 12.4
 - Gitleaks Version: 8.8.11

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@AvaniAModak you must clone the repo. Use `--source` to point to the cloned repo path

**Comment by AvaniAModak** [comment]
Thanks for the quick response!! 😊
