### ISSUE TITLE
Question about scanning historical commits

### ISSUE THREAD

**Issue by AvaniAModak** [zricethezav/gitleaks#924]
Hello team,

I am currently using gitleaks 8.8.11 locally to scan the Git Repo for my organization.
I cloned the repo locally and then ran gitleaks. 
However, since cloning the repo is just scanning the current code, I wanted to know how I would be able to scan the historical commits in the Git Repo using gitleaks. (I thought I would be able to do that if I could give the remote repo url in --source as then it would scan the whole repo, but I think using --source is not how I should go about it)...

It would be great if you could let me know how to include historical commits as well in my gitleaks scan. 
Please let me know if you need any more info from me.

Thanks a lot!!
Avani

**Comment by cpontvieux-systra** [comment]
Cloning get you all commits, not just the current one. Hence the name « clone ».

**Comment by zricethezav** [comment]
- `gitleaks detect --source={path to repo}` will scan historic commits
- `gitleaks detect --source={path to repo} --no-git` will treat the repo like a regular directory and scan all the _current_ code.
