### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by foolioo** [zricethezav/gitleaks#927]
**Is your feature request related to a problem? Please describe.**
GitLeaks is growing in usages and such its fans and community. Yet, the project lacks of centralize place to/for:

- Collaborative communication forum for the community
- Ask questions, discuss and answer the questions
- Share information and follow along on decisions affecting the community
- Conduct or participate in a conversation about the project

**Describe the solution you'd like**
Enable GitHub [discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)

**Describe alternatives you've considered**
~Utilize GitHub issues in the expense of the maintainers health :(~

cc @zricethezav

**Comment by zricethezav** [comment]
re-enabled discussions
