### ISSUE TITLE
default configuration vs configuration generator

### ISSUE THREAD

**Issue by electriquo** [zricethezav/gitleaks#928]
Until #927 would be considered, I am posting here my question :|

Following https://github.com/zricethezav/gitleaks/issues/876#issuecomment-1193358341 and looking at several PR's (#806, #918), could you please elaborate [what is the difference between the default configuration and the config generator](https://github.com/zricethezav/gitleaks/issues/862#issuecomment-1149424140)? (and maybe how does GitLeaks uses each of which)

cc @zricethezav

**Comment by zricethezav** [comment]
Hi @foolioo, thanks for being so active in the project! 

The  [default gitleaks configuration](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) is used by the `config` package to [load a toml file into a configuration struct](https://github.com/zricethezav/gitleaks/blob/master/config/config.go) used by the program in other parts of the code. 

The configuration generator (cmd/generate/config/main.go), is a self-contained go program used to _generate_ the default gitleaks configuration. Having this generator program makes maintaining the default configuration more manageable as now I can easily enforce a regex structure, validate true positives, and format the file easily (using templating).

The [contributing guideline](https://github.com/zricethezav/gitleaks/blob/master/CONTRIBUTING.md#adding-new-gitleaks-rules) goes into more details on how new rules can be added

**Comment by zricethezav** [comment]
> Does it imply that whatever appears in the [default configuration](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) was created only from the configuration generator?

Correct. I won't accept any PRs that change the `config/gitleaks.toml` file by hand.
