### ISSUE TITLE
Unable to get the output in CSV file

### ISSUE THREAD

**Issue by jasaz** [zricethezav/gitleaks#929]
**Describe the bug**
1. Unable to get the output of gitleaks detect in CSV format.
2. There is no option to save the output of gitleaks detect to a file (CSV\JSON)

**To Reproduce**
gitleaks detect -v -s file_path -f csv

**Expected behavior**
The output was expected to be in CSV format with each row with a comma seperated delimiter.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Windows 10
 - Gitleaks Version: 8.8.12

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@jasaz you're missing `-r, --report-path`  as defined I the usage section of the readme https://github.com/zricethezav/gitleaks#usage
