### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by satssin** [zricethezav/gitleaks#93]
I am running a scan against a repo that we, However it is giving me authentication error message even to I can clone the repo without any issue.

NFO[2018-09-17T11:11:26-04:00] cloning https://github.*********.com/*******/suite.git
WARN[2018-09-17T11:11:26-04:00] skipping audit for repo suite.git due to cloning error: authentication required
INFO[2018-09-17T11:11:26-04:00] writing report to %s/tmp/leaks

git clone command for the above repo runs perfectly fine.

**Comment by zricethezav** [comment]
check the wiki,
```
# audit a single private repo
# NOTE: SSH auth only -- this requires your private key (default: ~/.ssh/id_rsa) or set by --ssh-key
$ gitleaks --repo=git@github.com:gitleakstest/privaterepo.git
```
you need to supply a ssh target

**Comment by zricethezav** [comment]
Can I close this? @satssin

**Comment by zricethezav** [comment]
closing, ill reopen if i hear otherwise

**Comment by Droidzzzio** [comment]
I am having the same issue on public repo too 
ERRO[2019-08-06T04:11:59+05:30] authentication required

command given 
gitleaks --repo=https://github.com/user/repo --verbose

**Comment by Bream** [comment]
:~/$ docker run --rm --name=gitleaks zricethezav/gitleaks  -v --repo git@gitlabXXX  INFO[2019-11-22T16:27:28Z] cloning git@gitlabXXXXX
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6d697b]

goroutine 1 [running]:
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*PublicKeys).ClientConfig(0x0, 0xc00005b620, 0x60, 0x7f872d41d260)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/transport/ssh/auth_method.go:171 +0x3b
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0xc000075ae0, 0xbb3a60, 0x0)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/transport/ssh/common.go:111 +0x52
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0xc00000c548, 0xb1e3bd, 0xf, 0xc00005b620, 0xbb3a60, 0x0, 0xc00005b620, 0xc00009b440, 0xbb1640, 0xc0001d5890)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/transport/ssh/common.go:50 +0x8f
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0xc00004fb30, 0xb1e3bd, 0xf, 0xc00005b620, 0xbb3a60, 0x0, 0x0, 0x0, 0xc00005b620)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/transport/internal/common/common.go:112 +0x89
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0xc00004fb30, 0xc00005b620, 0xbb3a60, 0x0, 0xc00005b620, 0x0, 0x0, 0xc0001e4300)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/plumbing/transport/internal/common/common.go:89 +0x62
gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0x7ffd2cbc7f52, 0x30, 0xbb3a60, 0x0, 0xc0001d5980, 0x40bfa8, 0x20, 0xa7ce40)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/remote.go:325 +0x9c
gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc00013ba00, 0xbb65e0, 0xc000024018, 0xc0001d5b58, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/remote.go:263 +0x11f
gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc0001f0060, 0xbb65e0, 0xc000024018, 0xc0001d5b58, 0xb19f84, 0x4, 0x0, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/repository.go:860 +0xbf
gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc0001f0060, 0xbb65e0, 0xc000024018, 0xc0001ea770, 0xc0001f0060, 0x0)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/repository.go:727 +0x2bb
gopkg.in/src-d/go-git%2ev4.CloneContext(0xbb65e0, 0xc000024018, 0xbb9d20, 0xc00005b500, 0x0, 0x0, 0xc0001ea770, 0xae85e0, 0xae5b01, 0xc0001ea770)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/repository.go:210 +0xb6
gopkg.in/src-d/go-git%2ev4.Clone(0xbb9d20, 0xc00005b500, 0x0, 0x0, 0xc0001ea770, 0x203000, 0x203000, 0x2a)
	/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.9.1/repository.go:192 +0x72
github.com/zricethezav/gitleaks/src.(*Repo).clone(0xc00019ec80, 0x0, 0x0)
	/go/src/github.com/zricethezav/gitleaks/src/repo.go:122 +0x485
github.com/zricethezav/gitleaks/src.Run(0xc0000bab40, 0x0, 0x0, 0x0)
	/go/src/github.com/zricethezav/gitleaks/src/core.go:61 +0xe5
main.main()
	/go/src/github.com/zricethezav/gitleaks/main.go:12 +0x2b
