### ISSUE TITLE
Add an option to follow symlinks when running detection

### ISSUE THREAD

**Issue by RickyGrassmuck** [zricethezav/gitleaks#934]
**Is your feature request related to a problem? Please describe.**
The detect functionality does not currently allow scanning a file that is a symlink to another file. This makes sense when using in the context of git (scanning a symlink that points to something outside of the repo isn't very useful) but has usefulness when using the tool outside of the context of a git repository. In my use case, I would like to use the tool to scan specific directories of a system prior to creating a snapshot of the system.

**Describe the solution you'd like**
The addition of a flag or configuration option to enable scanning files that are symlinks.

**Describe alternatives you've considered**
One possibility is to ensure that you are running a scan against the directory that contains the actual file that the symlink is pointing to. While this does work, it requires prior knowledge of the symlink to ensure that the source files directory is also getting scanned.

**Additional context**
Took a stab at implementing this and was able to get scanning of symlinked files working. In order to keep it simple, I opted to forgo recursing into symlinked directories but that could be done too.

```
> ./gitleaks detect --no-git --report-path ./leaks.txt --source ~/.ssh/

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

9:17PM INF scan completed in 21.941383ms
9:17PM WRN leaks found: 4
> cat leaks.txt | jq '.[] | "\(.File) \(.SymlinkFile)"'
"/root/.ssh/id_rsa "
"/root/.ssh/id_ed25519 "
"/root/.ssh/test-key "
"/root/.ssh/test2 "
> ./gitleaks detect --no-git --follow-symlinks --report-path ./leaks.txt --source ~/.ssh/

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

Found symlinked directory: /root/.ssh/goleaks-test -> /root/goleaks-test [skipping]
Found symlink: /root/.ssh/test/id_ed25519 -> /root/.ssh/id_ed25519
9:17PM INF scan completed in 25.920083ms
9:17PM WRN leaks found: 5
> cat leaks.txt | jq '.[] | "\(.File) \(.SymlinkFile)"'
"/root/.ssh/id_ed25519 "
"/root/.ssh/id_rsa "
"/root/.ssh/test-key "
"/root/.ssh/test2 "
"/root/.ssh/id_ed25519 /root/.ssh/test/id_ed25519"
```

More than happy to clean up the code and submit a PR if this is something that y'all would be interested in adding!

cc @zricethezav

**Comment by zricethezav** [comment]
@RickyGrassmuck 

> More than happy to clean up the code and submit a PR if this is something that y'all would be interested in adding!

This sounds like a feature worth adding. I don't have the bandwidth right now to focus on introducing this so if you have the code available I would happily review and potentially accept a PR

**Comment by 26tanishabanik** [comment]
@zricethezav , can I work on this issue?

**Comment by zricethezav** [comment]
@26tanishabanik go for it, happy to review a PR

**Comment by 26tanishabanik** [comment]
@zricethezav , from where should I start with for this issue?

**Comment by weineran** [comment]
Reading the issue history, it looks like @RickyGrassmuck already has a rough implementation of this feature. @RickyGrassmuck If you haven't already done so, can you open a PR with whatever implementation you have so far? Then maybe @26tanishabanik can pick it up from there...

**Comment by RickyGrassmuck** [comment]
Yeah, I have it somewhere, I'll dig it up and get a PR open.

**Comment by RickyGrassmuck** [comment]
@weineran Just cleaned up and pushed the implementation I had come up with and added an additional test for the new functionality in #1010. 

I also updated all the existing tests so that they match the new findings structure and all the tests are passing on my local machine.
