### ISSUE TITLE
stopwords compared with contain and not exact match

### ISSUE THREAD

**Issue by anasoid** [zricethezav/gitleaks#937]
**Describe the bug**
When ignoring some secrets using stopwords, other secrets are ignore as they contain stopwords

**To Reproduce**
stop word "123" ignore also secret "qwerty123"  

**Expected behavior**
stopword ignore exact match (may be ignore case)

**Basic Info (please complete the following information):**
 - OS: ubuntu 22.04
 - Gitleaks Version: 8.9.0

cc @zricethezav

**Comment by zricethezav** [comment]
`123` is not part of the default stopwords. What you are describing is what is intended; if `123` is part of the secret, then the secret should be ignored if that is what is configured.

**Comment by anasoid** [comment]
Hello,

we have a custom gitleaks who extend from default config, thanks for this new feature, and for customization we have a small stopwords who can have a risk to hide a real secrets
