### ISSUE TITLE
Gitleaks will segfault when using the --source option with detect

### ISSUE THREAD

**Issue by det** [zricethezav/gitleaks#945]
**Describe the bug**
Gitleaks will segfault when using the --source option with detect.

**To Reproduce**
`gitleaks detect --source <file that exists>`

**Screenshots**
```
/path/to/gitleaks-8.10.1 detect --source=WORKSPACE

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6fb8f5]

goroutine 1 [running]:
github.com/zricethezav/gitleaks/v8/cmd.runDetect(0xa13400?, {0x785fb4?, 0x1?, 0x1?})
	/Users/zrice/code/zricethezav/gitleaks/cmd/detect.go:75 +0x4f5
github.com/spf13/cobra.(*Command).execute(0xa13400, {0xc0001140f0, 0x1, 0x1})
	/Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xa13180)
	/Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/zricethezav/gitleaks/v8/cmd.Execute()
	/Users/zrice/code/zricethezav/gitleaks/cmd/root.go:132 +0x25
main.main()
	/Users/zrice/code/zricethezav/gitleaks/main.go:22 +0x211
``` 

**Basic Info (please complete the following information):**
 - OS: Linux
 - Gitleaks Version: 8.10.0 and 8.10.1

**Additional context**
This began happening in 8.10.0. 8.9.x is fine.
Reproduced with both self-compiled gitleaks as well as the gitleaks binary from the releases page.

cc @zricethezav

**Comment by zricethezav** [comment]
@det thanks, likely because `info` is null in this [bit](https://github.com/zricethezav/gitleaks/blob/master/cmd/detect.go#L75-L77):

```golang
	// check for a .gitleaksignore file
	if info, err := os.Stat(filepath.Join(source, ".gitleaksignore")); !os.IsNotExist(err) && !info.IsDir() {
		detector.AddGitleaksIgnore(filepath.Join(source, ".gitleaksignore"))
	}
```

I'll try and push out a fix soon

**Comment by zricethezav** [comment]
@det 
https://github.com/zricethezav/gitleaks/pull/946 should fix it

**Comment by det** [comment]
Thanks for the quick turnaround!

**Comment by zricethezav** [comment]
You bet, https://github.com/zricethezav/gitleaks/releases/tag/v8.10.2 released. Feel free to reopen this issue if this change doesn't fix your error.
