### ISSUE TITLE
New Fingerprint generation + no git fingerprint support

### ISSUE THREAD

**Issue by H4Xx0R-PC** [zricethezav/gitleaks#950]
**Is your feature request related to a problem? Please describe.**
The current implementation of generating fingerprints would never work with the --no-git flag. This is because the first part of the fingerprint is the git commit ID of the secret and there wouldn't be a commit ID's in non repos's. See this line from utils.go:33
`finding.Fingerprint = fmt.Sprintf("%s:%s:%s:%d", finding.Commit, finding.File, finding.RuleID, finding.StartLine)`

Furthermore no fingerprints are returned when using the --no-git flag and that is because no code exists for it.

**Describe the solution you'd like**
I would very much like fingerprint support for the no-git option and maybe a solution for universal fingerprints (for git repo's and non git repo's) would be a good idea too. I think omitting the finding.commit and keeping the rest for the fingerprint is fine.

**Additional context**
I know that the fingerprints are experimental and subject to change, but I figured I should make this issue anyway.

cc @zricethezav

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/952
