### ISSUE TITLE
Test data and test routines for the config

### ISSUE THREAD

**Issue by ukaeufe** [zricethezav/gitleaks#951]
Hi there,

I am struggling with a few rules in your default config and was looking for a test suite that walk through the existing rules to verify they hit.
In the repo I could not find such a test suite.
How do you ensure that your all rules and your code works as expected?

E.g. I have an issue detecting passwords. I saw in generic-access-key that password is in "keywords" and "stopwords" - I wonder if this is correct or actually a config bug.

Thanks and best regards,
Uwe

**Comment by zricethezav** [comment]
@ukaeufe rules are validated upon generation here https://github.com/zricethezav/gitleaks/blob/master/cmd/generate/config/rules/rule.go#L57-L83.

I have plans to add this code to the unit test. If you want to play around with the generic rule you can do so here https://github.com/zricethezav/gitleaks/blob/master/cmd/generate/config/rules/generic.go#L41-L53

**Comment by zricethezav** [comment]
> password is in "keywords" and "stopwords"

Keywords are a pre filter on a chunk of code. I,e. if a chunk of code does not contain a keyword, then ignore it. Stopwords ignore findings if the _secret_ contains a stopword. Note that stopwords look at the _secret_, not the whole regex _match_. 


```
my_password = "fewakfjewajfkljwaf" // would be capture by keywords
my_token = "password123" // would be ignored by stopwords 
my_password = "password123" // would be ignored by stopwords
```
