### ISSUE TITLE
Scanning git but getting only last commit from file

### ISSUE THREAD

**Issue by YogevBokobza** [zricethezav/gitleaks#960]
Hi,
I am trying to scan some repo and getting too many leaks that are on the history of the git log but do not exist anymore.
when I am using --no-git I am getting the remaining leaks.

Something is discussed here: 
https://github.com/zricethezav/gitleaks/issues/156

How to achieve this behavior right now with --log-opts?

cc @zricethezav

**Comment by zricethezav** [comment]
You can use `--log-opts=-1`

https://git-scm.com/docs/git-log#_commit_limiting

I recommend spending some time reading https://git-scm.com/docs/git-log and googling around if you want faster results. /

<img width="745" alt="Screen Shot 2022-08-18 at 3 09 14 PM" src="https://user-images.githubusercontent.com/15034943/185485368-fa59588e-c227-4b2a-b92a-106c7313d857.png">


If you want to see exactly what gitleaks is scanning you can run `git log -p {whatever log options you want here}`. So for just most recent commit you can run `git log -p -1`

**Comment by YogevBokobza** [comment]
@zricethezav 
This is not quite what I wanted...
`--log-opts=-1` will scan the last commit.
It won't scan the current master branch.
So if I do `--log-opts=-1` I get no leaks but if I do `--no-git` I am getting leaks.
