### ISSUE TITLE
`--log-opts` with multiple parameters not being correctly parsed

### ISSUE THREAD

**Issue by davidsalvador-tf** [zricethezav/gitleaks#964]
**Describe the bug** 
When running [the container version of gitleaks](https://hub.docker.com/r/zricethezav/gitleaks) and using `--log-opts` with multiple `git log` parameters, such as `--log-opts="--first-parent --no-merge"` the second (and following) `git log` parameters will be interpreted as a `gitleaks` parameter instead.

**To Reproduce**

1. Create the following Bash file:
```bash
#!/bin/bash
base_ref=aValidBaseRef
head_ref=aValidHeadRef
log_opts="--first-parent --no-merges ${base_ref}^..${head_ref}"

gitleaks_cmd="detect --source=/tmp/a-repo --log-opts=\"${log_opts}\" --verbose"
docker container run --rm --name=gitleaks -v /tmp/a-repo:/tmp/a-repo zricethezav/gitleaks:v8.8.8 ${gitleaks_cmd}
```
2. Now run it

The following error will appear:
```Error: unknown flag: --no-merges```

Followed by the `gitleaks` usage menu, as if a wrong `gitleaks` parameter had been passed.

**Expected behavior**
I would expect that the content of the variable `$log_opts` is correctly parsed as a string and not just the first argument of it.

**Basic Info (please complete the following information):**
 - OS: macOS 12.5.1
 - Gitleaks Version: 8.8.8

cc @zricethezav

**Comment by zricethezav** [comment]
@davidsalvador-tf Thanks for raising the issue. 

have you tried using single quotes?

```
gitleaks_cmd='detect --source=/tmp/a-repo --log-opts=\"${log_opts}\" --verbose'
```

Without spending too much time looking into this, this seems to get parsed correctly

**Comment by rommi4** [comment]
@davidsalvador-tf , what can help
please try:
```
#!/bin/bash

base_ref=aValidBaseRef
head_ref=aValidHeadRef
log_opts="--first-parent --no-merges ${base_ref}^..${head_ref}"

gitleaks_cmd="detect --source=/tmp/a-repo --log-opts=${log_opts} --verbose"
declare -a gitleaks_cmd_array=(detect --source=/tmp/a-repo --log-opts="${log_opts}" --verbose)

docker container run --rm --name=gitleaks -v /tmp/a-repo:/tmp/a-repo zricethezav/gitleaks:v8.12.0 "${gitleaks_cmd_array[@]}"
```

**Comment by zricethezav** [comment]
@davidsalvador-tf does the solution provided by @rommi4 work?

**Comment by zricethezav** [comment]
Going to close this issue as @rommi4 provided a solution. If this is not acceptable, please feel free to reopen @davidsalvador-tf
