### ISSUE TITLE
Entropy checks

### ISSUE THREAD

**Issue by camaya** [zricethezav/gitleaks#97]
Although the first version did entropy checks apart from regexes (https://github.com/zricethezav/gitleaks/blob/v0.1.0/checks.go#L34), that's no longer the case in the latest version.

I know entropy checks could create lots of false positives, but they can also catch things that regex don't so I see a lot of value in there. Also, using the whitelisting options can reduce a lot of the false positives.

Could this be added again?

**Comment by zricethezav** [comment]
It can, yes. I'll work on adding that next release

**Comment by zricethezav** [comment]
Or, someone else could take charge of that, itd be a simple add in https://github.com/zricethezav/gitleaks/blob/master/main.go#L539-L588

**Comment by camaya** [comment]
Nice, I can do it :+1: 
What do you think if a new option is added called `--entropy` so you can adjust the level of entropy you want to report? For instance `gitleaks --entropy=4.2`

**Comment by zricethezav** [comment]
yep exactly what i was thinking, maybe scale it 1-10?

**Comment by zricethezav** [comment]
need to make a contributing guideline >.<
