### ISSUE TITLE
Baselining

### ISSUE THREAD

**Issue by gawansch** [zricethezav/gitleaks#974]
**Is your feature request related to a problem? Please describe.**
There is no easy way to create a baseline allowing users to ignore large number of legacy false positives. 

**Describe the solution you'd like**
By adding --baseline argument pointing to a previously generated report, the user can ask gitleaks to hide known issues from the new report.

**Describe alternatives you've considered**
Write a script comparing and old report to a new report used after running gitleaks.

**Additional context**
I have a solution ready/working on the feature.

cc @zricethezav

**Comment by zricethezav** [comment]
Closing with https://github.com/zricethezav/gitleaks/pull/975, thanks for the contribution @gawansch, you will be mentioned in the release
