### ISSUE TITLE
Ignore secrets with .gitleaksignore

### ISSUE THREAD

**Issue by stefan-kolb** [zricethezav/gitleaks#979]
**Describe the bug**
When I try to add specific findings to the .gitleaksignore via their fingerprint, each of the findings reports a new fingerprint on the next commit and reappears. I want to ignore certain secrets but I'm not sure if this is possible with this feature or if I am doing something fundamentally wrong.

**To Reproduce**

0. Scan is done via `gitleaks -v detect`
1. Use a finding fingerprint, e.g., `8a72ee99785fe3af5979d3e0a8cf6718841c244a:config/key.pem:private-key:1` from a gitleaks scan and add it to the .gitleaksignore
2. Do a new commit that does not change the secret from the previous commit but something else
3. gitleaks reports the finding from the previous commit as a new finding with the new commit hash from 2.

**Expected behavior**

The secret from a detection is not reported as a finding again when added to the .gitleaksignore via its fingerprint.

**Basic Info (please complete the following information):**
 - OS: Unix
 - Gitleaks Version: v8.11.2

cc @zricethezav

**Comment by zricethezav** [comment]
@stefan-kolb can you give me commands to run to reproduce this bug because I have not experienced this
