### ISSUE TITLE
Ignore Remotes

### ISSUE THREAD

**Issue by Kurt-von-Laven** [zricethezav/gitleaks#992]
**Is your feature request related to a problem? Please describe.**
Gitleaks is exceptionally thorough and checks commits that were never a part of the history of the repository in question at any time. For instance, Git retains commits that have been fetched from a remote even once the remote has been removed and `git gc --aggressive --prune=now` has been run. In a repository that once fetched from a remote containing a secret, this entails a choice between including secrets that were never a part of a project's history in its `.gitleaksignore` (whether or not the secret actually was a false positive) and creating a fresh clone. With the possible exception of `origin`, I don't recommend scanning remotes unless the tool is explicitly asked to do so. This behavior needlessly increases the runtime of Gitleaks scanning for secrets that aren't necessarily under the user's control (although the tool is fast enough that this isn't a serious concern for our team at least). In addition to these reports potentially being unactionable, they are counterintuitive, because one expects to run Gitleaks on the remote repository if they desire a report concerning that repository. This is exacerbated by the fact that there is no indication of the repository the commit belongs to in the output.

**Describe the solution you'd like**
Don't scan remotes, with the possible exception of `origin`.

**Describe alternatives you've considered**
If one desires to prioritize backwards compatibility, an alternative would be to add a configuration option to ignore remotes. Another alternative would be to look for `.gitleaksignore` recursively up the directory tree and ignore the union of all ignore directives. This would allow developers to add ignore directives to their home directory, for instance.

**Additional context**
Since we make an effort to use the same linters, CI, and development environment configurations between repositories, we often have occasion to cherry-pick commits between repositories with unrelated histories. This is how we noticed that Gitleaks was scanning remotes other than `origin` even once they were removed.

cc @zricethezav

**Comment by weineran** [comment]
@Kurt-von-Laven This is interesting. Thanks for the thorough write up.

Are you able to provide basic steps to reproduce this issue?

**Comment by Kurt-von-Laven** [comment]
Thanks for the quick reply!

1. Clone a repository without any leaks, such as [ScribeMD/pre-commit-hooks](https://github.com/ScribeMD/pre-commit-hooks).
1. Change directories into the repository.
1. Either [follow the setup steps in our contributing guide](https://github.com/ScribeMD/.github/blob/main/CONTRIBUTING.md#setup) and then run `pre-commit run --all-files --hook-stage push`, or else run Gitleaks directly. Observe that Gitleaks succeeds.
1. Run `git remote add docker-cache git@github.com:ScribeMD/docker-cache && git fetch --all` to fetch the history of a repository with a Gitleak (a false positive in this particular case).
1. Run `pre-commit run --all-files --hook-stage push` or Gitleaks directly once again, but observe that it now fails.

**Comment by Kurt-von-Laven** [comment]
@weineran, I am curious what result you experience from the repro steps.

**Comment by zricethezav** [comment]
@Kurt-von-Laven including remotes is the intended default behavior. You can exclude remote by supplying a `log-opts` option. Something like: `--exclude=refs/remotes/* --all`. 

The resulting command might look like: 

```
gitleaks detect --log-opts="--exclude=refs/remotes/* --all"
```
