### ISSUE TITLE
Fingerprint shows no "hash" 

### ISSUE THREAD

**Issue by ukaeufe** [zricethezav/gitleaks#995]
**Describe the bug**
In the output of gitleaks I do not see any unique hash or id in the fingerprint. Instead I see the path to the file plus and ending like :"758"

**To Reproduce**
1) run gitleaks detect
2) check report

**Expected behavior**
A fingerprint as in your gitleaksignore is visible

**Screenshots**

{
  "Description": "Generic API Key",
  "StartLine": 10,
  "EndLine": 10,
  "StartColumn": 3,
  "EndColumn": 27,
  "Match": "key = \"REDACTED\"",
  "Secret": "REDACTED",
  "File": "C:\\Users\\BLA\\prj\\BLI\\testgl.txt",
  "Commit": "",
  "Entropy": 3.8077636,
  "Author": "",
  "Email": "",
  "Date": "",
  "Message": "",
  "Tags": [],
  "RuleID": "generic-api-key",
  **"Fingerprint": "C:\\Users\\BLA\\prj\\BLI\\testgl.txt:generic-api-key:10"**
 }
]

**Basic Info (please complete the following information):**
 - OS: Windows 10
 - Gitleaks Version: 8.13

**Additional context**

cc @zricethezav

**Comment by theprobugmaker** [comment]
@zricethezav I'm confused with this... I'm using pre-commit and I can't commit cause of that, how am I supposed to ignore a file that doesn't have a hash yet?

**Comment by weineran** [comment]
@theprobugmaker The .gitleaksignore feature is more intended for ignoring previously leaked secrets. If you always want to ignore a file during pre-commit scans, you might be better off adding that file to your allowlist.

Screenshot from readme:
![image](https://user-images.githubusercontent.com/5898785/197814700-c89f9018-8ec9-46d7-897b-4741c55bbe43.png)

Example of how gitleaks uses an allowlist in the default config: https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L13-L21

**Comment by theprobugmaker** [comment]
@weineran Thank you for the answer. I tried to create a `gitleaks.toml` file to insert the `testdata` (a folder that usually contains keys for testing purposes) but it doesn't work when creating the commit (with `pre-commit`):

```toml
[allowlist]
paths = [
  '''testdata''',
  '''**/testdata/**''',
]
```

I even tried with different formats `**/testdata/**` but it still gives me an error saying that the key is being leaked.

**Comment by theprobugmaker** [comment]
Hi there @weineran and @zricethezav, anything on this? I'm kinda stuck with this :(

**Comment by weineran** [comment]
@theprobugmaker I'm a little stumped...Are you able to provide a test repo and full steps to reproduce the behavior you're seeing? Then maybe we can play around with it and figure it out.

**Comment by theprobugmaker** [comment]
@weineran Here is an example: https://github.com/theprobugmaker/gitleaks-bug

Just install `pre-commit` as mentioned in the docs and try to create a commit, it will fail.

**Comment by weineran** [comment]
Just had an idea. Are you specifying your gitleaks.toml file using `--config` or `GITLEAKS_CONFIG`? If not, it needs to be named `.gitleaks.toml` (notice the leading `.`) and placed in the root of your repo. See https://github.com/zricethezav/gitleaks#usage for more info

If it's using your custom config, you'll see something in the logs that tells you so.

**Comment by weineran** [comment]
I just looked at your repo https://github.com/theprobugmaker/gitleaks-bug. Pretty sure the issue is just you need to rename your config file with a leading `.`

**Comment by theprobugmaker** [comment]
> I just looked at your repo https://github.com/theprobugmaker/gitleaks-bug. Pretty sure the issue is just you need to rename your config file with a leading `.`

You are 100% right, for some reason I thought there would be a dot (.) in the name 🤦‍♂️ 

Thank you very much @weineran

**Comment by weineran** [comment]
I've made that same mistake before myself. Probably an opportunity for us to improve something to make it less error-prone

**Comment by theprobugmaker** [comment]
@weineran I noticed a weird behavior...

It doesn't matter how I configure the `.gitleaks.toml` it's either going to ignore all leaks or won't ignore the ones I want at all.

Approach 1:

```toml
[[rules]]
[rules.allowlist]
paths = ['''testdata''', '''.*/testdata/.*''']
```

Approach 2:

```toml
[rules.allowlist]
paths = ['''testdata''', '''.*/testdata/.*''']
```

What happens is that doing this allows me to commit but I created another file out of the `testdata` to check if it would warn and nothing, it's like it's disabling all the rules.

I tried using the following:

```toml
[extend]
useDefault = true
```

It does work but it doesn't ignore the files from the `testdata` folder like it's ignoring my rules...

**Comment by theprobugmaker** [comment]
I opened an issue to track this problem and avoid commenting here on another issue (kinda unrelated): https://github.com/zricethezav/gitleaks/issues/1023
